use feather_loot_model::LootTableSet;
use once_cell::sync::Lazy;

/// Implements sampling of loot tables.

/// The global loot table store, initialized at runtime from
/// the embedded loot table dump. (Generated by the build script)
static STORE: Lazy<LootTableSet> = Lazy::new(|| {
    static BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/dump.cbor"));

    serde_cbor::from_slice(BYTES).expect("invalid loot table dump")
});

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn store_deserializes_successfully() {
        Lazy::force(&STORE);
    }
}
