// This file is @generated. Please do not edit.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum VanillaBlockTags {
    Stairs,
    WallCorals,
    TallFlowers,
    Leaves,
    Buttons,
    ValidSpawn,
    GoldOres,
    WoodenFences,
    WallSigns,
    CrimsonStems,
    Doors,
    Logs,
    Wool,
    FenceGates,
    UnstableBottomCenter,
    BeeGrowables,
    Anvil,
    Beds,
    Signs,
    EndermanHoldable,
    Nylium,
    StoneBricks,
    WoodenDoors,
    SoulSpeedBlocks,
    Climbable,
    AcaciaLogs,
    WoodenSlabs,
    Impermeable,
    InfiniburnEnd,
    StonePressurePlates,
    WitherSummonBaseBlocks,
    Portals,
    ShulkerBoxes,
    WartBlocks,
    MushroomGrowBlock,
    WallPostOverride,
    PiglinRepellents,
    JungleLogs,
    WitherImmune,
    HoglinRepellents,
    StriderWarmBlocks,
    CoralPlants,
    SpruceLogs,
    Trapdoors,
    Walls,
    Banners,
    StandingSigns,
    BambooPlantableOn,
    SoulFireBaseBlocks,
    PressurePlates,
    FlowerPots,
    WoodenStairs,
    Slabs,
    WoodenButtons,
    BeaconBaseBlocks,
    Saplings,
    BaseStoneNether,
    Planks,
    SmallFlowers,
    InfiniburnNether,
    Ice,
    Rails,
    PreventMobSpawningInside,
    LogsThatBurn,
    Beehives,
    WoodenPressurePlates,
    UnderwaterBonemeals,
    Fences,
    Fire,
    Flowers,
    Sand,
    CoralBlocks,
    Crops,
    Carpets,
    GuardedByPiglins,
    OakLogs,
    InfiniburnOverworld,
    BirchLogs,
    NonFlammableWood,
    DarkOakLogs,
    WoodenTrapdoors,
    BaseStoneOverworld,
    Corals,
    WarpedStems,
    DragonImmune,
    Campfires,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum VanillaEntityTypes {
    Skeletons,
    ImpactProjectiles,
    Raiders,
    BeehiveInhabitors,
    Arrows,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum VanillaFluidTags {
    Lava,
    Water,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum VanillaItemTags {
    Sand,
    BeaconPaymentItems,
    Fences,
    Slabs,
    SoulFireBaseBlocks,
    Fishes,
    Doors,
    Rails,
    Carpets,
    PiglinLoved,
    TallFlowers,
    Trapdoors,
    Boats,
    Beds,
    Wool,
    StoneBricks,
    BirchLogs,
    WarpedStems,
    Banners,
    CrimsonStems,
    Stairs,
    WoodenStairs,
    WoodenButtons,
    Anvil,
    StoneToolMaterials,
    CreeperDropMusicDiscs,
    GoldOres,
    Logs,
    AcaciaLogs,
    NonFlammableWood,
    Flowers,
    WoodenFences,
    SmallFlowers,
    Planks,
    SpruceLogs,
    Saplings,
    Signs,
    LecternBooks,
    Arrows,
    StoneCraftingMaterials,
    WoodenPressurePlates,
    OakLogs,
    WoodenSlabs,
    Walls,
    Coals,
    WoodenTrapdoors,
    PiglinRepellents,
    WoodenDoors,
    DarkOakLogs,
    LogsThatBurn,
    MusicDiscs,
    JungleLogs,
    Leaves,
    Buttons,
}

impl VanillaBlockTags {
    pub fn name(&self) -> &'static str {
        match self {
            VanillaBlockTags::Stairs => "stairs",
            VanillaBlockTags::WallCorals => "wall_corals",
            VanillaBlockTags::TallFlowers => "tall_flowers",
            VanillaBlockTags::Leaves => "leaves",
            VanillaBlockTags::Buttons => "buttons",
            VanillaBlockTags::ValidSpawn => "valid_spawn",
            VanillaBlockTags::GoldOres => "gold_ores",
            VanillaBlockTags::WoodenFences => "wooden_fences",
            VanillaBlockTags::WallSigns => "wall_signs",
            VanillaBlockTags::CrimsonStems => "crimson_stems",
            VanillaBlockTags::Doors => "doors",
            VanillaBlockTags::Logs => "logs",
            VanillaBlockTags::Wool => "wool",
            VanillaBlockTags::FenceGates => "fence_gates",
            VanillaBlockTags::UnstableBottomCenter => "unstable_bottom_center",
            VanillaBlockTags::BeeGrowables => "bee_growables",
            VanillaBlockTags::Anvil => "anvil",
            VanillaBlockTags::Beds => "beds",
            VanillaBlockTags::Signs => "signs",
            VanillaBlockTags::EndermanHoldable => "enderman_holdable",
            VanillaBlockTags::Nylium => "nylium",
            VanillaBlockTags::StoneBricks => "stone_bricks",
            VanillaBlockTags::WoodenDoors => "wooden_doors",
            VanillaBlockTags::SoulSpeedBlocks => "soul_speed_blocks",
            VanillaBlockTags::Climbable => "climbable",
            VanillaBlockTags::AcaciaLogs => "acacia_logs",
            VanillaBlockTags::WoodenSlabs => "wooden_slabs",
            VanillaBlockTags::Impermeable => "impermeable",
            VanillaBlockTags::InfiniburnEnd => "infiniburn_end",
            VanillaBlockTags::StonePressurePlates => "stone_pressure_plates",
            VanillaBlockTags::WitherSummonBaseBlocks => "wither_summon_base_blocks",
            VanillaBlockTags::Portals => "portals",
            VanillaBlockTags::ShulkerBoxes => "shulker_boxes",
            VanillaBlockTags::WartBlocks => "wart_blocks",
            VanillaBlockTags::MushroomGrowBlock => "mushroom_grow_block",
            VanillaBlockTags::WallPostOverride => "wall_post_override",
            VanillaBlockTags::PiglinRepellents => "piglin_repellents",
            VanillaBlockTags::JungleLogs => "jungle_logs",
            VanillaBlockTags::WitherImmune => "wither_immune",
            VanillaBlockTags::HoglinRepellents => "hoglin_repellents",
            VanillaBlockTags::StriderWarmBlocks => "strider_warm_blocks",
            VanillaBlockTags::CoralPlants => "coral_plants",
            VanillaBlockTags::SpruceLogs => "spruce_logs",
            VanillaBlockTags::Trapdoors => "trapdoors",
            VanillaBlockTags::Walls => "walls",
            VanillaBlockTags::Banners => "banners",
            VanillaBlockTags::StandingSigns => "standing_signs",
            VanillaBlockTags::BambooPlantableOn => "bamboo_plantable_on",
            VanillaBlockTags::SoulFireBaseBlocks => "soul_fire_base_blocks",
            VanillaBlockTags::PressurePlates => "pressure_plates",
            VanillaBlockTags::FlowerPots => "flower_pots",
            VanillaBlockTags::WoodenStairs => "wooden_stairs",
            VanillaBlockTags::Slabs => "slabs",
            VanillaBlockTags::WoodenButtons => "wooden_buttons",
            VanillaBlockTags::BeaconBaseBlocks => "beacon_base_blocks",
            VanillaBlockTags::Saplings => "saplings",
            VanillaBlockTags::BaseStoneNether => "base_stone_nether",
            VanillaBlockTags::Planks => "planks",
            VanillaBlockTags::SmallFlowers => "small_flowers",
            VanillaBlockTags::InfiniburnNether => "infiniburn_nether",
            VanillaBlockTags::Ice => "ice",
            VanillaBlockTags::Rails => "rails",
            VanillaBlockTags::PreventMobSpawningInside => "prevent_mob_spawning_inside",
            VanillaBlockTags::LogsThatBurn => "logs_that_burn",
            VanillaBlockTags::Beehives => "beehives",
            VanillaBlockTags::WoodenPressurePlates => "wooden_pressure_plates",
            VanillaBlockTags::UnderwaterBonemeals => "underwater_bonemeals",
            VanillaBlockTags::Fences => "fences",
            VanillaBlockTags::Fire => "fire",
            VanillaBlockTags::Flowers => "flowers",
            VanillaBlockTags::Sand => "sand",
            VanillaBlockTags::CoralBlocks => "coral_blocks",
            VanillaBlockTags::Crops => "crops",
            VanillaBlockTags::Carpets => "carpets",
            VanillaBlockTags::GuardedByPiglins => "guarded_by_piglins",
            VanillaBlockTags::OakLogs => "oak_logs",
            VanillaBlockTags::InfiniburnOverworld => "infiniburn_overworld",
            VanillaBlockTags::BirchLogs => "birch_logs",
            VanillaBlockTags::NonFlammableWood => "non_flammable_wood",
            VanillaBlockTags::DarkOakLogs => "dark_oak_logs",
            VanillaBlockTags::WoodenTrapdoors => "wooden_trapdoors",
            VanillaBlockTags::BaseStoneOverworld => "base_stone_overworld",
            VanillaBlockTags::Corals => "corals",
            VanillaBlockTags::WarpedStems => "warped_stems",
            VanillaBlockTags::DragonImmune => "dragon_immune",
            VanillaBlockTags::Campfires => "campfires",
        }
    }
}
impl From<VanillaBlockTags> for &'static str {
    fn from(tag: VanillaBlockTags) -> Self {
        tag.name()
    }
}
impl VanillaEntityTypes {
    pub fn name(&self) -> &'static str {
        match self {
            VanillaEntityTypes::Skeletons => "skeletons",
            VanillaEntityTypes::ImpactProjectiles => "impact_projectiles",
            VanillaEntityTypes::Raiders => "raiders",
            VanillaEntityTypes::BeehiveInhabitors => "beehive_inhabitors",
            VanillaEntityTypes::Arrows => "arrows",
        }
    }
}
impl From<VanillaEntityTypes> for &'static str {
    fn from(tag: VanillaEntityTypes) -> Self {
        tag.name()
    }
}
impl VanillaFluidTags {
    pub fn name(&self) -> &'static str {
        match self {
            VanillaFluidTags::Lava => "lava",
            VanillaFluidTags::Water => "water",
        }
    }
}
impl From<VanillaFluidTags> for &'static str {
    fn from(tag: VanillaFluidTags) -> Self {
        tag.name()
    }
}
impl VanillaItemTags {
    pub fn name(&self) -> &'static str {
        match self {
            VanillaItemTags::Sand => "sand",
            VanillaItemTags::BeaconPaymentItems => "beacon_payment_items",
            VanillaItemTags::Fences => "fences",
            VanillaItemTags::Slabs => "slabs",
            VanillaItemTags::SoulFireBaseBlocks => "soul_fire_base_blocks",
            VanillaItemTags::Fishes => "fishes",
            VanillaItemTags::Doors => "doors",
            VanillaItemTags::Rails => "rails",
            VanillaItemTags::Carpets => "carpets",
            VanillaItemTags::PiglinLoved => "piglin_loved",
            VanillaItemTags::TallFlowers => "tall_flowers",
            VanillaItemTags::Trapdoors => "trapdoors",
            VanillaItemTags::Boats => "boats",
            VanillaItemTags::Beds => "beds",
            VanillaItemTags::Wool => "wool",
            VanillaItemTags::StoneBricks => "stone_bricks",
            VanillaItemTags::BirchLogs => "birch_logs",
            VanillaItemTags::WarpedStems => "warped_stems",
            VanillaItemTags::Banners => "banners",
            VanillaItemTags::CrimsonStems => "crimson_stems",
            VanillaItemTags::Stairs => "stairs",
            VanillaItemTags::WoodenStairs => "wooden_stairs",
            VanillaItemTags::WoodenButtons => "wooden_buttons",
            VanillaItemTags::Anvil => "anvil",
            VanillaItemTags::StoneToolMaterials => "stone_tool_materials",
            VanillaItemTags::CreeperDropMusicDiscs => "creeper_drop_music_discs",
            VanillaItemTags::GoldOres => "gold_ores",
            VanillaItemTags::Logs => "logs",
            VanillaItemTags::AcaciaLogs => "acacia_logs",
            VanillaItemTags::NonFlammableWood => "non_flammable_wood",
            VanillaItemTags::Flowers => "flowers",
            VanillaItemTags::WoodenFences => "wooden_fences",
            VanillaItemTags::SmallFlowers => "small_flowers",
            VanillaItemTags::Planks => "planks",
            VanillaItemTags::SpruceLogs => "spruce_logs",
            VanillaItemTags::Saplings => "saplings",
            VanillaItemTags::Signs => "signs",
            VanillaItemTags::LecternBooks => "lectern_books",
            VanillaItemTags::Arrows => "arrows",
            VanillaItemTags::StoneCraftingMaterials => "stone_crafting_materials",
            VanillaItemTags::WoodenPressurePlates => "wooden_pressure_plates",
            VanillaItemTags::OakLogs => "oak_logs",
            VanillaItemTags::WoodenSlabs => "wooden_slabs",
            VanillaItemTags::Walls => "walls",
            VanillaItemTags::Coals => "coals",
            VanillaItemTags::WoodenTrapdoors => "wooden_trapdoors",
            VanillaItemTags::PiglinRepellents => "piglin_repellents",
            VanillaItemTags::WoodenDoors => "wooden_doors",
            VanillaItemTags::DarkOakLogs => "dark_oak_logs",
            VanillaItemTags::LogsThatBurn => "logs_that_burn",
            VanillaItemTags::MusicDiscs => "music_discs",
            VanillaItemTags::JungleLogs => "jungle_logs",
            VanillaItemTags::Leaves => "leaves",
            VanillaItemTags::Buttons => "buttons",
        }
    }
}
impl From<VanillaItemTags> for &'static str {
    fn from(tag: VanillaItemTags) -> Self {
        tag.name()
    }
}
