// This file is @generated. Please do not edit.

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Biome {
    Ocean,
    Plains,
    Desert,
    Mountains,
    Forest,
    Taiga,
    Swamp,
    River,
    NetherWastes,
    TheEnd,
    FrozenOcean,
    FrozenRiver,
    SnowyTundra,
    SnowyMountains,
    MushroomFields,
    MushroomFieldShore,
    Beach,
    DesertHills,
    WoodedHills,
    TaigaHills,
    MountainEdge,
    Jungle,
    JungleHills,
    JungleEdge,
    DeepOcean,
    StoneShore,
    SnowyBeach,
    BirchForest,
    BirchForestHills,
    DarkForest,
    SnowyTaiga,
    SnowyTaigaHills,
    GiantTreeTaiga,
    GiantTreeTaigaHills,
    WoodedMountains,
    Savanna,
    SavannaPlateau,
    Badlands,
    WoodedBadlandsPlateau,
    BadlandsPlateau,
    SmallEndIslands,
    EndMidlands,
    EndHighlands,
    EndBarrens,
    WarmOcean,
    LukewarmOcean,
    ColdOcean,
    DeepWarmOcean,
    DeepLukewarmOcean,
    DeepColdOcean,
    DeepFrozenOcean,
    TheVoid,
    SunflowerPlains,
    DesertLakes,
    GravellyMountains,
    FlowerForest,
    TaigaMountains,
    SwampHills,
    IceSpikes,
    ModifiedJungle,
    ModifiedJungleEdge,
    TallBirchForest,
    TallBirchHills,
    DarkForestHills,
    SnowyTaigaMountains,
    GiantSpruceTaiga,
    GiantSpruceTaigaHills,
    ModifiedGravellyMountains,
    ShatteredSavanna,
    ShatteredSavannaPlateau,
    ErodedBadlands,
    ModifiedWoodedBadlandsPlateau,
    ModifiedBadlandsPlateau,
    BambooJungle,
    BambooJungleHills,
    SoulSandValley,
    CrimsonForest,
    WarpedForest,
    BasaltDeltas,
}

#[allow(warnings)]
#[allow(clippy::all)]
impl Biome {
    /// Returns the `id` property of this `Biome`.
    pub fn id(&self) -> u32 {
        match self {
            Biome::Ocean => 0,
            Biome::Plains => 1,
            Biome::Desert => 2,
            Biome::Mountains => 3,
            Biome::Forest => 4,
            Biome::Taiga => 5,
            Biome::Swamp => 6,
            Biome::River => 7,
            Biome::NetherWastes => 8,
            Biome::TheEnd => 9,
            Biome::FrozenOcean => 10,
            Biome::FrozenRiver => 11,
            Biome::SnowyTundra => 12,
            Biome::SnowyMountains => 13,
            Biome::MushroomFields => 14,
            Biome::MushroomFieldShore => 15,
            Biome::Beach => 16,
            Biome::DesertHills => 17,
            Biome::WoodedHills => 18,
            Biome::TaigaHills => 19,
            Biome::MountainEdge => 20,
            Biome::Jungle => 21,
            Biome::JungleHills => 22,
            Biome::JungleEdge => 23,
            Biome::DeepOcean => 24,
            Biome::StoneShore => 25,
            Biome::SnowyBeach => 26,
            Biome::BirchForest => 27,
            Biome::BirchForestHills => 28,
            Biome::DarkForest => 29,
            Biome::SnowyTaiga => 30,
            Biome::SnowyTaigaHills => 31,
            Biome::GiantTreeTaiga => 32,
            Biome::GiantTreeTaigaHills => 33,
            Biome::WoodedMountains => 34,
            Biome::Savanna => 35,
            Biome::SavannaPlateau => 36,
            Biome::Badlands => 37,
            Biome::WoodedBadlandsPlateau => 38,
            Biome::BadlandsPlateau => 39,
            Biome::SmallEndIslands => 40,
            Biome::EndMidlands => 41,
            Biome::EndHighlands => 42,
            Biome::EndBarrens => 43,
            Biome::WarmOcean => 44,
            Biome::LukewarmOcean => 45,
            Biome::ColdOcean => 46,
            Biome::DeepWarmOcean => 47,
            Biome::DeepLukewarmOcean => 48,
            Biome::DeepColdOcean => 49,
            Biome::DeepFrozenOcean => 50,
            Biome::TheVoid => 127,
            Biome::SunflowerPlains => 129,
            Biome::DesertLakes => 130,
            Biome::GravellyMountains => 131,
            Biome::FlowerForest => 132,
            Biome::TaigaMountains => 133,
            Biome::SwampHills => 134,
            Biome::IceSpikes => 140,
            Biome::ModifiedJungle => 149,
            Biome::ModifiedJungleEdge => 151,
            Biome::TallBirchForest => 155,
            Biome::TallBirchHills => 156,
            Biome::DarkForestHills => 157,
            Biome::SnowyTaigaMountains => 158,
            Biome::GiantSpruceTaiga => 160,
            Biome::GiantSpruceTaigaHills => 161,
            Biome::ModifiedGravellyMountains => 162,
            Biome::ShatteredSavanna => 163,
            Biome::ShatteredSavannaPlateau => 164,
            Biome::ErodedBadlands => 165,
            Biome::ModifiedWoodedBadlandsPlateau => 166,
            Biome::ModifiedBadlandsPlateau => 167,
            Biome::BambooJungle => 168,
            Biome::BambooJungleHills => 169,
            Biome::SoulSandValley => 170,
            Biome::CrimsonForest => 171,
            Biome::WarpedForest => 172,
            Biome::BasaltDeltas => 173,
        }
    }

    /// Gets a `Biome` by its `id`.
    pub fn from_id(id: u32) -> Option<Self> {
        match id {
            0 => Some(Biome::Ocean),
            1 => Some(Biome::Plains),
            2 => Some(Biome::Desert),
            3 => Some(Biome::Mountains),
            4 => Some(Biome::Forest),
            5 => Some(Biome::Taiga),
            6 => Some(Biome::Swamp),
            7 => Some(Biome::River),
            8 => Some(Biome::NetherWastes),
            9 => Some(Biome::TheEnd),
            10 => Some(Biome::FrozenOcean),
            11 => Some(Biome::FrozenRiver),
            12 => Some(Biome::SnowyTundra),
            13 => Some(Biome::SnowyMountains),
            14 => Some(Biome::MushroomFields),
            15 => Some(Biome::MushroomFieldShore),
            16 => Some(Biome::Beach),
            17 => Some(Biome::DesertHills),
            18 => Some(Biome::WoodedHills),
            19 => Some(Biome::TaigaHills),
            20 => Some(Biome::MountainEdge),
            21 => Some(Biome::Jungle),
            22 => Some(Biome::JungleHills),
            23 => Some(Biome::JungleEdge),
            24 => Some(Biome::DeepOcean),
            25 => Some(Biome::StoneShore),
            26 => Some(Biome::SnowyBeach),
            27 => Some(Biome::BirchForest),
            28 => Some(Biome::BirchForestHills),
            29 => Some(Biome::DarkForest),
            30 => Some(Biome::SnowyTaiga),
            31 => Some(Biome::SnowyTaigaHills),
            32 => Some(Biome::GiantTreeTaiga),
            33 => Some(Biome::GiantTreeTaigaHills),
            34 => Some(Biome::WoodedMountains),
            35 => Some(Biome::Savanna),
            36 => Some(Biome::SavannaPlateau),
            37 => Some(Biome::Badlands),
            38 => Some(Biome::WoodedBadlandsPlateau),
            39 => Some(Biome::BadlandsPlateau),
            40 => Some(Biome::SmallEndIslands),
            41 => Some(Biome::EndMidlands),
            42 => Some(Biome::EndHighlands),
            43 => Some(Biome::EndBarrens),
            44 => Some(Biome::WarmOcean),
            45 => Some(Biome::LukewarmOcean),
            46 => Some(Biome::ColdOcean),
            47 => Some(Biome::DeepWarmOcean),
            48 => Some(Biome::DeepLukewarmOcean),
            49 => Some(Biome::DeepColdOcean),
            50 => Some(Biome::DeepFrozenOcean),
            127 => Some(Biome::TheVoid),
            129 => Some(Biome::SunflowerPlains),
            130 => Some(Biome::DesertLakes),
            131 => Some(Biome::GravellyMountains),
            132 => Some(Biome::FlowerForest),
            133 => Some(Biome::TaigaMountains),
            134 => Some(Biome::SwampHills),
            140 => Some(Biome::IceSpikes),
            149 => Some(Biome::ModifiedJungle),
            151 => Some(Biome::ModifiedJungleEdge),
            155 => Some(Biome::TallBirchForest),
            156 => Some(Biome::TallBirchHills),
            157 => Some(Biome::DarkForestHills),
            158 => Some(Biome::SnowyTaigaMountains),
            160 => Some(Biome::GiantSpruceTaiga),
            161 => Some(Biome::GiantSpruceTaigaHills),
            162 => Some(Biome::ModifiedGravellyMountains),
            163 => Some(Biome::ShatteredSavanna),
            164 => Some(Biome::ShatteredSavannaPlateau),
            165 => Some(Biome::ErodedBadlands),
            166 => Some(Biome::ModifiedWoodedBadlandsPlateau),
            167 => Some(Biome::ModifiedBadlandsPlateau),
            168 => Some(Biome::BambooJungle),
            169 => Some(Biome::BambooJungleHills),
            170 => Some(Biome::SoulSandValley),
            171 => Some(Biome::CrimsonForest),
            172 => Some(Biome::WarpedForest),
            173 => Some(Biome::BasaltDeltas),
            _ => None,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Biome {
    /// Returns the `name` property of this `Biome`.
    pub fn name(&self) -> &'static str {
        match self {
            Biome::Ocean => "ocean",
            Biome::Plains => "plains",
            Biome::Desert => "desert",
            Biome::Mountains => "mountains",
            Biome::Forest => "forest",
            Biome::Taiga => "taiga",
            Biome::Swamp => "swamp",
            Biome::River => "river",
            Biome::NetherWastes => "nether_wastes",
            Biome::TheEnd => "the_end",
            Biome::FrozenOcean => "frozen_ocean",
            Biome::FrozenRiver => "frozen_river",
            Biome::SnowyTundra => "snowy_tundra",
            Biome::SnowyMountains => "snowy_mountains",
            Biome::MushroomFields => "mushroom_fields",
            Biome::MushroomFieldShore => "mushroom_field_shore",
            Biome::Beach => "beach",
            Biome::DesertHills => "desert_hills",
            Biome::WoodedHills => "wooded_hills",
            Biome::TaigaHills => "taiga_hills",
            Biome::MountainEdge => "mountain_edge",
            Biome::Jungle => "jungle",
            Biome::JungleHills => "jungle_hills",
            Biome::JungleEdge => "jungle_edge",
            Biome::DeepOcean => "deep_ocean",
            Biome::StoneShore => "stone_shore",
            Biome::SnowyBeach => "snowy_beach",
            Biome::BirchForest => "birch_forest",
            Biome::BirchForestHills => "birch_forest_hills",
            Biome::DarkForest => "dark_forest",
            Biome::SnowyTaiga => "snowy_taiga",
            Biome::SnowyTaigaHills => "snowy_taiga_hills",
            Biome::GiantTreeTaiga => "giant_tree_taiga",
            Biome::GiantTreeTaigaHills => "giant_tree_taiga_hills",
            Biome::WoodedMountains => "wooded_mountains",
            Biome::Savanna => "savanna",
            Biome::SavannaPlateau => "savanna_plateau",
            Biome::Badlands => "badlands",
            Biome::WoodedBadlandsPlateau => "wooded_badlands_plateau",
            Biome::BadlandsPlateau => "badlands_plateau",
            Biome::SmallEndIslands => "small_end_islands",
            Biome::EndMidlands => "end_midlands",
            Biome::EndHighlands => "end_highlands",
            Biome::EndBarrens => "end_barrens",
            Biome::WarmOcean => "warm_ocean",
            Biome::LukewarmOcean => "lukewarm_ocean",
            Biome::ColdOcean => "cold_ocean",
            Biome::DeepWarmOcean => "deep_warm_ocean",
            Biome::DeepLukewarmOcean => "deep_lukewarm_ocean",
            Biome::DeepColdOcean => "deep_cold_ocean",
            Biome::DeepFrozenOcean => "deep_frozen_ocean",
            Biome::TheVoid => "the_void",
            Biome::SunflowerPlains => "sunflower_plains",
            Biome::DesertLakes => "desert_lakes",
            Biome::GravellyMountains => "gravelly_mountains",
            Biome::FlowerForest => "flower_forest",
            Biome::TaigaMountains => "taiga_mountains",
            Biome::SwampHills => "swamp_hills",
            Biome::IceSpikes => "ice_spikes",
            Biome::ModifiedJungle => "modified_jungle",
            Biome::ModifiedJungleEdge => "modified_jungle_edge",
            Biome::TallBirchForest => "tall_birch_forest",
            Biome::TallBirchHills => "tall_birch_hills",
            Biome::DarkForestHills => "dark_forest_hills",
            Biome::SnowyTaigaMountains => "snowy_taiga_mountains",
            Biome::GiantSpruceTaiga => "giant_spruce_taiga",
            Biome::GiantSpruceTaigaHills => "giant_spruce_taiga_hills",
            Biome::ModifiedGravellyMountains => "modified_gravelly_mountains",
            Biome::ShatteredSavanna => "shattered_savanna",
            Biome::ShatteredSavannaPlateau => "shattered_savanna_plateau",
            Biome::ErodedBadlands => "eroded_badlands",
            Biome::ModifiedWoodedBadlandsPlateau => "modified_wooded_badlands_plateau",
            Biome::ModifiedBadlandsPlateau => "modified_badlands_plateau",
            Biome::BambooJungle => "bamboo_jungle",
            Biome::BambooJungleHills => "bamboo_jungle_hills",
            Biome::SoulSandValley => "soul_sand_valley",
            Biome::CrimsonForest => "crimson_forest",
            Biome::WarpedForest => "warped_forest",
            Biome::BasaltDeltas => "basalt_deltas",
        }
    }

    /// Gets a `Biome` by its `name`.
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "ocean" => Some(Biome::Ocean),
            "plains" => Some(Biome::Plains),
            "desert" => Some(Biome::Desert),
            "mountains" => Some(Biome::Mountains),
            "forest" => Some(Biome::Forest),
            "taiga" => Some(Biome::Taiga),
            "swamp" => Some(Biome::Swamp),
            "river" => Some(Biome::River),
            "nether_wastes" => Some(Biome::NetherWastes),
            "the_end" => Some(Biome::TheEnd),
            "frozen_ocean" => Some(Biome::FrozenOcean),
            "frozen_river" => Some(Biome::FrozenRiver),
            "snowy_tundra" => Some(Biome::SnowyTundra),
            "snowy_mountains" => Some(Biome::SnowyMountains),
            "mushroom_fields" => Some(Biome::MushroomFields),
            "mushroom_field_shore" => Some(Biome::MushroomFieldShore),
            "beach" => Some(Biome::Beach),
            "desert_hills" => Some(Biome::DesertHills),
            "wooded_hills" => Some(Biome::WoodedHills),
            "taiga_hills" => Some(Biome::TaigaHills),
            "mountain_edge" => Some(Biome::MountainEdge),
            "jungle" => Some(Biome::Jungle),
            "jungle_hills" => Some(Biome::JungleHills),
            "jungle_edge" => Some(Biome::JungleEdge),
            "deep_ocean" => Some(Biome::DeepOcean),
            "stone_shore" => Some(Biome::StoneShore),
            "snowy_beach" => Some(Biome::SnowyBeach),
            "birch_forest" => Some(Biome::BirchForest),
            "birch_forest_hills" => Some(Biome::BirchForestHills),
            "dark_forest" => Some(Biome::DarkForest),
            "snowy_taiga" => Some(Biome::SnowyTaiga),
            "snowy_taiga_hills" => Some(Biome::SnowyTaigaHills),
            "giant_tree_taiga" => Some(Biome::GiantTreeTaiga),
            "giant_tree_taiga_hills" => Some(Biome::GiantTreeTaigaHills),
            "wooded_mountains" => Some(Biome::WoodedMountains),
            "savanna" => Some(Biome::Savanna),
            "savanna_plateau" => Some(Biome::SavannaPlateau),
            "badlands" => Some(Biome::Badlands),
            "wooded_badlands_plateau" => Some(Biome::WoodedBadlandsPlateau),
            "badlands_plateau" => Some(Biome::BadlandsPlateau),
            "small_end_islands" => Some(Biome::SmallEndIslands),
            "end_midlands" => Some(Biome::EndMidlands),
            "end_highlands" => Some(Biome::EndHighlands),
            "end_barrens" => Some(Biome::EndBarrens),
            "warm_ocean" => Some(Biome::WarmOcean),
            "lukewarm_ocean" => Some(Biome::LukewarmOcean),
            "cold_ocean" => Some(Biome::ColdOcean),
            "deep_warm_ocean" => Some(Biome::DeepWarmOcean),
            "deep_lukewarm_ocean" => Some(Biome::DeepLukewarmOcean),
            "deep_cold_ocean" => Some(Biome::DeepColdOcean),
            "deep_frozen_ocean" => Some(Biome::DeepFrozenOcean),
            "the_void" => Some(Biome::TheVoid),
            "sunflower_plains" => Some(Biome::SunflowerPlains),
            "desert_lakes" => Some(Biome::DesertLakes),
            "gravelly_mountains" => Some(Biome::GravellyMountains),
            "flower_forest" => Some(Biome::FlowerForest),
            "taiga_mountains" => Some(Biome::TaigaMountains),
            "swamp_hills" => Some(Biome::SwampHills),
            "ice_spikes" => Some(Biome::IceSpikes),
            "modified_jungle" => Some(Biome::ModifiedJungle),
            "modified_jungle_edge" => Some(Biome::ModifiedJungleEdge),
            "tall_birch_forest" => Some(Biome::TallBirchForest),
            "tall_birch_hills" => Some(Biome::TallBirchHills),
            "dark_forest_hills" => Some(Biome::DarkForestHills),
            "snowy_taiga_mountains" => Some(Biome::SnowyTaigaMountains),
            "giant_spruce_taiga" => Some(Biome::GiantSpruceTaiga),
            "giant_spruce_taiga_hills" => Some(Biome::GiantSpruceTaigaHills),
            "modified_gravelly_mountains" => Some(Biome::ModifiedGravellyMountains),
            "shattered_savanna" => Some(Biome::ShatteredSavanna),
            "shattered_savanna_plateau" => Some(Biome::ShatteredSavannaPlateau),
            "eroded_badlands" => Some(Biome::ErodedBadlands),
            "modified_wooded_badlands_plateau" => Some(Biome::ModifiedWoodedBadlandsPlateau),
            "modified_badlands_plateau" => Some(Biome::ModifiedBadlandsPlateau),
            "bamboo_jungle" => Some(Biome::BambooJungle),
            "bamboo_jungle_hills" => Some(Biome::BambooJungleHills),
            "soul_sand_valley" => Some(Biome::SoulSandValley),
            "crimson_forest" => Some(Biome::CrimsonForest),
            "warped_forest" => Some(Biome::WarpedForest),
            "basalt_deltas" => Some(Biome::BasaltDeltas),
            _ => None,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Biome {
    /// Returns the `display_name` property of this `Biome`.
    pub fn display_name(&self) -> &'static str {
        match self {
            Biome::Ocean => "Ocean",
            Biome::Plains => "Plains",
            Biome::Desert => "Desert",
            Biome::Mountains => "Mountains",
            Biome::Forest => "Forest",
            Biome::Taiga => "Taiga",
            Biome::Swamp => "Swamp",
            Biome::River => "River",
            Biome::NetherWastes => "Nether Wastes",
            Biome::TheEnd => "The End",
            Biome::FrozenOcean => "Frozen Ocean",
            Biome::FrozenRiver => "Frozen River",
            Biome::SnowyTundra => "Snowy Tundra",
            Biome::SnowyMountains => "Snowy Mountains",
            Biome::MushroomFields => "Mushroom Fields",
            Biome::MushroomFieldShore => "Mushroom Fields Shore",
            Biome::Beach => "Beach",
            Biome::DesertHills => "Desert Hills",
            Biome::WoodedHills => "Wooded Hills",
            Biome::TaigaHills => "Taiga Hills",
            Biome::MountainEdge => "Mountain Edge",
            Biome::Jungle => "Jungle",
            Biome::JungleHills => "Jungle Hills",
            Biome::JungleEdge => "Jungle Edge",
            Biome::DeepOcean => "Deep Ocean",
            Biome::StoneShore => "Stone Shore",
            Biome::SnowyBeach => "Snowy Beach",
            Biome::BirchForest => "Birch Forest",
            Biome::BirchForestHills => "Birch Forest Hills",
            Biome::DarkForest => "Dark Forest",
            Biome::SnowyTaiga => "Snowy Taiga",
            Biome::SnowyTaigaHills => "Snowy Taiga Hills",
            Biome::GiantTreeTaiga => "Giant Tree Taiga",
            Biome::GiantTreeTaigaHills => "Giant Tree Taiga Hills",
            Biome::WoodedMountains => "Wooded Mountains",
            Biome::Savanna => "Savanna",
            Biome::SavannaPlateau => "Savanna Plateau",
            Biome::Badlands => "Badlands",
            Biome::WoodedBadlandsPlateau => "Wooded Badlands Plateau",
            Biome::BadlandsPlateau => "Badlands Plateau",
            Biome::SmallEndIslands => "Small End Islands",
            Biome::EndMidlands => "End Midlands",
            Biome::EndHighlands => "End Highlands",
            Biome::EndBarrens => "End Barrens",
            Biome::WarmOcean => "Warm Ocean",
            Biome::LukewarmOcean => "Lukewarm Ocean",
            Biome::ColdOcean => "Cold Ocean",
            Biome::DeepWarmOcean => "Deep Warm Ocean",
            Biome::DeepLukewarmOcean => "Deep Lukewarm Ocean",
            Biome::DeepColdOcean => "Deep Cold Ocean",
            Biome::DeepFrozenOcean => "Deep Frozen Ocean",
            Biome::TheVoid => "the_void",
            Biome::SunflowerPlains => "Sunflower Plains",
            Biome::DesertLakes => "Desert Lakes",
            Biome::GravellyMountains => "Gravelly Mountains",
            Biome::FlowerForest => "Flower Forest",
            Biome::TaigaMountains => "Taiga Mountains",
            Biome::SwampHills => "Swamp Hills",
            Biome::IceSpikes => "Ice Spikes",
            Biome::ModifiedJungle => "Modified Jungle",
            Biome::ModifiedJungleEdge => "Modified Jungle Edge",
            Biome::TallBirchForest => "Tall Birch Forest",
            Biome::TallBirchHills => "Tall Birch Hills",
            Biome::DarkForestHills => "Dark Forest Hills",
            Biome::SnowyTaigaMountains => "Snowy Taiga Mountains",
            Biome::GiantSpruceTaiga => "Giant Spruce Taiga",
            Biome::GiantSpruceTaigaHills => "Giant Spruce Taiga Hills",
            Biome::ModifiedGravellyMountains => "Gravelly Mountains+",
            Biome::ShatteredSavanna => "Shattered Savanna",
            Biome::ShatteredSavannaPlateau => "Shattered Savanna Plateau",
            Biome::ErodedBadlands => "Eroded Badlands",
            Biome::ModifiedWoodedBadlandsPlateau => "Modified Wooded Badlands Plateau",
            Biome::ModifiedBadlandsPlateau => "Modified Badlands Plateau",
            Biome::BambooJungle => "Bamboo Jungle",
            Biome::BambooJungleHills => "Bamboo Jungle Hills",
            Biome::SoulSandValley => "Soul Sand Valley",
            Biome::CrimsonForest => "Crimson Forest",
            Biome::WarpedForest => "Warped Forest",
            Biome::BasaltDeltas => "Basalt Deltas",
        }
    }

    /// Gets a `Biome` by its `display_name`.
    pub fn from_display_name(display_name: &str) -> Option<Self> {
        match display_name {
            "Ocean" => Some(Biome::Ocean),
            "Plains" => Some(Biome::Plains),
            "Desert" => Some(Biome::Desert),
            "Mountains" => Some(Biome::Mountains),
            "Forest" => Some(Biome::Forest),
            "Taiga" => Some(Biome::Taiga),
            "Swamp" => Some(Biome::Swamp),
            "River" => Some(Biome::River),
            "Nether Wastes" => Some(Biome::NetherWastes),
            "The End" => Some(Biome::TheEnd),
            "Frozen Ocean" => Some(Biome::FrozenOcean),
            "Frozen River" => Some(Biome::FrozenRiver),
            "Snowy Tundra" => Some(Biome::SnowyTundra),
            "Snowy Mountains" => Some(Biome::SnowyMountains),
            "Mushroom Fields" => Some(Biome::MushroomFields),
            "Mushroom Fields Shore" => Some(Biome::MushroomFieldShore),
            "Beach" => Some(Biome::Beach),
            "Desert Hills" => Some(Biome::DesertHills),
            "Wooded Hills" => Some(Biome::WoodedHills),
            "Taiga Hills" => Some(Biome::TaigaHills),
            "Mountain Edge" => Some(Biome::MountainEdge),
            "Jungle" => Some(Biome::Jungle),
            "Jungle Hills" => Some(Biome::JungleHills),
            "Jungle Edge" => Some(Biome::JungleEdge),
            "Deep Ocean" => Some(Biome::DeepOcean),
            "Stone Shore" => Some(Biome::StoneShore),
            "Snowy Beach" => Some(Biome::SnowyBeach),
            "Birch Forest" => Some(Biome::BirchForest),
            "Birch Forest Hills" => Some(Biome::BirchForestHills),
            "Dark Forest" => Some(Biome::DarkForest),
            "Snowy Taiga" => Some(Biome::SnowyTaiga),
            "Snowy Taiga Hills" => Some(Biome::SnowyTaigaHills),
            "Giant Tree Taiga" => Some(Biome::GiantTreeTaiga),
            "Giant Tree Taiga Hills" => Some(Biome::GiantTreeTaigaHills),
            "Wooded Mountains" => Some(Biome::WoodedMountains),
            "Savanna" => Some(Biome::Savanna),
            "Savanna Plateau" => Some(Biome::SavannaPlateau),
            "Badlands" => Some(Biome::Badlands),
            "Wooded Badlands Plateau" => Some(Biome::WoodedBadlandsPlateau),
            "Badlands Plateau" => Some(Biome::BadlandsPlateau),
            "Small End Islands" => Some(Biome::SmallEndIslands),
            "End Midlands" => Some(Biome::EndMidlands),
            "End Highlands" => Some(Biome::EndHighlands),
            "End Barrens" => Some(Biome::EndBarrens),
            "Warm Ocean" => Some(Biome::WarmOcean),
            "Lukewarm Ocean" => Some(Biome::LukewarmOcean),
            "Cold Ocean" => Some(Biome::ColdOcean),
            "Deep Warm Ocean" => Some(Biome::DeepWarmOcean),
            "Deep Lukewarm Ocean" => Some(Biome::DeepLukewarmOcean),
            "Deep Cold Ocean" => Some(Biome::DeepColdOcean),
            "Deep Frozen Ocean" => Some(Biome::DeepFrozenOcean),
            "the_void" => Some(Biome::TheVoid),
            "Sunflower Plains" => Some(Biome::SunflowerPlains),
            "Desert Lakes" => Some(Biome::DesertLakes),
            "Gravelly Mountains" => Some(Biome::GravellyMountains),
            "Flower Forest" => Some(Biome::FlowerForest),
            "Taiga Mountains" => Some(Biome::TaigaMountains),
            "Swamp Hills" => Some(Biome::SwampHills),
            "Ice Spikes" => Some(Biome::IceSpikes),
            "Modified Jungle" => Some(Biome::ModifiedJungle),
            "Modified Jungle Edge" => Some(Biome::ModifiedJungleEdge),
            "Tall Birch Forest" => Some(Biome::TallBirchForest),
            "Tall Birch Hills" => Some(Biome::TallBirchHills),
            "Dark Forest Hills" => Some(Biome::DarkForestHills),
            "Snowy Taiga Mountains" => Some(Biome::SnowyTaigaMountains),
            "Giant Spruce Taiga" => Some(Biome::GiantSpruceTaiga),
            "Giant Spruce Taiga Hills" => Some(Biome::GiantSpruceTaigaHills),
            "Gravelly Mountains+" => Some(Biome::ModifiedGravellyMountains),
            "Shattered Savanna" => Some(Biome::ShatteredSavanna),
            "Shattered Savanna Plateau" => Some(Biome::ShatteredSavannaPlateau),
            "Eroded Badlands" => Some(Biome::ErodedBadlands),
            "Modified Wooded Badlands Plateau" => Some(Biome::ModifiedWoodedBadlandsPlateau),
            "Modified Badlands Plateau" => Some(Biome::ModifiedBadlandsPlateau),
            "Bamboo Jungle" => Some(Biome::BambooJungle),
            "Bamboo Jungle Hills" => Some(Biome::BambooJungleHills),
            "Soul Sand Valley" => Some(Biome::SoulSandValley),
            "Crimson Forest" => Some(Biome::CrimsonForest),
            "Warped Forest" => Some(Biome::WarpedForest),
            "Basalt Deltas" => Some(Biome::BasaltDeltas),
            _ => None,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Biome {
    /// Returns the `rainfall` property of this `Biome`.
    pub fn rainfall(&self) -> f32 {
        match self {
            Biome::Ocean => 0.5 as f32,
            Biome::Plains => 0.4 as f32,
            Biome::Desert => 0 as f32,
            Biome::Mountains => 0.3 as f32,
            Biome::Forest => 0.8 as f32,
            Biome::Taiga => 0.8 as f32,
            Biome::Swamp => 0.9 as f32,
            Biome::River => 0.5 as f32,
            Biome::NetherWastes => 0 as f32,
            Biome::TheEnd => 0.5 as f32,
            Biome::FrozenOcean => 0.5 as f32,
            Biome::FrozenRiver => 0.5 as f32,
            Biome::SnowyTundra => 0.5 as f32,
            Biome::SnowyMountains => 0.5 as f32,
            Biome::MushroomFields => 1 as f32,
            Biome::MushroomFieldShore => 1 as f32,
            Biome::Beach => 0.4 as f32,
            Biome::DesertHills => 0 as f32,
            Biome::WoodedHills => 0.8 as f32,
            Biome::TaigaHills => 0.8 as f32,
            Biome::MountainEdge => 0.3 as f32,
            Biome::Jungle => 0.9 as f32,
            Biome::JungleHills => 0.9 as f32,
            Biome::JungleEdge => 0.8 as f32,
            Biome::DeepOcean => 0.5 as f32,
            Biome::StoneShore => 0.3 as f32,
            Biome::SnowyBeach => 0.3 as f32,
            Biome::BirchForest => 0.6 as f32,
            Biome::BirchForestHills => 0.6 as f32,
            Biome::DarkForest => 0.8 as f32,
            Biome::SnowyTaiga => 0.4 as f32,
            Biome::SnowyTaigaHills => 0.4 as f32,
            Biome::GiantTreeTaiga => 0.8 as f32,
            Biome::GiantTreeTaigaHills => 0.8 as f32,
            Biome::WoodedMountains => 0.3 as f32,
            Biome::Savanna => 0 as f32,
            Biome::SavannaPlateau => 0 as f32,
            Biome::Badlands => 0 as f32,
            Biome::WoodedBadlandsPlateau => 0 as f32,
            Biome::BadlandsPlateau => 0 as f32,
            Biome::SmallEndIslands => 0.5 as f32,
            Biome::EndMidlands => 0.5 as f32,
            Biome::EndHighlands => 0.5 as f32,
            Biome::EndBarrens => 0.5 as f32,
            Biome::WarmOcean => 0.5 as f32,
            Biome::LukewarmOcean => 0.5 as f32,
            Biome::ColdOcean => 0.5 as f32,
            Biome::DeepWarmOcean => 0.5 as f32,
            Biome::DeepLukewarmOcean => 0.5 as f32,
            Biome::DeepColdOcean => 0.5 as f32,
            Biome::DeepFrozenOcean => 0.5 as f32,
            Biome::TheVoid => 0.5 as f32,
            Biome::SunflowerPlains => 0.4 as f32,
            Biome::DesertLakes => 0 as f32,
            Biome::GravellyMountains => 0.3 as f32,
            Biome::FlowerForest => 0.8 as f32,
            Biome::TaigaMountains => 0.8 as f32,
            Biome::SwampHills => 0.9 as f32,
            Biome::IceSpikes => 0.5 as f32,
            Biome::ModifiedJungle => 0.9 as f32,
            Biome::ModifiedJungleEdge => 0.8 as f32,
            Biome::TallBirchForest => 0.6 as f32,
            Biome::TallBirchHills => 0.6 as f32,
            Biome::DarkForestHills => 0.8 as f32,
            Biome::SnowyTaigaMountains => 0.4 as f32,
            Biome::GiantSpruceTaiga => 0.8 as f32,
            Biome::GiantSpruceTaigaHills => 0.8 as f32,
            Biome::ModifiedGravellyMountains => 0.3 as f32,
            Biome::ShatteredSavanna => 0 as f32,
            Biome::ShatteredSavannaPlateau => 0 as f32,
            Biome::ErodedBadlands => 0 as f32,
            Biome::ModifiedWoodedBadlandsPlateau => 0 as f32,
            Biome::ModifiedBadlandsPlateau => 0 as f32,
            Biome::BambooJungle => 0.9 as f32,
            Biome::BambooJungleHills => 0.9 as f32,
            Biome::SoulSandValley => 0 as f32,
            Biome::CrimsonForest => 0 as f32,
            Biome::WarpedForest => 0 as f32,
            Biome::BasaltDeltas => 0 as f32,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Biome {
    /// Returns the `temperature` property of this `Biome`.
    pub fn temperature(&self) -> f32 {
        match self {
            Biome::Ocean => 0.5 as f32,
            Biome::Plains => 0.8 as f32,
            Biome::Desert => 2 as f32,
            Biome::Mountains => 0.2 as f32,
            Biome::Forest => 0.7 as f32,
            Biome::Taiga => 0.25 as f32,
            Biome::Swamp => 0.8 as f32,
            Biome::River => 0.5 as f32,
            Biome::NetherWastes => 2 as f32,
            Biome::TheEnd => 0.5 as f32,
            Biome::FrozenOcean => 0 as f32,
            Biome::FrozenRiver => 0 as f32,
            Biome::SnowyTundra => 0 as f32,
            Biome::SnowyMountains => 0 as f32,
            Biome::MushroomFields => 0.9 as f32,
            Biome::MushroomFieldShore => 0.9 as f32,
            Biome::Beach => 0.8 as f32,
            Biome::DesertHills => 2 as f32,
            Biome::WoodedHills => 0.7 as f32,
            Biome::TaigaHills => 0.25 as f32,
            Biome::MountainEdge => 0.2 as f32,
            Biome::Jungle => 0.95 as f32,
            Biome::JungleHills => 0.95 as f32,
            Biome::JungleEdge => 0.95 as f32,
            Biome::DeepOcean => 0.5 as f32,
            Biome::StoneShore => 0.2 as f32,
            Biome::SnowyBeach => 0.05 as f32,
            Biome::BirchForest => 0.6 as f32,
            Biome::BirchForestHills => 0.6 as f32,
            Biome::DarkForest => 0.7 as f32,
            Biome::SnowyTaiga => -0.5 as f32,
            Biome::SnowyTaigaHills => -0.5 as f32,
            Biome::GiantTreeTaiga => 0.3 as f32,
            Biome::GiantTreeTaigaHills => 0.3 as f32,
            Biome::WoodedMountains => 0.2 as f32,
            Biome::Savanna => 1.2 as f32,
            Biome::SavannaPlateau => 1 as f32,
            Biome::Badlands => 2 as f32,
            Biome::WoodedBadlandsPlateau => 2 as f32,
            Biome::BadlandsPlateau => 2 as f32,
            Biome::SmallEndIslands => 0.5 as f32,
            Biome::EndMidlands => 0.5 as f32,
            Biome::EndHighlands => 0.5 as f32,
            Biome::EndBarrens => 0.5 as f32,
            Biome::WarmOcean => 0.5 as f32,
            Biome::LukewarmOcean => 0.5 as f32,
            Biome::ColdOcean => 0.5 as f32,
            Biome::DeepWarmOcean => 0.5 as f32,
            Biome::DeepLukewarmOcean => 0.5 as f32,
            Biome::DeepColdOcean => 0.5 as f32,
            Biome::DeepFrozenOcean => 0.5 as f32,
            Biome::TheVoid => 0.5 as f32,
            Biome::SunflowerPlains => 0.8 as f32,
            Biome::DesertLakes => 2 as f32,
            Biome::GravellyMountains => 0.2 as f32,
            Biome::FlowerForest => 0.7 as f32,
            Biome::TaigaMountains => 0.25 as f32,
            Biome::SwampHills => 0.8 as f32,
            Biome::IceSpikes => 0 as f32,
            Biome::ModifiedJungle => 0.95 as f32,
            Biome::ModifiedJungleEdge => 0.95 as f32,
            Biome::TallBirchForest => 0.6 as f32,
            Biome::TallBirchHills => 0.6 as f32,
            Biome::DarkForestHills => 0.7 as f32,
            Biome::SnowyTaigaMountains => -0.5 as f32,
            Biome::GiantSpruceTaiga => 0.25 as f32,
            Biome::GiantSpruceTaigaHills => 0.25 as f32,
            Biome::ModifiedGravellyMountains => 0.2 as f32,
            Biome::ShatteredSavanna => 1.1 as f32,
            Biome::ShatteredSavannaPlateau => 1 as f32,
            Biome::ErodedBadlands => 2 as f32,
            Biome::ModifiedWoodedBadlandsPlateau => 2 as f32,
            Biome::ModifiedBadlandsPlateau => 2 as f32,
            Biome::BambooJungle => 0.95 as f32,
            Biome::BambooJungleHills => 0.95 as f32,
            Biome::SoulSandValley => 2 as f32,
            Biome::CrimsonForest => 2 as f32,
            Biome::WarpedForest => 2 as f32,
            Biome::BasaltDeltas => 2 as f32,
        }
    }
}
