// This file is @generated. Please do not edit.
#[derive(
    Copy,
    Clone,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    serde :: Serialize,
    serde :: Deserialize,
    bincode :: Encode,
    bincode :: Decode,
)]
#[serde(try_from = "String", into = "&'static str")]
pub enum EntityKind {
    AreaEffectCloud,
    ArmorStand,
    Arrow,
    Axolotl,
    Bat,
    Bee,
    Blaze,
    Boat,
    Cat,
    CaveSpider,
    Chicken,
    Cod,
    Cow,
    Creeper,
    Dolphin,
    Donkey,
    DragonFireball,
    Drowned,
    ElderGuardian,
    EndCrystal,
    EnderDragon,
    Enderman,
    Endermite,
    Evoker,
    EvokerFangs,
    ExperienceOrb,
    EyeOfEnder,
    FallingBlock,
    FireworkRocket,
    Fox,
    Ghast,
    Giant,
    GlowItemFrame,
    GlowSquid,
    Goat,
    Guardian,
    Hoglin,
    Horse,
    Husk,
    Illusioner,
    IronGolem,
    Item,
    ItemFrame,
    Fireball,
    LeashKnot,
    LightningBolt,
    Llama,
    LlamaSpit,
    MagmaCube,
    Marker,
    Minecart,
    ChestMinecart,
    CommandBlockMinecart,
    FurnaceMinecart,
    HopperMinecart,
    SpawnerMinecart,
    TntMinecart,
    Mule,
    Mooshroom,
    Ocelot,
    Painting,
    Panda,
    Parrot,
    Phantom,
    Pig,
    Piglin,
    PiglinBrute,
    Pillager,
    PolarBear,
    Tnt,
    Pufferfish,
    Rabbit,
    Ravager,
    Salmon,
    Sheep,
    Shulker,
    ShulkerBullet,
    Silverfish,
    Skeleton,
    SkeletonHorse,
    Slime,
    SmallFireball,
    SnowGolem,
    Snowball,
    SpectralArrow,
    Spider,
    Squid,
    Stray,
    Strider,
    Egg,
    EnderPearl,
    ExperienceBottle,
    Potion,
    Trident,
    TraderLlama,
    TropicalFish,
    Turtle,
    Vex,
    Villager,
    Vindicator,
    WanderingTrader,
    Witch,
    Wither,
    WitherSkeleton,
    WitherSkull,
    Wolf,
    Zoglin,
    Zombie,
    ZombieHorse,
    ZombieVillager,
    ZombifiedPiglin,
    Player,
    FishingBobber,
}
impl EntityKind {
    #[inline]
    pub fn values() -> &'static [EntityKind] {
        use EntityKind::*;
        &[
            AreaEffectCloud,
            ArmorStand,
            Arrow,
            Axolotl,
            Bat,
            Bee,
            Blaze,
            Boat,
            Cat,
            CaveSpider,
            Chicken,
            Cod,
            Cow,
            Creeper,
            Dolphin,
            Donkey,
            DragonFireball,
            Drowned,
            ElderGuardian,
            EndCrystal,
            EnderDragon,
            Enderman,
            Endermite,
            Evoker,
            EvokerFangs,
            ExperienceOrb,
            EyeOfEnder,
            FallingBlock,
            FireworkRocket,
            Fox,
            Ghast,
            Giant,
            GlowItemFrame,
            GlowSquid,
            Goat,
            Guardian,
            Hoglin,
            Horse,
            Husk,
            Illusioner,
            IronGolem,
            Item,
            ItemFrame,
            Fireball,
            LeashKnot,
            LightningBolt,
            Llama,
            LlamaSpit,
            MagmaCube,
            Marker,
            Minecart,
            ChestMinecart,
            CommandBlockMinecart,
            FurnaceMinecart,
            HopperMinecart,
            SpawnerMinecart,
            TntMinecart,
            Mule,
            Mooshroom,
            Ocelot,
            Painting,
            Panda,
            Parrot,
            Phantom,
            Pig,
            Piglin,
            PiglinBrute,
            Pillager,
            PolarBear,
            Tnt,
            Pufferfish,
            Rabbit,
            Ravager,
            Salmon,
            Sheep,
            Shulker,
            ShulkerBullet,
            Silverfish,
            Skeleton,
            SkeletonHorse,
            Slime,
            SmallFireball,
            SnowGolem,
            Snowball,
            SpectralArrow,
            Spider,
            Squid,
            Stray,
            Strider,
            Egg,
            EnderPearl,
            ExperienceBottle,
            Potion,
            Trident,
            TraderLlama,
            TropicalFish,
            Turtle,
            Vex,
            Villager,
            Vindicator,
            WanderingTrader,
            Witch,
            Wither,
            WitherSkeleton,
            WitherSkull,
            Wolf,
            Zoglin,
            Zombie,
            ZombieHorse,
            ZombieVillager,
            ZombifiedPiglin,
            Player,
            FishingBobber,
        ]
    }
}
impl EntityKind {
    #[doc = "Returns the `id` property of this `EntityKind`."]
    #[inline]
    pub fn id(&self) -> u32 {
        match self {
            EntityKind::AreaEffectCloud => 0u32,
            EntityKind::ArmorStand => 1u32,
            EntityKind::Arrow => 2u32,
            EntityKind::Axolotl => 3u32,
            EntityKind::Bat => 4u32,
            EntityKind::Bee => 5u32,
            EntityKind::Blaze => 6u32,
            EntityKind::Boat => 7u32,
            EntityKind::Cat => 8u32,
            EntityKind::CaveSpider => 9u32,
            EntityKind::Chicken => 10u32,
            EntityKind::Cod => 11u32,
            EntityKind::Cow => 12u32,
            EntityKind::Creeper => 13u32,
            EntityKind::Dolphin => 14u32,
            EntityKind::Donkey => 15u32,
            EntityKind::DragonFireball => 16u32,
            EntityKind::Drowned => 17u32,
            EntityKind::ElderGuardian => 18u32,
            EntityKind::EndCrystal => 19u32,
            EntityKind::EnderDragon => 20u32,
            EntityKind::Enderman => 21u32,
            EntityKind::Endermite => 22u32,
            EntityKind::Evoker => 23u32,
            EntityKind::EvokerFangs => 24u32,
            EntityKind::ExperienceOrb => 25u32,
            EntityKind::EyeOfEnder => 26u32,
            EntityKind::FallingBlock => 27u32,
            EntityKind::FireworkRocket => 28u32,
            EntityKind::Fox => 29u32,
            EntityKind::Ghast => 30u32,
            EntityKind::Giant => 31u32,
            EntityKind::GlowItemFrame => 32u32,
            EntityKind::GlowSquid => 33u32,
            EntityKind::Goat => 34u32,
            EntityKind::Guardian => 35u32,
            EntityKind::Hoglin => 36u32,
            EntityKind::Horse => 37u32,
            EntityKind::Husk => 38u32,
            EntityKind::Illusioner => 39u32,
            EntityKind::IronGolem => 40u32,
            EntityKind::Item => 41u32,
            EntityKind::ItemFrame => 42u32,
            EntityKind::Fireball => 43u32,
            EntityKind::LeashKnot => 44u32,
            EntityKind::LightningBolt => 45u32,
            EntityKind::Llama => 46u32,
            EntityKind::LlamaSpit => 47u32,
            EntityKind::MagmaCube => 48u32,
            EntityKind::Marker => 49u32,
            EntityKind::Minecart => 50u32,
            EntityKind::ChestMinecart => 51u32,
            EntityKind::CommandBlockMinecart => 52u32,
            EntityKind::FurnaceMinecart => 53u32,
            EntityKind::HopperMinecart => 54u32,
            EntityKind::SpawnerMinecart => 55u32,
            EntityKind::TntMinecart => 56u32,
            EntityKind::Mule => 57u32,
            EntityKind::Mooshroom => 58u32,
            EntityKind::Ocelot => 59u32,
            EntityKind::Painting => 60u32,
            EntityKind::Panda => 61u32,
            EntityKind::Parrot => 62u32,
            EntityKind::Phantom => 63u32,
            EntityKind::Pig => 64u32,
            EntityKind::Piglin => 65u32,
            EntityKind::PiglinBrute => 66u32,
            EntityKind::Pillager => 67u32,
            EntityKind::PolarBear => 68u32,
            EntityKind::Tnt => 69u32,
            EntityKind::Pufferfish => 70u32,
            EntityKind::Rabbit => 71u32,
            EntityKind::Ravager => 72u32,
            EntityKind::Salmon => 73u32,
            EntityKind::Sheep => 74u32,
            EntityKind::Shulker => 75u32,
            EntityKind::ShulkerBullet => 76u32,
            EntityKind::Silverfish => 77u32,
            EntityKind::Skeleton => 78u32,
            EntityKind::SkeletonHorse => 79u32,
            EntityKind::Slime => 80u32,
            EntityKind::SmallFireball => 81u32,
            EntityKind::SnowGolem => 82u32,
            EntityKind::Snowball => 83u32,
            EntityKind::SpectralArrow => 84u32,
            EntityKind::Spider => 85u32,
            EntityKind::Squid => 86u32,
            EntityKind::Stray => 87u32,
            EntityKind::Strider => 88u32,
            EntityKind::Egg => 89u32,
            EntityKind::EnderPearl => 90u32,
            EntityKind::ExperienceBottle => 91u32,
            EntityKind::Potion => 92u32,
            EntityKind::Trident => 93u32,
            EntityKind::TraderLlama => 94u32,
            EntityKind::TropicalFish => 95u32,
            EntityKind::Turtle => 96u32,
            EntityKind::Vex => 97u32,
            EntityKind::Villager => 98u32,
            EntityKind::Vindicator => 99u32,
            EntityKind::WanderingTrader => 100u32,
            EntityKind::Witch => 101u32,
            EntityKind::Wither => 102u32,
            EntityKind::WitherSkeleton => 103u32,
            EntityKind::WitherSkull => 104u32,
            EntityKind::Wolf => 105u32,
            EntityKind::Zoglin => 106u32,
            EntityKind::Zombie => 107u32,
            EntityKind::ZombieHorse => 108u32,
            EntityKind::ZombieVillager => 109u32,
            EntityKind::ZombifiedPiglin => 110u32,
            EntityKind::Player => 111u32,
            EntityKind::FishingBobber => 112u32,
        }
    }
    #[doc = "Gets a `EntityKind` by its `id`."]
    #[inline]
    pub fn from_id(id: u32) -> Option<Self> {
        match id {
            0u32 => Some(EntityKind::AreaEffectCloud),
            1u32 => Some(EntityKind::ArmorStand),
            2u32 => Some(EntityKind::Arrow),
            3u32 => Some(EntityKind::Axolotl),
            4u32 => Some(EntityKind::Bat),
            5u32 => Some(EntityKind::Bee),
            6u32 => Some(EntityKind::Blaze),
            7u32 => Some(EntityKind::Boat),
            8u32 => Some(EntityKind::Cat),
            9u32 => Some(EntityKind::CaveSpider),
            10u32 => Some(EntityKind::Chicken),
            11u32 => Some(EntityKind::Cod),
            12u32 => Some(EntityKind::Cow),
            13u32 => Some(EntityKind::Creeper),
            14u32 => Some(EntityKind::Dolphin),
            15u32 => Some(EntityKind::Donkey),
            16u32 => Some(EntityKind::DragonFireball),
            17u32 => Some(EntityKind::Drowned),
            18u32 => Some(EntityKind::ElderGuardian),
            19u32 => Some(EntityKind::EndCrystal),
            20u32 => Some(EntityKind::EnderDragon),
            21u32 => Some(EntityKind::Enderman),
            22u32 => Some(EntityKind::Endermite),
            23u32 => Some(EntityKind::Evoker),
            24u32 => Some(EntityKind::EvokerFangs),
            25u32 => Some(EntityKind::ExperienceOrb),
            26u32 => Some(EntityKind::EyeOfEnder),
            27u32 => Some(EntityKind::FallingBlock),
            28u32 => Some(EntityKind::FireworkRocket),
            29u32 => Some(EntityKind::Fox),
            30u32 => Some(EntityKind::Ghast),
            31u32 => Some(EntityKind::Giant),
            32u32 => Some(EntityKind::GlowItemFrame),
            33u32 => Some(EntityKind::GlowSquid),
            34u32 => Some(EntityKind::Goat),
            35u32 => Some(EntityKind::Guardian),
            36u32 => Some(EntityKind::Hoglin),
            37u32 => Some(EntityKind::Horse),
            38u32 => Some(EntityKind::Husk),
            39u32 => Some(EntityKind::Illusioner),
            40u32 => Some(EntityKind::IronGolem),
            41u32 => Some(EntityKind::Item),
            42u32 => Some(EntityKind::ItemFrame),
            43u32 => Some(EntityKind::Fireball),
            44u32 => Some(EntityKind::LeashKnot),
            45u32 => Some(EntityKind::LightningBolt),
            46u32 => Some(EntityKind::Llama),
            47u32 => Some(EntityKind::LlamaSpit),
            48u32 => Some(EntityKind::MagmaCube),
            49u32 => Some(EntityKind::Marker),
            50u32 => Some(EntityKind::Minecart),
            51u32 => Some(EntityKind::ChestMinecart),
            52u32 => Some(EntityKind::CommandBlockMinecart),
            53u32 => Some(EntityKind::FurnaceMinecart),
            54u32 => Some(EntityKind::HopperMinecart),
            55u32 => Some(EntityKind::SpawnerMinecart),
            56u32 => Some(EntityKind::TntMinecart),
            57u32 => Some(EntityKind::Mule),
            58u32 => Some(EntityKind::Mooshroom),
            59u32 => Some(EntityKind::Ocelot),
            60u32 => Some(EntityKind::Painting),
            61u32 => Some(EntityKind::Panda),
            62u32 => Some(EntityKind::Parrot),
            63u32 => Some(EntityKind::Phantom),
            64u32 => Some(EntityKind::Pig),
            65u32 => Some(EntityKind::Piglin),
            66u32 => Some(EntityKind::PiglinBrute),
            67u32 => Some(EntityKind::Pillager),
            68u32 => Some(EntityKind::PolarBear),
            69u32 => Some(EntityKind::Tnt),
            70u32 => Some(EntityKind::Pufferfish),
            71u32 => Some(EntityKind::Rabbit),
            72u32 => Some(EntityKind::Ravager),
            73u32 => Some(EntityKind::Salmon),
            74u32 => Some(EntityKind::Sheep),
            75u32 => Some(EntityKind::Shulker),
            76u32 => Some(EntityKind::ShulkerBullet),
            77u32 => Some(EntityKind::Silverfish),
            78u32 => Some(EntityKind::Skeleton),
            79u32 => Some(EntityKind::SkeletonHorse),
            80u32 => Some(EntityKind::Slime),
            81u32 => Some(EntityKind::SmallFireball),
            82u32 => Some(EntityKind::SnowGolem),
            83u32 => Some(EntityKind::Snowball),
            84u32 => Some(EntityKind::SpectralArrow),
            85u32 => Some(EntityKind::Spider),
            86u32 => Some(EntityKind::Squid),
            87u32 => Some(EntityKind::Stray),
            88u32 => Some(EntityKind::Strider),
            89u32 => Some(EntityKind::Egg),
            90u32 => Some(EntityKind::EnderPearl),
            91u32 => Some(EntityKind::ExperienceBottle),
            92u32 => Some(EntityKind::Potion),
            93u32 => Some(EntityKind::Trident),
            94u32 => Some(EntityKind::TraderLlama),
            95u32 => Some(EntityKind::TropicalFish),
            96u32 => Some(EntityKind::Turtle),
            97u32 => Some(EntityKind::Vex),
            98u32 => Some(EntityKind::Villager),
            99u32 => Some(EntityKind::Vindicator),
            100u32 => Some(EntityKind::WanderingTrader),
            101u32 => Some(EntityKind::Witch),
            102u32 => Some(EntityKind::Wither),
            103u32 => Some(EntityKind::WitherSkeleton),
            104u32 => Some(EntityKind::WitherSkull),
            105u32 => Some(EntityKind::Wolf),
            106u32 => Some(EntityKind::Zoglin),
            107u32 => Some(EntityKind::Zombie),
            108u32 => Some(EntityKind::ZombieHorse),
            109u32 => Some(EntityKind::ZombieVillager),
            110u32 => Some(EntityKind::ZombifiedPiglin),
            111u32 => Some(EntityKind::Player),
            112u32 => Some(EntityKind::FishingBobber),
            _ => None,
        }
    }
}
impl EntityKind {
    #[doc = "Returns the `width` property of this `EntityKind`."]
    #[inline]
    pub fn width(&self) -> f32 {
        match self {
            EntityKind::AreaEffectCloud => 6f32,
            EntityKind::ArmorStand => 0.5f32,
            EntityKind::Arrow => 0.5f32,
            EntityKind::Axolotl => 0.75f32,
            EntityKind::Bat => 0.5f32,
            EntityKind::Bee => 0.7f32,
            EntityKind::Blaze => 0.6f32,
            EntityKind::Boat => 1.375f32,
            EntityKind::Cat => 0.6f32,
            EntityKind::CaveSpider => 0.7f32,
            EntityKind::Chicken => 0.4f32,
            EntityKind::Cod => 0.5f32,
            EntityKind::Cow => 0.9f32,
            EntityKind::Creeper => 0.6f32,
            EntityKind::Dolphin => 0.9f32,
            EntityKind::Donkey => 1.39648f32,
            EntityKind::DragonFireball => 1f32,
            EntityKind::Drowned => 0.6f32,
            EntityKind::ElderGuardian => 1.9975f32,
            EntityKind::EndCrystal => 2f32,
            EntityKind::EnderDragon => 16f32,
            EntityKind::Enderman => 0.6f32,
            EntityKind::Endermite => 0.4f32,
            EntityKind::Evoker => 0.6f32,
            EntityKind::EvokerFangs => 0.5f32,
            EntityKind::ExperienceOrb => 0.5f32,
            EntityKind::EyeOfEnder => 0.25f32,
            EntityKind::FallingBlock => 0.98f32,
            EntityKind::FireworkRocket => 0.25f32,
            EntityKind::Fox => 0.6f32,
            EntityKind::Ghast => 4f32,
            EntityKind::Giant => 3.6f32,
            EntityKind::GlowItemFrame => 0.5f32,
            EntityKind::GlowSquid => 0.8f32,
            EntityKind::Goat => 0.9f32,
            EntityKind::Guardian => 0.85f32,
            EntityKind::Hoglin => 1.39648f32,
            EntityKind::Horse => 1.39648f32,
            EntityKind::Husk => 0.6f32,
            EntityKind::Illusioner => 0.6f32,
            EntityKind::IronGolem => 1.4f32,
            EntityKind::Item => 0.25f32,
            EntityKind::ItemFrame => 0.5f32,
            EntityKind::Fireball => 1f32,
            EntityKind::LeashKnot => 0.375f32,
            EntityKind::LightningBolt => 0f32,
            EntityKind::Llama => 0.9f32,
            EntityKind::LlamaSpit => 0.25f32,
            EntityKind::MagmaCube => 2.04f32,
            EntityKind::Marker => 0f32,
            EntityKind::Minecart => 0.98f32,
            EntityKind::ChestMinecart => 0.98f32,
            EntityKind::CommandBlockMinecart => 0.98f32,
            EntityKind::FurnaceMinecart => 0.98f32,
            EntityKind::HopperMinecart => 0.98f32,
            EntityKind::SpawnerMinecart => 0.98f32,
            EntityKind::TntMinecart => 0.98f32,
            EntityKind::Mule => 1.39648f32,
            EntityKind::Mooshroom => 0.9f32,
            EntityKind::Ocelot => 0.6f32,
            EntityKind::Painting => 0.5f32,
            EntityKind::Panda => 1.3f32,
            EntityKind::Parrot => 0.5f32,
            EntityKind::Phantom => 0.9f32,
            EntityKind::Pig => 0.9f32,
            EntityKind::Piglin => 0.6f32,
            EntityKind::PiglinBrute => 0.6f32,
            EntityKind::Pillager => 0.6f32,
            EntityKind::PolarBear => 1.4f32,
            EntityKind::Tnt => 0.98f32,
            EntityKind::Pufferfish => 0.7f32,
            EntityKind::Rabbit => 0.4f32,
            EntityKind::Ravager => 1.95f32,
            EntityKind::Salmon => 0.7f32,
            EntityKind::Sheep => 0.9f32,
            EntityKind::Shulker => 1f32,
            EntityKind::ShulkerBullet => 0.3125f32,
            EntityKind::Silverfish => 0.4f32,
            EntityKind::Skeleton => 0.6f32,
            EntityKind::SkeletonHorse => 1.39648f32,
            EntityKind::Slime => 2.04f32,
            EntityKind::SmallFireball => 0.3125f32,
            EntityKind::SnowGolem => 0.7f32,
            EntityKind::Snowball => 0.25f32,
            EntityKind::SpectralArrow => 0.5f32,
            EntityKind::Spider => 1.4f32,
            EntityKind::Squid => 0.8f32,
            EntityKind::Stray => 0.6f32,
            EntityKind::Strider => 0.9f32,
            EntityKind::Egg => 0.25f32,
            EntityKind::EnderPearl => 0.25f32,
            EntityKind::ExperienceBottle => 0.25f32,
            EntityKind::Potion => 0.25f32,
            EntityKind::Trident => 0.5f32,
            EntityKind::TraderLlama => 0.9f32,
            EntityKind::TropicalFish => 0.5f32,
            EntityKind::Turtle => 1.2f32,
            EntityKind::Vex => 0.4f32,
            EntityKind::Villager => 0.6f32,
            EntityKind::Vindicator => 0.6f32,
            EntityKind::WanderingTrader => 0.6f32,
            EntityKind::Witch => 0.6f32,
            EntityKind::Wither => 0.9f32,
            EntityKind::WitherSkeleton => 0.7f32,
            EntityKind::WitherSkull => 0.3125f32,
            EntityKind::Wolf => 0.6f32,
            EntityKind::Zoglin => 1.39648f32,
            EntityKind::Zombie => 0.6f32,
            EntityKind::ZombieHorse => 1.39648f32,
            EntityKind::ZombieVillager => 0.6f32,
            EntityKind::ZombifiedPiglin => 0.6f32,
            EntityKind::Player => 0.6f32,
            EntityKind::FishingBobber => 0.25f32,
        }
    }
}
impl EntityKind {
    #[doc = "Returns the `height` property of this `EntityKind`."]
    #[inline]
    pub fn height(&self) -> f32 {
        match self {
            EntityKind::AreaEffectCloud => 0.5f32,
            EntityKind::ArmorStand => 1.975f32,
            EntityKind::Arrow => 0.5f32,
            EntityKind::Axolotl => 0.42f32,
            EntityKind::Bat => 0.9f32,
            EntityKind::Bee => 0.6f32,
            EntityKind::Blaze => 1.8f32,
            EntityKind::Boat => 0.5625f32,
            EntityKind::Cat => 0.7f32,
            EntityKind::CaveSpider => 0.5f32,
            EntityKind::Chicken => 0.7f32,
            EntityKind::Cod => 0.3f32,
            EntityKind::Cow => 1.4f32,
            EntityKind::Creeper => 1.7f32,
            EntityKind::Dolphin => 0.6f32,
            EntityKind::Donkey => 1.5f32,
            EntityKind::DragonFireball => 1f32,
            EntityKind::Drowned => 1.95f32,
            EntityKind::ElderGuardian => 1.9975f32,
            EntityKind::EndCrystal => 2f32,
            EntityKind::EnderDragon => 8f32,
            EntityKind::Enderman => 2.9f32,
            EntityKind::Endermite => 0.3f32,
            EntityKind::Evoker => 1.95f32,
            EntityKind::EvokerFangs => 0.8f32,
            EntityKind::ExperienceOrb => 0.5f32,
            EntityKind::EyeOfEnder => 0.25f32,
            EntityKind::FallingBlock => 0.98f32,
            EntityKind::FireworkRocket => 0.25f32,
            EntityKind::Fox => 0.7f32,
            EntityKind::Ghast => 4f32,
            EntityKind::Giant => 12f32,
            EntityKind::GlowItemFrame => 0.5f32,
            EntityKind::GlowSquid => 0.8f32,
            EntityKind::Goat => 1.3f32,
            EntityKind::Guardian => 0.85f32,
            EntityKind::Hoglin => 1.4f32,
            EntityKind::Horse => 1.6f32,
            EntityKind::Husk => 1.95f32,
            EntityKind::Illusioner => 1.95f32,
            EntityKind::IronGolem => 2.7f32,
            EntityKind::Item => 0.25f32,
            EntityKind::ItemFrame => 0.5f32,
            EntityKind::Fireball => 1f32,
            EntityKind::LeashKnot => 0.5f32,
            EntityKind::LightningBolt => 0f32,
            EntityKind::Llama => 1.87f32,
            EntityKind::LlamaSpit => 0.25f32,
            EntityKind::MagmaCube => 2.04f32,
            EntityKind::Marker => 0f32,
            EntityKind::Minecart => 0.7f32,
            EntityKind::ChestMinecart => 0.7f32,
            EntityKind::CommandBlockMinecart => 0.7f32,
            EntityKind::FurnaceMinecart => 0.7f32,
            EntityKind::HopperMinecart => 0.7f32,
            EntityKind::SpawnerMinecart => 0.7f32,
            EntityKind::TntMinecart => 0.7f32,
            EntityKind::Mule => 1.6f32,
            EntityKind::Mooshroom => 1.4f32,
            EntityKind::Ocelot => 0.7f32,
            EntityKind::Painting => 0.5f32,
            EntityKind::Panda => 1.25f32,
            EntityKind::Parrot => 0.9f32,
            EntityKind::Phantom => 0.5f32,
            EntityKind::Pig => 0.9f32,
            EntityKind::Piglin => 1.95f32,
            EntityKind::PiglinBrute => 1.95f32,
            EntityKind::Pillager => 1.95f32,
            EntityKind::PolarBear => 1.4f32,
            EntityKind::Tnt => 0.98f32,
            EntityKind::Pufferfish => 0.7f32,
            EntityKind::Rabbit => 0.5f32,
            EntityKind::Ravager => 2.2f32,
            EntityKind::Salmon => 0.4f32,
            EntityKind::Sheep => 1.3f32,
            EntityKind::Shulker => 1f32,
            EntityKind::ShulkerBullet => 0.3125f32,
            EntityKind::Silverfish => 0.3f32,
            EntityKind::Skeleton => 1.99f32,
            EntityKind::SkeletonHorse => 1.6f32,
            EntityKind::Slime => 2.04f32,
            EntityKind::SmallFireball => 0.3125f32,
            EntityKind::SnowGolem => 1.9f32,
            EntityKind::Snowball => 0.25f32,
            EntityKind::SpectralArrow => 0.5f32,
            EntityKind::Spider => 0.9f32,
            EntityKind::Squid => 0.8f32,
            EntityKind::Stray => 1.99f32,
            EntityKind::Strider => 1.7f32,
            EntityKind::Egg => 0.25f32,
            EntityKind::EnderPearl => 0.25f32,
            EntityKind::ExperienceBottle => 0.25f32,
            EntityKind::Potion => 0.25f32,
            EntityKind::Trident => 0.5f32,
            EntityKind::TraderLlama => 1.87f32,
            EntityKind::TropicalFish => 0.4f32,
            EntityKind::Turtle => 0.4f32,
            EntityKind::Vex => 0.8f32,
            EntityKind::Villager => 1.95f32,
            EntityKind::Vindicator => 1.95f32,
            EntityKind::WanderingTrader => 1.95f32,
            EntityKind::Witch => 1.95f32,
            EntityKind::Wither => 3.5f32,
            EntityKind::WitherSkeleton => 2.4f32,
            EntityKind::WitherSkull => 0.3125f32,
            EntityKind::Wolf => 0.85f32,
            EntityKind::Zoglin => 1.4f32,
            EntityKind::Zombie => 1.95f32,
            EntityKind::ZombieHorse => 1.6f32,
            EntityKind::ZombieVillager => 1.95f32,
            EntityKind::ZombifiedPiglin => 1.95f32,
            EntityKind::Player => 1.8f32,
            EntityKind::FishingBobber => 0.25f32,
        }
    }
}
impl EntityKind {
    #[doc = "Returns the `name` property of this `EntityKind`."]
    #[inline]
    pub fn name(&self) -> &'static str {
        match self {
            EntityKind::AreaEffectCloud => "area_effect_cloud",
            EntityKind::ArmorStand => "armor_stand",
            EntityKind::Arrow => "arrow",
            EntityKind::Axolotl => "axolotl",
            EntityKind::Bat => "bat",
            EntityKind::Bee => "bee",
            EntityKind::Blaze => "blaze",
            EntityKind::Boat => "boat",
            EntityKind::Cat => "cat",
            EntityKind::CaveSpider => "cave_spider",
            EntityKind::Chicken => "chicken",
            EntityKind::Cod => "cod",
            EntityKind::Cow => "cow",
            EntityKind::Creeper => "creeper",
            EntityKind::Dolphin => "dolphin",
            EntityKind::Donkey => "donkey",
            EntityKind::DragonFireball => "dragon_fireball",
            EntityKind::Drowned => "drowned",
            EntityKind::ElderGuardian => "elder_guardian",
            EntityKind::EndCrystal => "end_crystal",
            EntityKind::EnderDragon => "ender_dragon",
            EntityKind::Enderman => "enderman",
            EntityKind::Endermite => "endermite",
            EntityKind::Evoker => "evoker",
            EntityKind::EvokerFangs => "evoker_fangs",
            EntityKind::ExperienceOrb => "experience_orb",
            EntityKind::EyeOfEnder => "eye_of_ender",
            EntityKind::FallingBlock => "falling_block",
            EntityKind::FireworkRocket => "firework_rocket",
            EntityKind::Fox => "fox",
            EntityKind::Ghast => "ghast",
            EntityKind::Giant => "giant",
            EntityKind::GlowItemFrame => "glow_item_frame",
            EntityKind::GlowSquid => "glow_squid",
            EntityKind::Goat => "goat",
            EntityKind::Guardian => "guardian",
            EntityKind::Hoglin => "hoglin",
            EntityKind::Horse => "horse",
            EntityKind::Husk => "husk",
            EntityKind::Illusioner => "illusioner",
            EntityKind::IronGolem => "iron_golem",
            EntityKind::Item => "item",
            EntityKind::ItemFrame => "item_frame",
            EntityKind::Fireball => "fireball",
            EntityKind::LeashKnot => "leash_knot",
            EntityKind::LightningBolt => "lightning_bolt",
            EntityKind::Llama => "llama",
            EntityKind::LlamaSpit => "llama_spit",
            EntityKind::MagmaCube => "magma_cube",
            EntityKind::Marker => "marker",
            EntityKind::Minecart => "minecart",
            EntityKind::ChestMinecart => "chest_minecart",
            EntityKind::CommandBlockMinecart => "command_block_minecart",
            EntityKind::FurnaceMinecart => "furnace_minecart",
            EntityKind::HopperMinecart => "hopper_minecart",
            EntityKind::SpawnerMinecart => "spawner_minecart",
            EntityKind::TntMinecart => "tnt_minecart",
            EntityKind::Mule => "mule",
            EntityKind::Mooshroom => "mooshroom",
            EntityKind::Ocelot => "ocelot",
            EntityKind::Painting => "painting",
            EntityKind::Panda => "panda",
            EntityKind::Parrot => "parrot",
            EntityKind::Phantom => "phantom",
            EntityKind::Pig => "pig",
            EntityKind::Piglin => "piglin",
            EntityKind::PiglinBrute => "piglin_brute",
            EntityKind::Pillager => "pillager",
            EntityKind::PolarBear => "polar_bear",
            EntityKind::Tnt => "tnt",
            EntityKind::Pufferfish => "pufferfish",
            EntityKind::Rabbit => "rabbit",
            EntityKind::Ravager => "ravager",
            EntityKind::Salmon => "salmon",
            EntityKind::Sheep => "sheep",
            EntityKind::Shulker => "shulker",
            EntityKind::ShulkerBullet => "shulker_bullet",
            EntityKind::Silverfish => "silverfish",
            EntityKind::Skeleton => "skeleton",
            EntityKind::SkeletonHorse => "skeleton_horse",
            EntityKind::Slime => "slime",
            EntityKind::SmallFireball => "small_fireball",
            EntityKind::SnowGolem => "snow_golem",
            EntityKind::Snowball => "snowball",
            EntityKind::SpectralArrow => "spectral_arrow",
            EntityKind::Spider => "spider",
            EntityKind::Squid => "squid",
            EntityKind::Stray => "stray",
            EntityKind::Strider => "strider",
            EntityKind::Egg => "egg",
            EntityKind::EnderPearl => "ender_pearl",
            EntityKind::ExperienceBottle => "experience_bottle",
            EntityKind::Potion => "potion",
            EntityKind::Trident => "trident",
            EntityKind::TraderLlama => "trader_llama",
            EntityKind::TropicalFish => "tropical_fish",
            EntityKind::Turtle => "turtle",
            EntityKind::Vex => "vex",
            EntityKind::Villager => "villager",
            EntityKind::Vindicator => "vindicator",
            EntityKind::WanderingTrader => "wandering_trader",
            EntityKind::Witch => "witch",
            EntityKind::Wither => "wither",
            EntityKind::WitherSkeleton => "wither_skeleton",
            EntityKind::WitherSkull => "wither_skull",
            EntityKind::Wolf => "wolf",
            EntityKind::Zoglin => "zoglin",
            EntityKind::Zombie => "zombie",
            EntityKind::ZombieHorse => "zombie_horse",
            EntityKind::ZombieVillager => "zombie_villager",
            EntityKind::ZombifiedPiglin => "zombified_piglin",
            EntityKind::Player => "player",
            EntityKind::FishingBobber => "fishing_bobber",
        }
    }
    #[doc = "Gets a `EntityKind` by its `name`."]
    #[inline]
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "area_effect_cloud" => Some(EntityKind::AreaEffectCloud),
            "armor_stand" => Some(EntityKind::ArmorStand),
            "arrow" => Some(EntityKind::Arrow),
            "axolotl" => Some(EntityKind::Axolotl),
            "bat" => Some(EntityKind::Bat),
            "bee" => Some(EntityKind::Bee),
            "blaze" => Some(EntityKind::Blaze),
            "boat" => Some(EntityKind::Boat),
            "cat" => Some(EntityKind::Cat),
            "cave_spider" => Some(EntityKind::CaveSpider),
            "chicken" => Some(EntityKind::Chicken),
            "cod" => Some(EntityKind::Cod),
            "cow" => Some(EntityKind::Cow),
            "creeper" => Some(EntityKind::Creeper),
            "dolphin" => Some(EntityKind::Dolphin),
            "donkey" => Some(EntityKind::Donkey),
            "dragon_fireball" => Some(EntityKind::DragonFireball),
            "drowned" => Some(EntityKind::Drowned),
            "elder_guardian" => Some(EntityKind::ElderGuardian),
            "end_crystal" => Some(EntityKind::EndCrystal),
            "ender_dragon" => Some(EntityKind::EnderDragon),
            "enderman" => Some(EntityKind::Enderman),
            "endermite" => Some(EntityKind::Endermite),
            "evoker" => Some(EntityKind::Evoker),
            "evoker_fangs" => Some(EntityKind::EvokerFangs),
            "experience_orb" => Some(EntityKind::ExperienceOrb),
            "eye_of_ender" => Some(EntityKind::EyeOfEnder),
            "falling_block" => Some(EntityKind::FallingBlock),
            "firework_rocket" => Some(EntityKind::FireworkRocket),
            "fox" => Some(EntityKind::Fox),
            "ghast" => Some(EntityKind::Ghast),
            "giant" => Some(EntityKind::Giant),
            "glow_item_frame" => Some(EntityKind::GlowItemFrame),
            "glow_squid" => Some(EntityKind::GlowSquid),
            "goat" => Some(EntityKind::Goat),
            "guardian" => Some(EntityKind::Guardian),
            "hoglin" => Some(EntityKind::Hoglin),
            "horse" => Some(EntityKind::Horse),
            "husk" => Some(EntityKind::Husk),
            "illusioner" => Some(EntityKind::Illusioner),
            "iron_golem" => Some(EntityKind::IronGolem),
            "item" => Some(EntityKind::Item),
            "item_frame" => Some(EntityKind::ItemFrame),
            "fireball" => Some(EntityKind::Fireball),
            "leash_knot" => Some(EntityKind::LeashKnot),
            "lightning_bolt" => Some(EntityKind::LightningBolt),
            "llama" => Some(EntityKind::Llama),
            "llama_spit" => Some(EntityKind::LlamaSpit),
            "magma_cube" => Some(EntityKind::MagmaCube),
            "marker" => Some(EntityKind::Marker),
            "minecart" => Some(EntityKind::Minecart),
            "chest_minecart" => Some(EntityKind::ChestMinecart),
            "command_block_minecart" => Some(EntityKind::CommandBlockMinecart),
            "furnace_minecart" => Some(EntityKind::FurnaceMinecart),
            "hopper_minecart" => Some(EntityKind::HopperMinecart),
            "spawner_minecart" => Some(EntityKind::SpawnerMinecart),
            "tnt_minecart" => Some(EntityKind::TntMinecart),
            "mule" => Some(EntityKind::Mule),
            "mooshroom" => Some(EntityKind::Mooshroom),
            "ocelot" => Some(EntityKind::Ocelot),
            "painting" => Some(EntityKind::Painting),
            "panda" => Some(EntityKind::Panda),
            "parrot" => Some(EntityKind::Parrot),
            "phantom" => Some(EntityKind::Phantom),
            "pig" => Some(EntityKind::Pig),
            "piglin" => Some(EntityKind::Piglin),
            "piglin_brute" => Some(EntityKind::PiglinBrute),
            "pillager" => Some(EntityKind::Pillager),
            "polar_bear" => Some(EntityKind::PolarBear),
            "tnt" => Some(EntityKind::Tnt),
            "pufferfish" => Some(EntityKind::Pufferfish),
            "rabbit" => Some(EntityKind::Rabbit),
            "ravager" => Some(EntityKind::Ravager),
            "salmon" => Some(EntityKind::Salmon),
            "sheep" => Some(EntityKind::Sheep),
            "shulker" => Some(EntityKind::Shulker),
            "shulker_bullet" => Some(EntityKind::ShulkerBullet),
            "silverfish" => Some(EntityKind::Silverfish),
            "skeleton" => Some(EntityKind::Skeleton),
            "skeleton_horse" => Some(EntityKind::SkeletonHorse),
            "slime" => Some(EntityKind::Slime),
            "small_fireball" => Some(EntityKind::SmallFireball),
            "snow_golem" => Some(EntityKind::SnowGolem),
            "snowball" => Some(EntityKind::Snowball),
            "spectral_arrow" => Some(EntityKind::SpectralArrow),
            "spider" => Some(EntityKind::Spider),
            "squid" => Some(EntityKind::Squid),
            "stray" => Some(EntityKind::Stray),
            "strider" => Some(EntityKind::Strider),
            "egg" => Some(EntityKind::Egg),
            "ender_pearl" => Some(EntityKind::EnderPearl),
            "experience_bottle" => Some(EntityKind::ExperienceBottle),
            "potion" => Some(EntityKind::Potion),
            "trident" => Some(EntityKind::Trident),
            "trader_llama" => Some(EntityKind::TraderLlama),
            "tropical_fish" => Some(EntityKind::TropicalFish),
            "turtle" => Some(EntityKind::Turtle),
            "vex" => Some(EntityKind::Vex),
            "villager" => Some(EntityKind::Villager),
            "vindicator" => Some(EntityKind::Vindicator),
            "wandering_trader" => Some(EntityKind::WanderingTrader),
            "witch" => Some(EntityKind::Witch),
            "wither" => Some(EntityKind::Wither),
            "wither_skeleton" => Some(EntityKind::WitherSkeleton),
            "wither_skull" => Some(EntityKind::WitherSkull),
            "wolf" => Some(EntityKind::Wolf),
            "zoglin" => Some(EntityKind::Zoglin),
            "zombie" => Some(EntityKind::Zombie),
            "zombie_horse" => Some(EntityKind::ZombieHorse),
            "zombie_villager" => Some(EntityKind::ZombieVillager),
            "zombified_piglin" => Some(EntityKind::ZombifiedPiglin),
            "player" => Some(EntityKind::Player),
            "fishing_bobber" => Some(EntityKind::FishingBobber),
            _ => None,
        }
    }
}
impl EntityKind {
    #[doc = "Returns the `namespaced_id` property of this `EntityKind`."]
    #[inline]
    pub fn namespaced_id(&self) -> &'static str {
        match self {
            EntityKind::AreaEffectCloud => "minecraft:area_effect_cloud",
            EntityKind::ArmorStand => "minecraft:armor_stand",
            EntityKind::Arrow => "minecraft:arrow",
            EntityKind::Axolotl => "minecraft:axolotl",
            EntityKind::Bat => "minecraft:bat",
            EntityKind::Bee => "minecraft:bee",
            EntityKind::Blaze => "minecraft:blaze",
            EntityKind::Boat => "minecraft:boat",
            EntityKind::Cat => "minecraft:cat",
            EntityKind::CaveSpider => "minecraft:cave_spider",
            EntityKind::Chicken => "minecraft:chicken",
            EntityKind::Cod => "minecraft:cod",
            EntityKind::Cow => "minecraft:cow",
            EntityKind::Creeper => "minecraft:creeper",
            EntityKind::Dolphin => "minecraft:dolphin",
            EntityKind::Donkey => "minecraft:donkey",
            EntityKind::DragonFireball => "minecraft:dragon_fireball",
            EntityKind::Drowned => "minecraft:drowned",
            EntityKind::ElderGuardian => "minecraft:elder_guardian",
            EntityKind::EndCrystal => "minecraft:end_crystal",
            EntityKind::EnderDragon => "minecraft:ender_dragon",
            EntityKind::Enderman => "minecraft:enderman",
            EntityKind::Endermite => "minecraft:endermite",
            EntityKind::Evoker => "minecraft:evoker",
            EntityKind::EvokerFangs => "minecraft:evoker_fangs",
            EntityKind::ExperienceOrb => "minecraft:experience_orb",
            EntityKind::EyeOfEnder => "minecraft:eye_of_ender",
            EntityKind::FallingBlock => "minecraft:falling_block",
            EntityKind::FireworkRocket => "minecraft:firework_rocket",
            EntityKind::Fox => "minecraft:fox",
            EntityKind::Ghast => "minecraft:ghast",
            EntityKind::Giant => "minecraft:giant",
            EntityKind::GlowItemFrame => "minecraft:glow_item_frame",
            EntityKind::GlowSquid => "minecraft:glow_squid",
            EntityKind::Goat => "minecraft:goat",
            EntityKind::Guardian => "minecraft:guardian",
            EntityKind::Hoglin => "minecraft:hoglin",
            EntityKind::Horse => "minecraft:horse",
            EntityKind::Husk => "minecraft:husk",
            EntityKind::Illusioner => "minecraft:illusioner",
            EntityKind::IronGolem => "minecraft:iron_golem",
            EntityKind::Item => "minecraft:item",
            EntityKind::ItemFrame => "minecraft:item_frame",
            EntityKind::Fireball => "minecraft:fireball",
            EntityKind::LeashKnot => "minecraft:leash_knot",
            EntityKind::LightningBolt => "minecraft:lightning_bolt",
            EntityKind::Llama => "minecraft:llama",
            EntityKind::LlamaSpit => "minecraft:llama_spit",
            EntityKind::MagmaCube => "minecraft:magma_cube",
            EntityKind::Marker => "minecraft:marker",
            EntityKind::Minecart => "minecraft:minecart",
            EntityKind::ChestMinecart => "minecraft:chest_minecart",
            EntityKind::CommandBlockMinecart => "minecraft:command_block_minecart",
            EntityKind::FurnaceMinecart => "minecraft:furnace_minecart",
            EntityKind::HopperMinecart => "minecraft:hopper_minecart",
            EntityKind::SpawnerMinecart => "minecraft:spawner_minecart",
            EntityKind::TntMinecart => "minecraft:tnt_minecart",
            EntityKind::Mule => "minecraft:mule",
            EntityKind::Mooshroom => "minecraft:mooshroom",
            EntityKind::Ocelot => "minecraft:ocelot",
            EntityKind::Painting => "minecraft:painting",
            EntityKind::Panda => "minecraft:panda",
            EntityKind::Parrot => "minecraft:parrot",
            EntityKind::Phantom => "minecraft:phantom",
            EntityKind::Pig => "minecraft:pig",
            EntityKind::Piglin => "minecraft:piglin",
            EntityKind::PiglinBrute => "minecraft:piglin_brute",
            EntityKind::Pillager => "minecraft:pillager",
            EntityKind::PolarBear => "minecraft:polar_bear",
            EntityKind::Tnt => "minecraft:tnt",
            EntityKind::Pufferfish => "minecraft:pufferfish",
            EntityKind::Rabbit => "minecraft:rabbit",
            EntityKind::Ravager => "minecraft:ravager",
            EntityKind::Salmon => "minecraft:salmon",
            EntityKind::Sheep => "minecraft:sheep",
            EntityKind::Shulker => "minecraft:shulker",
            EntityKind::ShulkerBullet => "minecraft:shulker_bullet",
            EntityKind::Silverfish => "minecraft:silverfish",
            EntityKind::Skeleton => "minecraft:skeleton",
            EntityKind::SkeletonHorse => "minecraft:skeleton_horse",
            EntityKind::Slime => "minecraft:slime",
            EntityKind::SmallFireball => "minecraft:small_fireball",
            EntityKind::SnowGolem => "minecraft:snow_golem",
            EntityKind::Snowball => "minecraft:snowball",
            EntityKind::SpectralArrow => "minecraft:spectral_arrow",
            EntityKind::Spider => "minecraft:spider",
            EntityKind::Squid => "minecraft:squid",
            EntityKind::Stray => "minecraft:stray",
            EntityKind::Strider => "minecraft:strider",
            EntityKind::Egg => "minecraft:egg",
            EntityKind::EnderPearl => "minecraft:ender_pearl",
            EntityKind::ExperienceBottle => "minecraft:experience_bottle",
            EntityKind::Potion => "minecraft:potion",
            EntityKind::Trident => "minecraft:trident",
            EntityKind::TraderLlama => "minecraft:trader_llama",
            EntityKind::TropicalFish => "minecraft:tropical_fish",
            EntityKind::Turtle => "minecraft:turtle",
            EntityKind::Vex => "minecraft:vex",
            EntityKind::Villager => "minecraft:villager",
            EntityKind::Vindicator => "minecraft:vindicator",
            EntityKind::WanderingTrader => "minecraft:wandering_trader",
            EntityKind::Witch => "minecraft:witch",
            EntityKind::Wither => "minecraft:wither",
            EntityKind::WitherSkeleton => "minecraft:wither_skeleton",
            EntityKind::WitherSkull => "minecraft:wither_skull",
            EntityKind::Wolf => "minecraft:wolf",
            EntityKind::Zoglin => "minecraft:zoglin",
            EntityKind::Zombie => "minecraft:zombie",
            EntityKind::ZombieHorse => "minecraft:zombie_horse",
            EntityKind::ZombieVillager => "minecraft:zombie_villager",
            EntityKind::ZombifiedPiglin => "minecraft:zombified_piglin",
            EntityKind::Player => "minecraft:player",
            EntityKind::FishingBobber => "minecraft:fishing_bobber",
        }
    }
    #[doc = "Gets a `EntityKind` by its `namespaced_id`."]
    #[inline]
    pub fn from_namespaced_id(namespaced_id: &str) -> Option<Self> {
        match namespaced_id {
            "minecraft:area_effect_cloud" => Some(EntityKind::AreaEffectCloud),
            "minecraft:armor_stand" => Some(EntityKind::ArmorStand),
            "minecraft:arrow" => Some(EntityKind::Arrow),
            "minecraft:axolotl" => Some(EntityKind::Axolotl),
            "minecraft:bat" => Some(EntityKind::Bat),
            "minecraft:bee" => Some(EntityKind::Bee),
            "minecraft:blaze" => Some(EntityKind::Blaze),
            "minecraft:boat" => Some(EntityKind::Boat),
            "minecraft:cat" => Some(EntityKind::Cat),
            "minecraft:cave_spider" => Some(EntityKind::CaveSpider),
            "minecraft:chicken" => Some(EntityKind::Chicken),
            "minecraft:cod" => Some(EntityKind::Cod),
            "minecraft:cow" => Some(EntityKind::Cow),
            "minecraft:creeper" => Some(EntityKind::Creeper),
            "minecraft:dolphin" => Some(EntityKind::Dolphin),
            "minecraft:donkey" => Some(EntityKind::Donkey),
            "minecraft:dragon_fireball" => Some(EntityKind::DragonFireball),
            "minecraft:drowned" => Some(EntityKind::Drowned),
            "minecraft:elder_guardian" => Some(EntityKind::ElderGuardian),
            "minecraft:end_crystal" => Some(EntityKind::EndCrystal),
            "minecraft:ender_dragon" => Some(EntityKind::EnderDragon),
            "minecraft:enderman" => Some(EntityKind::Enderman),
            "minecraft:endermite" => Some(EntityKind::Endermite),
            "minecraft:evoker" => Some(EntityKind::Evoker),
            "minecraft:evoker_fangs" => Some(EntityKind::EvokerFangs),
            "minecraft:experience_orb" => Some(EntityKind::ExperienceOrb),
            "minecraft:eye_of_ender" => Some(EntityKind::EyeOfEnder),
            "minecraft:falling_block" => Some(EntityKind::FallingBlock),
            "minecraft:firework_rocket" => Some(EntityKind::FireworkRocket),
            "minecraft:fox" => Some(EntityKind::Fox),
            "minecraft:ghast" => Some(EntityKind::Ghast),
            "minecraft:giant" => Some(EntityKind::Giant),
            "minecraft:glow_item_frame" => Some(EntityKind::GlowItemFrame),
            "minecraft:glow_squid" => Some(EntityKind::GlowSquid),
            "minecraft:goat" => Some(EntityKind::Goat),
            "minecraft:guardian" => Some(EntityKind::Guardian),
            "minecraft:hoglin" => Some(EntityKind::Hoglin),
            "minecraft:horse" => Some(EntityKind::Horse),
            "minecraft:husk" => Some(EntityKind::Husk),
            "minecraft:illusioner" => Some(EntityKind::Illusioner),
            "minecraft:iron_golem" => Some(EntityKind::IronGolem),
            "minecraft:item" => Some(EntityKind::Item),
            "minecraft:item_frame" => Some(EntityKind::ItemFrame),
            "minecraft:fireball" => Some(EntityKind::Fireball),
            "minecraft:leash_knot" => Some(EntityKind::LeashKnot),
            "minecraft:lightning_bolt" => Some(EntityKind::LightningBolt),
            "minecraft:llama" => Some(EntityKind::Llama),
            "minecraft:llama_spit" => Some(EntityKind::LlamaSpit),
            "minecraft:magma_cube" => Some(EntityKind::MagmaCube),
            "minecraft:marker" => Some(EntityKind::Marker),
            "minecraft:minecart" => Some(EntityKind::Minecart),
            "minecraft:chest_minecart" => Some(EntityKind::ChestMinecart),
            "minecraft:command_block_minecart" => Some(EntityKind::CommandBlockMinecart),
            "minecraft:furnace_minecart" => Some(EntityKind::FurnaceMinecart),
            "minecraft:hopper_minecart" => Some(EntityKind::HopperMinecart),
            "minecraft:spawner_minecart" => Some(EntityKind::SpawnerMinecart),
            "minecraft:tnt_minecart" => Some(EntityKind::TntMinecart),
            "minecraft:mule" => Some(EntityKind::Mule),
            "minecraft:mooshroom" => Some(EntityKind::Mooshroom),
            "minecraft:ocelot" => Some(EntityKind::Ocelot),
            "minecraft:painting" => Some(EntityKind::Painting),
            "minecraft:panda" => Some(EntityKind::Panda),
            "minecraft:parrot" => Some(EntityKind::Parrot),
            "minecraft:phantom" => Some(EntityKind::Phantom),
            "minecraft:pig" => Some(EntityKind::Pig),
            "minecraft:piglin" => Some(EntityKind::Piglin),
            "minecraft:piglin_brute" => Some(EntityKind::PiglinBrute),
            "minecraft:pillager" => Some(EntityKind::Pillager),
            "minecraft:polar_bear" => Some(EntityKind::PolarBear),
            "minecraft:tnt" => Some(EntityKind::Tnt),
            "minecraft:pufferfish" => Some(EntityKind::Pufferfish),
            "minecraft:rabbit" => Some(EntityKind::Rabbit),
            "minecraft:ravager" => Some(EntityKind::Ravager),
            "minecraft:salmon" => Some(EntityKind::Salmon),
            "minecraft:sheep" => Some(EntityKind::Sheep),
            "minecraft:shulker" => Some(EntityKind::Shulker),
            "minecraft:shulker_bullet" => Some(EntityKind::ShulkerBullet),
            "minecraft:silverfish" => Some(EntityKind::Silverfish),
            "minecraft:skeleton" => Some(EntityKind::Skeleton),
            "minecraft:skeleton_horse" => Some(EntityKind::SkeletonHorse),
            "minecraft:slime" => Some(EntityKind::Slime),
            "minecraft:small_fireball" => Some(EntityKind::SmallFireball),
            "minecraft:snow_golem" => Some(EntityKind::SnowGolem),
            "minecraft:snowball" => Some(EntityKind::Snowball),
            "minecraft:spectral_arrow" => Some(EntityKind::SpectralArrow),
            "minecraft:spider" => Some(EntityKind::Spider),
            "minecraft:squid" => Some(EntityKind::Squid),
            "minecraft:stray" => Some(EntityKind::Stray),
            "minecraft:strider" => Some(EntityKind::Strider),
            "minecraft:egg" => Some(EntityKind::Egg),
            "minecraft:ender_pearl" => Some(EntityKind::EnderPearl),
            "minecraft:experience_bottle" => Some(EntityKind::ExperienceBottle),
            "minecraft:potion" => Some(EntityKind::Potion),
            "minecraft:trident" => Some(EntityKind::Trident),
            "minecraft:trader_llama" => Some(EntityKind::TraderLlama),
            "minecraft:tropical_fish" => Some(EntityKind::TropicalFish),
            "minecraft:turtle" => Some(EntityKind::Turtle),
            "minecraft:vex" => Some(EntityKind::Vex),
            "minecraft:villager" => Some(EntityKind::Villager),
            "minecraft:vindicator" => Some(EntityKind::Vindicator),
            "minecraft:wandering_trader" => Some(EntityKind::WanderingTrader),
            "minecraft:witch" => Some(EntityKind::Witch),
            "minecraft:wither" => Some(EntityKind::Wither),
            "minecraft:wither_skeleton" => Some(EntityKind::WitherSkeleton),
            "minecraft:wither_skull" => Some(EntityKind::WitherSkull),
            "minecraft:wolf" => Some(EntityKind::Wolf),
            "minecraft:zoglin" => Some(EntityKind::Zoglin),
            "minecraft:zombie" => Some(EntityKind::Zombie),
            "minecraft:zombie_horse" => Some(EntityKind::ZombieHorse),
            "minecraft:zombie_villager" => Some(EntityKind::ZombieVillager),
            "minecraft:zombified_piglin" => Some(EntityKind::ZombifiedPiglin),
            "minecraft:player" => Some(EntityKind::Player),
            "minecraft:fishing_bobber" => Some(EntityKind::FishingBobber),
            _ => None,
        }
    }
}
use std::convert::TryFrom;
use std::str::FromStr;
impl TryFrom<String> for EntityKind {
    type Error = &'static str;
    fn try_from(value: String) -> Result<Self, Self::Error> {
        if let Some(kind) = EntityKind::from_name(value.as_str()) {
            Ok(kind)
        } else {
            Err("Unknown entity kind")
        }
    }
}
impl From<EntityKind> for &'static str {
    fn from(i: EntityKind) -> Self {
        i.name()
    }
}
impl FromStr for EntityKind {
    type Err = &'static str;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if let Some(kind) = EntityKind::from_name(s) {
            Ok(kind)
        } else {
            Err("Unknown entity kind")
        }
    }
}
