// This file is @generated. Please do not edit.

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Particle {
    AmbientEntityEffect,
    AngryVillager,
    Barrier,
    Block(BlockId),
    Bubble,
    Cloud,
    Crit,
    DamageIndicator,
    DragonBreath,
    DrippingLava,
    FallingLava,
    LandingLava,
    DrippingWater,
    FallingWater,
    Dust {
        red: f32,
        green: f32,
        blue: f32,
        scale: f32,
    },
    Effect,
    ElderGuardian,
    EnchantedHit,
    Enchant,
    EndRod,
    EntityEffect,
    ExplosionEmitter,
    Explosion,
    FallingDust(BlockId),
    Firework,
    Fishing,
    Flame,
    SoulFireFlame,
    Soul,
    Flash,
    HappyVillager,
    Composter,
    Heart,
    InstantEffect,
    Item(f32),
    ItemSlime,
    ItemSnowball,
    LargeSmoke,
    Lava,
    Mycelium,
    Note,
    Poof,
    Portal,
    Rain,
    Smoke,
    Sneeze,
    Spit,
    SquidInk,
    SweepAttack,
    TotemOfUndying,
    Underwater,
    Splash,
    Witch,
    BubblePop,
    CurrentDown,
    BubbleColumnUp,
    Nautilus,
    Dolphin,
    CampfireCosySmoke,
    CampfireSignalSmoke,
    DrippingHoney,
    FallingHoney,
    LandingHoney,
    FallingNectar,
    Ash,
    CrimsonSpore,
    WarpedSpore,
    DrippingObsidianTear,
    FallingObsidianTear,
    LandingObsidianTear,
    ReversePortal,
    WhiteAsh,
}

#[allow(warnings)]
#[allow(clippy::all)]
impl Particle {
    /// Returns the `id` property of this `Particle`.
    pub fn id(&self) -> u32 {
        match self {
            Particle::AmbientEntityEffect => 0,
            Particle::AngryVillager => 1,
            Particle::Barrier => 2,
            Particle::Block => 3,
            Particle::Bubble => 4,
            Particle::Cloud => 5,
            Particle::Crit => 6,
            Particle::DamageIndicator => 7,
            Particle::DragonBreath => 8,
            Particle::DrippingLava => 9,
            Particle::FallingLava => 10,
            Particle::LandingLava => 11,
            Particle::DrippingWater => 12,
            Particle::FallingWater => 13,
            Particle::Dust => 14,
            Particle::Effect => 15,
            Particle::ElderGuardian => 16,
            Particle::EnchantedHit => 17,
            Particle::Enchant => 18,
            Particle::EndRod => 19,
            Particle::EntityEffect => 20,
            Particle::ExplosionEmitter => 21,
            Particle::Explosion => 22,
            Particle::FallingDust => 23,
            Particle::Firework => 24,
            Particle::Fishing => 25,
            Particle::Flame => 26,
            Particle::SoulFireFlame => 27,
            Particle::Soul => 28,
            Particle::Flash => 29,
            Particle::HappyVillager => 30,
            Particle::Composter => 31,
            Particle::Heart => 32,
            Particle::InstantEffect => 33,
            Particle::Item => 34,
            Particle::ItemSlime => 35,
            Particle::ItemSnowball => 36,
            Particle::LargeSmoke => 37,
            Particle::Lava => 38,
            Particle::Mycelium => 39,
            Particle::Note => 40,
            Particle::Poof => 41,
            Particle::Portal => 42,
            Particle::Rain => 43,
            Particle::Smoke => 44,
            Particle::Sneeze => 45,
            Particle::Spit => 46,
            Particle::SquidInk => 47,
            Particle::SweepAttack => 48,
            Particle::TotemOfUndying => 49,
            Particle::Underwater => 50,
            Particle::Splash => 51,
            Particle::Witch => 52,
            Particle::BubblePop => 53,
            Particle::CurrentDown => 54,
            Particle::BubbleColumnUp => 55,
            Particle::Nautilus => 56,
            Particle::Dolphin => 57,
            Particle::CampfireCosySmoke => 58,
            Particle::CampfireSignalSmoke => 59,
            Particle::DrippingHoney => 60,
            Particle::FallingHoney => 61,
            Particle::LandingHoney => 62,
            Particle::FallingNectar => 63,
            Particle::Ash => 64,
            Particle::CrimsonSpore => 65,
            Particle::WarpedSpore => 66,
            Particle::DrippingObsidianTear => 67,
            Particle::FallingObsidianTear => 68,
            Particle::LandingObsidianTear => 69,
            Particle::ReversePortal => 70,
            Particle::WhiteAsh => 71,
        }
    }

    /// Gets a `Particle` by its `id`.
    pub fn from_id(id: u32) -> Option<Self> {
        match id {
            0 => Some(Particle::AmbientEntityEffect),
            1 => Some(Particle::AngryVillager),
            2 => Some(Particle::Barrier),
            3 => Some(Particle::Block),
            4 => Some(Particle::Bubble),
            5 => Some(Particle::Cloud),
            6 => Some(Particle::Crit),
            7 => Some(Particle::DamageIndicator),
            8 => Some(Particle::DragonBreath),
            9 => Some(Particle::DrippingLava),
            10 => Some(Particle::FallingLava),
            11 => Some(Particle::LandingLava),
            12 => Some(Particle::DrippingWater),
            13 => Some(Particle::FallingWater),
            14 => Some(Particle::Dust),
            15 => Some(Particle::Effect),
            16 => Some(Particle::ElderGuardian),
            17 => Some(Particle::EnchantedHit),
            18 => Some(Particle::Enchant),
            19 => Some(Particle::EndRod),
            20 => Some(Particle::EntityEffect),
            21 => Some(Particle::ExplosionEmitter),
            22 => Some(Particle::Explosion),
            23 => Some(Particle::FallingDust),
            24 => Some(Particle::Firework),
            25 => Some(Particle::Fishing),
            26 => Some(Particle::Flame),
            27 => Some(Particle::SoulFireFlame),
            28 => Some(Particle::Soul),
            29 => Some(Particle::Flash),
            30 => Some(Particle::HappyVillager),
            31 => Some(Particle::Composter),
            32 => Some(Particle::Heart),
            33 => Some(Particle::InstantEffect),
            34 => Some(Particle::Item),
            35 => Some(Particle::ItemSlime),
            36 => Some(Particle::ItemSnowball),
            37 => Some(Particle::LargeSmoke),
            38 => Some(Particle::Lava),
            39 => Some(Particle::Mycelium),
            40 => Some(Particle::Note),
            41 => Some(Particle::Poof),
            42 => Some(Particle::Portal),
            43 => Some(Particle::Rain),
            44 => Some(Particle::Smoke),
            45 => Some(Particle::Sneeze),
            46 => Some(Particle::Spit),
            47 => Some(Particle::SquidInk),
            48 => Some(Particle::SweepAttack),
            49 => Some(Particle::TotemOfUndying),
            50 => Some(Particle::Underwater),
            51 => Some(Particle::Splash),
            52 => Some(Particle::Witch),
            53 => Some(Particle::BubblePop),
            54 => Some(Particle::CurrentDown),
            55 => Some(Particle::BubbleColumnUp),
            56 => Some(Particle::Nautilus),
            57 => Some(Particle::Dolphin),
            58 => Some(Particle::CampfireCosySmoke),
            59 => Some(Particle::CampfireSignalSmoke),
            60 => Some(Particle::DrippingHoney),
            61 => Some(Particle::FallingHoney),
            62 => Some(Particle::LandingHoney),
            63 => Some(Particle::FallingNectar),
            64 => Some(Particle::Ash),
            65 => Some(Particle::CrimsonSpore),
            66 => Some(Particle::WarpedSpore),
            67 => Some(Particle::DrippingObsidianTear),
            68 => Some(Particle::FallingObsidianTear),
            69 => Some(Particle::LandingObsidianTear),
            70 => Some(Particle::ReversePortal),
            71 => Some(Particle::WhiteAsh),
            _ => None,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Particle {
    /// Returns the `name` property of this `Particle`.
    pub fn name(&self) -> &'static str {
        match self {
            Particle::AmbientEntityEffect => "ambient_entity_effect",
            Particle::AngryVillager => "angry_villager",
            Particle::Barrier => "barrier",
            Particle::Block => "block",
            Particle::Bubble => "bubble",
            Particle::Cloud => "cloud",
            Particle::Crit => "crit",
            Particle::DamageIndicator => "damage_indicator",
            Particle::DragonBreath => "dragon_breath",
            Particle::DrippingLava => "dripping_lava",
            Particle::FallingLava => "falling_lava",
            Particle::LandingLava => "landing_lava",
            Particle::DrippingWater => "dripping_water",
            Particle::FallingWater => "falling_water",
            Particle::Dust => "dust",
            Particle::Effect => "effect",
            Particle::ElderGuardian => "elder_guardian",
            Particle::EnchantedHit => "enchanted_hit",
            Particle::Enchant => "enchant",
            Particle::EndRod => "end_rod",
            Particle::EntityEffect => "entity_effect",
            Particle::ExplosionEmitter => "explosion_emitter",
            Particle::Explosion => "explosion",
            Particle::FallingDust => "falling_dust",
            Particle::Firework => "firework",
            Particle::Fishing => "fishing",
            Particle::Flame => "flame",
            Particle::SoulFireFlame => "soul_fire_flame",
            Particle::Soul => "soul",
            Particle::Flash => "flash",
            Particle::HappyVillager => "happy_villager",
            Particle::Composter => "composter",
            Particle::Heart => "heart",
            Particle::InstantEffect => "instant_effect",
            Particle::Item => "item",
            Particle::ItemSlime => "item_slime",
            Particle::ItemSnowball => "item_snowball",
            Particle::LargeSmoke => "large_smoke",
            Particle::Lava => "lava",
            Particle::Mycelium => "mycelium",
            Particle::Note => "note",
            Particle::Poof => "poof",
            Particle::Portal => "portal",
            Particle::Rain => "rain",
            Particle::Smoke => "smoke",
            Particle::Sneeze => "sneeze",
            Particle::Spit => "spit",
            Particle::SquidInk => "squid_ink",
            Particle::SweepAttack => "sweep_attack",
            Particle::TotemOfUndying => "totem_of_undying",
            Particle::Underwater => "underwater",
            Particle::Splash => "splash",
            Particle::Witch => "witch",
            Particle::BubblePop => "bubble_pop",
            Particle::CurrentDown => "current_down",
            Particle::BubbleColumnUp => "bubble_column_up",
            Particle::Nautilus => "nautilus",
            Particle::Dolphin => "dolphin",
            Particle::CampfireCosySmoke => "campfire_cosy_smoke",
            Particle::CampfireSignalSmoke => "campfire_signal_smoke",
            Particle::DrippingHoney => "dripping_honey",
            Particle::FallingHoney => "falling_honey",
            Particle::LandingHoney => "landing_honey",
            Particle::FallingNectar => "falling_nectar",
            Particle::Ash => "ash",
            Particle::CrimsonSpore => "crimson_spore",
            Particle::WarpedSpore => "warped_spore",
            Particle::DrippingObsidianTear => "dripping_obsidian_tear",
            Particle::FallingObsidianTear => "falling_obsidian_tear",
            Particle::LandingObsidianTear => "landing_obsidian_tear",
            Particle::ReversePortal => "reverse_portal",
            Particle::WhiteAsh => "white_ash",
        }
    }

    /// Gets a `Particle` by its `name`.
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "ambient_entity_effect" => Some(Particle::AmbientEntityEffect),
            "angry_villager" => Some(Particle::AngryVillager),
            "barrier" => Some(Particle::Barrier),
            "block" => Some(Particle::Block),
            "bubble" => Some(Particle::Bubble),
            "cloud" => Some(Particle::Cloud),
            "crit" => Some(Particle::Crit),
            "damage_indicator" => Some(Particle::DamageIndicator),
            "dragon_breath" => Some(Particle::DragonBreath),
            "dripping_lava" => Some(Particle::DrippingLava),
            "falling_lava" => Some(Particle::FallingLava),
            "landing_lava" => Some(Particle::LandingLava),
            "dripping_water" => Some(Particle::DrippingWater),
            "falling_water" => Some(Particle::FallingWater),
            "dust" => Some(Particle::Dust),
            "effect" => Some(Particle::Effect),
            "elder_guardian" => Some(Particle::ElderGuardian),
            "enchanted_hit" => Some(Particle::EnchantedHit),
            "enchant" => Some(Particle::Enchant),
            "end_rod" => Some(Particle::EndRod),
            "entity_effect" => Some(Particle::EntityEffect),
            "explosion_emitter" => Some(Particle::ExplosionEmitter),
            "explosion" => Some(Particle::Explosion),
            "falling_dust" => Some(Particle::FallingDust),
            "firework" => Some(Particle::Firework),
            "fishing" => Some(Particle::Fishing),
            "flame" => Some(Particle::Flame),
            "soul_fire_flame" => Some(Particle::SoulFireFlame),
            "soul" => Some(Particle::Soul),
            "flash" => Some(Particle::Flash),
            "happy_villager" => Some(Particle::HappyVillager),
            "composter" => Some(Particle::Composter),
            "heart" => Some(Particle::Heart),
            "instant_effect" => Some(Particle::InstantEffect),
            "item" => Some(Particle::Item),
            "item_slime" => Some(Particle::ItemSlime),
            "item_snowball" => Some(Particle::ItemSnowball),
            "large_smoke" => Some(Particle::LargeSmoke),
            "lava" => Some(Particle::Lava),
            "mycelium" => Some(Particle::Mycelium),
            "note" => Some(Particle::Note),
            "poof" => Some(Particle::Poof),
            "portal" => Some(Particle::Portal),
            "rain" => Some(Particle::Rain),
            "smoke" => Some(Particle::Smoke),
            "sneeze" => Some(Particle::Sneeze),
            "spit" => Some(Particle::Spit),
            "squid_ink" => Some(Particle::SquidInk),
            "sweep_attack" => Some(Particle::SweepAttack),
            "totem_of_undying" => Some(Particle::TotemOfUndying),
            "underwater" => Some(Particle::Underwater),
            "splash" => Some(Particle::Splash),
            "witch" => Some(Particle::Witch),
            "bubble_pop" => Some(Particle::BubblePop),
            "current_down" => Some(Particle::CurrentDown),
            "bubble_column_up" => Some(Particle::BubbleColumnUp),
            "nautilus" => Some(Particle::Nautilus),
            "dolphin" => Some(Particle::Dolphin),
            "campfire_cosy_smoke" => Some(Particle::CampfireCosySmoke),
            "campfire_signal_smoke" => Some(Particle::CampfireSignalSmoke),
            "dripping_honey" => Some(Particle::DrippingHoney),
            "falling_honey" => Some(Particle::FallingHoney),
            "landing_honey" => Some(Particle::LandingHoney),
            "falling_nectar" => Some(Particle::FallingNectar),
            "ash" => Some(Particle::Ash),
            "crimson_spore" => Some(Particle::CrimsonSpore),
            "warped_spore" => Some(Particle::WarpedSpore),
            "dripping_obsidian_tear" => Some(Particle::DrippingObsidianTear),
            "falling_obsidian_tear" => Some(Particle::FallingObsidianTear),
            "landing_obsidian_tear" => Some(Particle::LandingObsidianTear),
            "reverse_portal" => Some(Particle::ReversePortal),
            "white_ash" => Some(Particle::WhiteAsh),
            _ => None,
        }
    }
}
