//! Implements the Feather command dispatching framework,
//! based on our `lieutenant` library (a Rust fork
//! of Mojang's [brigadier](https://github.com/Mojang/brigadier).
//!
//! Also implements vanilla commands not defined by plugins.

mod arguments;
mod impls;

use feather_core::text::{Text, TextComponentBuilder};
use feather_server_types::{Game, MessageReceiver};
use fecs::{Entity, World};
use impls::*;
use lieutenant::CommandDispatcher;
use std::ops::{Deref, DerefMut};
use std::sync::Arc;

/// Dumb workaround for a certain lifetime issue.
///
/// `CommandCtx` stores references to `Game`, and it
/// is used as the `C` parameter for `CommandDispatcher`,
/// This combination of lifetimes and storage in structs
/// prevents a lifetime-based `CommandCtx` from being stored
/// in `CommandState` without adding a lifetime parameter to `CommandState`.
///
/// Since `CommandCtx` is never actually _stored_ in `CommandState` (it's
/// only passed into a function), we can (hopefully) soundly erase
/// the lifetime parameters. FIXME: if someone has a better solution,
/// a PR is welcome :)
pub struct LifetimelessMut<T>(*mut T);

impl<T> Deref for LifetimelessMut<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        unsafe { &mut *self.0 }
    }
}

impl<T> DerefMut for LifetimelessMut<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *self.0 }
    }
}

unsafe impl<T> Send for LifetimelessMut<T> where T: Send {}
unsafe impl<T> Sync for LifetimelessMut<T> where T: Sync {}

/// Context passed into a command. This value can be used
/// for access to game and entity data, such as components.
pub struct CommandCtx {
    /// The entity which triggered the command.
    ///
    /// _Not necessarily a player_. If the command was executed
    /// from the server console, then this will be the "server entity"
    /// associated with the console. You may check if an entity is a player
    /// by checking if it has the `Player` component. Similarly, you
    /// may check if an entity is the server console through the `Console` component.
    ///
    /// Note that players and the console are not the only possible command senders,
    /// and command implementations should account for this.
    pub sender: Entity,
    /// The game state.
    pub game: LifetimelessMut<Game>,
    /// The `World`, for access to components.
    pub world: LifetimelessMut<World>,
}

impl lieutenant::Context for CommandCtx {
    type Error = anyhow::Error;
    type Ok = Option<String>;
}

macro_rules! commands {
    ($dispatcher:ident : $($command:expr,)*) => {
        $(
            $dispatcher.register($command).unwrap();
        )*
    }
}

/// State storing all registered commands.
pub struct CommandState {
    dispatcher: Arc<CommandDispatcher<CommandCtx>>,
}

impl Default for CommandState {
    fn default() -> Self {
        Self::new()
    }
}

impl CommandState {
    /// Initializes the command state.
    pub fn new() -> Self {
        let mut dispatcher = CommandDispatcher::<CommandCtx>::new();
        
        commands! {
            dispatcher:
                advancement_grant_targets_everything,
                advancement_grant_targets_from_advancement,
                advancement_grant_targets_only_advancement,
                advancement_grant_targets_only_advancement_criterion,
                advancement_grant_targets_through_advancement,
                advancement_grant_targets_until_advancement,
                advancement_revoke_targets_everything,
                advancement_revoke_targets_from_advancement,
                advancement_revoke_targets_only_advancement,
                advancement_revoke_targets_only_advancement_criterion,
                advancement_revoke_targets_through_advancement,
                advancement_revoke_targets_until_advancement,
                attribute_target_attribute_base_get,
                attribute_target_attribute_base_get_scale,
                attribute_target_attribute_base_set_value,
                attribute_target_attribute_get,
                attribute_target_attribute_get_scale,
                attribute_target_attribute_modifier_add_uuid_name_value_add,
                attribute_target_attribute_modifier_add_uuid_name_value_multiply,
                attribute_target_attribute_modifier_add_uuid_name_value_multiply_base,
                attribute_target_attribute_modifier_remove_uuid,
                attribute_target_attribute_modifier_value_get_uuid,
                attribute_target_attribute_modifier_value_get_uuid_scale,
                ban_targets,
                ban_targets_reason,
                ban_ip_target,
                ban_ip_target_reason,
                banlist,
                banlist_ips,
                banlist_players,
                bossbar_add_id_name,
                bossbar_get_id_max,
                bossbar_get_id_players,
                bossbar_get_id_value,
                bossbar_get_id_visible,
                bossbar_list,
                bossbar_remove_id,
                bossbar_set_id_color_blue,
                bossbar_set_id_color_green,
                bossbar_set_id_color_pink,
                bossbar_set_id_color_purple,
                bossbar_set_id_color_red,
                bossbar_set_id_color_white,
                bossbar_set_id_color_yellow,
                bossbar_set_id_max_max,
                bossbar_set_id_name_name,
                bossbar_set_id_players,
                bossbar_set_id_players_targets,
                bossbar_set_id_style_notched_10,
                bossbar_set_id_style_notched_12,
                bossbar_set_id_style_notched_20,
                bossbar_set_id_style_notched_6,
                bossbar_set_id_style_progress,
                bossbar_set_id_value_value,
                bossbar_set_id_visible_visible,
                clear,
                clear_targets,
                clear_targets_item,
                clear_targets_item_maxCount,
                clone_begin_end_destination,
                clone_begin_end_destination_filtered_filter,
                clone_begin_end_destination_filtered_filter_force,
                clone_begin_end_destination_filtered_filter_move,
                clone_begin_end_destination_filtered_filter_normal,
                clone_begin_end_destination_masked,
                clone_begin_end_destination_masked_force,
                clone_begin_end_destination_masked_move,
                clone_begin_end_destination_masked_normal,
                clone_begin_end_destination_replace,
                clone_begin_end_destination_replace_force,
                clone_begin_end_destination_replace_move,
                clone_begin_end_destination_replace_normal,
                data_get_block_targetPos,
                data_get_block_targetPos_path,
                data_get_block_targetPos_path_scale,
                data_get_entity_target,
                data_get_entity_target_path,
                data_get_entity_target_path_scale,
                data_get_storage_target,
                data_get_storage_target_path,
                data_get_storage_target_path_scale,
                data_merge_block_targetPos_nbt,
                data_merge_entity_target_nbt,
                data_merge_storage_target_nbt,
                data_modify_block_targetPos_targetPath_append_from_block_sourcePos,
                data_modify_block_targetPos_targetPath_append_from_block_sourcePos_sourcePath,
                data_modify_block_targetPos_targetPath_append_from_entity_source,
                data_modify_block_targetPos_targetPath_append_from_entity_source_sourcePath,
                data_modify_block_targetPos_targetPath_append_from_storage_source,
                data_modify_block_targetPos_targetPath_append_from_storage_source_sourcePath,
                data_modify_block_targetPos_targetPath_append_value_value,
                data_modify_block_targetPos_targetPath_insert_index_from_block_sourcePos,
                data_modify_block_targetPos_targetPath_insert_index_from_block_sourcePos_sourcePath,
                data_modify_block_targetPos_targetPath_insert_index_from_entity_source,
                data_modify_block_targetPos_targetPath_insert_index_from_entity_source_sourcePath,
                data_modify_block_targetPos_targetPath_insert_index_from_storage_source,
                data_modify_block_targetPos_targetPath_insert_index_from_storage_source_sourcePath,
                data_modify_block_targetPos_targetPath_insert_index_value_value,
                data_modify_block_targetPos_targetPath_merge_from_block_sourcePos,
                data_modify_block_targetPos_targetPath_merge_from_block_sourcePos_sourcePath,
                data_modify_block_targetPos_targetPath_merge_from_entity_source,
                data_modify_block_targetPos_targetPath_merge_from_entity_source_sourcePath,
                data_modify_block_targetPos_targetPath_merge_from_storage_source,
                data_modify_block_targetPos_targetPath_merge_from_storage_source_sourcePath,
                data_modify_block_targetPos_targetPath_merge_value_value,
                data_modify_block_targetPos_targetPath_prepend_from_block_sourcePos,
                data_modify_block_targetPos_targetPath_prepend_from_block_sourcePos_sourcePath,
                data_modify_block_targetPos_targetPath_prepend_from_entity_source,
                data_modify_block_targetPos_targetPath_prepend_from_entity_source_sourcePath,
                data_modify_block_targetPos_targetPath_prepend_from_storage_source,
                data_modify_block_targetPos_targetPath_prepend_from_storage_source_sourcePath,
                data_modify_block_targetPos_targetPath_prepend_value_value,
                data_modify_block_targetPos_targetPath_set_from_block_sourcePos,
                data_modify_block_targetPos_targetPath_set_from_block_sourcePos_sourcePath,
                data_modify_block_targetPos_targetPath_set_from_entity_source,
                data_modify_block_targetPos_targetPath_set_from_entity_source_sourcePath,
                data_modify_block_targetPos_targetPath_set_from_storage_source,
                data_modify_block_targetPos_targetPath_set_from_storage_source_sourcePath,
                data_modify_block_targetPos_targetPath_set_value_value,
                data_modify_entity_target_targetPath_append_from_block_sourcePos,
                data_modify_entity_target_targetPath_append_from_block_sourcePos_sourcePath,
                data_modify_entity_target_targetPath_append_from_entity_source,
                data_modify_entity_target_targetPath_append_from_entity_source_sourcePath,
                data_modify_entity_target_targetPath_append_from_storage_source,
                data_modify_entity_target_targetPath_append_from_storage_source_sourcePath,
                data_modify_entity_target_targetPath_append_value_value,
                data_modify_entity_target_targetPath_insert_index_from_block_sourcePos,
                data_modify_entity_target_targetPath_insert_index_from_block_sourcePos_sourcePath,
                data_modify_entity_target_targetPath_insert_index_from_entity_source,
                data_modify_entity_target_targetPath_insert_index_from_entity_source_sourcePath,
                data_modify_entity_target_targetPath_insert_index_from_storage_source,
                data_modify_entity_target_targetPath_insert_index_from_storage_source_sourcePath,
                data_modify_entity_target_targetPath_insert_index_value_value,
                data_modify_entity_target_targetPath_merge_from_block_sourcePos,
                data_modify_entity_target_targetPath_merge_from_block_sourcePos_sourcePath,
                data_modify_entity_target_targetPath_merge_from_entity_source,
                data_modify_entity_target_targetPath_merge_from_entity_source_sourcePath,
                data_modify_entity_target_targetPath_merge_from_storage_source,
                data_modify_entity_target_targetPath_merge_from_storage_source_sourcePath,
                data_modify_entity_target_targetPath_merge_value_value,
                data_modify_entity_target_targetPath_prepend_from_block_sourcePos,
                data_modify_entity_target_targetPath_prepend_from_block_sourcePos_sourcePath,
                data_modify_entity_target_targetPath_prepend_from_entity_source,
                data_modify_entity_target_targetPath_prepend_from_entity_source_sourcePath,
                data_modify_entity_target_targetPath_prepend_from_storage_source,
                data_modify_entity_target_targetPath_prepend_from_storage_source_sourcePath,
                data_modify_entity_target_targetPath_prepend_value_value,
                data_modify_entity_target_targetPath_set_from_block_sourcePos,
                data_modify_entity_target_targetPath_set_from_block_sourcePos_sourcePath,
                data_modify_entity_target_targetPath_set_from_entity_source,
                data_modify_entity_target_targetPath_set_from_entity_source_sourcePath,
                data_modify_entity_target_targetPath_set_from_storage_source,
                data_modify_entity_target_targetPath_set_from_storage_source_sourcePath,
                data_modify_entity_target_targetPath_set_value_value,
                data_modify_storage_target_targetPath_append_from_block_sourcePos,
                data_modify_storage_target_targetPath_append_from_block_sourcePos_sourcePath,
                data_modify_storage_target_targetPath_append_from_entity_source,
                data_modify_storage_target_targetPath_append_from_entity_source_sourcePath,
                data_modify_storage_target_targetPath_append_from_storage_source,
                data_modify_storage_target_targetPath_append_from_storage_source_sourcePath,
                data_modify_storage_target_targetPath_append_value_value,
                data_modify_storage_target_targetPath_insert_index_from_block_sourcePos,
                data_modify_storage_target_targetPath_insert_index_from_block_sourcePos_sourcePath,
                data_modify_storage_target_targetPath_insert_index_from_entity_source,
                data_modify_storage_target_targetPath_insert_index_from_entity_source_sourcePath,
                data_modify_storage_target_targetPath_insert_index_from_storage_source,
                data_modify_storage_target_targetPath_insert_index_from_storage_source_sourcePath,
                data_modify_storage_target_targetPath_insert_index_value_value,
                data_modify_storage_target_targetPath_merge_from_block_sourcePos,
                data_modify_storage_target_targetPath_merge_from_block_sourcePos_sourcePath,
                data_modify_storage_target_targetPath_merge_from_entity_source,
                data_modify_storage_target_targetPath_merge_from_entity_source_sourcePath,
                data_modify_storage_target_targetPath_merge_from_storage_source,
                data_modify_storage_target_targetPath_merge_from_storage_source_sourcePath,
                data_modify_storage_target_targetPath_merge_value_value,
                data_modify_storage_target_targetPath_prepend_from_block_sourcePos,
                data_modify_storage_target_targetPath_prepend_from_block_sourcePos_sourcePath,
                data_modify_storage_target_targetPath_prepend_from_entity_source,
                data_modify_storage_target_targetPath_prepend_from_entity_source_sourcePath,
                data_modify_storage_target_targetPath_prepend_from_storage_source,
                data_modify_storage_target_targetPath_prepend_from_storage_source_sourcePath,
                data_modify_storage_target_targetPath_prepend_value_value,
                data_modify_storage_target_targetPath_set_from_block_sourcePos,
                data_modify_storage_target_targetPath_set_from_block_sourcePos_sourcePath,
                data_modify_storage_target_targetPath_set_from_entity_source,
                data_modify_storage_target_targetPath_set_from_entity_source_sourcePath,
                data_modify_storage_target_targetPath_set_from_storage_source,
                data_modify_storage_target_targetPath_set_from_storage_source_sourcePath,
                data_modify_storage_target_targetPath_set_value_value,
                data_remove_block_targetPos_path,
                data_remove_entity_target_path,
                data_remove_storage_target_path,
                datapack_disable_name,
                datapack_enable_name,
                datapack_enable_name_after_existing,
                datapack_enable_name_before_existing,
                datapack_enable_name_first,
                datapack_enable_name_last,
                datapack_list,
                datapack_list_available,
                datapack_list_enabled,
                debug_report,
                debug_start,
                debug_stop,
                defaultgamemode_adventure,
                defaultgamemode_creative,
                defaultgamemode_spectator,
                defaultgamemode_survival,
                deop_targets,
                difficulty,
                difficulty_easy,
                difficulty_hard,
                difficulty_normal,
                difficulty_peaceful,
                effect_clear,
                effect_clear_targets,
                effect_clear_targets_effect,
                effect_give_targets_effect,
                effect_give_targets_effect_seconds,
                effect_give_targets_effect_seconds_amplifier,
                effect_give_targets_effect_seconds_amplifier_hideParticles,
                enchant_targets_enchantment,
                enchant_targets_enchantment_level,
                execute_if_block_pos_block,
                execute_if_blocks_start_end_destination_all,
                execute_if_blocks_start_end_destination_masked,
                execute_if_data_block_sourcePos_path,
                execute_if_data_entity_source_path,
                execute_if_data_storage_source_path,
                execute_if_entity_entities,
                execute_if_predicate_predicate,
                execute_if_score_target_targetObjective_lteq_source_sourceObjective,
                execute_if_score_target_targetObjective_gteq_source_sourceObjective,
                execute_if_score_target_targetObjective_matches_range,
                execute_unless_block_pos_block,
                execute_unless_blocks_start_end_destination_all,
                execute_unless_blocks_start_end_destination_masked,
                execute_unless_data_block_sourcePos_path,
                execute_unless_data_entity_source_path,
                execute_unless_data_storage_source_path,
                execute_unless_entity_entities,
                execute_unless_predicate_predicate,
                execute_unless_score_target_targetObjective_gteq_source_sourceObjective,
                execute_unless_score_target_targetObjective_lteq_source_sourceObjective,
                experience_add_targets_amount,
                experience_add_targets_amount_levels,
                experience_add_targets_amount_points,
                execute_unless_score_target_targetObjective_matches_range,
                experience_query_targets_points,
                experience_set_targets_amount_levels,
                experience_set_targets_amount_points,
                fill_from_to_block,
                fill_from_to_block_destroy,
                fill_from_to_block_hollow,
                fill_from_to_block_keep,
                fill_from_to_block_outline,
                fill_from_to_block_replace,
                fill_from_to_block_replace_filter,
                forceload_add_from,
                forceload_add_from_to,
                forceload_query,
                forceload_query_pos,
                forceload_remove_all,
                forceload_remove_from,
                forceload_remove_from_to,
                function_name,
                gamemode_adventure,
                gamemode_adventure_target,
                gamemode_creative,
                gamemode_creative_target,
                gamemode_spectator,
                gamemode_spectator_target,
                gamemode_survival,
                gamemode_survival_target,
                gamerule_announceAdvancements,
                gamerule_announceAdvancements_value,
                gamerule_commandBlockOutput,
                gamerule_commandBlockOutput_value,
                gamerule_disableElytraMovementCheck,
                gamerule_disableElytraMovementCheck_value,
                gamerule_disableRaids,
                gamerule_disableRaids_value,
                gamerule_doDaylightCycle,
                gamerule_doDaylightCycle_value,
                gamerule_doEntityDrops,
                gamerule_doEntityDrops_value,
                gamerule_doFireTick,
                gamerule_doFireTick_value,
                gamerule_doImmediateRespawn,
                gamerule_doImmediateRespawn_value,
                gamerule_doInsomnia,
                gamerule_doInsomnia_value,
                gamerule_doLimitedCrafting,
                gamerule_doLimitedCrafting_value,
                gamerule_doMobLoot,
                gamerule_doMobLoot_value,
                gamerule_doMobSpawning,
                gamerule_doMobSpawning_value,
                gamerule_doPatrolSpawning,
                gamerule_doPatrolSpawning_value,
                gamerule_doTileDrops,
                gamerule_doTileDrops_value,
                gamerule_doTraderSpawning,
                gamerule_doTraderSpawning_value,
                gamerule_doWeatherCycle,
                gamerule_doWeatherCycle_value,
                gamerule_drowningDamage,
                gamerule_drowningDamage_value,
                gamerule_fallDamage,
                gamerule_fallDamage_value,
                gamerule_fireDamage,
                gamerule_fireDamage_value,
                gamerule_forgiveDeadPlayers,
                gamerule_forgiveDeadPlayers_value,
                gamerule_keepInventory,
                gamerule_keepInventory_value,
                gamerule_logAdminCommands,
                gamerule_logAdminCommands_value,
                gamerule_maxCommandChainLength,
                gamerule_maxCommandChainLength_value,
                gamerule_maxEntityCramming,
                gamerule_maxEntityCramming_value,
                gamerule_mobGriefing,
                gamerule_mobGriefing_value,
                gamerule_naturalRegeneration,
                gamerule_naturalRegeneration_value,
                gamerule_randomTickSpeed,
                gamerule_randomTickSpeed_value,
                gamerule_reducedDebugInfo,
                gamerule_reducedDebugInfo_value,
                gamerule_sendCommandFeedback,
                gamerule_sendCommandFeedback_value,
                gamerule_showDeathMessages,
                gamerule_showDeathMessages_value,
                gamerule_spawnRadius,
                gamerule_spawnRadius_value,
                gamerule_spectatorsGenerateChunks,
                gamerule_spectatorsGenerateChunks_value,
                gamerule_universalAnger,
                gamerule_universalAnger_value,
                give_targets_item,
                give_targets_item_count,
                help,
                help_command,
                kick_targets,
                kick_targets_reason,
                kill,
                kill_targets,
                list,
                list_uuids,
                locate_bastion_remnant,
                locate_buried_treasure,
                locate_desert_pyramid,
                locate_endcity,
                locate_fortress,
                locate_igloo,
                locate_jungle_pyramid,
                locate_mansion,
                locate_mineshaft,
                locate_monument,
                locate_nether_fossil,
                locate_ocean_ruin,
                locate_pillager_outpost,
                locate_ruined_portal,
                locate_shipwreck,
                locate_stronghold,
                locate_swamp_hut,
                locate_village,
                locatebiome_biome,
                loot_give_players_fish_loot_table_pos,
                loot_give_players_fish_loot_table_pos_mainhand,
                loot_give_players_fish_loot_table_pos_offhand,
                loot_give_players_fish_loot_table_pos_tool,
                loot_give_players_kill_target,
                loot_give_players_loot_loot_table,
                loot_give_players_mine_pos,
                loot_give_players_mine_pos_mainhand,
                loot_give_players_mine_pos_offhand,
                loot_give_players_mine_pos_tool,
                loot_insert_targetPos_fish_loot_table_pos,
                loot_insert_targetPos_fish_loot_table_pos_mainhand,
                loot_insert_targetPos_fish_loot_table_pos_offhand,
                loot_insert_targetPos_fish_loot_table_pos_tool,
                loot_insert_targetPos_kill_target,
                loot_insert_targetPos_loot_loot_table,
                loot_insert_targetPos_mine_pos,
                loot_insert_targetPos_mine_pos_mainhand,
                loot_insert_targetPos_mine_pos_offhand,
                loot_insert_targetPos_mine_pos_tool,
                loot_replace_block_targetPos_slot_fish_loot_table_pos,
                loot_replace_block_targetPos_slot_fish_loot_table_pos_mainhand,
                loot_replace_block_targetPos_slot_fish_loot_table_pos_offhand,
                loot_replace_block_targetPos_slot_fish_loot_table_pos_tool,
                loot_replace_block_targetPos_slot_kill_target,
                loot_replace_block_targetPos_slot_loot_loot_table,
                loot_replace_block_targetPos_slot_mine_pos,
                loot_replace_block_targetPos_slot_mine_pos_mainhand,
                loot_replace_block_targetPos_slot_mine_pos_offhand,
                loot_replace_block_targetPos_slot_mine_pos_tool,
                loot_replace_block_targetPos_slot_count_fish_loot_table_pos,
                loot_replace_block_targetPos_slot_count_fish_loot_table_pos_mainhand,
                loot_replace_block_targetPos_slot_count_fish_loot_table_pos_offhand,
                loot_replace_block_targetPos_slot_count_fish_loot_table_pos_tool,
                loot_replace_block_targetPos_slot_count_kill_target,
                loot_replace_block_targetPos_slot_count_loot_loot_table,
                loot_replace_block_targetPos_slot_count_mine_pos,
                loot_replace_block_targetPos_slot_count_mine_pos_mainhand,
                loot_replace_block_targetPos_slot_count_mine_pos_offhand,
                loot_replace_block_targetPos_slot_count_mine_pos_tool,
                loot_replace_entity_entities_slot_fish_loot_table_pos,
                loot_replace_entity_entities_slot_fish_loot_table_pos_mainhand,
                loot_replace_entity_entities_slot_fish_loot_table_pos_offhand,
                loot_replace_entity_entities_slot_fish_loot_table_pos_tool,
                loot_replace_entity_entities_slot_kill_target,
                loot_replace_entity_entities_slot_loot_loot_table,
                loot_replace_entity_entities_slot_mine_pos,
                loot_replace_entity_entities_slot_mine_pos_mainhand,
                loot_replace_entity_entities_slot_mine_pos_offhand,
                loot_replace_entity_entities_slot_mine_pos_tool,
                loot_replace_entity_entities_slot_count_fish_loot_table_pos,
                loot_replace_entity_entities_slot_count_fish_loot_table_pos_mainhand,
                loot_replace_entity_entities_slot_count_fish_loot_table_pos_offhand,
                loot_replace_entity_entities_slot_count_fish_loot_table_pos_tool,
                loot_replace_entity_entities_slot_count_kill_target,
                loot_replace_entity_entities_slot_count_loot_loot_table,
                loot_replace_entity_entities_slot_count_mine_pos,
                loot_replace_entity_entities_slot_count_mine_pos_mainhand,
                loot_replace_entity_entities_slot_count_mine_pos_offhand,
                loot_replace_entity_entities_slot_count_mine_pos_tool,
                loot_spawn_targetPos_fish_loot_table_pos,
                loot_spawn_targetPos_fish_loot_table_pos_mainhand,
                loot_spawn_targetPos_fish_loot_table_pos_offhand,
                loot_spawn_targetPos_fish_loot_table_pos_tool,
                loot_spawn_targetPos_kill_target,
                loot_spawn_targetPos_loot_loot_table,
                loot_spawn_targetPos_mine_pos,
                loot_spawn_targetPos_mine_pos_mainhand,
                loot_spawn_targetPos_mine_pos_offhand,
                loot_spawn_targetPos_mine_pos_tool,
                me_action,
                msg_targets_message,
                op_targets,
                pardon_targets,
                pardon_ip_target,
                particle_name,
                particle_name_pos,
                particle_name_pos_delta_speed_count,
                particle_name_pos_delta_speed_count_force,
                particle_name_pos_delta_speed_count_force_viewers,
                particle_name_pos_delta_speed_count_normal,
                particle_name_pos_delta_speed_count_normal_viewers,
                playsound_sound_ambient_targets,
                playsound_sound_ambient_targets_pos,
                playsound_sound_ambient_targets_pos_volume,
                playsound_sound_ambient_targets_pos_volume_pitch,
                playsound_sound_ambient_targets_pos_volume_pitch_minVolume,
                playsound_sound_block_targets,
                playsound_sound_block_targets_pos,
                playsound_sound_block_targets_pos_volume,
                playsound_sound_block_targets_pos_volume_pitch,
                playsound_sound_block_targets_pos_volume_pitch_minVolume,
                playsound_sound_hostile_targets,
                playsound_sound_hostile_targets_pos,
                playsound_sound_hostile_targets_pos_volume,
                playsound_sound_hostile_targets_pos_volume_pitch,
                playsound_sound_hostile_targets_pos_volume_pitch_minVolume,
                playsound_sound_master_targets,
                playsound_sound_master_targets_pos,
                playsound_sound_master_targets_pos_volume,
                playsound_sound_master_targets_pos_volume_pitch,
                playsound_sound_master_targets_pos_volume_pitch_minVolume,
                playsound_sound_music_targets,
                playsound_sound_music_targets_pos,
                playsound_sound_music_targets_pos_volume,
                playsound_sound_music_targets_pos_volume_pitch,
                playsound_sound_music_targets_pos_volume_pitch_minVolume,
                playsound_sound_neutral_targets,
                playsound_sound_neutral_targets_pos,
                playsound_sound_neutral_targets_pos_volume,
                playsound_sound_neutral_targets_pos_volume_pitch,
                playsound_sound_neutral_targets_pos_volume_pitch_minVolume,
                playsound_sound_player_targets,
                playsound_sound_player_targets_pos,
                playsound_sound_player_targets_pos_volume,
                playsound_sound_player_targets_pos_volume_pitch,
                playsound_sound_player_targets_pos_volume_pitch_minVolume,
                playsound_sound_record_targets,
                playsound_sound_record_targets_pos,
                playsound_sound_record_targets_pos_volume,
                playsound_sound_record_targets_pos_volume_pitch,
                playsound_sound_record_targets_pos_volume_pitch_minVolume,
                playsound_sound_voice_targets,
                playsound_sound_voice_targets_pos,
                playsound_sound_voice_targets_pos_volume,
                playsound_sound_voice_targets_pos_volume_pitch,
                playsound_sound_voice_targets_pos_volume_pitch_minVolume,
                playsound_sound_weather_targets,
                playsound_sound_weather_targets_pos,
                playsound_sound_weather_targets_pos_volume,
                playsound_sound_weather_targets_pos_volume_pitch,
                playsound_sound_weather_targets_pos_volume_pitch_minVolume,
                publish,
                recipe_take_targets_recipe,
                reload,
                replaceitem_block_pos_slot_item,
                replaceitem_block_pos_slot_item_count,
                replaceitem_entity_targets_slot_item,
                replaceitem_entity_targets_slot_item_count,
                save_all,
                save_all_flush,
                save_off,
                save_on,
                say_message,
                schedule_clear_function,
                schedule_function_function_time,
                schedule_function_function_time_append,
                schedule_function_function_time_replace,
                scoreboard_objectives_add_objective_criteria,
                scoreboard_objectives_add_objective_criteria_displayName,
                scoreboard_objectives_list,
                scoreboard_objectives_modify_objective_displayname_displayName,
                scoreboard_objectives_modify_objective_rendertype_hearts,
                scoreboard_objectives_modify_objective_rendertype_integer,
                scoreboard_objectives_remove_objective,
                scoreboard_objectives_setdisplay_slot,
                scoreboard_objectives_setdisplay_slot_objective,
                scoreboard_players_add_targets_objective_score,
                scoreboard_players_enable_targets_objective,
                scoreboard_players_get_target_objective,
                scoreboard_players_list,
                scoreboard_players_list_target,
                scoreboard_players_operation_targets_targetObjective_operation_source_sourceObjective,
                scoreboard_players_remove_targets_objective_score,
                scoreboard_players_reset_targets,
                scoreboard_players_reset_targets_objective,
                scoreboard_players_set_targets_objective_score,
                seed,
                setblock_pos_block,
                setblock_pos_block_destroy,
                setblock_pos_block_keep,
                setblock_pos_block_replace,
                setidletimeout_minutes,
                setworldspawn,
                setworldspawn_pos,
                spawnpoint,
                spawnpoint_targets,
                spawnpoint_targets_pos,
                spectate,
                spectate_target,
                spectate_target_player,
                spreadplayers_center_spreadDistance_maxRange_under_maxHeight_respectTeams_targets,
                spreadplayers_center_spreadDistance_maxRange_respectTeams_targets,
                stop,
                stopsound_targets,
                stopsound_targets_ambient,
                stopsound_targets_ambient_sound,
                stopsound_targets_block,
                stopsound_targets_block_sound,
                stopsound_targets_hostile,
                stopsound_targets_hostile_sound,
                stopsound_targets_master,
                stopsound_targets_master_sound,
                stopsound_targets_music,
                stopsound_targets_music_sound,
                stopsound_targets_neutral,
                stopsound_targets_neutral_sound,
                stopsound_targets_player,
                stopsound_targets_player_sound,
                stopsound_targets_record,
                stopsound_targets_record_sound,
                stopsound_targets_voice,
                stopsound_targets_voice_sound,
                stopsound_targets_weather,
                stopsound_targets_weather_sound,
                summon_entity,
                summon_entity_pos,
                summon_entity_pos_nbt,
                tag_targets_add_name,
                tag_targets_list,
                tag_targets_remove_name,
                team_add_team,
                team_add_team_displayName,
                team_empty_team,
                team_join_team,
                team_join_team_members,
                team_leave_members,
                team_list,
                team_list_team,
                team_modify_team_collisionRule_always,
                team_modify_team_collisionRule_never,
                team_modify_team_collisionRule_pushOtherTeams,
                team_modify_team_collisionRule_pushOwnTeam,
                team_modify_team_color_value,
                team_modify_team_deathMessageVisibility_always,
                team_modify_team_deathMessageVisibility_hideForOtherTeams,
                team_modify_team_deathMessageVisibility_hideForOwnTeam,
                team_modify_team_deathMessageVisibility_never,
                team_modify_team_displayName_displayName,
                team_modify_team_friendlyFire_allowed,
                team_modify_team_nametagVisibility_always,
                team_modify_team_nametagVisibility_hideForOtherTeams,
                team_modify_team_nametagVisibility_hideForOwnTeam,
                team_modify_team_nametagVisibility_never,
                team_modify_team_prefix_prefix,
                team_modify_team_seeFriendlyInvisibles_allowed,
                team_modify_team_suffix_suffix,
                team_remove_team,
                teammsg_message,
                teleport_destination,
                teleport_location,
                teleport_targets_destination,
                teleport_targets_location,
                teleport_targets_location_facing_entity_facingEntity,
                teleport_targets_location_facing_entity_facingEntity_facingAnchor,
                teleport_targets_location_facing_facingLocation,
                teleport_targets_location_rotation,
                tell_targets_message,
                tellraw_targets_message,
                time_add_time,
                time_query_day,
                time_query_daytime,
                time_query_gametime,
                time_set_day,
                time_set_midnight,
                time_set_night,
                time_set_noon,
                time_set_time,
                title_targets_actionbar_title,
                title_targets_clear,
                title_targets_reset,
                title_targets_subtitle_title,
                title_targets_times_fadeIn_stay_fadeOut,
                title_targets_title_title,
                tm_message,
                tp_destination,
                tp_location,
                tp_targets_destination,
                tp_targets_location,
                tp_targets_location_facing_entity_facingEntity,
                tp_targets_location_facing_entity_facingEntity_facingAnchor,
                tp_targets_location_facing_facingLocation,
                tp_targets_location_rotation,
                trigger_objective,
                trigger_objective_add_value,
                trigger_objective_set_value,
                weather_clear,
                weather_clear_duration,
                weather_rain,
                weather_thunder,
                weather_thunder_duration,
                whitelist_add_targets,
                whitelist_list,
                whitelist_off,
                whitelist_on,
                whitelist_reload,
                whitelist_remove_targets,
                worldborder_add_distance,
                worldborder_add_distance_time,
                worldborder_center_pos,
                worldborder_damage_amount_damagePerBlock,
                worldborder_damage_buffer_distance,
                worldborder_get,
                worldborder_set_distance,
                worldborder_set_distance_time,
                worldborder_warning_distance_distance,
                worldborder_warning_time_time,
                xp_add_targets_amount,
                xp_add_targets_amount_levels,
                xp_add_targets_amount_points,
                xp_query_targets_levels,
                xp_query_targets_points,
                xp_set_targets_amount,
                xp_set_targets_amount_levels,
                xp_set_targets_amount_points,
                publish_port,
                recipe_give_targets_recipe,
                weather_rain_duration,
                experience_set_targets_amount,
                experience_query_targets_levels,
                //recipe_give_targets_star,
                //recipe_take_targets_star,
                //w_targets_message,
                //stopsound_targets_star_sound,
                //execute_unless_score_target_targetObjective_lt_source_sourceObjective,
                //execute_if_score_target_targetObjective_lt_source_sourceObjective,
                //execute_unless_score_target_targetObjective_eq_source_sourceObjective,
                //execute_unless_score_target_targetObjective_gt_source_sourceObjective,
                //execute_if_score_target_targetObjective_gt_source_sourceObjective,
                //execute_if_score_target_targetObjective_eq_source_sourceObjective,
            
            
        }

        Self {
            dispatcher: Arc::new(dispatcher),
        }
    }

    /// Dispatches a command.
    pub fn dispatch(&self, game: &mut Game, world: &mut World, sender: Entity, command: &str) {
        let mut ctx = CommandCtx {
            game: LifetimelessMut(game),
            world: LifetimelessMut(world),
            sender,
        };

        match self.dispatcher.dispatch(&mut ctx, command) {
            Ok(ok) => {
                if let Some(msg) = ok {
                    if let Some(mut receiver) = world.try_get_mut::<MessageReceiver>(sender) {
                        receiver.send(Text::from(msg));
                    }
                }
            }

            Err(errs) => {
                let msg = if let Some(last) = errs.last() {
                    Text::from(last.to_string()).red()
                } else {
                    Text::from("Unknown command.")
                };

                if let Some(mut receiver) = world.try_get_mut::<MessageReceiver>(sender) {
                    receiver.send(msg);
                }
            }
        }
    }
}
