use feather_blocks::*;
use feather_items::Item;
pub fn item_to_block(item: Item) -> Option<Block> {
    match item {
        Item::Air => Some(Block::Air),
        Item::Stone => Some(Block::Stone),
        Item::Granite => Some(Block::Granite),
        Item::PolishedGranite => Some(Block::PolishedGranite),
        Item::Diorite => Some(Block::Diorite),
        Item::PolishedDiorite => Some(Block::PolishedDiorite),
        Item::Andesite => Some(Block::Andesite),
        Item::PolishedAndesite => Some(Block::PolishedAndesite),
        Item::GrassBlock => Some(Block::GrassBlock(GrassBlockData { snowy: false })),
        Item::Dirt => Some(Block::Dirt),
        Item::CoarseDirt => Some(Block::CoarseDirt),
        Item::Podzol => Some(Block::Podzol(PodzolData { snowy: false })),
        Item::Cobblestone => Some(Block::Cobblestone),
        Item::OakPlanks => Some(Block::OakPlanks),
        Item::SprucePlanks => Some(Block::SprucePlanks),
        Item::BirchPlanks => Some(Block::BirchPlanks),
        Item::JunglePlanks => Some(Block::JunglePlanks),
        Item::AcaciaPlanks => Some(Block::AcaciaPlanks),
        Item::DarkOakPlanks => Some(Block::DarkOakPlanks),
        Item::OakSapling => Some(Block::OakSapling(OakSaplingData { stage: 0i32 })),
        Item::SpruceSapling => Some(Block::SpruceSapling(SpruceSaplingData { stage: 0i32 })),
        Item::BirchSapling => Some(Block::BirchSapling(BirchSaplingData { stage: 0i32 })),
        Item::JungleSapling => Some(Block::JungleSapling(JungleSaplingData { stage: 0i32 })),
        Item::AcaciaSapling => Some(Block::AcaciaSapling(AcaciaSaplingData { stage: 0i32 })),
        Item::DarkOakSapling => Some(Block::DarkOakSapling(DarkOakSaplingData { stage: 0i32 })),
        Item::Bedrock => Some(Block::Bedrock),
        Item::Sand => Some(Block::Sand),
        Item::RedSand => Some(Block::RedSand),
        Item::Gravel => Some(Block::Gravel),
        Item::GoldOre => Some(Block::GoldOre),
        Item::IronOre => Some(Block::IronOre),
        Item::CoalOre => Some(Block::CoalOre),
        Item::OakLog => Some(Block::OakLog(OakLogData {
            axis: OakLogAxis::Y,
        })),
        Item::SpruceLog => Some(Block::SpruceLog(SpruceLogData {
            axis: SpruceLogAxis::Y,
        })),
        Item::BirchLog => Some(Block::BirchLog(BirchLogData {
            axis: BirchLogAxis::Y,
        })),
        Item::JungleLog => Some(Block::JungleLog(JungleLogData {
            axis: JungleLogAxis::Y,
        })),
        Item::AcaciaLog => Some(Block::AcaciaLog(AcaciaLogData {
            axis: AcaciaLogAxis::Y,
        })),
        Item::DarkOakLog => Some(Block::DarkOakLog(DarkOakLogData {
            axis: DarkOakLogAxis::Y,
        })),
        Item::StrippedOakLog => Some(Block::StrippedOakLog(StrippedOakLogData {
            axis: StrippedOakLogAxis::Y,
        })),
        Item::StrippedSpruceLog => Some(Block::StrippedSpruceLog(StrippedSpruceLogData {
            axis: StrippedSpruceLogAxis::Y,
        })),
        Item::StrippedBirchLog => Some(Block::StrippedBirchLog(StrippedBirchLogData {
            axis: StrippedBirchLogAxis::Y,
        })),
        Item::StrippedJungleLog => Some(Block::StrippedJungleLog(StrippedJungleLogData {
            axis: StrippedJungleLogAxis::Y,
        })),
        Item::StrippedAcaciaLog => Some(Block::StrippedAcaciaLog(StrippedAcaciaLogData {
            axis: StrippedAcaciaLogAxis::Y,
        })),
        Item::StrippedDarkOakLog => Some(Block::StrippedDarkOakLog(StrippedDarkOakLogData {
            axis: StrippedDarkOakLogAxis::Y,
        })),
        Item::StrippedOakWood => Some(Block::StrippedOakWood(StrippedOakWoodData {
            axis: StrippedOakWoodAxis::Y,
        })),
        Item::StrippedSpruceWood => Some(Block::StrippedSpruceWood(StrippedSpruceWoodData {
            axis: StrippedSpruceWoodAxis::Y,
        })),
        Item::StrippedBirchWood => Some(Block::StrippedBirchWood(StrippedBirchWoodData {
            axis: StrippedBirchWoodAxis::Y,
        })),
        Item::StrippedJungleWood => Some(Block::StrippedJungleWood(StrippedJungleWoodData {
            axis: StrippedJungleWoodAxis::Y,
        })),
        Item::StrippedAcaciaWood => Some(Block::StrippedAcaciaWood(StrippedAcaciaWoodData {
            axis: StrippedAcaciaWoodAxis::Y,
        })),
        Item::StrippedDarkOakWood => Some(Block::StrippedDarkOakWood(StrippedDarkOakWoodData {
            axis: StrippedDarkOakWoodAxis::Y,
        })),
        Item::OakWood => Some(Block::OakWood(OakWoodData {
            axis: OakWoodAxis::Y,
        })),
        Item::SpruceWood => Some(Block::SpruceWood(SpruceWoodData {
            axis: SpruceWoodAxis::Y,
        })),
        Item::BirchWood => Some(Block::BirchWood(BirchWoodData {
            axis: BirchWoodAxis::Y,
        })),
        Item::JungleWood => Some(Block::JungleWood(JungleWoodData {
            axis: JungleWoodAxis::Y,
        })),
        Item::AcaciaWood => Some(Block::AcaciaWood(AcaciaWoodData {
            axis: AcaciaWoodAxis::Y,
        })),
        Item::DarkOakWood => Some(Block::DarkOakWood(DarkOakWoodData {
            axis: DarkOakWoodAxis::Y,
        })),
        Item::OakLeaves => Some(Block::OakLeaves(OakLeavesData {
            persistent: false,
            distance: 7i32,
        })),
        Item::SpruceLeaves => Some(Block::SpruceLeaves(SpruceLeavesData {
            persistent: false,
            distance: 7i32,
        })),
        Item::BirchLeaves => Some(Block::BirchLeaves(BirchLeavesData {
            persistent: false,
            distance: 7i32,
        })),
        Item::JungleLeaves => Some(Block::JungleLeaves(JungleLeavesData {
            persistent: false,
            distance: 7i32,
        })),
        Item::AcaciaLeaves => Some(Block::AcaciaLeaves(AcaciaLeavesData {
            persistent: false,
            distance: 7i32,
        })),
        Item::DarkOakLeaves => Some(Block::DarkOakLeaves(DarkOakLeavesData {
            distance: 7i32,
            persistent: false,
        })),
        Item::Sponge => Some(Block::Sponge),
        Item::WetSponge => Some(Block::WetSponge),
        Item::Glass => Some(Block::Glass),
        Item::LapisOre => Some(Block::LapisOre),
        Item::LapisBlock => Some(Block::LapisBlock),
        Item::Dispenser => Some(Block::Dispenser(DispenserData {
            triggered: false,
            facing: DispenserFacing::North,
        })),
        Item::Sandstone => Some(Block::Sandstone),
        Item::ChiseledSandstone => Some(Block::ChiseledSandstone),
        Item::CutSandstone => Some(Block::CutSandstone),
        Item::NoteBlock => Some(Block::NoteBlock(NoteBlockData {
            instrument: NoteBlockInstrument::Harp,
            powered: false,
            note: 0i32,
        })),
        Item::PoweredRail => Some(Block::PoweredRail(PoweredRailData {
            shape: PoweredRailShape::NorthSouth,
            powered: false,
        })),
        Item::DetectorRail => Some(Block::DetectorRail(DetectorRailData {
            powered: false,
            shape: DetectorRailShape::NorthSouth,
        })),
        Item::StickyPiston => Some(Block::StickyPiston(StickyPistonData {
            facing: StickyPistonFacing::North,
            extended: false,
        })),
        Item::Cobweb => Some(Block::Cobweb),
        Item::Grass => Some(Block::Grass),
        Item::Fern => Some(Block::Fern),
        Item::DeadBush => Some(Block::DeadBush),
        Item::Seagrass => Some(Block::Seagrass),
        Item::SeaPickle => Some(Block::SeaPickle(SeaPickleData {
            pickles: 1i32,
            waterlogged: true,
        })),
        Item::Piston => Some(Block::Piston(PistonData {
            facing: PistonFacing::North,
            extended: false,
        })),
        Item::WhiteWool => Some(Block::WhiteWool),
        Item::OrangeWool => Some(Block::OrangeWool),
        Item::MagentaWool => Some(Block::MagentaWool),
        Item::LightBlueWool => Some(Block::LightBlueWool),
        Item::YellowWool => Some(Block::YellowWool),
        Item::LimeWool => Some(Block::LimeWool),
        Item::PinkWool => Some(Block::PinkWool),
        Item::GrayWool => Some(Block::GrayWool),
        Item::LightGrayWool => Some(Block::LightGrayWool),
        Item::CyanWool => Some(Block::CyanWool),
        Item::PurpleWool => Some(Block::PurpleWool),
        Item::BlueWool => Some(Block::BlueWool),
        Item::BrownWool => Some(Block::BrownWool),
        Item::GreenWool => Some(Block::GreenWool),
        Item::RedWool => Some(Block::RedWool),
        Item::BlackWool => Some(Block::BlackWool),
        Item::Dandelion => Some(Block::Dandelion),
        Item::Poppy => Some(Block::Poppy),
        Item::BlueOrchid => Some(Block::BlueOrchid),
        Item::Allium => Some(Block::Allium),
        Item::AzureBluet => Some(Block::AzureBluet),
        Item::RedTulip => Some(Block::RedTulip),
        Item::OrangeTulip => Some(Block::OrangeTulip),
        Item::WhiteTulip => Some(Block::WhiteTulip),
        Item::PinkTulip => Some(Block::PinkTulip),
        Item::OxeyeDaisy => Some(Block::OxeyeDaisy),
        Item::BrownMushroom => Some(Block::BrownMushroom),
        Item::RedMushroom => Some(Block::RedMushroom),
        Item::GoldBlock => Some(Block::GoldBlock),
        Item::IronBlock => Some(Block::IronBlock),
        Item::OakSlab => Some(Block::OakSlab(OakSlabData {
            ty: OakSlabType::Bottom,
            waterlogged: false,
        })),
        Item::SpruceSlab => Some(Block::SpruceSlab(SpruceSlabData {
            waterlogged: false,
            ty: SpruceSlabType::Bottom,
        })),
        Item::BirchSlab => Some(Block::BirchSlab(BirchSlabData {
            ty: BirchSlabType::Bottom,
            waterlogged: false,
        })),
        Item::JungleSlab => Some(Block::JungleSlab(JungleSlabData {
            ty: JungleSlabType::Bottom,
            waterlogged: false,
        })),
        Item::AcaciaSlab => Some(Block::AcaciaSlab(AcaciaSlabData {
            ty: AcaciaSlabType::Bottom,
            waterlogged: false,
        })),
        Item::DarkOakSlab => Some(Block::DarkOakSlab(DarkOakSlabData {
            waterlogged: false,
            ty: DarkOakSlabType::Bottom,
        })),
        Item::StoneSlab => Some(Block::StoneSlab(StoneSlabData {
            ty: StoneSlabType::Bottom,
            waterlogged: false,
        })),
        Item::SandstoneSlab => Some(Block::SandstoneSlab(SandstoneSlabData {
            waterlogged: false,
            ty: SandstoneSlabType::Bottom,
        })),
        Item::PetrifiedOakSlab => Some(Block::PetrifiedOakSlab(PetrifiedOakSlabData {
            waterlogged: false,
            ty: PetrifiedOakSlabType::Bottom,
        })),
        Item::CobblestoneSlab => Some(Block::CobblestoneSlab(CobblestoneSlabData {
            ty: CobblestoneSlabType::Bottom,
            waterlogged: false,
        })),
        Item::BrickSlab => Some(Block::BrickSlab(BrickSlabData {
            ty: BrickSlabType::Bottom,
            waterlogged: false,
        })),
        Item::StoneBrickSlab => Some(Block::StoneBrickSlab(StoneBrickSlabData {
            ty: StoneBrickSlabType::Bottom,
            waterlogged: false,
        })),
        Item::NetherBrickSlab => Some(Block::NetherBrickSlab(NetherBrickSlabData {
            ty: NetherBrickSlabType::Bottom,
            waterlogged: false,
        })),
        Item::QuartzSlab => Some(Block::QuartzSlab(QuartzSlabData {
            waterlogged: false,
            ty: QuartzSlabType::Bottom,
        })),
        Item::RedSandstoneSlab => Some(Block::RedSandstoneSlab(RedSandstoneSlabData {
            ty: RedSandstoneSlabType::Bottom,
            waterlogged: false,
        })),
        Item::PurpurSlab => Some(Block::PurpurSlab(PurpurSlabData {
            ty: PurpurSlabType::Bottom,
            waterlogged: false,
        })),
        Item::PrismarineSlab => Some(Block::PrismarineSlab(PrismarineSlabData {
            ty: PrismarineSlabType::Bottom,
            waterlogged: false,
        })),
        Item::PrismarineBrickSlab => Some(Block::PrismarineBrickSlab(PrismarineBrickSlabData {
            ty: PrismarineBrickSlabType::Bottom,
            waterlogged: false,
        })),
        Item::DarkPrismarineSlab => Some(Block::DarkPrismarineSlab(DarkPrismarineSlabData {
            waterlogged: false,
            ty: DarkPrismarineSlabType::Bottom,
        })),
        Item::SmoothQuartz => Some(Block::SmoothQuartz),
        Item::SmoothRedSandstone => Some(Block::SmoothRedSandstone),
        Item::SmoothSandstone => Some(Block::SmoothSandstone),
        Item::SmoothStone => Some(Block::SmoothStone),
        Item::Bricks => Some(Block::Bricks),
        Item::Tnt => Some(Block::Tnt(TntData { unstable: false })),
        Item::Bookshelf => Some(Block::Bookshelf),
        Item::MossyCobblestone => Some(Block::MossyCobblestone),
        Item::Obsidian => Some(Block::Obsidian),
        Item::Torch => Some(Block::Torch),
        Item::EndRod => Some(Block::EndRod(EndRodData {
            facing: EndRodFacing::Up,
        })),
        Item::ChorusPlant => Some(Block::ChorusPlant(ChorusPlantData {
            east: false,
            west: false,
            north: false,
            down: false,
            south: false,
            up: false,
        })),
        Item::ChorusFlower => Some(Block::ChorusFlower(ChorusFlowerData { age: 0i32 })),
        Item::PurpurBlock => Some(Block::PurpurBlock),
        Item::PurpurPillar => Some(Block::PurpurPillar(PurpurPillarData {
            axis: PurpurPillarAxis::Y,
        })),
        Item::PurpurStairs => Some(Block::PurpurStairs(PurpurStairsData {
            shape: PurpurStairsShape::Straight,
            waterlogged: false,
            half: PurpurStairsHalf::Bottom,
            facing: PurpurStairsFacing::North,
        })),
        Item::Spawner => Some(Block::Spawner),
        Item::OakStairs => Some(Block::OakStairs(OakStairsData {
            half: OakStairsHalf::Bottom,
            waterlogged: false,
            shape: OakStairsShape::Straight,
            facing: OakStairsFacing::North,
        })),
        Item::Chest => Some(Block::Chest(ChestData {
            waterlogged: false,
            facing: ChestFacing::North,
            ty: ChestType::Single,
        })),
        Item::DiamondOre => Some(Block::DiamondOre),
        Item::DiamondBlock => Some(Block::DiamondBlock),
        Item::CraftingTable => Some(Block::CraftingTable),
        Item::Farmland => Some(Block::Farmland(FarmlandData { moisture: 0i32 })),
        Item::Furnace => Some(Block::Furnace(FurnaceData {
            lit: false,
            facing: FurnaceFacing::North,
        })),
        Item::Ladder => Some(Block::Ladder(LadderData {
            facing: LadderFacing::North,
            waterlogged: false,
        })),
        Item::Rail => Some(Block::Rail(RailData {
            shape: RailShape::NorthSouth,
        })),
        Item::CobblestoneStairs => Some(Block::CobblestoneStairs(CobblestoneStairsData {
            half: CobblestoneStairsHalf::Bottom,
            shape: CobblestoneStairsShape::Straight,
            facing: CobblestoneStairsFacing::North,
            waterlogged: false,
        })),
        Item::Lever => Some(Block::Lever(LeverData {
            face: LeverFace::Wall,
            facing: LeverFacing::North,
            powered: false,
        })),
        Item::StonePressurePlate => Some(Block::StonePressurePlate(StonePressurePlateData {
            powered: false,
        })),
        Item::OakPressurePlate => Some(Block::OakPressurePlate(OakPressurePlateData {
            powered: false,
        })),
        Item::SprucePressurePlate => Some(Block::SprucePressurePlate(SprucePressurePlateData {
            powered: false,
        })),
        Item::BirchPressurePlate => Some(Block::BirchPressurePlate(BirchPressurePlateData {
            powered: false,
        })),
        Item::JunglePressurePlate => Some(Block::JunglePressurePlate(JunglePressurePlateData {
            powered: false,
        })),
        Item::AcaciaPressurePlate => Some(Block::AcaciaPressurePlate(AcaciaPressurePlateData {
            powered: false,
        })),
        Item::DarkOakPressurePlate => Some(Block::DarkOakPressurePlate(DarkOakPressurePlateData {
            powered: false,
        })),
        Item::RedstoneOre => Some(Block::RedstoneOre(RedstoneOreData { lit: false })),
        Item::RedstoneTorch => Some(Block::RedstoneTorch(RedstoneTorchData { lit: true })),
        Item::StoneButton => Some(Block::StoneButton(StoneButtonData {
            facing: StoneButtonFacing::North,
            face: StoneButtonFace::Wall,
            powered: false,
        })),
        Item::Snow => Some(Block::Snow(SnowData { layers: 1i32 })),
        Item::Ice => Some(Block::Ice),
        Item::SnowBlock => Some(Block::SnowBlock),
        Item::Cactus => Some(Block::Cactus(CactusData { age: 0i32 })),
        Item::Clay => Some(Block::Clay),
        Item::Jukebox => Some(Block::Jukebox(JukeboxData { has_record: false })),
        Item::OakFence => Some(Block::OakFence(OakFenceData {
            south: false,
            waterlogged: false,
            west: false,
            east: false,
            north: false,
        })),
        Item::SpruceFence => Some(Block::SpruceFence(SpruceFenceData {
            north: false,
            waterlogged: false,
            south: false,
            east: false,
            west: false,
        })),
        Item::BirchFence => Some(Block::BirchFence(BirchFenceData {
            waterlogged: false,
            west: false,
            north: false,
            east: false,
            south: false,
        })),
        Item::JungleFence => Some(Block::JungleFence(JungleFenceData {
            waterlogged: false,
            north: false,
            west: false,
            south: false,
            east: false,
        })),
        Item::AcaciaFence => Some(Block::AcaciaFence(AcaciaFenceData {
            east: false,
            waterlogged: false,
            west: false,
            south: false,
            north: false,
        })),
        Item::DarkOakFence => Some(Block::DarkOakFence(DarkOakFenceData {
            north: false,
            south: false,
            east: false,
            waterlogged: false,
            west: false,
        })),
        Item::Pumpkin => Some(Block::Pumpkin),
        Item::CarvedPumpkin => Some(Block::CarvedPumpkin(CarvedPumpkinData {
            facing: CarvedPumpkinFacing::North,
        })),
        Item::Netherrack => Some(Block::Netherrack),
        Item::SoulSand => Some(Block::SoulSand),
        Item::Glowstone => Some(Block::Glowstone),
        Item::JackOLantern => Some(Block::JackOLantern(JackOLanternData {
            facing: JackOLanternFacing::North,
        })),
        Item::OakTrapdoor => Some(Block::OakTrapdoor(OakTrapdoorData {
            waterlogged: false,
            facing: OakTrapdoorFacing::North,
            open: false,
            half: OakTrapdoorHalf::Bottom,
            powered: false,
        })),
        Item::SpruceTrapdoor => Some(Block::SpruceTrapdoor(SpruceTrapdoorData {
            open: false,
            waterlogged: false,
            powered: false,
            facing: SpruceTrapdoorFacing::North,
            half: SpruceTrapdoorHalf::Bottom,
        })),
        Item::BirchTrapdoor => Some(Block::BirchTrapdoor(BirchTrapdoorData {
            facing: BirchTrapdoorFacing::North,
            waterlogged: false,
            powered: false,
            half: BirchTrapdoorHalf::Bottom,
            open: false,
        })),
        Item::JungleTrapdoor => Some(Block::JungleTrapdoor(JungleTrapdoorData {
            facing: JungleTrapdoorFacing::North,
            half: JungleTrapdoorHalf::Bottom,
            powered: false,
            waterlogged: false,
            open: false,
        })),
        Item::AcaciaTrapdoor => Some(Block::AcaciaTrapdoor(AcaciaTrapdoorData {
            facing: AcaciaTrapdoorFacing::North,
            half: AcaciaTrapdoorHalf::Bottom,
            powered: false,
            open: false,
            waterlogged: false,
        })),
        Item::DarkOakTrapdoor => Some(Block::DarkOakTrapdoor(DarkOakTrapdoorData {
            powered: false,
            facing: DarkOakTrapdoorFacing::North,
            open: false,
            half: DarkOakTrapdoorHalf::Bottom,
            waterlogged: false,
        })),
        Item::InfestedStone => Some(Block::InfestedStone),
        Item::InfestedCobblestone => Some(Block::InfestedCobblestone),
        Item::InfestedStoneBricks => Some(Block::InfestedStoneBricks),
        Item::InfestedMossyStoneBricks => Some(Block::InfestedMossyStoneBricks),
        Item::InfestedCrackedStoneBricks => Some(Block::InfestedCrackedStoneBricks),
        Item::InfestedChiseledStoneBricks => Some(Block::InfestedChiseledStoneBricks),
        Item::StoneBricks => Some(Block::StoneBricks),
        Item::MossyStoneBricks => Some(Block::MossyStoneBricks),
        Item::CrackedStoneBricks => Some(Block::CrackedStoneBricks),
        Item::ChiseledStoneBricks => Some(Block::ChiseledStoneBricks),
        Item::BrownMushroomBlock => Some(Block::BrownMushroomBlock(BrownMushroomBlockData {
            east: true,
            down: true,
            up: true,
            south: true,
            west: true,
            north: true,
        })),
        Item::RedMushroomBlock => Some(Block::RedMushroomBlock(RedMushroomBlockData {
            south: true,
            up: true,
            west: true,
            east: true,
            north: true,
            down: true,
        })),
        Item::MushroomStem => Some(Block::MushroomStem(MushroomStemData {
            east: true,
            up: true,
            north: true,
            west: true,
            down: true,
            south: true,
        })),
        Item::IronBars => Some(Block::IronBars(IronBarsData {
            east: false,
            south: false,
            north: false,
            west: false,
            waterlogged: false,
        })),
        Item::GlassPane => Some(Block::GlassPane(GlassPaneData {
            waterlogged: false,
            north: false,
            west: false,
            south: false,
            east: false,
        })),
        Item::Melon => Some(Block::Melon),
        Item::Vine => Some(Block::Vine(VineData {
            south: false,
            north: false,
            up: false,
            east: false,
            west: false,
        })),
        Item::OakFenceGate => Some(Block::OakFenceGate(OakFenceGateData {
            facing: OakFenceGateFacing::North,
            in_wall: false,
            open: false,
            powered: false,
        })),
        Item::SpruceFenceGate => Some(Block::SpruceFenceGate(SpruceFenceGateData {
            facing: SpruceFenceGateFacing::North,
            powered: false,
            open: false,
            in_wall: false,
        })),
        Item::BirchFenceGate => Some(Block::BirchFenceGate(BirchFenceGateData {
            powered: false,
            in_wall: false,
            open: false,
            facing: BirchFenceGateFacing::North,
        })),
        Item::JungleFenceGate => Some(Block::JungleFenceGate(JungleFenceGateData {
            powered: false,
            in_wall: false,
            facing: JungleFenceGateFacing::North,
            open: false,
        })),
        Item::AcaciaFenceGate => Some(Block::AcaciaFenceGate(AcaciaFenceGateData {
            facing: AcaciaFenceGateFacing::North,
            powered: false,
            open: false,
            in_wall: false,
        })),
        Item::DarkOakFenceGate => Some(Block::DarkOakFenceGate(DarkOakFenceGateData {
            in_wall: false,
            facing: DarkOakFenceGateFacing::North,
            open: false,
            powered: false,
        })),
        Item::BrickStairs => Some(Block::BrickStairs(BrickStairsData {
            shape: BrickStairsShape::Straight,
            half: BrickStairsHalf::Bottom,
            waterlogged: false,
            facing: BrickStairsFacing::North,
        })),
        Item::StoneBrickStairs => Some(Block::StoneBrickStairs(StoneBrickStairsData {
            waterlogged: false,
            shape: StoneBrickStairsShape::Straight,
            half: StoneBrickStairsHalf::Bottom,
            facing: StoneBrickStairsFacing::North,
        })),
        Item::Mycelium => Some(Block::Mycelium(MyceliumData { snowy: false })),
        Item::LilyPad => Some(Block::LilyPad),
        Item::NetherBricks => Some(Block::NetherBricks),
        Item::NetherBrickFence => Some(Block::NetherBrickFence(NetherBrickFenceData {
            waterlogged: false,
            west: false,
            north: false,
            east: false,
            south: false,
        })),
        Item::NetherBrickStairs => Some(Block::NetherBrickStairs(NetherBrickStairsData {
            shape: NetherBrickStairsShape::Straight,
            facing: NetherBrickStairsFacing::North,
            half: NetherBrickStairsHalf::Bottom,
            waterlogged: false,
        })),
        Item::EnchantingTable => Some(Block::EnchantingTable),
        Item::EndPortalFrame => Some(Block::EndPortalFrame(EndPortalFrameData {
            eye: false,
            facing: EndPortalFrameFacing::North,
        })),
        Item::EndStone => Some(Block::EndStone),
        Item::EndStoneBricks => Some(Block::EndStoneBricks),
        Item::DragonEgg => Some(Block::DragonEgg),
        Item::RedstoneLamp => Some(Block::RedstoneLamp(RedstoneLampData { lit: false })),
        Item::SandstoneStairs => Some(Block::SandstoneStairs(SandstoneStairsData {
            waterlogged: false,
            half: SandstoneStairsHalf::Bottom,
            facing: SandstoneStairsFacing::North,
            shape: SandstoneStairsShape::Straight,
        })),
        Item::EmeraldOre => Some(Block::EmeraldOre),
        Item::EnderChest => Some(Block::EnderChest(EnderChestData {
            facing: EnderChestFacing::North,
            waterlogged: false,
        })),
        Item::TripwireHook => Some(Block::TripwireHook(TripwireHookData {
            facing: TripwireHookFacing::North,
            attached: false,
            powered: false,
        })),
        Item::EmeraldBlock => Some(Block::EmeraldBlock),
        Item::SpruceStairs => Some(Block::SpruceStairs(SpruceStairsData {
            shape: SpruceStairsShape::Straight,
            half: SpruceStairsHalf::Bottom,
            facing: SpruceStairsFacing::North,
            waterlogged: false,
        })),
        Item::BirchStairs => Some(Block::BirchStairs(BirchStairsData {
            facing: BirchStairsFacing::North,
            waterlogged: false,
            half: BirchStairsHalf::Bottom,
            shape: BirchStairsShape::Straight,
        })),
        Item::JungleStairs => Some(Block::JungleStairs(JungleStairsData {
            facing: JungleStairsFacing::North,
            shape: JungleStairsShape::Straight,
            half: JungleStairsHalf::Bottom,
            waterlogged: false,
        })),
        Item::CommandBlock => Some(Block::CommandBlock(CommandBlockData {
            facing: CommandBlockFacing::North,
            conditional: false,
        })),
        Item::Beacon => Some(Block::Beacon),
        Item::CobblestoneWall => Some(Block::CobblestoneWall(CobblestoneWallData {
            up: true,
            waterlogged: false,
            north: false,
            west: false,
            south: false,
            east: false,
        })),
        Item::MossyCobblestoneWall => Some(Block::MossyCobblestoneWall(MossyCobblestoneWallData {
            up: true,
            south: false,
            north: false,
            east: false,
            west: false,
            waterlogged: false,
        })),
        Item::OakButton => Some(Block::OakButton(OakButtonData {
            powered: false,
            facing: OakButtonFacing::North,
            face: OakButtonFace::Wall,
        })),
        Item::SpruceButton => Some(Block::SpruceButton(SpruceButtonData {
            face: SpruceButtonFace::Wall,
            powered: false,
            facing: SpruceButtonFacing::North,
        })),
        Item::BirchButton => Some(Block::BirchButton(BirchButtonData {
            facing: BirchButtonFacing::North,
            face: BirchButtonFace::Wall,
            powered: false,
        })),
        Item::JungleButton => Some(Block::JungleButton(JungleButtonData {
            facing: JungleButtonFacing::North,
            powered: false,
            face: JungleButtonFace::Wall,
        })),
        Item::AcaciaButton => Some(Block::AcaciaButton(AcaciaButtonData {
            face: AcaciaButtonFace::Wall,
            powered: false,
            facing: AcaciaButtonFacing::North,
        })),
        Item::DarkOakButton => Some(Block::DarkOakButton(DarkOakButtonData {
            powered: false,
            face: DarkOakButtonFace::Wall,
            facing: DarkOakButtonFacing::North,
        })),
        Item::Anvil => Some(Block::Anvil(AnvilData {
            facing: AnvilFacing::North,
        })),
        Item::ChippedAnvil => Some(Block::ChippedAnvil(ChippedAnvilData {
            facing: ChippedAnvilFacing::North,
        })),
        Item::DamagedAnvil => Some(Block::DamagedAnvil(DamagedAnvilData {
            facing: DamagedAnvilFacing::North,
        })),
        Item::TrappedChest => Some(Block::TrappedChest(TrappedChestData {
            waterlogged: false,
            facing: TrappedChestFacing::North,
            ty: TrappedChestType::Single,
        })),
        Item::LightWeightedPressurePlate => Some(Block::LightWeightedPressurePlate(
            LightWeightedPressurePlateData { power: 0i32 },
        )),
        Item::HeavyWeightedPressurePlate => Some(Block::HeavyWeightedPressurePlate(
            HeavyWeightedPressurePlateData { power: 0i32 },
        )),
        Item::DaylightDetector => Some(Block::DaylightDetector(DaylightDetectorData {
            inverted: false,
            power: 0i32,
        })),
        Item::RedstoneBlock => Some(Block::RedstoneBlock),
        Item::NetherQuartzOre => Some(Block::NetherQuartzOre),
        Item::Hopper => Some(Block::Hopper(HopperData {
            enabled: true,
            facing: HopperFacing::Down,
        })),
        Item::ChiseledQuartzBlock => Some(Block::ChiseledQuartzBlock),
        Item::QuartzBlock => Some(Block::QuartzBlock),
        Item::QuartzPillar => Some(Block::QuartzPillar(QuartzPillarData {
            axis: QuartzPillarAxis::Y,
        })),
        Item::QuartzStairs => Some(Block::QuartzStairs(QuartzStairsData {
            shape: QuartzStairsShape::Straight,
            waterlogged: false,
            half: QuartzStairsHalf::Bottom,
            facing: QuartzStairsFacing::North,
        })),
        Item::ActivatorRail => Some(Block::ActivatorRail(ActivatorRailData {
            powered: false,
            shape: ActivatorRailShape::NorthSouth,
        })),
        Item::Dropper => Some(Block::Dropper(DropperData {
            facing: DropperFacing::North,
            triggered: false,
        })),
        Item::WhiteTerracotta => Some(Block::WhiteTerracotta),
        Item::OrangeTerracotta => Some(Block::OrangeTerracotta),
        Item::MagentaTerracotta => Some(Block::MagentaTerracotta),
        Item::LightBlueTerracotta => Some(Block::LightBlueTerracotta),
        Item::YellowTerracotta => Some(Block::YellowTerracotta),
        Item::LimeTerracotta => Some(Block::LimeTerracotta),
        Item::PinkTerracotta => Some(Block::PinkTerracotta),
        Item::GrayTerracotta => Some(Block::GrayTerracotta),
        Item::LightGrayTerracotta => Some(Block::LightGrayTerracotta),
        Item::CyanTerracotta => Some(Block::CyanTerracotta),
        Item::PurpleTerracotta => Some(Block::PurpleTerracotta),
        Item::BlueTerracotta => Some(Block::BlueTerracotta),
        Item::BrownTerracotta => Some(Block::BrownTerracotta),
        Item::GreenTerracotta => Some(Block::GreenTerracotta),
        Item::RedTerracotta => Some(Block::RedTerracotta),
        Item::BlackTerracotta => Some(Block::BlackTerracotta),
        Item::Barrier => Some(Block::Barrier),
        Item::IronTrapdoor => Some(Block::IronTrapdoor(IronTrapdoorData {
            open: false,
            facing: IronTrapdoorFacing::North,
            powered: false,
            half: IronTrapdoorHalf::Bottom,
            waterlogged: false,
        })),
        Item::HayBlock => Some(Block::HayBlock(HayBlockData {
            axis: HayBlockAxis::Y,
        })),
        Item::WhiteCarpet => Some(Block::WhiteCarpet),
        Item::OrangeCarpet => Some(Block::OrangeCarpet),
        Item::MagentaCarpet => Some(Block::MagentaCarpet),
        Item::LightBlueCarpet => Some(Block::LightBlueCarpet),
        Item::YellowCarpet => Some(Block::YellowCarpet),
        Item::LimeCarpet => Some(Block::LimeCarpet),
        Item::PinkCarpet => Some(Block::PinkCarpet),
        Item::GrayCarpet => Some(Block::GrayCarpet),
        Item::LightGrayCarpet => Some(Block::LightGrayCarpet),
        Item::CyanCarpet => Some(Block::CyanCarpet),
        Item::PurpleCarpet => Some(Block::PurpleCarpet),
        Item::BlueCarpet => Some(Block::BlueCarpet),
        Item::BrownCarpet => Some(Block::BrownCarpet),
        Item::GreenCarpet => Some(Block::GreenCarpet),
        Item::RedCarpet => Some(Block::RedCarpet),
        Item::BlackCarpet => Some(Block::BlackCarpet),
        Item::Terracotta => Some(Block::Terracotta),
        Item::CoalBlock => Some(Block::CoalBlock),
        Item::PackedIce => Some(Block::PackedIce),
        Item::AcaciaStairs => Some(Block::AcaciaStairs(AcaciaStairsData {
            half: AcaciaStairsHalf::Bottom,
            shape: AcaciaStairsShape::Straight,
            waterlogged: false,
            facing: AcaciaStairsFacing::North,
        })),
        Item::DarkOakStairs => Some(Block::DarkOakStairs(DarkOakStairsData {
            shape: DarkOakStairsShape::Straight,
            half: DarkOakStairsHalf::Bottom,
            waterlogged: false,
            facing: DarkOakStairsFacing::North,
        })),
        Item::SlimeBlock => Some(Block::SlimeBlock),
        Item::GrassPath => Some(Block::GrassPath),
        Item::Sunflower => Some(Block::Sunflower(SunflowerData {
            half: SunflowerHalf::Lower,
        })),
        Item::Lilac => Some(Block::Lilac(LilacData {
            half: LilacHalf::Lower,
        })),
        Item::RoseBush => Some(Block::RoseBush(RoseBushData {
            half: RoseBushHalf::Lower,
        })),
        Item::Peony => Some(Block::Peony(PeonyData {
            half: PeonyHalf::Lower,
        })),
        Item::TallGrass => Some(Block::TallGrass(TallGrassData {
            half: TallGrassHalf::Lower,
        })),
        Item::LargeFern => Some(Block::LargeFern(LargeFernData {
            half: LargeFernHalf::Lower,
        })),
        Item::WhiteStainedGlass => Some(Block::WhiteStainedGlass),
        Item::OrangeStainedGlass => Some(Block::OrangeStainedGlass),
        Item::MagentaStainedGlass => Some(Block::MagentaStainedGlass),
        Item::LightBlueStainedGlass => Some(Block::LightBlueStainedGlass),
        Item::YellowStainedGlass => Some(Block::YellowStainedGlass),
        Item::LimeStainedGlass => Some(Block::LimeStainedGlass),
        Item::PinkStainedGlass => Some(Block::PinkStainedGlass),
        Item::GrayStainedGlass => Some(Block::GrayStainedGlass),
        Item::LightGrayStainedGlass => Some(Block::LightGrayStainedGlass),
        Item::CyanStainedGlass => Some(Block::CyanStainedGlass),
        Item::PurpleStainedGlass => Some(Block::PurpleStainedGlass),
        Item::BlueStainedGlass => Some(Block::BlueStainedGlass),
        Item::BrownStainedGlass => Some(Block::BrownStainedGlass),
        Item::GreenStainedGlass => Some(Block::GreenStainedGlass),
        Item::RedStainedGlass => Some(Block::RedStainedGlass),
        Item::BlackStainedGlass => Some(Block::BlackStainedGlass),
        Item::WhiteStainedGlassPane => {
            Some(Block::WhiteStainedGlassPane(WhiteStainedGlassPaneData {
                west: false,
                east: false,
                waterlogged: false,
                north: false,
                south: false,
            }))
        }
        Item::OrangeStainedGlassPane => {
            Some(Block::OrangeStainedGlassPane(OrangeStainedGlassPaneData {
                south: false,
                waterlogged: false,
                east: false,
                west: false,
                north: false,
            }))
        }
        Item::MagentaStainedGlassPane => Some(Block::MagentaStainedGlassPane(
            MagentaStainedGlassPaneData {
                south: false,
                waterlogged: false,
                east: false,
                north: false,
                west: false,
            },
        )),
        Item::LightBlueStainedGlassPane => Some(Block::LightBlueStainedGlassPane(
            LightBlueStainedGlassPaneData {
                north: false,
                east: false,
                west: false,
                waterlogged: false,
                south: false,
            },
        )),
        Item::YellowStainedGlassPane => {
            Some(Block::YellowStainedGlassPane(YellowStainedGlassPaneData {
                west: false,
                south: false,
                north: false,
                waterlogged: false,
                east: false,
            }))
        }
        Item::LimeStainedGlassPane => Some(Block::LimeStainedGlassPane(LimeStainedGlassPaneData {
            south: false,
            north: false,
            west: false,
            east: false,
            waterlogged: false,
        })),
        Item::PinkStainedGlassPane => Some(Block::PinkStainedGlassPane(PinkStainedGlassPaneData {
            waterlogged: false,
            north: false,
            east: false,
            south: false,
            west: false,
        })),
        Item::GrayStainedGlassPane => Some(Block::GrayStainedGlassPane(GrayStainedGlassPaneData {
            waterlogged: false,
            east: false,
            north: false,
            west: false,
            south: false,
        })),
        Item::LightGrayStainedGlassPane => Some(Block::LightGrayStainedGlassPane(
            LightGrayStainedGlassPaneData {
                east: false,
                waterlogged: false,
                west: false,
                north: false,
                south: false,
            },
        )),
        Item::CyanStainedGlassPane => Some(Block::CyanStainedGlassPane(CyanStainedGlassPaneData {
            west: false,
            waterlogged: false,
            east: false,
            north: false,
            south: false,
        })),
        Item::PurpleStainedGlassPane => {
            Some(Block::PurpleStainedGlassPane(PurpleStainedGlassPaneData {
                west: false,
                waterlogged: false,
                east: false,
                north: false,
                south: false,
            }))
        }
        Item::BlueStainedGlassPane => Some(Block::BlueStainedGlassPane(BlueStainedGlassPaneData {
            east: false,
            north: false,
            south: false,
            waterlogged: false,
            west: false,
        })),
        Item::BrownStainedGlassPane => {
            Some(Block::BrownStainedGlassPane(BrownStainedGlassPaneData {
                east: false,
                west: false,
                north: false,
                waterlogged: false,
                south: false,
            }))
        }
        Item::GreenStainedGlassPane => {
            Some(Block::GreenStainedGlassPane(GreenStainedGlassPaneData {
                north: false,
                west: false,
                waterlogged: false,
                south: false,
                east: false,
            }))
        }
        Item::RedStainedGlassPane => Some(Block::RedStainedGlassPane(RedStainedGlassPaneData {
            waterlogged: false,
            south: false,
            west: false,
            east: false,
            north: false,
        })),
        Item::BlackStainedGlassPane => {
            Some(Block::BlackStainedGlassPane(BlackStainedGlassPaneData {
                east: false,
                south: false,
                west: false,
                waterlogged: false,
                north: false,
            }))
        }
        Item::Prismarine => Some(Block::Prismarine),
        Item::PrismarineBricks => Some(Block::PrismarineBricks),
        Item::DarkPrismarine => Some(Block::DarkPrismarine),
        Item::PrismarineStairs => Some(Block::PrismarineStairs(PrismarineStairsData {
            half: PrismarineStairsHalf::Bottom,
            shape: PrismarineStairsShape::Straight,
            facing: PrismarineStairsFacing::North,
            waterlogged: false,
        })),
        Item::PrismarineBrickStairs => {
            Some(Block::PrismarineBrickStairs(PrismarineBrickStairsData {
                half: PrismarineBrickStairsHalf::Bottom,
                waterlogged: false,
                shape: PrismarineBrickStairsShape::Straight,
                facing: PrismarineBrickStairsFacing::North,
            }))
        }
        Item::DarkPrismarineStairs => Some(Block::DarkPrismarineStairs(DarkPrismarineStairsData {
            facing: DarkPrismarineStairsFacing::North,
            half: DarkPrismarineStairsHalf::Bottom,
            waterlogged: false,
            shape: DarkPrismarineStairsShape::Straight,
        })),
        Item::SeaLantern => Some(Block::SeaLantern),
        Item::RedSandstone => Some(Block::RedSandstone),
        Item::ChiseledRedSandstone => Some(Block::ChiseledRedSandstone),
        Item::CutRedSandstone => Some(Block::CutRedSandstone),
        Item::RedSandstoneStairs => Some(Block::RedSandstoneStairs(RedSandstoneStairsData {
            waterlogged: false,
            facing: RedSandstoneStairsFacing::North,
            half: RedSandstoneStairsHalf::Bottom,
            shape: RedSandstoneStairsShape::Straight,
        })),
        Item::RepeatingCommandBlock => {
            Some(Block::RepeatingCommandBlock(RepeatingCommandBlockData {
                conditional: false,
                facing: RepeatingCommandBlockFacing::North,
            }))
        }
        Item::ChainCommandBlock => Some(Block::ChainCommandBlock(ChainCommandBlockData {
            conditional: false,
            facing: ChainCommandBlockFacing::North,
        })),
        Item::MagmaBlock => Some(Block::MagmaBlock),
        Item::NetherWartBlock => Some(Block::NetherWartBlock),
        Item::RedNetherBricks => Some(Block::RedNetherBricks),
        Item::BoneBlock => Some(Block::BoneBlock(BoneBlockData {
            axis: BoneBlockAxis::Y,
        })),
        Item::StructureVoid => Some(Block::StructureVoid),
        Item::Observer => Some(Block::Observer(ObserverData {
            facing: ObserverFacing::South,
            powered: false,
        })),
        Item::ShulkerBox => Some(Block::ShulkerBox(ShulkerBoxData {
            facing: ShulkerBoxFacing::Up,
        })),
        Item::WhiteShulkerBox => Some(Block::WhiteShulkerBox(WhiteShulkerBoxData {
            facing: WhiteShulkerBoxFacing::Up,
        })),
        Item::OrangeShulkerBox => Some(Block::OrangeShulkerBox(OrangeShulkerBoxData {
            facing: OrangeShulkerBoxFacing::Up,
        })),
        Item::MagentaShulkerBox => Some(Block::MagentaShulkerBox(MagentaShulkerBoxData {
            facing: MagentaShulkerBoxFacing::Up,
        })),
        Item::LightBlueShulkerBox => Some(Block::LightBlueShulkerBox(LightBlueShulkerBoxData {
            facing: LightBlueShulkerBoxFacing::Up,
        })),
        Item::YellowShulkerBox => Some(Block::YellowShulkerBox(YellowShulkerBoxData {
            facing: YellowShulkerBoxFacing::Up,
        })),
        Item::LimeShulkerBox => Some(Block::LimeShulkerBox(LimeShulkerBoxData {
            facing: LimeShulkerBoxFacing::Up,
        })),
        Item::PinkShulkerBox => Some(Block::PinkShulkerBox(PinkShulkerBoxData {
            facing: PinkShulkerBoxFacing::Up,
        })),
        Item::GrayShulkerBox => Some(Block::GrayShulkerBox(GrayShulkerBoxData {
            facing: GrayShulkerBoxFacing::Up,
        })),
        Item::LightGrayShulkerBox => Some(Block::LightGrayShulkerBox(LightGrayShulkerBoxData {
            facing: LightGrayShulkerBoxFacing::Up,
        })),
        Item::CyanShulkerBox => Some(Block::CyanShulkerBox(CyanShulkerBoxData {
            facing: CyanShulkerBoxFacing::Up,
        })),
        Item::PurpleShulkerBox => Some(Block::PurpleShulkerBox(PurpleShulkerBoxData {
            facing: PurpleShulkerBoxFacing::Up,
        })),
        Item::BlueShulkerBox => Some(Block::BlueShulkerBox(BlueShulkerBoxData {
            facing: BlueShulkerBoxFacing::Up,
        })),
        Item::BrownShulkerBox => Some(Block::BrownShulkerBox(BrownShulkerBoxData {
            facing: BrownShulkerBoxFacing::Up,
        })),
        Item::GreenShulkerBox => Some(Block::GreenShulkerBox(GreenShulkerBoxData {
            facing: GreenShulkerBoxFacing::Up,
        })),
        Item::RedShulkerBox => Some(Block::RedShulkerBox(RedShulkerBoxData {
            facing: RedShulkerBoxFacing::Up,
        })),
        Item::BlackShulkerBox => Some(Block::BlackShulkerBox(BlackShulkerBoxData {
            facing: BlackShulkerBoxFacing::Up,
        })),
        Item::WhiteGlazedTerracotta => {
            Some(Block::WhiteGlazedTerracotta(WhiteGlazedTerracottaData {
                facing: WhiteGlazedTerracottaFacing::North,
            }))
        }
        Item::OrangeGlazedTerracotta => {
            Some(Block::OrangeGlazedTerracotta(OrangeGlazedTerracottaData {
                facing: OrangeGlazedTerracottaFacing::North,
            }))
        }
        Item::MagentaGlazedTerracotta => Some(Block::MagentaGlazedTerracotta(
            MagentaGlazedTerracottaData {
                facing: MagentaGlazedTerracottaFacing::North,
            },
        )),
        Item::LightBlueGlazedTerracotta => Some(Block::LightBlueGlazedTerracotta(
            LightBlueGlazedTerracottaData {
                facing: LightBlueGlazedTerracottaFacing::North,
            },
        )),
        Item::YellowGlazedTerracotta => {
            Some(Block::YellowGlazedTerracotta(YellowGlazedTerracottaData {
                facing: YellowGlazedTerracottaFacing::North,
            }))
        }
        Item::LimeGlazedTerracotta => Some(Block::LimeGlazedTerracotta(LimeGlazedTerracottaData {
            facing: LimeGlazedTerracottaFacing::North,
        })),
        Item::PinkGlazedTerracotta => Some(Block::PinkGlazedTerracotta(PinkGlazedTerracottaData {
            facing: PinkGlazedTerracottaFacing::North,
        })),
        Item::GrayGlazedTerracotta => Some(Block::GrayGlazedTerracotta(GrayGlazedTerracottaData {
            facing: GrayGlazedTerracottaFacing::North,
        })),
        Item::LightGrayGlazedTerracotta => Some(Block::LightGrayGlazedTerracotta(
            LightGrayGlazedTerracottaData {
                facing: LightGrayGlazedTerracottaFacing::North,
            },
        )),
        Item::CyanGlazedTerracotta => Some(Block::CyanGlazedTerracotta(CyanGlazedTerracottaData {
            facing: CyanGlazedTerracottaFacing::North,
        })),
        Item::PurpleGlazedTerracotta => {
            Some(Block::PurpleGlazedTerracotta(PurpleGlazedTerracottaData {
                facing: PurpleGlazedTerracottaFacing::North,
            }))
        }
        Item::BlueGlazedTerracotta => Some(Block::BlueGlazedTerracotta(BlueGlazedTerracottaData {
            facing: BlueGlazedTerracottaFacing::North,
        })),
        Item::BrownGlazedTerracotta => {
            Some(Block::BrownGlazedTerracotta(BrownGlazedTerracottaData {
                facing: BrownGlazedTerracottaFacing::North,
            }))
        }
        Item::GreenGlazedTerracotta => {
            Some(Block::GreenGlazedTerracotta(GreenGlazedTerracottaData {
                facing: GreenGlazedTerracottaFacing::North,
            }))
        }
        Item::RedGlazedTerracotta => Some(Block::RedGlazedTerracotta(RedGlazedTerracottaData {
            facing: RedGlazedTerracottaFacing::North,
        })),
        Item::BlackGlazedTerracotta => {
            Some(Block::BlackGlazedTerracotta(BlackGlazedTerracottaData {
                facing: BlackGlazedTerracottaFacing::North,
            }))
        }
        Item::WhiteConcrete => Some(Block::WhiteConcrete),
        Item::OrangeConcrete => Some(Block::OrangeConcrete),
        Item::MagentaConcrete => Some(Block::MagentaConcrete),
        Item::LightBlueConcrete => Some(Block::LightBlueConcrete),
        Item::YellowConcrete => Some(Block::YellowConcrete),
        Item::LimeConcrete => Some(Block::LimeConcrete),
        Item::PinkConcrete => Some(Block::PinkConcrete),
        Item::GrayConcrete => Some(Block::GrayConcrete),
        Item::LightGrayConcrete => Some(Block::LightGrayConcrete),
        Item::CyanConcrete => Some(Block::CyanConcrete),
        Item::PurpleConcrete => Some(Block::PurpleConcrete),
        Item::BlueConcrete => Some(Block::BlueConcrete),
        Item::BrownConcrete => Some(Block::BrownConcrete),
        Item::GreenConcrete => Some(Block::GreenConcrete),
        Item::RedConcrete => Some(Block::RedConcrete),
        Item::BlackConcrete => Some(Block::BlackConcrete),
        Item::WhiteConcretePowder => Some(Block::WhiteConcretePowder),
        Item::OrangeConcretePowder => Some(Block::OrangeConcretePowder),
        Item::MagentaConcretePowder => Some(Block::MagentaConcretePowder),
        Item::LightBlueConcretePowder => Some(Block::LightBlueConcretePowder),
        Item::YellowConcretePowder => Some(Block::YellowConcretePowder),
        Item::LimeConcretePowder => Some(Block::LimeConcretePowder),
        Item::PinkConcretePowder => Some(Block::PinkConcretePowder),
        Item::GrayConcretePowder => Some(Block::GrayConcretePowder),
        Item::LightGrayConcretePowder => Some(Block::LightGrayConcretePowder),
        Item::CyanConcretePowder => Some(Block::CyanConcretePowder),
        Item::PurpleConcretePowder => Some(Block::PurpleConcretePowder),
        Item::BlueConcretePowder => Some(Block::BlueConcretePowder),
        Item::BrownConcretePowder => Some(Block::BrownConcretePowder),
        Item::GreenConcretePowder => Some(Block::GreenConcretePowder),
        Item::RedConcretePowder => Some(Block::RedConcretePowder),
        Item::BlackConcretePowder => Some(Block::BlackConcretePowder),
        Item::TurtleEgg => Some(Block::TurtleEgg(TurtleEggData {
            eggs: 1i32,
            hatch: 0i32,
        })),
        Item::DeadTubeCoralBlock => Some(Block::DeadTubeCoralBlock),
        Item::DeadBrainCoralBlock => Some(Block::DeadBrainCoralBlock),
        Item::DeadBubbleCoralBlock => Some(Block::DeadBubbleCoralBlock),
        Item::DeadFireCoralBlock => Some(Block::DeadFireCoralBlock),
        Item::DeadHornCoralBlock => Some(Block::DeadHornCoralBlock),
        Item::TubeCoralBlock => Some(Block::TubeCoralBlock),
        Item::BrainCoralBlock => Some(Block::BrainCoralBlock),
        Item::BubbleCoralBlock => Some(Block::BubbleCoralBlock),
        Item::FireCoralBlock => Some(Block::FireCoralBlock),
        Item::HornCoralBlock => Some(Block::HornCoralBlock),
        Item::TubeCoral => Some(Block::TubeCoral(TubeCoralData { waterlogged: true })),
        Item::BrainCoral => Some(Block::BrainCoral(BrainCoralData { waterlogged: true })),
        Item::BubbleCoral => Some(Block::BubbleCoral(BubbleCoralData { waterlogged: true })),
        Item::FireCoral => Some(Block::FireCoral(FireCoralData { waterlogged: true })),
        Item::HornCoral => Some(Block::HornCoral(HornCoralData { waterlogged: true })),
        Item::DeadBrainCoral => Some(Block::DeadBrainCoral(DeadBrainCoralData {
            waterlogged: true,
        })),
        Item::DeadBubbleCoral => Some(Block::DeadBubbleCoral(DeadBubbleCoralData {
            waterlogged: true,
        })),
        Item::DeadFireCoral => Some(Block::DeadFireCoral(DeadFireCoralData {
            waterlogged: true,
        })),
        Item::DeadHornCoral => Some(Block::DeadHornCoral(DeadHornCoralData {
            waterlogged: true,
        })),
        Item::DeadTubeCoral => Some(Block::DeadTubeCoral(DeadTubeCoralData {
            waterlogged: true,
        })),
        Item::TubeCoralFan => Some(Block::TubeCoralFan(TubeCoralFanData { waterlogged: true })),
        Item::BrainCoralFan => Some(Block::BrainCoralFan(BrainCoralFanData {
            waterlogged: true,
        })),
        Item::BubbleCoralFan => Some(Block::BubbleCoralFan(BubbleCoralFanData {
            waterlogged: true,
        })),
        Item::FireCoralFan => Some(Block::FireCoralFan(FireCoralFanData { waterlogged: true })),
        Item::HornCoralFan => Some(Block::HornCoralFan(HornCoralFanData { waterlogged: true })),
        Item::DeadTubeCoralFan => Some(Block::DeadTubeCoralFan(DeadTubeCoralFanData {
            waterlogged: true,
        })),
        Item::DeadBrainCoralFan => Some(Block::DeadBrainCoralFan(DeadBrainCoralFanData {
            waterlogged: true,
        })),
        Item::DeadBubbleCoralFan => Some(Block::DeadBubbleCoralFan(DeadBubbleCoralFanData {
            waterlogged: true,
        })),
        Item::DeadFireCoralFan => Some(Block::DeadFireCoralFan(DeadFireCoralFanData {
            waterlogged: true,
        })),
        Item::DeadHornCoralFan => Some(Block::DeadHornCoralFan(DeadHornCoralFanData {
            waterlogged: true,
        })),
        Item::BlueIce => Some(Block::BlueIce),
        Item::Conduit => Some(Block::Conduit(ConduitData { waterlogged: true })),
        Item::IronDoor => Some(Block::IronDoor(IronDoorData {
            powered: false,
            half: IronDoorHalf::Lower,
            open: false,
            facing: IronDoorFacing::North,
            hinge: IronDoorHinge::Left,
        })),
        Item::OakDoor => Some(Block::OakDoor(OakDoorData {
            facing: OakDoorFacing::North,
            powered: false,
            half: OakDoorHalf::Lower,
            open: false,
            hinge: OakDoorHinge::Left,
        })),
        Item::SpruceDoor => Some(Block::SpruceDoor(SpruceDoorData {
            powered: false,
            half: SpruceDoorHalf::Lower,
            facing: SpruceDoorFacing::North,
            hinge: SpruceDoorHinge::Left,
            open: false,
        })),
        Item::BirchDoor => Some(Block::BirchDoor(BirchDoorData {
            half: BirchDoorHalf::Lower,
            hinge: BirchDoorHinge::Left,
            open: false,
            facing: BirchDoorFacing::North,
            powered: false,
        })),
        Item::JungleDoor => Some(Block::JungleDoor(JungleDoorData {
            open: false,
            powered: false,
            hinge: JungleDoorHinge::Left,
            facing: JungleDoorFacing::North,
            half: JungleDoorHalf::Lower,
        })),
        Item::AcaciaDoor => Some(Block::AcaciaDoor(AcaciaDoorData {
            facing: AcaciaDoorFacing::North,
            hinge: AcaciaDoorHinge::Left,
            open: false,
            powered: false,
            half: AcaciaDoorHalf::Lower,
        })),
        Item::DarkOakDoor => Some(Block::DarkOakDoor(DarkOakDoorData {
            facing: DarkOakDoorFacing::North,
            hinge: DarkOakDoorHinge::Left,
            powered: false,
            half: DarkOakDoorHalf::Lower,
            open: false,
        })),
        Item::Repeater => Some(Block::Repeater(RepeaterData {
            delay: 1i32,
            facing: RepeaterFacing::North,
            locked: false,
            powered: false,
        })),
        Item::Comparator => Some(Block::Comparator(ComparatorData {
            mode: ComparatorMode::Compare,
            facing: ComparatorFacing::North,
            powered: false,
        })),
        Item::StructureBlock => Some(Block::StructureBlock(StructureBlockData {
            mode: StructureBlockMode::Save,
        })),
        Item::Wheat => Some(Block::Wheat(WheatData { age: 0i32 })),
        Item::Sign => Some(Block::Sign(SignData {
            waterlogged: false,
            rotation: 0i32,
        })),
        Item::SugarCane => Some(Block::SugarCane(SugarCaneData { age: 0i32 })),
        Item::Kelp => Some(Block::Kelp(KelpData { age: 0i32 })),
        Item::DriedKelpBlock => Some(Block::DriedKelpBlock),
        Item::Cake => Some(Block::Cake(CakeData { bites: 0i32 })),
        Item::WhiteBed => Some(Block::WhiteBed(WhiteBedData {
            occupied: false,
            facing: WhiteBedFacing::North,
            part: WhiteBedPart::Foot,
        })),
        Item::OrangeBed => Some(Block::OrangeBed(OrangeBedData {
            occupied: false,
            facing: OrangeBedFacing::North,
            part: OrangeBedPart::Foot,
        })),
        Item::MagentaBed => Some(Block::MagentaBed(MagentaBedData {
            facing: MagentaBedFacing::North,
            occupied: false,
            part: MagentaBedPart::Foot,
        })),
        Item::LightBlueBed => Some(Block::LightBlueBed(LightBlueBedData {
            part: LightBlueBedPart::Foot,
            occupied: false,
            facing: LightBlueBedFacing::North,
        })),
        Item::YellowBed => Some(Block::YellowBed(YellowBedData {
            occupied: false,
            part: YellowBedPart::Foot,
            facing: YellowBedFacing::North,
        })),
        Item::LimeBed => Some(Block::LimeBed(LimeBedData {
            facing: LimeBedFacing::North,
            occupied: false,
            part: LimeBedPart::Foot,
        })),
        Item::PinkBed => Some(Block::PinkBed(PinkBedData {
            facing: PinkBedFacing::North,
            occupied: false,
            part: PinkBedPart::Foot,
        })),
        Item::GrayBed => Some(Block::GrayBed(GrayBedData {
            part: GrayBedPart::Foot,
            occupied: false,
            facing: GrayBedFacing::North,
        })),
        Item::LightGrayBed => Some(Block::LightGrayBed(LightGrayBedData {
            occupied: false,
            part: LightGrayBedPart::Foot,
            facing: LightGrayBedFacing::North,
        })),
        Item::CyanBed => Some(Block::CyanBed(CyanBedData {
            part: CyanBedPart::Foot,
            facing: CyanBedFacing::North,
            occupied: false,
        })),
        Item::PurpleBed => Some(Block::PurpleBed(PurpleBedData {
            occupied: false,
            part: PurpleBedPart::Foot,
            facing: PurpleBedFacing::North,
        })),
        Item::BlueBed => Some(Block::BlueBed(BlueBedData {
            facing: BlueBedFacing::North,
            occupied: false,
            part: BlueBedPart::Foot,
        })),
        Item::BrownBed => Some(Block::BrownBed(BrownBedData {
            occupied: false,
            part: BrownBedPart::Foot,
            facing: BrownBedFacing::North,
        })),
        Item::GreenBed => Some(Block::GreenBed(GreenBedData {
            occupied: false,
            facing: GreenBedFacing::North,
            part: GreenBedPart::Foot,
        })),
        Item::RedBed => Some(Block::RedBed(RedBedData {
            occupied: false,
            facing: RedBedFacing::North,
            part: RedBedPart::Foot,
        })),
        Item::BlackBed => Some(Block::BlackBed(BlackBedData {
            facing: BlackBedFacing::North,
            part: BlackBedPart::Foot,
            occupied: false,
        })),
        Item::NetherWart => Some(Block::NetherWart(NetherWartData { age: 0i32 })),
        Item::BrewingStand => Some(Block::BrewingStand(BrewingStandData {
            has_bottle_2: false,
            has_bottle_0: false,
            has_bottle_1: false,
        })),
        Item::Cauldron => Some(Block::Cauldron(CauldronData { level: 0i32 })),
        Item::FlowerPot => Some(Block::FlowerPot),
        Item::SkeletonSkull => Some(Block::SkeletonSkull(SkeletonSkullData { rotation: 0i32 })),
        Item::WitherSkeletonSkull => Some(Block::WitherSkeletonSkull(WitherSkeletonSkullData {
            rotation: 0i32,
        })),
        Item::PlayerHead => Some(Block::PlayerHead(PlayerHeadData { rotation: 0i32 })),
        Item::ZombieHead => Some(Block::ZombieHead(ZombieHeadData { rotation: 0i32 })),
        Item::CreeperHead => Some(Block::CreeperHead(CreeperHeadData { rotation: 0i32 })),
        Item::DragonHead => Some(Block::DragonHead(DragonHeadData { rotation: 0i32 })),
        Item::WhiteBanner => Some(Block::WhiteBanner(WhiteBannerData { rotation: 0i32 })),
        Item::OrangeBanner => Some(Block::OrangeBanner(OrangeBannerData { rotation: 0i32 })),
        Item::MagentaBanner => Some(Block::MagentaBanner(MagentaBannerData { rotation: 0i32 })),
        Item::LightBlueBanner => Some(Block::LightBlueBanner(LightBlueBannerData {
            rotation: 0i32,
        })),
        Item::YellowBanner => Some(Block::YellowBanner(YellowBannerData { rotation: 0i32 })),
        Item::LimeBanner => Some(Block::LimeBanner(LimeBannerData { rotation: 0i32 })),
        Item::PinkBanner => Some(Block::PinkBanner(PinkBannerData { rotation: 0i32 })),
        Item::GrayBanner => Some(Block::GrayBanner(GrayBannerData { rotation: 0i32 })),
        Item::LightGrayBanner => Some(Block::LightGrayBanner(LightGrayBannerData {
            rotation: 0i32,
        })),
        Item::CyanBanner => Some(Block::CyanBanner(CyanBannerData { rotation: 0i32 })),
        Item::PurpleBanner => Some(Block::PurpleBanner(PurpleBannerData { rotation: 0i32 })),
        Item::BlueBanner => Some(Block::BlueBanner(BlueBannerData { rotation: 0i32 })),
        Item::BrownBanner => Some(Block::BrownBanner(BrownBannerData { rotation: 0i32 })),
        Item::GreenBanner => Some(Block::GreenBanner(GreenBannerData { rotation: 0i32 })),
        Item::RedBanner => Some(Block::RedBanner(RedBannerData { rotation: 0i32 })),
        Item::BlackBanner => Some(Block::BlackBanner(BlackBannerData { rotation: 0i32 })),
        _ => None,
    }
}
pub fn block_to_item(block: Block) -> Option<Item> {
    match block {
        Block::Air => Some(Item::Air),
        Block::Stone => Some(Item::Stone),
        Block::Granite => Some(Item::Granite),
        Block::PolishedGranite => Some(Item::PolishedGranite),
        Block::Diorite => Some(Item::Diorite),
        Block::PolishedDiorite => Some(Item::PolishedDiorite),
        Block::Andesite => Some(Item::Andesite),
        Block::PolishedAndesite => Some(Item::PolishedAndesite),
        Block::GrassBlock(_) => Some(Item::GrassBlock),
        Block::Dirt => Some(Item::Dirt),
        Block::CoarseDirt => Some(Item::CoarseDirt),
        Block::Podzol(_) => Some(Item::Podzol),
        Block::Cobblestone => Some(Item::Cobblestone),
        Block::OakPlanks => Some(Item::OakPlanks),
        Block::SprucePlanks => Some(Item::SprucePlanks),
        Block::BirchPlanks => Some(Item::BirchPlanks),
        Block::JunglePlanks => Some(Item::JunglePlanks),
        Block::AcaciaPlanks => Some(Item::AcaciaPlanks),
        Block::DarkOakPlanks => Some(Item::DarkOakPlanks),
        Block::OakSapling(_) => Some(Item::OakSapling),
        Block::SpruceSapling(_) => Some(Item::SpruceSapling),
        Block::BirchSapling(_) => Some(Item::BirchSapling),
        Block::JungleSapling(_) => Some(Item::JungleSapling),
        Block::AcaciaSapling(_) => Some(Item::AcaciaSapling),
        Block::DarkOakSapling(_) => Some(Item::DarkOakSapling),
        Block::Bedrock => Some(Item::Bedrock),
        Block::Sand => Some(Item::Sand),
        Block::RedSand => Some(Item::RedSand),
        Block::Gravel => Some(Item::Gravel),
        Block::GoldOre => Some(Item::GoldOre),
        Block::IronOre => Some(Item::IronOre),
        Block::CoalOre => Some(Item::CoalOre),
        Block::OakLog(_) => Some(Item::OakLog),
        Block::SpruceLog(_) => Some(Item::SpruceLog),
        Block::BirchLog(_) => Some(Item::BirchLog),
        Block::JungleLog(_) => Some(Item::JungleLog),
        Block::AcaciaLog(_) => Some(Item::AcaciaLog),
        Block::DarkOakLog(_) => Some(Item::DarkOakLog),
        Block::StrippedOakLog(_) => Some(Item::StrippedOakLog),
        Block::StrippedSpruceLog(_) => Some(Item::StrippedSpruceLog),
        Block::StrippedBirchLog(_) => Some(Item::StrippedBirchLog),
        Block::StrippedJungleLog(_) => Some(Item::StrippedJungleLog),
        Block::StrippedAcaciaLog(_) => Some(Item::StrippedAcaciaLog),
        Block::StrippedDarkOakLog(_) => Some(Item::StrippedDarkOakLog),
        Block::StrippedOakWood(_) => Some(Item::StrippedOakWood),
        Block::StrippedSpruceWood(_) => Some(Item::StrippedSpruceWood),
        Block::StrippedBirchWood(_) => Some(Item::StrippedBirchWood),
        Block::StrippedJungleWood(_) => Some(Item::StrippedJungleWood),
        Block::StrippedAcaciaWood(_) => Some(Item::StrippedAcaciaWood),
        Block::StrippedDarkOakWood(_) => Some(Item::StrippedDarkOakWood),
        Block::OakWood(_) => Some(Item::OakWood),
        Block::SpruceWood(_) => Some(Item::SpruceWood),
        Block::BirchWood(_) => Some(Item::BirchWood),
        Block::JungleWood(_) => Some(Item::JungleWood),
        Block::AcaciaWood(_) => Some(Item::AcaciaWood),
        Block::DarkOakWood(_) => Some(Item::DarkOakWood),
        Block::OakLeaves(_) => Some(Item::OakLeaves),
        Block::SpruceLeaves(_) => Some(Item::SpruceLeaves),
        Block::BirchLeaves(_) => Some(Item::BirchLeaves),
        Block::JungleLeaves(_) => Some(Item::JungleLeaves),
        Block::AcaciaLeaves(_) => Some(Item::AcaciaLeaves),
        Block::DarkOakLeaves(_) => Some(Item::DarkOakLeaves),
        Block::Sponge => Some(Item::Sponge),
        Block::WetSponge => Some(Item::WetSponge),
        Block::Glass => Some(Item::Glass),
        Block::LapisOre => Some(Item::LapisOre),
        Block::LapisBlock => Some(Item::LapisBlock),
        Block::Dispenser(_) => Some(Item::Dispenser),
        Block::Sandstone => Some(Item::Sandstone),
        Block::ChiseledSandstone => Some(Item::ChiseledSandstone),
        Block::CutSandstone => Some(Item::CutSandstone),
        Block::NoteBlock(_) => Some(Item::NoteBlock),
        Block::PoweredRail(_) => Some(Item::PoweredRail),
        Block::DetectorRail(_) => Some(Item::DetectorRail),
        Block::StickyPiston(_) => Some(Item::StickyPiston),
        Block::Cobweb => Some(Item::Cobweb),
        Block::Grass => Some(Item::Grass),
        Block::Fern => Some(Item::Fern),
        Block::DeadBush => Some(Item::DeadBush),
        Block::Seagrass => Some(Item::Seagrass),
        Block::SeaPickle(_) => Some(Item::SeaPickle),
        Block::Piston(_) => Some(Item::Piston),
        Block::WhiteWool => Some(Item::WhiteWool),
        Block::OrangeWool => Some(Item::OrangeWool),
        Block::MagentaWool => Some(Item::MagentaWool),
        Block::LightBlueWool => Some(Item::LightBlueWool),
        Block::YellowWool => Some(Item::YellowWool),
        Block::LimeWool => Some(Item::LimeWool),
        Block::PinkWool => Some(Item::PinkWool),
        Block::GrayWool => Some(Item::GrayWool),
        Block::LightGrayWool => Some(Item::LightGrayWool),
        Block::CyanWool => Some(Item::CyanWool),
        Block::PurpleWool => Some(Item::PurpleWool),
        Block::BlueWool => Some(Item::BlueWool),
        Block::BrownWool => Some(Item::BrownWool),
        Block::GreenWool => Some(Item::GreenWool),
        Block::RedWool => Some(Item::RedWool),
        Block::BlackWool => Some(Item::BlackWool),
        Block::Dandelion => Some(Item::Dandelion),
        Block::Poppy => Some(Item::Poppy),
        Block::BlueOrchid => Some(Item::BlueOrchid),
        Block::Allium => Some(Item::Allium),
        Block::AzureBluet => Some(Item::AzureBluet),
        Block::RedTulip => Some(Item::RedTulip),
        Block::OrangeTulip => Some(Item::OrangeTulip),
        Block::WhiteTulip => Some(Item::WhiteTulip),
        Block::PinkTulip => Some(Item::PinkTulip),
        Block::OxeyeDaisy => Some(Item::OxeyeDaisy),
        Block::BrownMushroom => Some(Item::BrownMushroom),
        Block::RedMushroom => Some(Item::RedMushroom),
        Block::GoldBlock => Some(Item::GoldBlock),
        Block::IronBlock => Some(Item::IronBlock),
        Block::OakSlab(_) => Some(Item::OakSlab),
        Block::SpruceSlab(_) => Some(Item::SpruceSlab),
        Block::BirchSlab(_) => Some(Item::BirchSlab),
        Block::JungleSlab(_) => Some(Item::JungleSlab),
        Block::AcaciaSlab(_) => Some(Item::AcaciaSlab),
        Block::DarkOakSlab(_) => Some(Item::DarkOakSlab),
        Block::StoneSlab(_) => Some(Item::StoneSlab),
        Block::SandstoneSlab(_) => Some(Item::SandstoneSlab),
        Block::PetrifiedOakSlab(_) => Some(Item::PetrifiedOakSlab),
        Block::CobblestoneSlab(_) => Some(Item::CobblestoneSlab),
        Block::BrickSlab(_) => Some(Item::BrickSlab),
        Block::StoneBrickSlab(_) => Some(Item::StoneBrickSlab),
        Block::NetherBrickSlab(_) => Some(Item::NetherBrickSlab),
        Block::QuartzSlab(_) => Some(Item::QuartzSlab),
        Block::RedSandstoneSlab(_) => Some(Item::RedSandstoneSlab),
        Block::PurpurSlab(_) => Some(Item::PurpurSlab),
        Block::PrismarineSlab(_) => Some(Item::PrismarineSlab),
        Block::PrismarineBrickSlab(_) => Some(Item::PrismarineBrickSlab),
        Block::DarkPrismarineSlab(_) => Some(Item::DarkPrismarineSlab),
        Block::SmoothQuartz => Some(Item::SmoothQuartz),
        Block::SmoothRedSandstone => Some(Item::SmoothRedSandstone),
        Block::SmoothSandstone => Some(Item::SmoothSandstone),
        Block::SmoothStone => Some(Item::SmoothStone),
        Block::Bricks => Some(Item::Bricks),
        Block::Tnt(_) => Some(Item::Tnt),
        Block::Bookshelf => Some(Item::Bookshelf),
        Block::MossyCobblestone => Some(Item::MossyCobblestone),
        Block::Obsidian => Some(Item::Obsidian),
        Block::Torch => Some(Item::Torch),
        Block::EndRod(_) => Some(Item::EndRod),
        Block::ChorusPlant(_) => Some(Item::ChorusPlant),
        Block::ChorusFlower(_) => Some(Item::ChorusFlower),
        Block::PurpurBlock => Some(Item::PurpurBlock),
        Block::PurpurPillar(_) => Some(Item::PurpurPillar),
        Block::PurpurStairs(_) => Some(Item::PurpurStairs),
        Block::Spawner => Some(Item::Spawner),
        Block::OakStairs(_) => Some(Item::OakStairs),
        Block::Chest(_) => Some(Item::Chest),
        Block::DiamondOre => Some(Item::DiamondOre),
        Block::DiamondBlock => Some(Item::DiamondBlock),
        Block::CraftingTable => Some(Item::CraftingTable),
        Block::Farmland(_) => Some(Item::Farmland),
        Block::Furnace(_) => Some(Item::Furnace),
        Block::Ladder(_) => Some(Item::Ladder),
        Block::Rail(_) => Some(Item::Rail),
        Block::CobblestoneStairs(_) => Some(Item::CobblestoneStairs),
        Block::Lever(_) => Some(Item::Lever),
        Block::StonePressurePlate(_) => Some(Item::StonePressurePlate),
        Block::OakPressurePlate(_) => Some(Item::OakPressurePlate),
        Block::SprucePressurePlate(_) => Some(Item::SprucePressurePlate),
        Block::BirchPressurePlate(_) => Some(Item::BirchPressurePlate),
        Block::JunglePressurePlate(_) => Some(Item::JunglePressurePlate),
        Block::AcaciaPressurePlate(_) => Some(Item::AcaciaPressurePlate),
        Block::DarkOakPressurePlate(_) => Some(Item::DarkOakPressurePlate),
        Block::RedstoneOre(_) => Some(Item::RedstoneOre),
        Block::RedstoneTorch(_) => Some(Item::RedstoneTorch),
        Block::StoneButton(_) => Some(Item::StoneButton),
        Block::Snow(_) => Some(Item::Snow),
        Block::Ice => Some(Item::Ice),
        Block::SnowBlock => Some(Item::SnowBlock),
        Block::Cactus(_) => Some(Item::Cactus),
        Block::Clay => Some(Item::Clay),
        Block::Jukebox(_) => Some(Item::Jukebox),
        Block::OakFence(_) => Some(Item::OakFence),
        Block::SpruceFence(_) => Some(Item::SpruceFence),
        Block::BirchFence(_) => Some(Item::BirchFence),
        Block::JungleFence(_) => Some(Item::JungleFence),
        Block::AcaciaFence(_) => Some(Item::AcaciaFence),
        Block::DarkOakFence(_) => Some(Item::DarkOakFence),
        Block::Pumpkin => Some(Item::Pumpkin),
        Block::CarvedPumpkin(_) => Some(Item::CarvedPumpkin),
        Block::Netherrack => Some(Item::Netherrack),
        Block::SoulSand => Some(Item::SoulSand),
        Block::Glowstone => Some(Item::Glowstone),
        Block::JackOLantern(_) => Some(Item::JackOLantern),
        Block::OakTrapdoor(_) => Some(Item::OakTrapdoor),
        Block::SpruceTrapdoor(_) => Some(Item::SpruceTrapdoor),
        Block::BirchTrapdoor(_) => Some(Item::BirchTrapdoor),
        Block::JungleTrapdoor(_) => Some(Item::JungleTrapdoor),
        Block::AcaciaTrapdoor(_) => Some(Item::AcaciaTrapdoor),
        Block::DarkOakTrapdoor(_) => Some(Item::DarkOakTrapdoor),
        Block::InfestedStone => Some(Item::InfestedStone),
        Block::InfestedCobblestone => Some(Item::InfestedCobblestone),
        Block::InfestedStoneBricks => Some(Item::InfestedStoneBricks),
        Block::InfestedMossyStoneBricks => Some(Item::InfestedMossyStoneBricks),
        Block::InfestedCrackedStoneBricks => Some(Item::InfestedCrackedStoneBricks),
        Block::InfestedChiseledStoneBricks => Some(Item::InfestedChiseledStoneBricks),
        Block::StoneBricks => Some(Item::StoneBricks),
        Block::MossyStoneBricks => Some(Item::MossyStoneBricks),
        Block::CrackedStoneBricks => Some(Item::CrackedStoneBricks),
        Block::ChiseledStoneBricks => Some(Item::ChiseledStoneBricks),
        Block::BrownMushroomBlock(_) => Some(Item::BrownMushroomBlock),
        Block::RedMushroomBlock(_) => Some(Item::RedMushroomBlock),
        Block::MushroomStem(_) => Some(Item::MushroomStem),
        Block::IronBars(_) => Some(Item::IronBars),
        Block::GlassPane(_) => Some(Item::GlassPane),
        Block::Melon => Some(Item::Melon),
        Block::Vine(_) => Some(Item::Vine),
        Block::OakFenceGate(_) => Some(Item::OakFenceGate),
        Block::SpruceFenceGate(_) => Some(Item::SpruceFenceGate),
        Block::BirchFenceGate(_) => Some(Item::BirchFenceGate),
        Block::JungleFenceGate(_) => Some(Item::JungleFenceGate),
        Block::AcaciaFenceGate(_) => Some(Item::AcaciaFenceGate),
        Block::DarkOakFenceGate(_) => Some(Item::DarkOakFenceGate),
        Block::BrickStairs(_) => Some(Item::BrickStairs),
        Block::StoneBrickStairs(_) => Some(Item::StoneBrickStairs),
        Block::Mycelium(_) => Some(Item::Mycelium),
        Block::LilyPad => Some(Item::LilyPad),
        Block::NetherBricks => Some(Item::NetherBricks),
        Block::NetherBrickFence(_) => Some(Item::NetherBrickFence),
        Block::NetherBrickStairs(_) => Some(Item::NetherBrickStairs),
        Block::EnchantingTable => Some(Item::EnchantingTable),
        Block::EndPortalFrame(_) => Some(Item::EndPortalFrame),
        Block::EndStone => Some(Item::EndStone),
        Block::EndStoneBricks => Some(Item::EndStoneBricks),
        Block::DragonEgg => Some(Item::DragonEgg),
        Block::RedstoneLamp(_) => Some(Item::RedstoneLamp),
        Block::SandstoneStairs(_) => Some(Item::SandstoneStairs),
        Block::EmeraldOre => Some(Item::EmeraldOre),
        Block::EnderChest(_) => Some(Item::EnderChest),
        Block::TripwireHook(_) => Some(Item::TripwireHook),
        Block::EmeraldBlock => Some(Item::EmeraldBlock),
        Block::SpruceStairs(_) => Some(Item::SpruceStairs),
        Block::BirchStairs(_) => Some(Item::BirchStairs),
        Block::JungleStairs(_) => Some(Item::JungleStairs),
        Block::CommandBlock(_) => Some(Item::CommandBlock),
        Block::Beacon => Some(Item::Beacon),
        Block::CobblestoneWall(_) => Some(Item::CobblestoneWall),
        Block::MossyCobblestoneWall(_) => Some(Item::MossyCobblestoneWall),
        Block::OakButton(_) => Some(Item::OakButton),
        Block::SpruceButton(_) => Some(Item::SpruceButton),
        Block::BirchButton(_) => Some(Item::BirchButton),
        Block::JungleButton(_) => Some(Item::JungleButton),
        Block::AcaciaButton(_) => Some(Item::AcaciaButton),
        Block::DarkOakButton(_) => Some(Item::DarkOakButton),
        Block::Anvil(_) => Some(Item::Anvil),
        Block::ChippedAnvil(_) => Some(Item::ChippedAnvil),
        Block::DamagedAnvil(_) => Some(Item::DamagedAnvil),
        Block::TrappedChest(_) => Some(Item::TrappedChest),
        Block::LightWeightedPressurePlate(_) => Some(Item::LightWeightedPressurePlate),
        Block::HeavyWeightedPressurePlate(_) => Some(Item::HeavyWeightedPressurePlate),
        Block::DaylightDetector(_) => Some(Item::DaylightDetector),
        Block::RedstoneBlock => Some(Item::RedstoneBlock),
        Block::NetherQuartzOre => Some(Item::NetherQuartzOre),
        Block::Hopper(_) => Some(Item::Hopper),
        Block::ChiseledQuartzBlock => Some(Item::ChiseledQuartzBlock),
        Block::QuartzBlock => Some(Item::QuartzBlock),
        Block::QuartzPillar(_) => Some(Item::QuartzPillar),
        Block::QuartzStairs(_) => Some(Item::QuartzStairs),
        Block::ActivatorRail(_) => Some(Item::ActivatorRail),
        Block::Dropper(_) => Some(Item::Dropper),
        Block::WhiteTerracotta => Some(Item::WhiteTerracotta),
        Block::OrangeTerracotta => Some(Item::OrangeTerracotta),
        Block::MagentaTerracotta => Some(Item::MagentaTerracotta),
        Block::LightBlueTerracotta => Some(Item::LightBlueTerracotta),
        Block::YellowTerracotta => Some(Item::YellowTerracotta),
        Block::LimeTerracotta => Some(Item::LimeTerracotta),
        Block::PinkTerracotta => Some(Item::PinkTerracotta),
        Block::GrayTerracotta => Some(Item::GrayTerracotta),
        Block::LightGrayTerracotta => Some(Item::LightGrayTerracotta),
        Block::CyanTerracotta => Some(Item::CyanTerracotta),
        Block::PurpleTerracotta => Some(Item::PurpleTerracotta),
        Block::BlueTerracotta => Some(Item::BlueTerracotta),
        Block::BrownTerracotta => Some(Item::BrownTerracotta),
        Block::GreenTerracotta => Some(Item::GreenTerracotta),
        Block::RedTerracotta => Some(Item::RedTerracotta),
        Block::BlackTerracotta => Some(Item::BlackTerracotta),
        Block::Barrier => Some(Item::Barrier),
        Block::IronTrapdoor(_) => Some(Item::IronTrapdoor),
        Block::HayBlock(_) => Some(Item::HayBlock),
        Block::WhiteCarpet => Some(Item::WhiteCarpet),
        Block::OrangeCarpet => Some(Item::OrangeCarpet),
        Block::MagentaCarpet => Some(Item::MagentaCarpet),
        Block::LightBlueCarpet => Some(Item::LightBlueCarpet),
        Block::YellowCarpet => Some(Item::YellowCarpet),
        Block::LimeCarpet => Some(Item::LimeCarpet),
        Block::PinkCarpet => Some(Item::PinkCarpet),
        Block::GrayCarpet => Some(Item::GrayCarpet),
        Block::LightGrayCarpet => Some(Item::LightGrayCarpet),
        Block::CyanCarpet => Some(Item::CyanCarpet),
        Block::PurpleCarpet => Some(Item::PurpleCarpet),
        Block::BlueCarpet => Some(Item::BlueCarpet),
        Block::BrownCarpet => Some(Item::BrownCarpet),
        Block::GreenCarpet => Some(Item::GreenCarpet),
        Block::RedCarpet => Some(Item::RedCarpet),
        Block::BlackCarpet => Some(Item::BlackCarpet),
        Block::Terracotta => Some(Item::Terracotta),
        Block::CoalBlock => Some(Item::CoalBlock),
        Block::PackedIce => Some(Item::PackedIce),
        Block::AcaciaStairs(_) => Some(Item::AcaciaStairs),
        Block::DarkOakStairs(_) => Some(Item::DarkOakStairs),
        Block::SlimeBlock => Some(Item::SlimeBlock),
        Block::GrassPath => Some(Item::GrassPath),
        Block::Sunflower(_) => Some(Item::Sunflower),
        Block::Lilac(_) => Some(Item::Lilac),
        Block::RoseBush(_) => Some(Item::RoseBush),
        Block::Peony(_) => Some(Item::Peony),
        Block::TallGrass(_) => Some(Item::TallGrass),
        Block::LargeFern(_) => Some(Item::LargeFern),
        Block::WhiteStainedGlass => Some(Item::WhiteStainedGlass),
        Block::OrangeStainedGlass => Some(Item::OrangeStainedGlass),
        Block::MagentaStainedGlass => Some(Item::MagentaStainedGlass),
        Block::LightBlueStainedGlass => Some(Item::LightBlueStainedGlass),
        Block::YellowStainedGlass => Some(Item::YellowStainedGlass),
        Block::LimeStainedGlass => Some(Item::LimeStainedGlass),
        Block::PinkStainedGlass => Some(Item::PinkStainedGlass),
        Block::GrayStainedGlass => Some(Item::GrayStainedGlass),
        Block::LightGrayStainedGlass => Some(Item::LightGrayStainedGlass),
        Block::CyanStainedGlass => Some(Item::CyanStainedGlass),
        Block::PurpleStainedGlass => Some(Item::PurpleStainedGlass),
        Block::BlueStainedGlass => Some(Item::BlueStainedGlass),
        Block::BrownStainedGlass => Some(Item::BrownStainedGlass),
        Block::GreenStainedGlass => Some(Item::GreenStainedGlass),
        Block::RedStainedGlass => Some(Item::RedStainedGlass),
        Block::BlackStainedGlass => Some(Item::BlackStainedGlass),
        Block::WhiteStainedGlassPane(_) => Some(Item::WhiteStainedGlassPane),
        Block::OrangeStainedGlassPane(_) => Some(Item::OrangeStainedGlassPane),
        Block::MagentaStainedGlassPane(_) => Some(Item::MagentaStainedGlassPane),
        Block::LightBlueStainedGlassPane(_) => Some(Item::LightBlueStainedGlassPane),
        Block::YellowStainedGlassPane(_) => Some(Item::YellowStainedGlassPane),
        Block::LimeStainedGlassPane(_) => Some(Item::LimeStainedGlassPane),
        Block::PinkStainedGlassPane(_) => Some(Item::PinkStainedGlassPane),
        Block::GrayStainedGlassPane(_) => Some(Item::GrayStainedGlassPane),
        Block::LightGrayStainedGlassPane(_) => Some(Item::LightGrayStainedGlassPane),
        Block::CyanStainedGlassPane(_) => Some(Item::CyanStainedGlassPane),
        Block::PurpleStainedGlassPane(_) => Some(Item::PurpleStainedGlassPane),
        Block::BlueStainedGlassPane(_) => Some(Item::BlueStainedGlassPane),
        Block::BrownStainedGlassPane(_) => Some(Item::BrownStainedGlassPane),
        Block::GreenStainedGlassPane(_) => Some(Item::GreenStainedGlassPane),
        Block::RedStainedGlassPane(_) => Some(Item::RedStainedGlassPane),
        Block::BlackStainedGlassPane(_) => Some(Item::BlackStainedGlassPane),
        Block::Prismarine => Some(Item::Prismarine),
        Block::PrismarineBricks => Some(Item::PrismarineBricks),
        Block::DarkPrismarine => Some(Item::DarkPrismarine),
        Block::PrismarineStairs(_) => Some(Item::PrismarineStairs),
        Block::PrismarineBrickStairs(_) => Some(Item::PrismarineBrickStairs),
        Block::DarkPrismarineStairs(_) => Some(Item::DarkPrismarineStairs),
        Block::SeaLantern => Some(Item::SeaLantern),
        Block::RedSandstone => Some(Item::RedSandstone),
        Block::ChiseledRedSandstone => Some(Item::ChiseledRedSandstone),
        Block::CutRedSandstone => Some(Item::CutRedSandstone),
        Block::RedSandstoneStairs(_) => Some(Item::RedSandstoneStairs),
        Block::RepeatingCommandBlock(_) => Some(Item::RepeatingCommandBlock),
        Block::ChainCommandBlock(_) => Some(Item::ChainCommandBlock),
        Block::MagmaBlock => Some(Item::MagmaBlock),
        Block::NetherWartBlock => Some(Item::NetherWartBlock),
        Block::RedNetherBricks => Some(Item::RedNetherBricks),
        Block::BoneBlock(_) => Some(Item::BoneBlock),
        Block::StructureVoid => Some(Item::StructureVoid),
        Block::Observer(_) => Some(Item::Observer),
        Block::ShulkerBox(_) => Some(Item::ShulkerBox),
        Block::WhiteShulkerBox(_) => Some(Item::WhiteShulkerBox),
        Block::OrangeShulkerBox(_) => Some(Item::OrangeShulkerBox),
        Block::MagentaShulkerBox(_) => Some(Item::MagentaShulkerBox),
        Block::LightBlueShulkerBox(_) => Some(Item::LightBlueShulkerBox),
        Block::YellowShulkerBox(_) => Some(Item::YellowShulkerBox),
        Block::LimeShulkerBox(_) => Some(Item::LimeShulkerBox),
        Block::PinkShulkerBox(_) => Some(Item::PinkShulkerBox),
        Block::GrayShulkerBox(_) => Some(Item::GrayShulkerBox),
        Block::LightGrayShulkerBox(_) => Some(Item::LightGrayShulkerBox),
        Block::CyanShulkerBox(_) => Some(Item::CyanShulkerBox),
        Block::PurpleShulkerBox(_) => Some(Item::PurpleShulkerBox),
        Block::BlueShulkerBox(_) => Some(Item::BlueShulkerBox),
        Block::BrownShulkerBox(_) => Some(Item::BrownShulkerBox),
        Block::GreenShulkerBox(_) => Some(Item::GreenShulkerBox),
        Block::RedShulkerBox(_) => Some(Item::RedShulkerBox),
        Block::BlackShulkerBox(_) => Some(Item::BlackShulkerBox),
        Block::WhiteGlazedTerracotta(_) => Some(Item::WhiteGlazedTerracotta),
        Block::OrangeGlazedTerracotta(_) => Some(Item::OrangeGlazedTerracotta),
        Block::MagentaGlazedTerracotta(_) => Some(Item::MagentaGlazedTerracotta),
        Block::LightBlueGlazedTerracotta(_) => Some(Item::LightBlueGlazedTerracotta),
        Block::YellowGlazedTerracotta(_) => Some(Item::YellowGlazedTerracotta),
        Block::LimeGlazedTerracotta(_) => Some(Item::LimeGlazedTerracotta),
        Block::PinkGlazedTerracotta(_) => Some(Item::PinkGlazedTerracotta),
        Block::GrayGlazedTerracotta(_) => Some(Item::GrayGlazedTerracotta),
        Block::LightGrayGlazedTerracotta(_) => Some(Item::LightGrayGlazedTerracotta),
        Block::CyanGlazedTerracotta(_) => Some(Item::CyanGlazedTerracotta),
        Block::PurpleGlazedTerracotta(_) => Some(Item::PurpleGlazedTerracotta),
        Block::BlueGlazedTerracotta(_) => Some(Item::BlueGlazedTerracotta),
        Block::BrownGlazedTerracotta(_) => Some(Item::BrownGlazedTerracotta),
        Block::GreenGlazedTerracotta(_) => Some(Item::GreenGlazedTerracotta),
        Block::RedGlazedTerracotta(_) => Some(Item::RedGlazedTerracotta),
        Block::BlackGlazedTerracotta(_) => Some(Item::BlackGlazedTerracotta),
        Block::WhiteConcrete => Some(Item::WhiteConcrete),
        Block::OrangeConcrete => Some(Item::OrangeConcrete),
        Block::MagentaConcrete => Some(Item::MagentaConcrete),
        Block::LightBlueConcrete => Some(Item::LightBlueConcrete),
        Block::YellowConcrete => Some(Item::YellowConcrete),
        Block::LimeConcrete => Some(Item::LimeConcrete),
        Block::PinkConcrete => Some(Item::PinkConcrete),
        Block::GrayConcrete => Some(Item::GrayConcrete),
        Block::LightGrayConcrete => Some(Item::LightGrayConcrete),
        Block::CyanConcrete => Some(Item::CyanConcrete),
        Block::PurpleConcrete => Some(Item::PurpleConcrete),
        Block::BlueConcrete => Some(Item::BlueConcrete),
        Block::BrownConcrete => Some(Item::BrownConcrete),
        Block::GreenConcrete => Some(Item::GreenConcrete),
        Block::RedConcrete => Some(Item::RedConcrete),
        Block::BlackConcrete => Some(Item::BlackConcrete),
        Block::WhiteConcretePowder => Some(Item::WhiteConcretePowder),
        Block::OrangeConcretePowder => Some(Item::OrangeConcretePowder),
        Block::MagentaConcretePowder => Some(Item::MagentaConcretePowder),
        Block::LightBlueConcretePowder => Some(Item::LightBlueConcretePowder),
        Block::YellowConcretePowder => Some(Item::YellowConcretePowder),
        Block::LimeConcretePowder => Some(Item::LimeConcretePowder),
        Block::PinkConcretePowder => Some(Item::PinkConcretePowder),
        Block::GrayConcretePowder => Some(Item::GrayConcretePowder),
        Block::LightGrayConcretePowder => Some(Item::LightGrayConcretePowder),
        Block::CyanConcretePowder => Some(Item::CyanConcretePowder),
        Block::PurpleConcretePowder => Some(Item::PurpleConcretePowder),
        Block::BlueConcretePowder => Some(Item::BlueConcretePowder),
        Block::BrownConcretePowder => Some(Item::BrownConcretePowder),
        Block::GreenConcretePowder => Some(Item::GreenConcretePowder),
        Block::RedConcretePowder => Some(Item::RedConcretePowder),
        Block::BlackConcretePowder => Some(Item::BlackConcretePowder),
        Block::TurtleEgg(_) => Some(Item::TurtleEgg),
        Block::DeadTubeCoralBlock => Some(Item::DeadTubeCoralBlock),
        Block::DeadBrainCoralBlock => Some(Item::DeadBrainCoralBlock),
        Block::DeadBubbleCoralBlock => Some(Item::DeadBubbleCoralBlock),
        Block::DeadFireCoralBlock => Some(Item::DeadFireCoralBlock),
        Block::DeadHornCoralBlock => Some(Item::DeadHornCoralBlock),
        Block::TubeCoralBlock => Some(Item::TubeCoralBlock),
        Block::BrainCoralBlock => Some(Item::BrainCoralBlock),
        Block::BubbleCoralBlock => Some(Item::BubbleCoralBlock),
        Block::FireCoralBlock => Some(Item::FireCoralBlock),
        Block::HornCoralBlock => Some(Item::HornCoralBlock),
        Block::TubeCoral(_) => Some(Item::TubeCoral),
        Block::BrainCoral(_) => Some(Item::BrainCoral),
        Block::BubbleCoral(_) => Some(Item::BubbleCoral),
        Block::FireCoral(_) => Some(Item::FireCoral),
        Block::HornCoral(_) => Some(Item::HornCoral),
        Block::DeadBrainCoral(_) => Some(Item::DeadBrainCoral),
        Block::DeadBubbleCoral(_) => Some(Item::DeadBubbleCoral),
        Block::DeadFireCoral(_) => Some(Item::DeadFireCoral),
        Block::DeadHornCoral(_) => Some(Item::DeadHornCoral),
        Block::DeadTubeCoral(_) => Some(Item::DeadTubeCoral),
        Block::TubeCoralFan(_) => Some(Item::TubeCoralFan),
        Block::BrainCoralFan(_) => Some(Item::BrainCoralFan),
        Block::BubbleCoralFan(_) => Some(Item::BubbleCoralFan),
        Block::FireCoralFan(_) => Some(Item::FireCoralFan),
        Block::HornCoralFan(_) => Some(Item::HornCoralFan),
        Block::DeadTubeCoralFan(_) => Some(Item::DeadTubeCoralFan),
        Block::DeadBrainCoralFan(_) => Some(Item::DeadBrainCoralFan),
        Block::DeadBubbleCoralFan(_) => Some(Item::DeadBubbleCoralFan),
        Block::DeadFireCoralFan(_) => Some(Item::DeadFireCoralFan),
        Block::DeadHornCoralFan(_) => Some(Item::DeadHornCoralFan),
        Block::BlueIce => Some(Item::BlueIce),
        Block::Conduit(_) => Some(Item::Conduit),
        Block::IronDoor(_) => Some(Item::IronDoor),
        Block::OakDoor(_) => Some(Item::OakDoor),
        Block::SpruceDoor(_) => Some(Item::SpruceDoor),
        Block::BirchDoor(_) => Some(Item::BirchDoor),
        Block::JungleDoor(_) => Some(Item::JungleDoor),
        Block::AcaciaDoor(_) => Some(Item::AcaciaDoor),
        Block::DarkOakDoor(_) => Some(Item::DarkOakDoor),
        Block::Repeater(_) => Some(Item::Repeater),
        Block::Comparator(_) => Some(Item::Comparator),
        Block::StructureBlock(_) => Some(Item::StructureBlock),
        Block::Wheat(_) => Some(Item::Wheat),
        Block::Sign(_) => Some(Item::Sign),
        Block::SugarCane(_) => Some(Item::SugarCane),
        Block::Kelp(_) => Some(Item::Kelp),
        Block::DriedKelpBlock => Some(Item::DriedKelpBlock),
        Block::Cake(_) => Some(Item::Cake),
        Block::WhiteBed(_) => Some(Item::WhiteBed),
        Block::OrangeBed(_) => Some(Item::OrangeBed),
        Block::MagentaBed(_) => Some(Item::MagentaBed),
        Block::LightBlueBed(_) => Some(Item::LightBlueBed),
        Block::YellowBed(_) => Some(Item::YellowBed),
        Block::LimeBed(_) => Some(Item::LimeBed),
        Block::PinkBed(_) => Some(Item::PinkBed),
        Block::GrayBed(_) => Some(Item::GrayBed),
        Block::LightGrayBed(_) => Some(Item::LightGrayBed),
        Block::CyanBed(_) => Some(Item::CyanBed),
        Block::PurpleBed(_) => Some(Item::PurpleBed),
        Block::BlueBed(_) => Some(Item::BlueBed),
        Block::BrownBed(_) => Some(Item::BrownBed),
        Block::GreenBed(_) => Some(Item::GreenBed),
        Block::RedBed(_) => Some(Item::RedBed),
        Block::BlackBed(_) => Some(Item::BlackBed),
        Block::NetherWart(_) => Some(Item::NetherWart),
        Block::BrewingStand(_) => Some(Item::BrewingStand),
        Block::Cauldron(_) => Some(Item::Cauldron),
        Block::FlowerPot => Some(Item::FlowerPot),
        Block::SkeletonSkull(_) => Some(Item::SkeletonSkull),
        Block::WitherSkeletonSkull(_) => Some(Item::WitherSkeletonSkull),
        Block::PlayerHead(_) => Some(Item::PlayerHead),
        Block::ZombieHead(_) => Some(Item::ZombieHead),
        Block::CreeperHead(_) => Some(Item::CreeperHead),
        Block::DragonHead(_) => Some(Item::DragonHead),
        Block::WhiteBanner(_) => Some(Item::WhiteBanner),
        Block::OrangeBanner(_) => Some(Item::OrangeBanner),
        Block::MagentaBanner(_) => Some(Item::MagentaBanner),
        Block::LightBlueBanner(_) => Some(Item::LightBlueBanner),
        Block::YellowBanner(_) => Some(Item::YellowBanner),
        Block::LimeBanner(_) => Some(Item::LimeBanner),
        Block::PinkBanner(_) => Some(Item::PinkBanner),
        Block::GrayBanner(_) => Some(Item::GrayBanner),
        Block::LightGrayBanner(_) => Some(Item::LightGrayBanner),
        Block::CyanBanner(_) => Some(Item::CyanBanner),
        Block::PurpleBanner(_) => Some(Item::PurpleBanner),
        Block::BlueBanner(_) => Some(Item::BlueBanner),
        Block::BrownBanner(_) => Some(Item::BrownBanner),
        Block::GreenBanner(_) => Some(Item::GreenBanner),
        Block::RedBanner(_) => Some(Item::RedBanner),
        Block::BlackBanner(_) => Some(Item::BlackBanner),
        _ => None,
    }
}
