use libcraft_blocks::BlockKind;
use libcraft_items::Item;
use ordinalizer::Ordinal;

/// This is an enum over the kinds of particles
/// listed on [the Particle data type](https://wiki.vg/index.php?title=Protocol&diff=14889&oldid=14881#Particle).
#[derive(Copy, Clone, Debug, PartialEq, Ordinal)]
pub enum Particle {
    AmbientEntityEffect,
    AngryVillager,
    Barrier,
    /// Block break particles
    Block(BlockKind),
    Bubble,
    Cloud,
    Crit,
    DamageIndicator,
    DragonBreath,
    DrippingLava,
    FallingLava,
    LandingLava,
    DrippingWater,
    FallingWater,
    Dust {
        red: f32,
        green: f32,
        blue: f32,
        /// Will be clamped between 0.01 and 4.0.
        scale: f32,
    },
    Effect,
    ElderGuardian,
    EnchantedHit,
    Enchant,
    EndRod,
    EntityEffect,
    ExplosionEmitter,
    Explosion,
    FallingDust(BlockKind),
    Firework,
    Fishing,
    Flame,
    Flash,
    HappyVillager,
    Composter,
    Heart,
    InstantEffect,
    Item(Option<Item>),
    ItemSlime,
    ItemSnowball,
    LargeSmoke,
    Lava,
    Mycelium,
    Note,
    Poof,
    Portal,
    Rain,
    Smoke,
    Sneeze,
    Spit,
    SquidInk,
    SweepAttack,
    TotemOfUndying,
    Underwater,
    Splash,
    Witch,
    BublePop,
    CurrentDown,
    BubbleColumnUp,
    Nautilus,
    Dolphin,
    CampfireCosySmoke,
    CampfireSignalSmoke,
    DrippingHoney,
    FallingHoney,
    LandingHoney,
    FallingNectar,
}
