// This file is @generated. Please do not edit.
use crate::BlockKind;
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SimplifiedBlockKind {
    Air,
    Planks,
    Sapling,
    Log,
    Leaves,
    Bed,
    Wool,
    Flower,
    WoodenPressurePlate,
    StainedGlass,
    WoodenTrapdoor,
    WoodenButton,
    Anvil,
    GlazedTeracotta,
    Teracotta,
    StainedGlassPane,
    Carpet,
    WallBanner,
    Banner,
    Slab,
    Stairs,
    FenceGate,
    Fence,
    WoodenDoor,
    ShulkerBox,
    Concrete,
    ConcretePowder,
    Coral,
    CoralBlock,
    CoralFan,
    CoralWallFan,
    Mushroom,
    WallSign,
    Sign,
    Stone,
    Granite,
    PolishedGranite,
    Diorite,
    PolishedDiorite,
    Andesite,
    PolishedAndesite,
    GrassBlock,
    Dirt,
    CoarseDirt,
    Podzol,
    Cobblestone,
    Bedrock,
    Water,
    Lava,
    Sand,
    RedSand,
    Gravel,
    GoldOre,
    IronOre,
    CoalOre,
    NetherGoldOre,
    Sponge,
    WetSponge,
    Glass,
    LapisOre,
    LapisBlock,
    Dispenser,
    Sandstone,
    ChiseledSandstone,
    CutSandstone,
    NoteBlock,
    PoweredRail,
    DetectorRail,
    StickyPiston,
    Cobweb,
    Grass,
    Fern,
    DeadBush,
    Seagrass,
    TallSeagrass,
    Piston,
    PistonHead,
    MovingPiston,
    Cornflower,
    WitherRose,
    LilyOfTheValley,
    GoldBlock,
    IronBlock,
    Bricks,
    Tnt,
    Bookshelf,
    MossyCobblestone,
    Obsidian,
    Torch,
    WallTorch,
    Fire,
    SoulFire,
    Spawner,
    Chest,
    RedstoneWire,
    DiamondOre,
    DiamondBlock,
    CraftingTable,
    Wheat,
    Farmland,
    Furnace,
    Ladder,
    Rail,
    Lever,
    StonePressurePlate,
    IronDoor,
    RedstoneOre,
    RedstoneTorch,
    RedstoneWallTorch,
    StoneButton,
    Snow,
    Ice,
    SnowBlock,
    Cactus,
    Clay,
    SugarCane,
    Jukebox,
    Pumpkin,
    Netherrack,
    SoulSand,
    SoulSoil,
    Basalt,
    PolishedBasalt,
    SoulTorch,
    SoulWallTorch,
    Glowstone,
    NetherPortal,
    CarvedPumpkin,
    JackOLantern,
    Cake,
    Repeater,
    StoneBricks,
    MossyStoneBricks,
    CrackedStoneBricks,
    ChiseledStoneBricks,
    InfestedStone,
    InfestedCobblestone,
    InfestedStoneBricks,
    InfestedMossyStoneBricks,
    InfestedCrackedStoneBricks,
    InfestedChiseledStoneBricks,
    BrownMushroomBlock,
    RedMushroomBlock,
    MushroomStem,
    IronBars,
    Chain,
    GlassPane,
    Melon,
    AttachedPumpkinStem,
    AttachedMelonStem,
    PumpkinStem,
    MelonStem,
    Vine,
    Mycelium,
    LilyPad,
    NetherBricks,
    NetherWart,
    EnchantingTable,
    BrewingStand,
    Cauldron,
    EndPortal,
    EndPortalFrame,
    EndStone,
    DragonEgg,
    RedstoneLamp,
    Cocoa,
    EmeraldOre,
    EnderChest,
    TripwireHook,
    Tripwire,
    EmeraldBlock,
    CommandBlock,
    Beacon,
    CobblestoneWall,
    MossyCobblestoneWall,
    FlowerPot,
    PottedFern,
    PottedDandelion,
    PottedPoppy,
    PottedAllium,
    PottedCornflower,
    PottedLilyOfTheValley,
    PottedWitherRose,
    PottedDeadBush,
    PottedCactus,
    Carrots,
    Potatoes,
    SkeletonSkull,
    SkeletonWallSkull,
    WitherSkeletonSkull,
    WitherSkeletonWallSkull,
    ZombieHead,
    ZombieWallHead,
    PlayerHead,
    PlayerWallHead,
    CreeperHead,
    CreeperWallHead,
    DragonHead,
    DragonWallHead,
    TrappedChest,
    LightWeightedPressurePlate,
    HeavyWeightedPressurePlate,
    Comparator,
    DaylightDetector,
    RedstoneBlock,
    NetherQuartzOre,
    Hopper,
    QuartzBlock,
    ChiseledQuartzBlock,
    QuartzPillar,
    ActivatorRail,
    Dropper,
    SlimeBlock,
    Barrier,
    IronTrapdoor,
    Prismarine,
    PrismarineBricks,
    DarkPrismarine,
    SeaLantern,
    HayBlock,
    CoalBlock,
    PackedIce,
    Sunflower,
    Lilac,
    RoseBush,
    Peony,
    TallGrass,
    LargeFern,
    RedSandstone,
    ChiseledRedSandstone,
    CutRedSandstone,
    SmoothStone,
    SmoothSandstone,
    SmoothQuartz,
    SmoothRedSandstone,
    EndRod,
    ChorusPlant,
    ChorusFlower,
    PurpurBlock,
    PurpurPillar,
    EndStoneBricks,
    Beetroots,
    GrassPath,
    EndGateway,
    RepeatingCommandBlock,
    ChainCommandBlock,
    FrostedIce,
    MagmaBlock,
    NetherWartBlock,
    RedNetherBricks,
    BoneBlock,
    StructureVoid,
    Observer,
    Kelp,
    KelpPlant,
    DriedKelpBlock,
    TurtleEgg,
    SeaPickle,
    BlueIce,
    Conduit,
    Bamboo,
    PottedBamboo,
    BubbleColumn,
    BrickWall,
    PrismarineWall,
    RedSandstoneWall,
    MossyStoneBrickWall,
    GraniteWall,
    StoneBrickWall,
    NetherBrickWall,
    AndesiteWall,
    RedNetherBrickWall,
    SandstoneWall,
    EndStoneBrickWall,
    DioriteWall,
    Scaffolding,
    Loom,
    Barrel,
    Smoker,
    BlastFurnace,
    CartographyTable,
    FletchingTable,
    Grindstone,
    Lectern,
    SmithingTable,
    Stonecutter,
    Bell,
    Lantern,
    SoulLantern,
    Campfire,
    SoulCampfire,
    SweetBerryBush,
    WarpedStem,
    StrippedWarpedStem,
    WarpedHyphae,
    StrippedWarpedHyphae,
    WarpedNylium,
    WarpedFungus,
    WarpedWartBlock,
    WarpedRoots,
    NetherSprouts,
    CrimsonStem,
    StrippedCrimsonStem,
    CrimsonHyphae,
    StrippedCrimsonHyphae,
    CrimsonNylium,
    CrimsonFungus,
    Shroomlight,
    WeepingVines,
    WeepingVinesPlant,
    TwistingVines,
    TwistingVinesPlant,
    CrimsonRoots,
    CrimsonPressurePlate,
    WarpedPressurePlate,
    CrimsonTrapdoor,
    WarpedTrapdoor,
    CrimsonButton,
    WarpedButton,
    CrimsonDoor,
    WarpedDoor,
    StructureBlock,
    Jigsaw,
    Composter,
    Target,
    BeeNest,
    Beehive,
    HoneyBlock,
    HoneycombBlock,
    NetheriteBlock,
    AncientDebris,
    CryingObsidian,
    RespawnAnchor,
    PottedCrimsonFungus,
    PottedWarpedFungus,
    PottedCrimsonRoots,
    PottedWarpedRoots,
    Lodestone,
    Blackstone,
    BlackstoneWall,
    PolishedBlackstone,
    PolishedBlackstoneBricks,
    CrackedPolishedBlackstoneBricks,
    ChiseledPolishedBlackstone,
    PolishedBlackstoneBrickWall,
    GildedBlackstone,
    PolishedBlackstonePressurePlate,
    PolishedBlackstoneButton,
    PolishedBlackstoneWall,
    ChiseledNetherBricks,
    CrackedNetherBricks,
    QuartzBricks,
}

#[allow(warnings)]
#[allow(clippy::all)]
impl BlockKind {
    /// Returns the `simplified_kind` property of this `BlockKind`.
    pub fn simplified_kind(&self) -> SimplifiedBlockKind {
        match self {
            BlockKind::Air => SimplifiedBlockKind::Air,
            BlockKind::Stone => SimplifiedBlockKind::Stone,
            BlockKind::Granite => SimplifiedBlockKind::Granite,
            BlockKind::PolishedGranite => SimplifiedBlockKind::PolishedGranite,
            BlockKind::Diorite => SimplifiedBlockKind::Diorite,
            BlockKind::PolishedDiorite => SimplifiedBlockKind::PolishedDiorite,
            BlockKind::Andesite => SimplifiedBlockKind::Andesite,
            BlockKind::PolishedAndesite => SimplifiedBlockKind::PolishedAndesite,
            BlockKind::GrassBlock => SimplifiedBlockKind::GrassBlock,
            BlockKind::Dirt => SimplifiedBlockKind::Dirt,
            BlockKind::CoarseDirt => SimplifiedBlockKind::CoarseDirt,
            BlockKind::Podzol => SimplifiedBlockKind::Podzol,
            BlockKind::Cobblestone => SimplifiedBlockKind::Cobblestone,
            BlockKind::OakPlanks => SimplifiedBlockKind::Planks,
            BlockKind::SprucePlanks => SimplifiedBlockKind::Planks,
            BlockKind::BirchPlanks => SimplifiedBlockKind::Planks,
            BlockKind::JunglePlanks => SimplifiedBlockKind::Planks,
            BlockKind::AcaciaPlanks => SimplifiedBlockKind::Planks,
            BlockKind::DarkOakPlanks => SimplifiedBlockKind::Planks,
            BlockKind::OakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::SpruceSapling => SimplifiedBlockKind::Sapling,
            BlockKind::BirchSapling => SimplifiedBlockKind::Sapling,
            BlockKind::JungleSapling => SimplifiedBlockKind::Sapling,
            BlockKind::AcaciaSapling => SimplifiedBlockKind::Sapling,
            BlockKind::DarkOakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::Bedrock => SimplifiedBlockKind::Bedrock,
            BlockKind::Water => SimplifiedBlockKind::Water,
            BlockKind::Lava => SimplifiedBlockKind::Lava,
            BlockKind::Sand => SimplifiedBlockKind::Sand,
            BlockKind::RedSand => SimplifiedBlockKind::RedSand,
            BlockKind::Gravel => SimplifiedBlockKind::Gravel,
            BlockKind::GoldOre => SimplifiedBlockKind::GoldOre,
            BlockKind::IronOre => SimplifiedBlockKind::IronOre,
            BlockKind::CoalOre => SimplifiedBlockKind::CoalOre,
            BlockKind::NetherGoldOre => SimplifiedBlockKind::NetherGoldOre,
            BlockKind::OakLog => SimplifiedBlockKind::Log,
            BlockKind::SpruceLog => SimplifiedBlockKind::Log,
            BlockKind::BirchLog => SimplifiedBlockKind::Log,
            BlockKind::JungleLog => SimplifiedBlockKind::Log,
            BlockKind::AcaciaLog => SimplifiedBlockKind::Log,
            BlockKind::DarkOakLog => SimplifiedBlockKind::Log,
            BlockKind::StrippedSpruceLog => SimplifiedBlockKind::Log,
            BlockKind::StrippedBirchLog => SimplifiedBlockKind::Log,
            BlockKind::StrippedJungleLog => SimplifiedBlockKind::Log,
            BlockKind::StrippedAcaciaLog => SimplifiedBlockKind::Log,
            BlockKind::StrippedDarkOakLog => SimplifiedBlockKind::Log,
            BlockKind::StrippedOakLog => SimplifiedBlockKind::Log,
            BlockKind::OakWood => SimplifiedBlockKind::Log,
            BlockKind::SpruceWood => SimplifiedBlockKind::Log,
            BlockKind::BirchWood => SimplifiedBlockKind::Log,
            BlockKind::JungleWood => SimplifiedBlockKind::Log,
            BlockKind::AcaciaWood => SimplifiedBlockKind::Log,
            BlockKind::DarkOakWood => SimplifiedBlockKind::Log,
            BlockKind::StrippedOakWood => SimplifiedBlockKind::Log,
            BlockKind::StrippedSpruceWood => SimplifiedBlockKind::Log,
            BlockKind::StrippedBirchWood => SimplifiedBlockKind::Log,
            BlockKind::StrippedJungleWood => SimplifiedBlockKind::Log,
            BlockKind::StrippedAcaciaWood => SimplifiedBlockKind::Log,
            BlockKind::StrippedDarkOakWood => SimplifiedBlockKind::Log,
            BlockKind::OakLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::SpruceLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::BirchLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::JungleLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::AcaciaLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::DarkOakLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::Sponge => SimplifiedBlockKind::Sponge,
            BlockKind::WetSponge => SimplifiedBlockKind::WetSponge,
            BlockKind::Glass => SimplifiedBlockKind::Glass,
            BlockKind::LapisOre => SimplifiedBlockKind::LapisOre,
            BlockKind::LapisBlock => SimplifiedBlockKind::LapisBlock,
            BlockKind::Dispenser => SimplifiedBlockKind::Dispenser,
            BlockKind::Sandstone => SimplifiedBlockKind::Sandstone,
            BlockKind::ChiseledSandstone => SimplifiedBlockKind::ChiseledSandstone,
            BlockKind::CutSandstone => SimplifiedBlockKind::CutSandstone,
            BlockKind::NoteBlock => SimplifiedBlockKind::NoteBlock,
            BlockKind::WhiteBed => SimplifiedBlockKind::Bed,
            BlockKind::OrangeBed => SimplifiedBlockKind::Bed,
            BlockKind::MagentaBed => SimplifiedBlockKind::Bed,
            BlockKind::LightBlueBed => SimplifiedBlockKind::Bed,
            BlockKind::YellowBed => SimplifiedBlockKind::Bed,
            BlockKind::LimeBed => SimplifiedBlockKind::Bed,
            BlockKind::PinkBed => SimplifiedBlockKind::Bed,
            BlockKind::GrayBed => SimplifiedBlockKind::Bed,
            BlockKind::LightGrayBed => SimplifiedBlockKind::Bed,
            BlockKind::CyanBed => SimplifiedBlockKind::Bed,
            BlockKind::PurpleBed => SimplifiedBlockKind::Bed,
            BlockKind::BlueBed => SimplifiedBlockKind::Bed,
            BlockKind::BrownBed => SimplifiedBlockKind::Bed,
            BlockKind::GreenBed => SimplifiedBlockKind::Bed,
            BlockKind::RedBed => SimplifiedBlockKind::Bed,
            BlockKind::BlackBed => SimplifiedBlockKind::Bed,
            BlockKind::PoweredRail => SimplifiedBlockKind::PoweredRail,
            BlockKind::DetectorRail => SimplifiedBlockKind::DetectorRail,
            BlockKind::StickyPiston => SimplifiedBlockKind::StickyPiston,
            BlockKind::Cobweb => SimplifiedBlockKind::Cobweb,
            BlockKind::Grass => SimplifiedBlockKind::Grass,
            BlockKind::Fern => SimplifiedBlockKind::Fern,
            BlockKind::DeadBush => SimplifiedBlockKind::DeadBush,
            BlockKind::Seagrass => SimplifiedBlockKind::Seagrass,
            BlockKind::TallSeagrass => SimplifiedBlockKind::TallSeagrass,
            BlockKind::Piston => SimplifiedBlockKind::Piston,
            BlockKind::PistonHead => SimplifiedBlockKind::PistonHead,
            BlockKind::WhiteWool => SimplifiedBlockKind::Wool,
            BlockKind::OrangeWool => SimplifiedBlockKind::Wool,
            BlockKind::MagentaWool => SimplifiedBlockKind::Wool,
            BlockKind::LightBlueWool => SimplifiedBlockKind::Wool,
            BlockKind::YellowWool => SimplifiedBlockKind::Wool,
            BlockKind::LimeWool => SimplifiedBlockKind::Wool,
            BlockKind::PinkWool => SimplifiedBlockKind::Wool,
            BlockKind::GrayWool => SimplifiedBlockKind::Wool,
            BlockKind::LightGrayWool => SimplifiedBlockKind::Wool,
            BlockKind::CyanWool => SimplifiedBlockKind::Wool,
            BlockKind::PurpleWool => SimplifiedBlockKind::Wool,
            BlockKind::BlueWool => SimplifiedBlockKind::Wool,
            BlockKind::BrownWool => SimplifiedBlockKind::Wool,
            BlockKind::GreenWool => SimplifiedBlockKind::Wool,
            BlockKind::RedWool => SimplifiedBlockKind::Wool,
            BlockKind::BlackWool => SimplifiedBlockKind::Wool,
            BlockKind::MovingPiston => SimplifiedBlockKind::MovingPiston,
            BlockKind::Dandelion => SimplifiedBlockKind::Flower,
            BlockKind::Poppy => SimplifiedBlockKind::Flower,
            BlockKind::BlueOrchid => SimplifiedBlockKind::Flower,
            BlockKind::Allium => SimplifiedBlockKind::Flower,
            BlockKind::AzureBluet => SimplifiedBlockKind::Flower,
            BlockKind::RedTulip => SimplifiedBlockKind::Flower,
            BlockKind::OrangeTulip => SimplifiedBlockKind::Flower,
            BlockKind::WhiteTulip => SimplifiedBlockKind::Flower,
            BlockKind::PinkTulip => SimplifiedBlockKind::Flower,
            BlockKind::OxeyeDaisy => SimplifiedBlockKind::Flower,
            BlockKind::Cornflower => SimplifiedBlockKind::Cornflower,
            BlockKind::WitherRose => SimplifiedBlockKind::WitherRose,
            BlockKind::LilyOfTheValley => SimplifiedBlockKind::LilyOfTheValley,
            BlockKind::BrownMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::RedMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::GoldBlock => SimplifiedBlockKind::GoldBlock,
            BlockKind::IronBlock => SimplifiedBlockKind::IronBlock,
            BlockKind::Bricks => SimplifiedBlockKind::Bricks,
            BlockKind::Tnt => SimplifiedBlockKind::Tnt,
            BlockKind::Bookshelf => SimplifiedBlockKind::Bookshelf,
            BlockKind::MossyCobblestone => SimplifiedBlockKind::MossyCobblestone,
            BlockKind::Obsidian => SimplifiedBlockKind::Obsidian,
            BlockKind::Torch => SimplifiedBlockKind::Torch,
            BlockKind::WallTorch => SimplifiedBlockKind::WallTorch,
            BlockKind::Fire => SimplifiedBlockKind::Fire,
            BlockKind::SoulFire => SimplifiedBlockKind::SoulFire,
            BlockKind::Spawner => SimplifiedBlockKind::Spawner,
            BlockKind::OakStairs => SimplifiedBlockKind::Stairs,
            BlockKind::Chest => SimplifiedBlockKind::Chest,
            BlockKind::RedstoneWire => SimplifiedBlockKind::RedstoneWire,
            BlockKind::DiamondOre => SimplifiedBlockKind::DiamondOre,
            BlockKind::DiamondBlock => SimplifiedBlockKind::DiamondBlock,
            BlockKind::CraftingTable => SimplifiedBlockKind::CraftingTable,
            BlockKind::Wheat => SimplifiedBlockKind::Wheat,
            BlockKind::Farmland => SimplifiedBlockKind::Farmland,
            BlockKind::Furnace => SimplifiedBlockKind::Furnace,
            BlockKind::OakSign => SimplifiedBlockKind::Sign,
            BlockKind::SpruceSign => SimplifiedBlockKind::Sign,
            BlockKind::BirchSign => SimplifiedBlockKind::Sign,
            BlockKind::AcaciaSign => SimplifiedBlockKind::Sign,
            BlockKind::JungleSign => SimplifiedBlockKind::Sign,
            BlockKind::DarkOakSign => SimplifiedBlockKind::Sign,
            BlockKind::OakDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::Ladder => SimplifiedBlockKind::Ladder,
            BlockKind::Rail => SimplifiedBlockKind::Rail,
            BlockKind::CobblestoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::OakWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::SpruceWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::BirchWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::AcaciaWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::JungleWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::DarkOakWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::Lever => SimplifiedBlockKind::Lever,
            BlockKind::StonePressurePlate => SimplifiedBlockKind::StonePressurePlate,
            BlockKind::IronDoor => SimplifiedBlockKind::IronDoor,
            BlockKind::OakPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::SprucePressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::BirchPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::JunglePressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::AcaciaPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::DarkOakPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::RedstoneOre => SimplifiedBlockKind::RedstoneOre,
            BlockKind::RedstoneTorch => SimplifiedBlockKind::RedstoneTorch,
            BlockKind::RedstoneWallTorch => SimplifiedBlockKind::RedstoneWallTorch,
            BlockKind::StoneButton => SimplifiedBlockKind::StoneButton,
            BlockKind::Snow => SimplifiedBlockKind::Snow,
            BlockKind::Ice => SimplifiedBlockKind::Ice,
            BlockKind::SnowBlock => SimplifiedBlockKind::SnowBlock,
            BlockKind::Cactus => SimplifiedBlockKind::Cactus,
            BlockKind::Clay => SimplifiedBlockKind::Clay,
            BlockKind::SugarCane => SimplifiedBlockKind::SugarCane,
            BlockKind::Jukebox => SimplifiedBlockKind::Jukebox,
            BlockKind::OakFence => SimplifiedBlockKind::Fence,
            BlockKind::Pumpkin => SimplifiedBlockKind::Pumpkin,
            BlockKind::Netherrack => SimplifiedBlockKind::Netherrack,
            BlockKind::SoulSand => SimplifiedBlockKind::SoulSand,
            BlockKind::SoulSoil => SimplifiedBlockKind::SoulSoil,
            BlockKind::Basalt => SimplifiedBlockKind::Basalt,
            BlockKind::PolishedBasalt => SimplifiedBlockKind::PolishedBasalt,
            BlockKind::SoulTorch => SimplifiedBlockKind::SoulTorch,
            BlockKind::SoulWallTorch => SimplifiedBlockKind::SoulWallTorch,
            BlockKind::Glowstone => SimplifiedBlockKind::Glowstone,
            BlockKind::NetherPortal => SimplifiedBlockKind::NetherPortal,
            BlockKind::CarvedPumpkin => SimplifiedBlockKind::CarvedPumpkin,
            BlockKind::JackOLantern => SimplifiedBlockKind::JackOLantern,
            BlockKind::Cake => SimplifiedBlockKind::Cake,
            BlockKind::Repeater => SimplifiedBlockKind::Repeater,
            BlockKind::WhiteStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::OrangeStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::MagentaStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::LightBlueStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::YellowStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::LimeStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::PinkStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::GrayStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::LightGrayStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::CyanStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::PurpleStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::BlueStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::BrownStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::GreenStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::RedStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::BlackStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::OakTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::SpruceTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::BirchTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::JungleTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::AcaciaTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::DarkOakTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::StoneBricks => SimplifiedBlockKind::StoneBricks,
            BlockKind::MossyStoneBricks => SimplifiedBlockKind::MossyStoneBricks,
            BlockKind::CrackedStoneBricks => SimplifiedBlockKind::CrackedStoneBricks,
            BlockKind::ChiseledStoneBricks => SimplifiedBlockKind::ChiseledStoneBricks,
            BlockKind::InfestedStone => SimplifiedBlockKind::InfestedStone,
            BlockKind::InfestedCobblestone => SimplifiedBlockKind::InfestedCobblestone,
            BlockKind::InfestedStoneBricks => SimplifiedBlockKind::InfestedStoneBricks,
            BlockKind::InfestedMossyStoneBricks => SimplifiedBlockKind::InfestedMossyStoneBricks,
            BlockKind::InfestedCrackedStoneBricks => {
                SimplifiedBlockKind::InfestedCrackedStoneBricks
            }
            BlockKind::InfestedChiseledStoneBricks => {
                SimplifiedBlockKind::InfestedChiseledStoneBricks
            }
            BlockKind::BrownMushroomBlock => SimplifiedBlockKind::BrownMushroomBlock,
            BlockKind::RedMushroomBlock => SimplifiedBlockKind::RedMushroomBlock,
            BlockKind::MushroomStem => SimplifiedBlockKind::MushroomStem,
            BlockKind::IronBars => SimplifiedBlockKind::IronBars,
            BlockKind::Chain => SimplifiedBlockKind::Chain,
            BlockKind::GlassPane => SimplifiedBlockKind::GlassPane,
            BlockKind::Melon => SimplifiedBlockKind::Melon,
            BlockKind::AttachedPumpkinStem => SimplifiedBlockKind::AttachedPumpkinStem,
            BlockKind::AttachedMelonStem => SimplifiedBlockKind::AttachedMelonStem,
            BlockKind::PumpkinStem => SimplifiedBlockKind::PumpkinStem,
            BlockKind::MelonStem => SimplifiedBlockKind::MelonStem,
            BlockKind::Vine => SimplifiedBlockKind::Vine,
            BlockKind::OakFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::BrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::StoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::Mycelium => SimplifiedBlockKind::Mycelium,
            BlockKind::LilyPad => SimplifiedBlockKind::LilyPad,
            BlockKind::NetherBricks => SimplifiedBlockKind::NetherBricks,
            BlockKind::NetherBrickFence => SimplifiedBlockKind::Fence,
            BlockKind::NetherBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::NetherWart => SimplifiedBlockKind::NetherWart,
            BlockKind::EnchantingTable => SimplifiedBlockKind::EnchantingTable,
            BlockKind::BrewingStand => SimplifiedBlockKind::BrewingStand,
            BlockKind::Cauldron => SimplifiedBlockKind::Cauldron,
            BlockKind::EndPortal => SimplifiedBlockKind::EndPortal,
            BlockKind::EndPortalFrame => SimplifiedBlockKind::EndPortalFrame,
            BlockKind::EndStone => SimplifiedBlockKind::EndStone,
            BlockKind::DragonEgg => SimplifiedBlockKind::DragonEgg,
            BlockKind::RedstoneLamp => SimplifiedBlockKind::RedstoneLamp,
            BlockKind::Cocoa => SimplifiedBlockKind::Cocoa,
            BlockKind::SandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::EmeraldOre => SimplifiedBlockKind::EmeraldOre,
            BlockKind::EnderChest => SimplifiedBlockKind::EnderChest,
            BlockKind::TripwireHook => SimplifiedBlockKind::TripwireHook,
            BlockKind::Tripwire => SimplifiedBlockKind::Tripwire,
            BlockKind::EmeraldBlock => SimplifiedBlockKind::EmeraldBlock,
            BlockKind::SpruceStairs => SimplifiedBlockKind::Stairs,
            BlockKind::BirchStairs => SimplifiedBlockKind::Stairs,
            BlockKind::JungleStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CommandBlock => SimplifiedBlockKind::CommandBlock,
            BlockKind::Beacon => SimplifiedBlockKind::Beacon,
            BlockKind::CobblestoneWall => SimplifiedBlockKind::CobblestoneWall,
            BlockKind::MossyCobblestoneWall => SimplifiedBlockKind::MossyCobblestoneWall,
            BlockKind::FlowerPot => SimplifiedBlockKind::FlowerPot,
            BlockKind::PottedOakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::PottedSpruceSapling => SimplifiedBlockKind::Sapling,
            BlockKind::PottedBirchSapling => SimplifiedBlockKind::Sapling,
            BlockKind::PottedJungleSapling => SimplifiedBlockKind::Sapling,
            BlockKind::PottedAcaciaSapling => SimplifiedBlockKind::Sapling,
            BlockKind::PottedDarkOakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::PottedFern => SimplifiedBlockKind::PottedFern,
            BlockKind::PottedDandelion => SimplifiedBlockKind::PottedDandelion,
            BlockKind::PottedPoppy => SimplifiedBlockKind::PottedPoppy,
            BlockKind::PottedBlueOrchid => SimplifiedBlockKind::Flower,
            BlockKind::PottedAllium => SimplifiedBlockKind::PottedAllium,
            BlockKind::PottedAzureBluet => SimplifiedBlockKind::Flower,
            BlockKind::PottedRedTulip => SimplifiedBlockKind::Flower,
            BlockKind::PottedOrangeTulip => SimplifiedBlockKind::Flower,
            BlockKind::PottedWhiteTulip => SimplifiedBlockKind::Flower,
            BlockKind::PottedPinkTulip => SimplifiedBlockKind::Flower,
            BlockKind::PottedOxeyeDaisy => SimplifiedBlockKind::Flower,
            BlockKind::PottedCornflower => SimplifiedBlockKind::PottedCornflower,
            BlockKind::PottedLilyOfTheValley => SimplifiedBlockKind::PottedLilyOfTheValley,
            BlockKind::PottedWitherRose => SimplifiedBlockKind::PottedWitherRose,
            BlockKind::PottedRedMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::PottedBrownMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::PottedDeadBush => SimplifiedBlockKind::PottedDeadBush,
            BlockKind::PottedCactus => SimplifiedBlockKind::PottedCactus,
            BlockKind::Carrots => SimplifiedBlockKind::Carrots,
            BlockKind::Potatoes => SimplifiedBlockKind::Potatoes,
            BlockKind::OakButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::SpruceButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::BirchButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::JungleButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::AcaciaButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::DarkOakButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::SkeletonSkull => SimplifiedBlockKind::SkeletonSkull,
            BlockKind::SkeletonWallSkull => SimplifiedBlockKind::SkeletonWallSkull,
            BlockKind::WitherSkeletonSkull => SimplifiedBlockKind::WitherSkeletonSkull,
            BlockKind::WitherSkeletonWallSkull => SimplifiedBlockKind::WitherSkeletonWallSkull,
            BlockKind::ZombieHead => SimplifiedBlockKind::ZombieHead,
            BlockKind::ZombieWallHead => SimplifiedBlockKind::ZombieWallHead,
            BlockKind::PlayerHead => SimplifiedBlockKind::PlayerHead,
            BlockKind::PlayerWallHead => SimplifiedBlockKind::PlayerWallHead,
            BlockKind::CreeperHead => SimplifiedBlockKind::CreeperHead,
            BlockKind::CreeperWallHead => SimplifiedBlockKind::CreeperWallHead,
            BlockKind::DragonHead => SimplifiedBlockKind::DragonHead,
            BlockKind::DragonWallHead => SimplifiedBlockKind::DragonWallHead,
            BlockKind::Anvil => SimplifiedBlockKind::Anvil,
            BlockKind::ChippedAnvil => SimplifiedBlockKind::Anvil,
            BlockKind::DamagedAnvil => SimplifiedBlockKind::Anvil,
            BlockKind::TrappedChest => SimplifiedBlockKind::TrappedChest,
            BlockKind::LightWeightedPressurePlate => {
                SimplifiedBlockKind::LightWeightedPressurePlate
            }
            BlockKind::HeavyWeightedPressurePlate => {
                SimplifiedBlockKind::HeavyWeightedPressurePlate
            }
            BlockKind::Comparator => SimplifiedBlockKind::Comparator,
            BlockKind::DaylightDetector => SimplifiedBlockKind::DaylightDetector,
            BlockKind::RedstoneBlock => SimplifiedBlockKind::RedstoneBlock,
            BlockKind::NetherQuartzOre => SimplifiedBlockKind::NetherQuartzOre,
            BlockKind::Hopper => SimplifiedBlockKind::Hopper,
            BlockKind::QuartzBlock => SimplifiedBlockKind::QuartzBlock,
            BlockKind::ChiseledQuartzBlock => SimplifiedBlockKind::ChiseledQuartzBlock,
            BlockKind::QuartzPillar => SimplifiedBlockKind::QuartzPillar,
            BlockKind::QuartzStairs => SimplifiedBlockKind::Stairs,
            BlockKind::ActivatorRail => SimplifiedBlockKind::ActivatorRail,
            BlockKind::Dropper => SimplifiedBlockKind::Dropper,
            BlockKind::WhiteTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::OrangeTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::MagentaTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::LightBlueTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::YellowTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::LimeTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::PinkTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::GrayTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::LightGrayTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::CyanTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::PurpleTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::BlueTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::BrownTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::GreenTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::RedTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::BlackTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::WhiteStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::OrangeStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::MagentaStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::LightBlueStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::YellowStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::LimeStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::PinkStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::GrayStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::LightGrayStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::CyanStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::PurpleStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::BlueStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::BrownStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::GreenStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::RedStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::BlackStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::AcaciaStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DarkOakStairs => SimplifiedBlockKind::Stairs,
            BlockKind::SlimeBlock => SimplifiedBlockKind::SlimeBlock,
            BlockKind::Barrier => SimplifiedBlockKind::Barrier,
            BlockKind::IronTrapdoor => SimplifiedBlockKind::IronTrapdoor,
            BlockKind::Prismarine => SimplifiedBlockKind::Prismarine,
            BlockKind::PrismarineBricks => SimplifiedBlockKind::PrismarineBricks,
            BlockKind::DarkPrismarine => SimplifiedBlockKind::DarkPrismarine,
            BlockKind::PrismarineStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PrismarineBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DarkPrismarineStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PrismarineSlab => SimplifiedBlockKind::Slab,
            BlockKind::PrismarineBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::DarkPrismarineSlab => SimplifiedBlockKind::Slab,
            BlockKind::SeaLantern => SimplifiedBlockKind::SeaLantern,
            BlockKind::HayBlock => SimplifiedBlockKind::HayBlock,
            BlockKind::WhiteCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::OrangeCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::MagentaCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::LightBlueCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::YellowCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::LimeCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::PinkCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::GrayCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::LightGrayCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::CyanCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::PurpleCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::BlueCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::BrownCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::GreenCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::RedCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::BlackCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::Terracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::CoalBlock => SimplifiedBlockKind::CoalBlock,
            BlockKind::PackedIce => SimplifiedBlockKind::PackedIce,
            BlockKind::Sunflower => SimplifiedBlockKind::Sunflower,
            BlockKind::Lilac => SimplifiedBlockKind::Lilac,
            BlockKind::RoseBush => SimplifiedBlockKind::RoseBush,
            BlockKind::Peony => SimplifiedBlockKind::Peony,
            BlockKind::TallGrass => SimplifiedBlockKind::TallGrass,
            BlockKind::LargeFern => SimplifiedBlockKind::LargeFern,
            BlockKind::WhiteBanner => SimplifiedBlockKind::Banner,
            BlockKind::OrangeBanner => SimplifiedBlockKind::Banner,
            BlockKind::MagentaBanner => SimplifiedBlockKind::Banner,
            BlockKind::LightBlueBanner => SimplifiedBlockKind::Banner,
            BlockKind::YellowBanner => SimplifiedBlockKind::Banner,
            BlockKind::LimeBanner => SimplifiedBlockKind::Banner,
            BlockKind::PinkBanner => SimplifiedBlockKind::Banner,
            BlockKind::GrayBanner => SimplifiedBlockKind::Banner,
            BlockKind::LightGrayBanner => SimplifiedBlockKind::Banner,
            BlockKind::CyanBanner => SimplifiedBlockKind::Banner,
            BlockKind::PurpleBanner => SimplifiedBlockKind::Banner,
            BlockKind::BlueBanner => SimplifiedBlockKind::Banner,
            BlockKind::BrownBanner => SimplifiedBlockKind::Banner,
            BlockKind::GreenBanner => SimplifiedBlockKind::Banner,
            BlockKind::RedBanner => SimplifiedBlockKind::Banner,
            BlockKind::BlackBanner => SimplifiedBlockKind::Banner,
            BlockKind::WhiteWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::OrangeWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::MagentaWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::LightBlueWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::YellowWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::LimeWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::PinkWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::GrayWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::LightGrayWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::CyanWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::PurpleWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::BlueWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::BrownWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::GreenWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::RedWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::BlackWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::RedSandstone => SimplifiedBlockKind::RedSandstone,
            BlockKind::ChiseledRedSandstone => SimplifiedBlockKind::ChiseledRedSandstone,
            BlockKind::CutRedSandstone => SimplifiedBlockKind::CutRedSandstone,
            BlockKind::RedSandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::OakSlab => SimplifiedBlockKind::Slab,
            BlockKind::SpruceSlab => SimplifiedBlockKind::Slab,
            BlockKind::BirchSlab => SimplifiedBlockKind::Slab,
            BlockKind::JungleSlab => SimplifiedBlockKind::Slab,
            BlockKind::AcaciaSlab => SimplifiedBlockKind::Slab,
            BlockKind::DarkOakSlab => SimplifiedBlockKind::Slab,
            BlockKind::StoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::SmoothStoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::SandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::CutSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::PetrifiedOakSlab => SimplifiedBlockKind::Slab,
            BlockKind::CobblestoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::BrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::StoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::NetherBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::QuartzSlab => SimplifiedBlockKind::Slab,
            BlockKind::RedSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::CutRedSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::PurpurSlab => SimplifiedBlockKind::Slab,
            BlockKind::SmoothStone => SimplifiedBlockKind::SmoothStone,
            BlockKind::SmoothSandstone => SimplifiedBlockKind::SmoothSandstone,
            BlockKind::SmoothQuartz => SimplifiedBlockKind::SmoothQuartz,
            BlockKind::SmoothRedSandstone => SimplifiedBlockKind::SmoothRedSandstone,
            BlockKind::SpruceFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::BirchFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::JungleFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::AcaciaFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::DarkOakFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::SpruceFence => SimplifiedBlockKind::Fence,
            BlockKind::BirchFence => SimplifiedBlockKind::Fence,
            BlockKind::JungleFence => SimplifiedBlockKind::Fence,
            BlockKind::AcaciaFence => SimplifiedBlockKind::Fence,
            BlockKind::DarkOakFence => SimplifiedBlockKind::Fence,
            BlockKind::SpruceDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::BirchDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::JungleDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::AcaciaDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::DarkOakDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::EndRod => SimplifiedBlockKind::EndRod,
            BlockKind::ChorusPlant => SimplifiedBlockKind::ChorusPlant,
            BlockKind::ChorusFlower => SimplifiedBlockKind::ChorusFlower,
            BlockKind::PurpurBlock => SimplifiedBlockKind::PurpurBlock,
            BlockKind::PurpurPillar => SimplifiedBlockKind::PurpurPillar,
            BlockKind::PurpurStairs => SimplifiedBlockKind::Stairs,
            BlockKind::EndStoneBricks => SimplifiedBlockKind::EndStoneBricks,
            BlockKind::Beetroots => SimplifiedBlockKind::Beetroots,
            BlockKind::GrassPath => SimplifiedBlockKind::GrassPath,
            BlockKind::EndGateway => SimplifiedBlockKind::EndGateway,
            BlockKind::RepeatingCommandBlock => SimplifiedBlockKind::RepeatingCommandBlock,
            BlockKind::ChainCommandBlock => SimplifiedBlockKind::ChainCommandBlock,
            BlockKind::FrostedIce => SimplifiedBlockKind::FrostedIce,
            BlockKind::MagmaBlock => SimplifiedBlockKind::MagmaBlock,
            BlockKind::NetherWartBlock => SimplifiedBlockKind::NetherWartBlock,
            BlockKind::RedNetherBricks => SimplifiedBlockKind::RedNetherBricks,
            BlockKind::BoneBlock => SimplifiedBlockKind::BoneBlock,
            BlockKind::StructureVoid => SimplifiedBlockKind::StructureVoid,
            BlockKind::Observer => SimplifiedBlockKind::Observer,
            BlockKind::ShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::WhiteShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::OrangeShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::MagentaShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::LightBlueShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::YellowShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::LimeShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::PinkShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::GrayShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::LightGrayShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::CyanShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::PurpleShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::BlueShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::BrownShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::GreenShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::RedShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::BlackShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::WhiteGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::OrangeGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::MagentaGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::LightBlueGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::YellowGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::LimeGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::PinkGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::GrayGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::LightGrayGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::CyanGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::PurpleGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::BlueGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::BrownGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::GreenGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::RedGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::BlackGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::WhiteConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::OrangeConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::MagentaConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::LightBlueConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::YellowConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::LimeConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::PinkConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::GrayConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::LightGrayConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::CyanConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::PurpleConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::BlueConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::BrownConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::GreenConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::RedConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::BlackConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::WhiteConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::OrangeConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::MagentaConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::LightBlueConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::YellowConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::LimeConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::PinkConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::GrayConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::LightGrayConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::CyanConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::PurpleConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::BlueConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::BrownConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::GreenConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::RedConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::BlackConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::Kelp => SimplifiedBlockKind::Kelp,
            BlockKind::KelpPlant => SimplifiedBlockKind::KelpPlant,
            BlockKind::DriedKelpBlock => SimplifiedBlockKind::DriedKelpBlock,
            BlockKind::TurtleEgg => SimplifiedBlockKind::TurtleEgg,
            BlockKind::DeadTubeCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::DeadBrainCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::DeadBubbleCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::DeadFireCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::DeadHornCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::TubeCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::BrainCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::BubbleCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::FireCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::HornCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::DeadTubeCoral => SimplifiedBlockKind::Coral,
            BlockKind::DeadBrainCoral => SimplifiedBlockKind::Coral,
            BlockKind::DeadBubbleCoral => SimplifiedBlockKind::Coral,
            BlockKind::DeadFireCoral => SimplifiedBlockKind::Coral,
            BlockKind::DeadHornCoral => SimplifiedBlockKind::Coral,
            BlockKind::TubeCoral => SimplifiedBlockKind::Coral,
            BlockKind::BrainCoral => SimplifiedBlockKind::Coral,
            BlockKind::BubbleCoral => SimplifiedBlockKind::Coral,
            BlockKind::FireCoral => SimplifiedBlockKind::Coral,
            BlockKind::HornCoral => SimplifiedBlockKind::Coral,
            BlockKind::DeadTubeCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::DeadBrainCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::DeadBubbleCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::DeadFireCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::DeadHornCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::TubeCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::BrainCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::BubbleCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::FireCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::HornCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::DeadTubeCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::DeadBrainCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::DeadBubbleCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::DeadFireCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::DeadHornCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::TubeCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::BrainCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::BubbleCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::FireCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::HornCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::SeaPickle => SimplifiedBlockKind::SeaPickle,
            BlockKind::BlueIce => SimplifiedBlockKind::BlueIce,
            BlockKind::Conduit => SimplifiedBlockKind::Conduit,
            BlockKind::BambooSapling => SimplifiedBlockKind::Sapling,
            BlockKind::Bamboo => SimplifiedBlockKind::Bamboo,
            BlockKind::PottedBamboo => SimplifiedBlockKind::PottedBamboo,
            BlockKind::VoidAir => SimplifiedBlockKind::Air,
            BlockKind::CaveAir => SimplifiedBlockKind::Air,
            BlockKind::BubbleColumn => SimplifiedBlockKind::BubbleColumn,
            BlockKind::PolishedGraniteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::SmoothRedSandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::MossyStoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PolishedDioriteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::MossyCobblestoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::EndStoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::StoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::SmoothSandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::SmoothQuartzStairs => SimplifiedBlockKind::Stairs,
            BlockKind::GraniteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::AndesiteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::RedNetherBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PolishedAndesiteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DioriteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PolishedGraniteSlab => SimplifiedBlockKind::Slab,
            BlockKind::SmoothRedSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::MossyStoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::PolishedDioriteSlab => SimplifiedBlockKind::Slab,
            BlockKind::MossyCobblestoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::EndStoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::SmoothSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::SmoothQuartzSlab => SimplifiedBlockKind::Slab,
            BlockKind::GraniteSlab => SimplifiedBlockKind::Slab,
            BlockKind::AndesiteSlab => SimplifiedBlockKind::Slab,
            BlockKind::RedNetherBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::PolishedAndesiteSlab => SimplifiedBlockKind::Slab,
            BlockKind::DioriteSlab => SimplifiedBlockKind::Slab,
            BlockKind::BrickWall => SimplifiedBlockKind::BrickWall,
            BlockKind::PrismarineWall => SimplifiedBlockKind::PrismarineWall,
            BlockKind::RedSandstoneWall => SimplifiedBlockKind::RedSandstoneWall,
            BlockKind::MossyStoneBrickWall => SimplifiedBlockKind::MossyStoneBrickWall,
            BlockKind::GraniteWall => SimplifiedBlockKind::GraniteWall,
            BlockKind::StoneBrickWall => SimplifiedBlockKind::StoneBrickWall,
            BlockKind::NetherBrickWall => SimplifiedBlockKind::NetherBrickWall,
            BlockKind::AndesiteWall => SimplifiedBlockKind::AndesiteWall,
            BlockKind::RedNetherBrickWall => SimplifiedBlockKind::RedNetherBrickWall,
            BlockKind::SandstoneWall => SimplifiedBlockKind::SandstoneWall,
            BlockKind::EndStoneBrickWall => SimplifiedBlockKind::EndStoneBrickWall,
            BlockKind::DioriteWall => SimplifiedBlockKind::DioriteWall,
            BlockKind::Scaffolding => SimplifiedBlockKind::Scaffolding,
            BlockKind::Loom => SimplifiedBlockKind::Loom,
            BlockKind::Barrel => SimplifiedBlockKind::Barrel,
            BlockKind::Smoker => SimplifiedBlockKind::Smoker,
            BlockKind::BlastFurnace => SimplifiedBlockKind::BlastFurnace,
            BlockKind::CartographyTable => SimplifiedBlockKind::CartographyTable,
            BlockKind::FletchingTable => SimplifiedBlockKind::FletchingTable,
            BlockKind::Grindstone => SimplifiedBlockKind::Grindstone,
            BlockKind::Lectern => SimplifiedBlockKind::Lectern,
            BlockKind::SmithingTable => SimplifiedBlockKind::SmithingTable,
            BlockKind::Stonecutter => SimplifiedBlockKind::Stonecutter,
            BlockKind::Bell => SimplifiedBlockKind::Bell,
            BlockKind::Lantern => SimplifiedBlockKind::Lantern,
            BlockKind::SoulLantern => SimplifiedBlockKind::SoulLantern,
            BlockKind::Campfire => SimplifiedBlockKind::Campfire,
            BlockKind::SoulCampfire => SimplifiedBlockKind::SoulCampfire,
            BlockKind::SweetBerryBush => SimplifiedBlockKind::SweetBerryBush,
            BlockKind::WarpedStem => SimplifiedBlockKind::WarpedStem,
            BlockKind::StrippedWarpedStem => SimplifiedBlockKind::StrippedWarpedStem,
            BlockKind::WarpedHyphae => SimplifiedBlockKind::WarpedHyphae,
            BlockKind::StrippedWarpedHyphae => SimplifiedBlockKind::StrippedWarpedHyphae,
            BlockKind::WarpedNylium => SimplifiedBlockKind::WarpedNylium,
            BlockKind::WarpedFungus => SimplifiedBlockKind::WarpedFungus,
            BlockKind::WarpedWartBlock => SimplifiedBlockKind::WarpedWartBlock,
            BlockKind::WarpedRoots => SimplifiedBlockKind::WarpedRoots,
            BlockKind::NetherSprouts => SimplifiedBlockKind::NetherSprouts,
            BlockKind::CrimsonStem => SimplifiedBlockKind::CrimsonStem,
            BlockKind::StrippedCrimsonStem => SimplifiedBlockKind::StrippedCrimsonStem,
            BlockKind::CrimsonHyphae => SimplifiedBlockKind::CrimsonHyphae,
            BlockKind::StrippedCrimsonHyphae => SimplifiedBlockKind::StrippedCrimsonHyphae,
            BlockKind::CrimsonNylium => SimplifiedBlockKind::CrimsonNylium,
            BlockKind::CrimsonFungus => SimplifiedBlockKind::CrimsonFungus,
            BlockKind::Shroomlight => SimplifiedBlockKind::Shroomlight,
            BlockKind::WeepingVines => SimplifiedBlockKind::WeepingVines,
            BlockKind::WeepingVinesPlant => SimplifiedBlockKind::WeepingVinesPlant,
            BlockKind::TwistingVines => SimplifiedBlockKind::TwistingVines,
            BlockKind::TwistingVinesPlant => SimplifiedBlockKind::TwistingVinesPlant,
            BlockKind::CrimsonRoots => SimplifiedBlockKind::CrimsonRoots,
            BlockKind::CrimsonPlanks => SimplifiedBlockKind::Planks,
            BlockKind::WarpedPlanks => SimplifiedBlockKind::Planks,
            BlockKind::CrimsonSlab => SimplifiedBlockKind::Slab,
            BlockKind::WarpedSlab => SimplifiedBlockKind::Slab,
            BlockKind::CrimsonPressurePlate => SimplifiedBlockKind::CrimsonPressurePlate,
            BlockKind::WarpedPressurePlate => SimplifiedBlockKind::WarpedPressurePlate,
            BlockKind::CrimsonFence => SimplifiedBlockKind::Fence,
            BlockKind::WarpedFence => SimplifiedBlockKind::Fence,
            BlockKind::CrimsonTrapdoor => SimplifiedBlockKind::CrimsonTrapdoor,
            BlockKind::WarpedTrapdoor => SimplifiedBlockKind::WarpedTrapdoor,
            BlockKind::CrimsonFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::WarpedFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::CrimsonStairs => SimplifiedBlockKind::Stairs,
            BlockKind::WarpedStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CrimsonButton => SimplifiedBlockKind::CrimsonButton,
            BlockKind::WarpedButton => SimplifiedBlockKind::WarpedButton,
            BlockKind::CrimsonDoor => SimplifiedBlockKind::CrimsonDoor,
            BlockKind::WarpedDoor => SimplifiedBlockKind::WarpedDoor,
            BlockKind::CrimsonSign => SimplifiedBlockKind::Sign,
            BlockKind::WarpedSign => SimplifiedBlockKind::Sign,
            BlockKind::CrimsonWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::WarpedWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::StructureBlock => SimplifiedBlockKind::StructureBlock,
            BlockKind::Jigsaw => SimplifiedBlockKind::Jigsaw,
            BlockKind::Composter => SimplifiedBlockKind::Composter,
            BlockKind::Target => SimplifiedBlockKind::Target,
            BlockKind::BeeNest => SimplifiedBlockKind::BeeNest,
            BlockKind::Beehive => SimplifiedBlockKind::Beehive,
            BlockKind::HoneyBlock => SimplifiedBlockKind::HoneyBlock,
            BlockKind::HoneycombBlock => SimplifiedBlockKind::HoneycombBlock,
            BlockKind::NetheriteBlock => SimplifiedBlockKind::NetheriteBlock,
            BlockKind::AncientDebris => SimplifiedBlockKind::AncientDebris,
            BlockKind::CryingObsidian => SimplifiedBlockKind::CryingObsidian,
            BlockKind::RespawnAnchor => SimplifiedBlockKind::RespawnAnchor,
            BlockKind::PottedCrimsonFungus => SimplifiedBlockKind::PottedCrimsonFungus,
            BlockKind::PottedWarpedFungus => SimplifiedBlockKind::PottedWarpedFungus,
            BlockKind::PottedCrimsonRoots => SimplifiedBlockKind::PottedCrimsonRoots,
            BlockKind::PottedWarpedRoots => SimplifiedBlockKind::PottedWarpedRoots,
            BlockKind::Lodestone => SimplifiedBlockKind::Lodestone,
            BlockKind::Blackstone => SimplifiedBlockKind::Blackstone,
            BlockKind::BlackstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::BlackstoneWall => SimplifiedBlockKind::BlackstoneWall,
            BlockKind::BlackstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::PolishedBlackstone => SimplifiedBlockKind::PolishedBlackstone,
            BlockKind::PolishedBlackstoneBricks => SimplifiedBlockKind::PolishedBlackstoneBricks,
            BlockKind::CrackedPolishedBlackstoneBricks => {
                SimplifiedBlockKind::CrackedPolishedBlackstoneBricks
            }
            BlockKind::ChiseledPolishedBlackstone => {
                SimplifiedBlockKind::ChiseledPolishedBlackstone
            }
            BlockKind::PolishedBlackstoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::PolishedBlackstoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PolishedBlackstoneBrickWall => {
                SimplifiedBlockKind::PolishedBlackstoneBrickWall
            }
            BlockKind::GildedBlackstone => SimplifiedBlockKind::GildedBlackstone,
            BlockKind::PolishedBlackstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PolishedBlackstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::PolishedBlackstonePressurePlate => {
                SimplifiedBlockKind::PolishedBlackstonePressurePlate
            }
            BlockKind::PolishedBlackstoneButton => SimplifiedBlockKind::PolishedBlackstoneButton,
            BlockKind::PolishedBlackstoneWall => SimplifiedBlockKind::PolishedBlackstoneWall,
            BlockKind::ChiseledNetherBricks => SimplifiedBlockKind::ChiseledNetherBricks,
            BlockKind::CrackedNetherBricks => SimplifiedBlockKind::CrackedNetherBricks,
            BlockKind::QuartzBricks => SimplifiedBlockKind::QuartzBricks,
        }
    }
}
