// This file is @generated. Please do not edit.
use crate::BlockKind;
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SimplifiedBlockKind {
    ActivatorRail,
    Air,
    AmethystBlock,
    AmethystCluster,
    AncientDebris,
    Andesite,
    AndesiteWall,
    Anvil,
    AttachedMelonStem,
    AttachedPumpkinStem,
    Azalea,
    Bamboo,
    Banner,
    Barrel,
    Barrier,
    Basalt,
    Beacon,
    Bed,
    Bedrock,
    BeeNest,
    Beehive,
    Beetroots,
    Bell,
    BigDripleaf,
    BigDripleafStem,
    BlackCandle,
    BlackCandleCake,
    Blackstone,
    BlackstoneWall,
    BlastFurnace,
    BlueCandle,
    BlueCandleCake,
    BlueIce,
    BoneBlock,
    Bookshelf,
    BrewingStand,
    BrickWall,
    Bricks,
    BrownCandle,
    BrownCandleCake,
    BrownMushroomBlock,
    BubbleColumn,
    BuddingAmethyst,
    Cactus,
    Cake,
    Calcite,
    Campfire,
    Candle,
    CandleCake,
    Carpet,
    Carrots,
    CartographyTable,
    CarvedPumpkin,
    Cauldron,
    CaveVines,
    CaveVinesPlant,
    Chain,
    ChainCommandBlock,
    Chest,
    ChiseledDeepslate,
    ChiseledNetherBricks,
    ChiseledPolishedBlackstone,
    ChiseledQuartzBlock,
    ChiseledRedSandstone,
    ChiseledSandstone,
    ChiseledStoneBricks,
    ChorusFlower,
    ChorusPlant,
    Clay,
    CoalBlock,
    CoalOre,
    CoarseDirt,
    CobbledDeepslate,
    CobbledDeepslateWall,
    Cobblestone,
    CobblestoneWall,
    Cobweb,
    Cocoa,
    CommandBlock,
    Comparator,
    Composter,
    Concrete,
    ConcretePowder,
    Conduit,
    CopperBlock,
    CopperOre,
    Coral,
    CoralBlock,
    CoralFan,
    CoralWallFan,
    Cornflower,
    CrackedDeepslateBricks,
    CrackedDeepslateTiles,
    CrackedNetherBricks,
    CrackedPolishedBlackstoneBricks,
    CrackedStoneBricks,
    CraftingTable,
    CreeperHead,
    CreeperWallHead,
    CrimsonButton,
    CrimsonDoor,
    CrimsonFungus,
    CrimsonHyphae,
    CrimsonNylium,
    CrimsonPressurePlate,
    CrimsonRoots,
    CrimsonStem,
    CrimsonTrapdoor,
    CryingObsidian,
    CutCopper,
    CutRedSandstone,
    CutSandstone,
    CyanCandle,
    CyanCandleCake,
    DarkPrismarine,
    DaylightDetector,
    DeadBush,
    Deepslate,
    DeepslateBrickWall,
    DeepslateBricks,
    DeepslateCoalOre,
    DeepslateCopperOre,
    DeepslateDiamondOre,
    DeepslateEmeraldOre,
    DeepslateGoldOre,
    DeepslateIronOre,
    DeepslateLapisOre,
    DeepslateRedstoneOre,
    DeepslateTileWall,
    DeepslateTiles,
    DetectorRail,
    DiamondBlock,
    DiamondOre,
    Diorite,
    DioriteWall,
    Dirt,
    DirtPath,
    Dispenser,
    DragonEgg,
    DragonHead,
    DragonWallHead,
    DriedKelpBlock,
    DripstoneBlock,
    Dropper,
    EmeraldBlock,
    EmeraldOre,
    EnchantingTable,
    EndGateway,
    EndPortal,
    EndPortalFrame,
    EndRod,
    EndStone,
    EndStoneBrickWall,
    EndStoneBricks,
    EnderChest,
    ExposedCopper,
    ExposedCutCopper,
    Farmland,
    Fence,
    FenceGate,
    Fern,
    Fire,
    FletchingTable,
    Flower,
    FlowerPot,
    FloweringAzalea,
    FrostedIce,
    Furnace,
    GildedBlackstone,
    Glass,
    GlassPane,
    GlazedTeracotta,
    GlowLichen,
    Glowstone,
    GoldBlock,
    GoldOre,
    Granite,
    GraniteWall,
    Grass,
    GrassBlock,
    Gravel,
    GrayCandle,
    GrayCandleCake,
    GreenCandle,
    GreenCandleCake,
    Grindstone,
    HangingRoots,
    HayBlock,
    HeavyWeightedPressurePlate,
    HoneyBlock,
    HoneycombBlock,
    Hopper,
    Ice,
    InfestedChiseledStoneBricks,
    InfestedCobblestone,
    InfestedCrackedStoneBricks,
    InfestedDeepslate,
    InfestedMossyStoneBricks,
    InfestedStone,
    InfestedStoneBricks,
    IronBars,
    IronBlock,
    IronDoor,
    IronOre,
    IronTrapdoor,
    JackOLantern,
    Jigsaw,
    Jukebox,
    Kelp,
    KelpPlant,
    Ladder,
    Lantern,
    LapisBlock,
    LapisOre,
    LargeAmethystBud,
    LargeFern,
    Lava,
    LavaCauldron,
    Leaves,
    Lectern,
    Lever,
    Light,
    LightBlueCandle,
    LightBlueCandleCake,
    LightGrayCandle,
    LightGrayCandleCake,
    LightWeightedPressurePlate,
    LightningRod,
    Lilac,
    LilyOfTheValley,
    LilyPad,
    LimeCandle,
    LimeCandleCake,
    Lodestone,
    Log,
    Loom,
    MagentaCandle,
    MagentaCandleCake,
    MagmaBlock,
    MediumAmethystBud,
    Melon,
    MelonStem,
    MossBlock,
    MossyCobblestone,
    MossyCobblestoneWall,
    MossyStoneBrickWall,
    MossyStoneBricks,
    MovingPiston,
    Mushroom,
    MushroomStem,
    Mycelium,
    NetherBrickWall,
    NetherBricks,
    NetherGoldOre,
    NetherPortal,
    NetherQuartzOre,
    NetherSprouts,
    NetherWart,
    NetherWartBlock,
    NetheriteBlock,
    Netherrack,
    NoteBlock,
    Observer,
    Obsidian,
    OrangeCandle,
    OrangeCandleCake,
    OxidizedCopper,
    OxidizedCutCopper,
    PackedIce,
    Peony,
    PinkCandle,
    PinkCandleCake,
    Piston,
    PistonHead,
    Planks,
    PlayerHead,
    PlayerWallHead,
    Podzol,
    PointedDripstone,
    PolishedAndesite,
    PolishedBasalt,
    PolishedBlackstone,
    PolishedBlackstoneBrickWall,
    PolishedBlackstoneBricks,
    PolishedBlackstoneButton,
    PolishedBlackstonePressurePlate,
    PolishedBlackstoneWall,
    PolishedDeepslate,
    PolishedDeepslateWall,
    PolishedDiorite,
    PolishedGranite,
    Potatoes,
    PottedAllium,
    PottedAzaleaBush,
    PottedBamboo,
    PottedCactus,
    PottedCornflower,
    PottedCrimsonFungus,
    PottedCrimsonRoots,
    PottedDandelion,
    PottedDeadBush,
    PottedFern,
    PottedFloweringAzaleaBush,
    PottedLilyOfTheValley,
    PottedPoppy,
    PottedWarpedFungus,
    PottedWarpedRoots,
    PottedWitherRose,
    PowderSnow,
    PowderSnowCauldron,
    PoweredRail,
    Prismarine,
    PrismarineBricks,
    PrismarineWall,
    Pumpkin,
    PumpkinStem,
    PurpleCandle,
    PurpleCandleCake,
    PurpurBlock,
    PurpurPillar,
    QuartzBlock,
    QuartzBricks,
    QuartzPillar,
    Rail,
    RawCopperBlock,
    RawGoldBlock,
    RawIronBlock,
    RedCandle,
    RedCandleCake,
    RedMushroomBlock,
    RedNetherBrickWall,
    RedNetherBricks,
    RedSand,
    RedSandstone,
    RedSandstoneWall,
    RedstoneBlock,
    RedstoneLamp,
    RedstoneOre,
    RedstoneTorch,
    RedstoneWallTorch,
    RedstoneWire,
    Repeater,
    RepeatingCommandBlock,
    RespawnAnchor,
    RootedDirt,
    RoseBush,
    Sand,
    Sandstone,
    SandstoneWall,
    Sapling,
    Scaffolding,
    SculkSensor,
    SeaLantern,
    SeaPickle,
    Seagrass,
    Shroomlight,
    ShulkerBox,
    Sign,
    SkeletonSkull,
    SkeletonWallSkull,
    Slab,
    SlimeBlock,
    SmallAmethystBud,
    SmallDripleaf,
    SmithingTable,
    Smoker,
    SmoothBasalt,
    SmoothQuartz,
    SmoothRedSandstone,
    SmoothSandstone,
    SmoothStone,
    Snow,
    SnowBlock,
    SoulCampfire,
    SoulFire,
    SoulLantern,
    SoulSand,
    SoulSoil,
    SoulTorch,
    SoulWallTorch,
    Spawner,
    Sponge,
    SporeBlossom,
    StainedGlass,
    StainedGlassPane,
    Stairs,
    StickyPiston,
    Stone,
    StoneBrickWall,
    StoneBricks,
    StoneButton,
    StonePressurePlate,
    Stonecutter,
    StrippedCrimsonHyphae,
    StrippedCrimsonStem,
    StrippedWarpedHyphae,
    StrippedWarpedStem,
    StructureBlock,
    StructureVoid,
    SugarCane,
    Sunflower,
    SweetBerryBush,
    TallGrass,
    TallSeagrass,
    Target,
    Teracotta,
    TintedGlass,
    Tnt,
    Torch,
    TrappedChest,
    Tripwire,
    TripwireHook,
    Tuff,
    TurtleEgg,
    TwistingVines,
    TwistingVinesPlant,
    Vine,
    WallBanner,
    WallSign,
    WallTorch,
    WarpedButton,
    WarpedDoor,
    WarpedFungus,
    WarpedHyphae,
    WarpedNylium,
    WarpedPressurePlate,
    WarpedRoots,
    WarpedStem,
    WarpedTrapdoor,
    WarpedWartBlock,
    Water,
    WaterCauldron,
    WaxedCopperBlock,
    WaxedCutCopper,
    WaxedExposedCopper,
    WaxedExposedCutCopper,
    WaxedOxidizedCopper,
    WaxedOxidizedCutCopper,
    WaxedWeatheredCopper,
    WaxedWeatheredCutCopper,
    WeatheredCopper,
    WeatheredCutCopper,
    WeepingVines,
    WeepingVinesPlant,
    WetSponge,
    Wheat,
    WhiteCandle,
    WhiteCandleCake,
    WitherRose,
    WitherSkeletonSkull,
    WitherSkeletonWallSkull,
    WoodenButton,
    WoodenDoor,
    WoodenPressurePlate,
    WoodenTrapdoor,
    Wool,
    YellowCandle,
    YellowCandleCake,
    ZombieHead,
    ZombieWallHead,
}
impl SimplifiedBlockKind {
    #[inline]
    pub fn values() -> &'static [SimplifiedBlockKind] {
        use SimplifiedBlockKind::*;
        &[
            ActivatorRail,
            Air,
            AmethystBlock,
            AmethystCluster,
            AncientDebris,
            Andesite,
            AndesiteWall,
            Anvil,
            AttachedMelonStem,
            AttachedPumpkinStem,
            Azalea,
            Bamboo,
            Banner,
            Barrel,
            Barrier,
            Basalt,
            Beacon,
            Bed,
            Bedrock,
            BeeNest,
            Beehive,
            Beetroots,
            Bell,
            BigDripleaf,
            BigDripleafStem,
            BlackCandle,
            BlackCandleCake,
            Blackstone,
            BlackstoneWall,
            BlastFurnace,
            BlueCandle,
            BlueCandleCake,
            BlueIce,
            BoneBlock,
            Bookshelf,
            BrewingStand,
            BrickWall,
            Bricks,
            BrownCandle,
            BrownCandleCake,
            BrownMushroomBlock,
            BubbleColumn,
            BuddingAmethyst,
            Cactus,
            Cake,
            Calcite,
            Campfire,
            Candle,
            CandleCake,
            Carpet,
            Carrots,
            CartographyTable,
            CarvedPumpkin,
            Cauldron,
            CaveVines,
            CaveVinesPlant,
            Chain,
            ChainCommandBlock,
            Chest,
            ChiseledDeepslate,
            ChiseledNetherBricks,
            ChiseledPolishedBlackstone,
            ChiseledQuartzBlock,
            ChiseledRedSandstone,
            ChiseledSandstone,
            ChiseledStoneBricks,
            ChorusFlower,
            ChorusPlant,
            Clay,
            CoalBlock,
            CoalOre,
            CoarseDirt,
            CobbledDeepslate,
            CobbledDeepslateWall,
            Cobblestone,
            CobblestoneWall,
            Cobweb,
            Cocoa,
            CommandBlock,
            Comparator,
            Composter,
            Concrete,
            ConcretePowder,
            Conduit,
            CopperBlock,
            CopperOre,
            Coral,
            CoralBlock,
            CoralFan,
            CoralWallFan,
            Cornflower,
            CrackedDeepslateBricks,
            CrackedDeepslateTiles,
            CrackedNetherBricks,
            CrackedPolishedBlackstoneBricks,
            CrackedStoneBricks,
            CraftingTable,
            CreeperHead,
            CreeperWallHead,
            CrimsonButton,
            CrimsonDoor,
            CrimsonFungus,
            CrimsonHyphae,
            CrimsonNylium,
            CrimsonPressurePlate,
            CrimsonRoots,
            CrimsonStem,
            CrimsonTrapdoor,
            CryingObsidian,
            CutCopper,
            CutRedSandstone,
            CutSandstone,
            CyanCandle,
            CyanCandleCake,
            DarkPrismarine,
            DaylightDetector,
            DeadBush,
            Deepslate,
            DeepslateBrickWall,
            DeepslateBricks,
            DeepslateCoalOre,
            DeepslateCopperOre,
            DeepslateDiamondOre,
            DeepslateEmeraldOre,
            DeepslateGoldOre,
            DeepslateIronOre,
            DeepslateLapisOre,
            DeepslateRedstoneOre,
            DeepslateTileWall,
            DeepslateTiles,
            DetectorRail,
            DiamondBlock,
            DiamondOre,
            Diorite,
            DioriteWall,
            Dirt,
            DirtPath,
            Dispenser,
            DragonEgg,
            DragonHead,
            DragonWallHead,
            DriedKelpBlock,
            DripstoneBlock,
            Dropper,
            EmeraldBlock,
            EmeraldOre,
            EnchantingTable,
            EndGateway,
            EndPortal,
            EndPortalFrame,
            EndRod,
            EndStone,
            EndStoneBrickWall,
            EndStoneBricks,
            EnderChest,
            ExposedCopper,
            ExposedCutCopper,
            Farmland,
            Fence,
            FenceGate,
            Fern,
            Fire,
            FletchingTable,
            Flower,
            FlowerPot,
            FloweringAzalea,
            FrostedIce,
            Furnace,
            GildedBlackstone,
            Glass,
            GlassPane,
            GlazedTeracotta,
            GlowLichen,
            Glowstone,
            GoldBlock,
            GoldOre,
            Granite,
            GraniteWall,
            Grass,
            GrassBlock,
            Gravel,
            GrayCandle,
            GrayCandleCake,
            GreenCandle,
            GreenCandleCake,
            Grindstone,
            HangingRoots,
            HayBlock,
            HeavyWeightedPressurePlate,
            HoneyBlock,
            HoneycombBlock,
            Hopper,
            Ice,
            InfestedChiseledStoneBricks,
            InfestedCobblestone,
            InfestedCrackedStoneBricks,
            InfestedDeepslate,
            InfestedMossyStoneBricks,
            InfestedStone,
            InfestedStoneBricks,
            IronBars,
            IronBlock,
            IronDoor,
            IronOre,
            IronTrapdoor,
            JackOLantern,
            Jigsaw,
            Jukebox,
            Kelp,
            KelpPlant,
            Ladder,
            Lantern,
            LapisBlock,
            LapisOre,
            LargeAmethystBud,
            LargeFern,
            Lava,
            LavaCauldron,
            Leaves,
            Lectern,
            Lever,
            Light,
            LightBlueCandle,
            LightBlueCandleCake,
            LightGrayCandle,
            LightGrayCandleCake,
            LightWeightedPressurePlate,
            LightningRod,
            Lilac,
            LilyOfTheValley,
            LilyPad,
            LimeCandle,
            LimeCandleCake,
            Lodestone,
            Log,
            Loom,
            MagentaCandle,
            MagentaCandleCake,
            MagmaBlock,
            MediumAmethystBud,
            Melon,
            MelonStem,
            MossBlock,
            MossyCobblestone,
            MossyCobblestoneWall,
            MossyStoneBrickWall,
            MossyStoneBricks,
            MovingPiston,
            Mushroom,
            MushroomStem,
            Mycelium,
            NetherBrickWall,
            NetherBricks,
            NetherGoldOre,
            NetherPortal,
            NetherQuartzOre,
            NetherSprouts,
            NetherWart,
            NetherWartBlock,
            NetheriteBlock,
            Netherrack,
            NoteBlock,
            Observer,
            Obsidian,
            OrangeCandle,
            OrangeCandleCake,
            OxidizedCopper,
            OxidizedCutCopper,
            PackedIce,
            Peony,
            PinkCandle,
            PinkCandleCake,
            Piston,
            PistonHead,
            Planks,
            PlayerHead,
            PlayerWallHead,
            Podzol,
            PointedDripstone,
            PolishedAndesite,
            PolishedBasalt,
            PolishedBlackstone,
            PolishedBlackstoneBrickWall,
            PolishedBlackstoneBricks,
            PolishedBlackstoneButton,
            PolishedBlackstonePressurePlate,
            PolishedBlackstoneWall,
            PolishedDeepslate,
            PolishedDeepslateWall,
            PolishedDiorite,
            PolishedGranite,
            Potatoes,
            PottedAllium,
            PottedAzaleaBush,
            PottedBamboo,
            PottedCactus,
            PottedCornflower,
            PottedCrimsonFungus,
            PottedCrimsonRoots,
            PottedDandelion,
            PottedDeadBush,
            PottedFern,
            PottedFloweringAzaleaBush,
            PottedLilyOfTheValley,
            PottedPoppy,
            PottedWarpedFungus,
            PottedWarpedRoots,
            PottedWitherRose,
            PowderSnow,
            PowderSnowCauldron,
            PoweredRail,
            Prismarine,
            PrismarineBricks,
            PrismarineWall,
            Pumpkin,
            PumpkinStem,
            PurpleCandle,
            PurpleCandleCake,
            PurpurBlock,
            PurpurPillar,
            QuartzBlock,
            QuartzBricks,
            QuartzPillar,
            Rail,
            RawCopperBlock,
            RawGoldBlock,
            RawIronBlock,
            RedCandle,
            RedCandleCake,
            RedMushroomBlock,
            RedNetherBrickWall,
            RedNetherBricks,
            RedSand,
            RedSandstone,
            RedSandstoneWall,
            RedstoneBlock,
            RedstoneLamp,
            RedstoneOre,
            RedstoneTorch,
            RedstoneWallTorch,
            RedstoneWire,
            Repeater,
            RepeatingCommandBlock,
            RespawnAnchor,
            RootedDirt,
            RoseBush,
            Sand,
            Sandstone,
            SandstoneWall,
            Sapling,
            Scaffolding,
            SculkSensor,
            SeaLantern,
            SeaPickle,
            Seagrass,
            Shroomlight,
            ShulkerBox,
            Sign,
            SkeletonSkull,
            SkeletonWallSkull,
            Slab,
            SlimeBlock,
            SmallAmethystBud,
            SmallDripleaf,
            SmithingTable,
            Smoker,
            SmoothBasalt,
            SmoothQuartz,
            SmoothRedSandstone,
            SmoothSandstone,
            SmoothStone,
            Snow,
            SnowBlock,
            SoulCampfire,
            SoulFire,
            SoulLantern,
            SoulSand,
            SoulSoil,
            SoulTorch,
            SoulWallTorch,
            Spawner,
            Sponge,
            SporeBlossom,
            StainedGlass,
            StainedGlassPane,
            Stairs,
            StickyPiston,
            Stone,
            StoneBrickWall,
            StoneBricks,
            StoneButton,
            StonePressurePlate,
            Stonecutter,
            StrippedCrimsonHyphae,
            StrippedCrimsonStem,
            StrippedWarpedHyphae,
            StrippedWarpedStem,
            StructureBlock,
            StructureVoid,
            SugarCane,
            Sunflower,
            SweetBerryBush,
            TallGrass,
            TallSeagrass,
            Target,
            Teracotta,
            TintedGlass,
            Tnt,
            Torch,
            TrappedChest,
            Tripwire,
            TripwireHook,
            Tuff,
            TurtleEgg,
            TwistingVines,
            TwistingVinesPlant,
            Vine,
            WallBanner,
            WallSign,
            WallTorch,
            WarpedButton,
            WarpedDoor,
            WarpedFungus,
            WarpedHyphae,
            WarpedNylium,
            WarpedPressurePlate,
            WarpedRoots,
            WarpedStem,
            WarpedTrapdoor,
            WarpedWartBlock,
            Water,
            WaterCauldron,
            WaxedCopperBlock,
            WaxedCutCopper,
            WaxedExposedCopper,
            WaxedExposedCutCopper,
            WaxedOxidizedCopper,
            WaxedOxidizedCutCopper,
            WaxedWeatheredCopper,
            WaxedWeatheredCutCopper,
            WeatheredCopper,
            WeatheredCutCopper,
            WeepingVines,
            WeepingVinesPlant,
            WetSponge,
            Wheat,
            WhiteCandle,
            WhiteCandleCake,
            WitherRose,
            WitherSkeletonSkull,
            WitherSkeletonWallSkull,
            WoodenButton,
            WoodenDoor,
            WoodenPressurePlate,
            WoodenTrapdoor,
            Wool,
            YellowCandle,
            YellowCandleCake,
            ZombieHead,
            ZombieWallHead,
        ]
    }
}
impl BlockKind {
    #[doc = "Returns the `simplified_kind` property of this `BlockKind`."]
    #[inline]
    pub fn simplified_kind(&self) -> SimplifiedBlockKind {
        match self {
            BlockKind::SmoothQuartz => SimplifiedBlockKind::SmoothQuartz,
            BlockKind::LimeTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::CutSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::ZombieWallHead => SimplifiedBlockKind::ZombieWallHead,
            BlockKind::BlueOrchid => SimplifiedBlockKind::Flower,
            BlockKind::OakFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::WaxedCutCopper => SimplifiedBlockKind::WaxedCutCopper,
            BlockKind::PistonHead => SimplifiedBlockKind::PistonHead,
            BlockKind::DarkPrismarineStairs => SimplifiedBlockKind::Stairs,
            BlockKind::BirchLog => SimplifiedBlockKind::Log,
            BlockKind::LightBlueBanner => SimplifiedBlockKind::Banner,
            BlockKind::Bamboo => SimplifiedBlockKind::Bamboo,
            BlockKind::CaveAir => SimplifiedBlockKind::Air,
            BlockKind::GoldOre => SimplifiedBlockKind::GoldOre,
            BlockKind::SmoothBasalt => SimplifiedBlockKind::SmoothBasalt,
            BlockKind::DeadBubbleCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::Shroomlight => SimplifiedBlockKind::Shroomlight,
            BlockKind::BrainCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::SmoothSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::OxeyeDaisy => SimplifiedBlockKind::Flower,
            BlockKind::Cocoa => SimplifiedBlockKind::Cocoa,
            BlockKind::AcaciaLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::PolishedBlackstoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::YellowBed => SimplifiedBlockKind::Bed,
            BlockKind::MagentaCandleCake => SimplifiedBlockKind::MagentaCandleCake,
            BlockKind::Chain => SimplifiedBlockKind::Chain,
            BlockKind::WaxedOxidizedCutCopper => SimplifiedBlockKind::WaxedOxidizedCutCopper,
            BlockKind::MagentaGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::WeatheredCutCopper => SimplifiedBlockKind::WeatheredCutCopper,
            BlockKind::NetherBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::Lantern => SimplifiedBlockKind::Lantern,
            BlockKind::DarkOakFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::RedNetherBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::BrownBanner => SimplifiedBlockKind::Banner,
            BlockKind::BrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::WitherSkeletonSkull => SimplifiedBlockKind::WitherSkeletonSkull,
            BlockKind::MagentaStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::SeaPickle => SimplifiedBlockKind::SeaPickle,
            BlockKind::RepeatingCommandBlock => SimplifiedBlockKind::RepeatingCommandBlock,
            BlockKind::WarpedHyphae => SimplifiedBlockKind::WarpedHyphae,
            BlockKind::MagentaStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::MagentaWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::WarpedWartBlock => SimplifiedBlockKind::WarpedWartBlock,
            BlockKind::MushroomStem => SimplifiedBlockKind::MushroomStem,
            BlockKind::SoulLantern => SimplifiedBlockKind::SoulLantern,
            BlockKind::InfestedCobblestone => SimplifiedBlockKind::InfestedCobblestone,
            BlockKind::GlassPane => SimplifiedBlockKind::GlassPane,
            BlockKind::BirchLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::LightGrayTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::StrippedCrimsonHyphae => SimplifiedBlockKind::StrippedCrimsonHyphae,
            BlockKind::PottedLilyOfTheValley => SimplifiedBlockKind::PottedLilyOfTheValley,
            BlockKind::StrippedBirchLog => SimplifiedBlockKind::Log,
            BlockKind::LightGrayStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::StrippedWarpedHyphae => SimplifiedBlockKind::StrippedWarpedHyphae,
            BlockKind::Stone => SimplifiedBlockKind::Stone,
            BlockKind::CommandBlock => SimplifiedBlockKind::CommandBlock,
            BlockKind::LapisBlock => SimplifiedBlockKind::LapisBlock,
            BlockKind::PottedBirchSapling => SimplifiedBlockKind::Sapling,
            BlockKind::WarpedPlanks => SimplifiedBlockKind::Planks,
            BlockKind::AcaciaPlanks => SimplifiedBlockKind::Planks,
            BlockKind::SpruceTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::RedstoneOre => SimplifiedBlockKind::RedstoneOre,
            BlockKind::LimeConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::OrangeTulip => SimplifiedBlockKind::Flower,
            BlockKind::CrackedDeepslateBricks => SimplifiedBlockKind::CrackedDeepslateBricks,
            BlockKind::PottedWitherRose => SimplifiedBlockKind::PottedWitherRose,
            BlockKind::DeadBubbleCoral => SimplifiedBlockKind::Coral,
            BlockKind::JungleFence => SimplifiedBlockKind::Fence,
            BlockKind::SpruceWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::WhiteCandleCake => SimplifiedBlockKind::WhiteCandleCake,
            BlockKind::JunglePressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::FrostedIce => SimplifiedBlockKind::FrostedIce,
            BlockKind::Smoker => SimplifiedBlockKind::Smoker,
            BlockKind::Target => SimplifiedBlockKind::Target,
            BlockKind::ChiseledRedSandstone => SimplifiedBlockKind::ChiseledRedSandstone,
            BlockKind::GreenConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::CrackedStoneBricks => SimplifiedBlockKind::CrackedStoneBricks,
            BlockKind::GrayTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::PoweredRail => SimplifiedBlockKind::PoweredRail,
            BlockKind::DarkPrismarineSlab => SimplifiedBlockKind::Slab,
            BlockKind::RedstoneWallTorch => SimplifiedBlockKind::RedstoneWallTorch,
            BlockKind::Kelp => SimplifiedBlockKind::Kelp,
            BlockKind::DaylightDetector => SimplifiedBlockKind::DaylightDetector,
            BlockKind::GrayConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::BlackCandle => SimplifiedBlockKind::BlackCandle,
            BlockKind::Furnace => SimplifiedBlockKind::Furnace,
            BlockKind::PolishedBlackstone => SimplifiedBlockKind::PolishedBlackstone,
            BlockKind::DriedKelpBlock => SimplifiedBlockKind::DriedKelpBlock,
            BlockKind::DarkOakWood => SimplifiedBlockKind::Log,
            BlockKind::WaxedWeatheredCutCopper => SimplifiedBlockKind::WaxedWeatheredCutCopper,
            BlockKind::MagentaShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::JungleSapling => SimplifiedBlockKind::Sapling,
            BlockKind::BlackShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::SpruceLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::DeadHornCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::PurpleBed => SimplifiedBlockKind::Bed,
            BlockKind::PolishedGraniteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::TubeCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::OrangeGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::BlueBed => SimplifiedBlockKind::Bed,
            BlockKind::PetrifiedOakSlab => SimplifiedBlockKind::Slab,
            BlockKind::SoulSand => SimplifiedBlockKind::SoulSand,
            BlockKind::BirchPlanks => SimplifiedBlockKind::Planks,
            BlockKind::AcaciaWood => SimplifiedBlockKind::Log,
            BlockKind::FlowerPot => SimplifiedBlockKind::FlowerPot,
            BlockKind::Campfire => SimplifiedBlockKind::Campfire,
            BlockKind::NetherBricks => SimplifiedBlockKind::NetherBricks,
            BlockKind::JungleSlab => SimplifiedBlockKind::Slab,
            BlockKind::OrangeCandle => SimplifiedBlockKind::OrangeCandle,
            BlockKind::BirchSapling => SimplifiedBlockKind::Sapling,
            BlockKind::DarkPrismarine => SimplifiedBlockKind::DarkPrismarine,
            BlockKind::GrayCandle => SimplifiedBlockKind::GrayCandle,
            BlockKind::WeepingVinesPlant => SimplifiedBlockKind::WeepingVinesPlant,
            BlockKind::CrimsonFence => SimplifiedBlockKind::Fence,
            BlockKind::AttachedPumpkinStem => SimplifiedBlockKind::AttachedPumpkinStem,
            BlockKind::PottedFloweringAzaleaBush => SimplifiedBlockKind::PottedFloweringAzaleaBush,
            BlockKind::YellowCandleCake => SimplifiedBlockKind::YellowCandleCake,
            BlockKind::BlackWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::Sponge => SimplifiedBlockKind::Sponge,
            BlockKind::SmoothSandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PottedDandelion => SimplifiedBlockKind::PottedDandelion,
            BlockKind::PottedAllium => SimplifiedBlockKind::PottedAllium,
            BlockKind::JungleWood => SimplifiedBlockKind::Log,
            BlockKind::PottedRedTulip => SimplifiedBlockKind::Flower,
            BlockKind::PottedSpruceSapling => SimplifiedBlockKind::Sapling,
            BlockKind::Beetroots => SimplifiedBlockKind::Beetroots,
            BlockKind::KelpPlant => SimplifiedBlockKind::KelpPlant,
            BlockKind::WarpedStem => SimplifiedBlockKind::WarpedStem,
            BlockKind::MossyStoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PurpleBanner => SimplifiedBlockKind::Banner,
            BlockKind::LightningRod => SimplifiedBlockKind::LightningRod,
            BlockKind::Conduit => SimplifiedBlockKind::Conduit,
            BlockKind::HornCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::Beehive => SimplifiedBlockKind::Beehive,
            BlockKind::PolishedAndesite => SimplifiedBlockKind::PolishedAndesite,
            BlockKind::Calcite => SimplifiedBlockKind::Calcite,
            BlockKind::PinkGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::Sand => SimplifiedBlockKind::Sand,
            BlockKind::Clay => SimplifiedBlockKind::Clay,
            BlockKind::DirtPath => SimplifiedBlockKind::DirtPath,
            BlockKind::MagentaCandle => SimplifiedBlockKind::MagentaCandle,
            BlockKind::PinkBed => SimplifiedBlockKind::Bed,
            BlockKind::SmallAmethystBud => SimplifiedBlockKind::SmallAmethystBud,
            BlockKind::WitherRose => SimplifiedBlockKind::WitherRose,
            BlockKind::StoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::RedSandstoneWall => SimplifiedBlockKind::RedSandstoneWall,
            BlockKind::WhiteTulip => SimplifiedBlockKind::Flower,
            BlockKind::BlackBed => SimplifiedBlockKind::Bed,
            BlockKind::JungleWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::PinkStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::RawIronBlock => SimplifiedBlockKind::RawIronBlock,
            BlockKind::PinkStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::DeepslateTileWall => SimplifiedBlockKind::DeepslateTileWall,
            BlockKind::InfestedDeepslate => SimplifiedBlockKind::InfestedDeepslate,
            BlockKind::GreenCandleCake => SimplifiedBlockKind::GreenCandleCake,
            BlockKind::PottedRedMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::GrayGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::RawGoldBlock => SimplifiedBlockKind::RawGoldBlock,
            BlockKind::LightGrayCandle => SimplifiedBlockKind::LightGrayCandle,
            BlockKind::RedSandstone => SimplifiedBlockKind::RedSandstone,
            BlockKind::OrangeTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::WhiteStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::Tnt => SimplifiedBlockKind::Tnt,
            BlockKind::CrimsonDoor => SimplifiedBlockKind::CrimsonDoor,
            BlockKind::SugarCane => SimplifiedBlockKind::SugarCane,
            BlockKind::BlackstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::EndGateway => SimplifiedBlockKind::EndGateway,
            BlockKind::LightGrayBanner => SimplifiedBlockKind::Banner,
            BlockKind::Cobblestone => SimplifiedBlockKind::Cobblestone,
            BlockKind::WarpedWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::PottedDeadBush => SimplifiedBlockKind::PottedDeadBush,
            BlockKind::RedstoneLamp => SimplifiedBlockKind::RedstoneLamp,
            BlockKind::PinkCandleCake => SimplifiedBlockKind::PinkCandleCake,
            BlockKind::SoulCampfire => SimplifiedBlockKind::SoulCampfire,
            BlockKind::GreenBed => SimplifiedBlockKind::Bed,
            BlockKind::WaxedExposedCopper => SimplifiedBlockKind::WaxedExposedCopper,
            BlockKind::SeaLantern => SimplifiedBlockKind::SeaLantern,
            BlockKind::PinkWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::Granite => SimplifiedBlockKind::Granite,
            BlockKind::DeadBush => SimplifiedBlockKind::DeadBush,
            BlockKind::Wheat => SimplifiedBlockKind::Wheat,
            BlockKind::Candle => SimplifiedBlockKind::Candle,
            BlockKind::HeavyWeightedPressurePlate => {
                SimplifiedBlockKind::HeavyWeightedPressurePlate
            }
            BlockKind::Glass => SimplifiedBlockKind::Glass,
            BlockKind::BlackStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::CyanShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::InfestedChiseledStoneBricks => {
                SimplifiedBlockKind::InfestedChiseledStoneBricks
            }
            BlockKind::RedSand => SimplifiedBlockKind::RedSand,
            BlockKind::CrimsonHyphae => SimplifiedBlockKind::CrimsonHyphae,
            BlockKind::DeepslateCoalOre => SimplifiedBlockKind::DeepslateCoalOre,
            BlockKind::PinkConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::FireCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::Jigsaw => SimplifiedBlockKind::Jigsaw,
            BlockKind::BlackStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::DioriteWall => SimplifiedBlockKind::DioriteWall,
            BlockKind::BirchButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::RedNetherBricks => SimplifiedBlockKind::RedNetherBricks,
            BlockKind::Sandstone => SimplifiedBlockKind::Sandstone,
            BlockKind::AndesiteSlab => SimplifiedBlockKind::Slab,
            BlockKind::OakTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::BrownMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::CyanGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::WarpedRoots => SimplifiedBlockKind::WarpedRoots,
            BlockKind::IronOre => SimplifiedBlockKind::IronOre,
            BlockKind::PottedPoppy => SimplifiedBlockKind::PottedPoppy,
            BlockKind::CrimsonRoots => SimplifiedBlockKind::CrimsonRoots,
            BlockKind::OakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::DeadBrainCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::PurpurSlab => SimplifiedBlockKind::Slab,
            BlockKind::RedShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::Piston => SimplifiedBlockKind::Piston,
            BlockKind::InfestedStone => SimplifiedBlockKind::InfestedStone,
            BlockKind::QuartzStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DeadTubeCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::WhiteWool => SimplifiedBlockKind::Wool,
            BlockKind::StoneBricks => SimplifiedBlockKind::StoneBricks,
            BlockKind::HoneyBlock => SimplifiedBlockKind::HoneyBlock,
            BlockKind::PurpleCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::IronDoor => SimplifiedBlockKind::IronDoor,
            BlockKind::StrippedAcaciaWood => SimplifiedBlockKind::Log,
            BlockKind::BrickWall => SimplifiedBlockKind::BrickWall,
            BlockKind::PolishedBlackstoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::TubeCoral => SimplifiedBlockKind::Coral,
            BlockKind::PurpleStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::DeadFireCoral => SimplifiedBlockKind::Coral,
            BlockKind::LavaCauldron => SimplifiedBlockKind::LavaCauldron,
            BlockKind::WarpedSlab => SimplifiedBlockKind::Slab,
            BlockKind::BubbleCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::LimeBed => SimplifiedBlockKind::Bed,
            BlockKind::QuartzBricks => SimplifiedBlockKind::QuartzBricks,
            BlockKind::CutRedSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::Prismarine => SimplifiedBlockKind::Prismarine,
            BlockKind::PrismarineBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::SprucePlanks => SimplifiedBlockKind::Planks,
            BlockKind::JackOLantern => SimplifiedBlockKind::JackOLantern,
            BlockKind::BlueCandleCake => SimplifiedBlockKind::BlueCandleCake,
            BlockKind::StoneBrickWall => SimplifiedBlockKind::StoneBrickWall,
            BlockKind::GrayShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::OrangeCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::LargeAmethystBud => SimplifiedBlockKind::LargeAmethystBud,
            BlockKind::OakButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::OakWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::EmeraldOre => SimplifiedBlockKind::EmeraldOre,
            BlockKind::SmoothQuartzStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CutCopper => SimplifiedBlockKind::CutCopper,
            BlockKind::BubbleCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::PinkShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::DiamondBlock => SimplifiedBlockKind::DiamondBlock,
            BlockKind::PurpurStairs => SimplifiedBlockKind::Stairs,
            BlockKind::OrangeStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::CrimsonPlanks => SimplifiedBlockKind::Planks,
            BlockKind::EndPortal => SimplifiedBlockKind::EndPortal,
            BlockKind::OxidizedCutCopper => SimplifiedBlockKind::OxidizedCutCopper,
            BlockKind::CyanConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::DeepslateBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::MelonStem => SimplifiedBlockKind::MelonStem,
            BlockKind::LightGrayCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::ZombieHead => SimplifiedBlockKind::ZombieHead,
            BlockKind::BirchWood => SimplifiedBlockKind::Log,
            BlockKind::PurpleConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::Torch => SimplifiedBlockKind::Torch,
            BlockKind::Grass => SimplifiedBlockKind::Grass,
            BlockKind::FireCoral => SimplifiedBlockKind::Coral,
            BlockKind::StrippedWarpedStem => SimplifiedBlockKind::StrippedWarpedStem,
            BlockKind::CrackedDeepslateTiles => SimplifiedBlockKind::CrackedDeepslateTiles,
            BlockKind::CaveVines => SimplifiedBlockKind::CaveVines,
            BlockKind::DarkOakPlanks => SimplifiedBlockKind::Planks,
            BlockKind::ShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::PurpurBlock => SimplifiedBlockKind::PurpurBlock,
            BlockKind::DeadBubbleCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::Dropper => SimplifiedBlockKind::Dropper,
            BlockKind::MagentaCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::GreenGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::YellowBanner => SimplifiedBlockKind::Banner,
            BlockKind::OrangeWool => SimplifiedBlockKind::Wool,
            BlockKind::PurpurPillar => SimplifiedBlockKind::PurpurPillar,
            BlockKind::SmoothStone => SimplifiedBlockKind::SmoothStone,
            BlockKind::YellowStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::Snow => SimplifiedBlockKind::Snow,
            BlockKind::OakLog => SimplifiedBlockKind::Log,
            BlockKind::Stonecutter => SimplifiedBlockKind::Stonecutter,
            BlockKind::Barrel => SimplifiedBlockKind::Barrel,
            BlockKind::StoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::HornCoral => SimplifiedBlockKind::Coral,
            BlockKind::RedCandle => SimplifiedBlockKind::RedCandle,
            BlockKind::BlastFurnace => SimplifiedBlockKind::BlastFurnace,
            BlockKind::Diorite => SimplifiedBlockKind::Diorite,
            BlockKind::YellowStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::LightGrayStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::BirchDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::RedCandleCake => SimplifiedBlockKind::RedCandleCake,
            BlockKind::PottedWhiteTulip => SimplifiedBlockKind::Flower,
            BlockKind::OakSlab => SimplifiedBlockKind::Slab,
            BlockKind::NetherBrickWall => SimplifiedBlockKind::NetherBrickWall,
            BlockKind::StrippedJungleWood => SimplifiedBlockKind::Log,
            BlockKind::Repeater => SimplifiedBlockKind::Repeater,
            BlockKind::GoldBlock => SimplifiedBlockKind::GoldBlock,
            BlockKind::WarpedSign => SimplifiedBlockKind::Sign,
            BlockKind::NetherPortal => SimplifiedBlockKind::NetherPortal,
            BlockKind::CobblestoneWall => SimplifiedBlockKind::CobblestoneWall,
            BlockKind::CreeperHead => SimplifiedBlockKind::CreeperHead,
            BlockKind::EndRod => SimplifiedBlockKind::EndRod,
            BlockKind::WhiteWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::PinkWool => SimplifiedBlockKind::Wool,
            BlockKind::WhiteStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::OrangeConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::PottedBrownMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::SpruceFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::SprucePressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::BambooSapling => SimplifiedBlockKind::Sapling,
            BlockKind::GrayCandleCake => SimplifiedBlockKind::GrayCandleCake,
            BlockKind::RedstoneBlock => SimplifiedBlockKind::RedstoneBlock,
            BlockKind::PolishedDiorite => SimplifiedBlockKind::PolishedDiorite,
            BlockKind::BeeNest => SimplifiedBlockKind::BeeNest,
            BlockKind::Blackstone => SimplifiedBlockKind::Blackstone,
            BlockKind::JungleStairs => SimplifiedBlockKind::Stairs,
            BlockKind::MossyCobblestoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CopperBlock => SimplifiedBlockKind::CopperBlock,
            BlockKind::CyanCandle => SimplifiedBlockKind::CyanCandle,
            BlockKind::PurpleGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::ExposedCopper => SimplifiedBlockKind::ExposedCopper,
            BlockKind::WeatheredCutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::Scaffolding => SimplifiedBlockKind::Scaffolding,
            BlockKind::BirchSlab => SimplifiedBlockKind::Slab,
            BlockKind::PottedBamboo => SimplifiedBlockKind::PottedBamboo,
            BlockKind::CrimsonButton => SimplifiedBlockKind::CrimsonButton,
            BlockKind::YellowConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::RedWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::RedstoneTorch => SimplifiedBlockKind::RedstoneTorch,
            BlockKind::DeepslateRedstoneOre => SimplifiedBlockKind::DeepslateRedstoneOre,
            BlockKind::SpruceWood => SimplifiedBlockKind::Log,
            BlockKind::AcaciaSlab => SimplifiedBlockKind::Slab,
            BlockKind::JungleLog => SimplifiedBlockKind::Log,
            BlockKind::LightBlueStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::Gravel => SimplifiedBlockKind::Gravel,
            BlockKind::EndStone => SimplifiedBlockKind::EndStone,
            BlockKind::BirchWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::QuartzPillar => SimplifiedBlockKind::QuartzPillar,
            BlockKind::RootedDirt => SimplifiedBlockKind::RootedDirt,
            BlockKind::MediumAmethystBud => SimplifiedBlockKind::MediumAmethystBud,
            BlockKind::SandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::WhiteCandle => SimplifiedBlockKind::WhiteCandle,
            BlockKind::BirchFence => SimplifiedBlockKind::Fence,
            BlockKind::MossBlock => SimplifiedBlockKind::MossBlock,
            BlockKind::PurpleCandle => SimplifiedBlockKind::PurpleCandle,
            BlockKind::EndPortalFrame => SimplifiedBlockKind::EndPortalFrame,
            BlockKind::OrangeBed => SimplifiedBlockKind::Bed,
            BlockKind::DeepslateGoldOre => SimplifiedBlockKind::DeepslateGoldOre,
            BlockKind::LimeBanner => SimplifiedBlockKind::Banner,
            BlockKind::DeepslateBricks => SimplifiedBlockKind::DeepslateBricks,
            BlockKind::LilyOfTheValley => SimplifiedBlockKind::LilyOfTheValley,
            BlockKind::CrackedPolishedBlackstoneBricks => {
                SimplifiedBlockKind::CrackedPolishedBlackstoneBricks
            }
            BlockKind::StrippedSpruceWood => SimplifiedBlockKind::Log,
            BlockKind::RedBanner => SimplifiedBlockKind::Banner,
            BlockKind::MagentaConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::SpruceFence => SimplifiedBlockKind::Fence,
            BlockKind::Composter => SimplifiedBlockKind::Composter,
            BlockKind::BrainCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::Rail => SimplifiedBlockKind::Rail,
            BlockKind::PottedAzureBluet => SimplifiedBlockKind::Flower,
            BlockKind::JungleFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::Lectern => SimplifiedBlockKind::Lectern,
            BlockKind::LightGrayConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::Lodestone => SimplifiedBlockKind::Lodestone,
            BlockKind::LightGrayBed => SimplifiedBlockKind::Bed,
            BlockKind::ExposedCutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DarkOakTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::RedNetherBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DiamondOre => SimplifiedBlockKind::DiamondOre,
            BlockKind::YellowCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::ChippedAnvil => SimplifiedBlockKind::Anvil,
            BlockKind::GreenStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::CyanStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::NetherBrickFence => SimplifiedBlockKind::Fence,
            BlockKind::BlackConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::PinkCandle => SimplifiedBlockKind::PinkCandle,
            BlockKind::CryingObsidian => SimplifiedBlockKind::CryingObsidian,
            BlockKind::LightBlueCandle => SimplifiedBlockKind::LightBlueCandle,
            BlockKind::NetherGoldOre => SimplifiedBlockKind::NetherGoldOre,
            BlockKind::BrownCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::PinkConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::PolishedGranite => SimplifiedBlockKind::PolishedGranite,
            BlockKind::GreenWool => SimplifiedBlockKind::Wool,
            BlockKind::DeepslateEmeraldOre => SimplifiedBlockKind::DeepslateEmeraldOre,
            BlockKind::SkeletonSkull => SimplifiedBlockKind::SkeletonSkull,
            BlockKind::ChiseledPolishedBlackstone => {
                SimplifiedBlockKind::ChiseledPolishedBlackstone
            }
            BlockKind::IronTrapdoor => SimplifiedBlockKind::IronTrapdoor,
            BlockKind::EmeraldBlock => SimplifiedBlockKind::EmeraldBlock,
            BlockKind::BlueCandle => SimplifiedBlockKind::BlueCandle,
            BlockKind::SoulSoil => SimplifiedBlockKind::SoulSoil,
            BlockKind::MossyStoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::PolishedDeepslateWall => SimplifiedBlockKind::PolishedDeepslateWall,
            BlockKind::Dispenser => SimplifiedBlockKind::Dispenser,
            BlockKind::Farmland => SimplifiedBlockKind::Farmland,
            BlockKind::Peony => SimplifiedBlockKind::Peony,
            BlockKind::PowderSnowCauldron => SimplifiedBlockKind::PowderSnowCauldron,
            BlockKind::DeepslateLapisOre => SimplifiedBlockKind::DeepslateLapisOre,
            BlockKind::CyanWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::CobblestoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::NetherQuartzOre => SimplifiedBlockKind::NetherQuartzOre,
            BlockKind::PottedDarkOakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::RedStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::InfestedStoneBricks => SimplifiedBlockKind::InfestedStoneBricks,
            BlockKind::LightBlueShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::Mycelium => SimplifiedBlockKind::Mycelium,
            BlockKind::HayBlock => SimplifiedBlockKind::HayBlock,
            BlockKind::FireCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::MossCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::WhiteBanner => SimplifiedBlockKind::Banner,
            BlockKind::RedCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::BrownWool => SimplifiedBlockKind::Wool,
            BlockKind::SmoothQuartzSlab => SimplifiedBlockKind::Slab,
            BlockKind::RoseBush => SimplifiedBlockKind::RoseBush,
            BlockKind::GildedBlackstone => SimplifiedBlockKind::GildedBlackstone,
            BlockKind::CrimsonStem => SimplifiedBlockKind::CrimsonStem,
            BlockKind::InfestedCrackedStoneBricks => {
                SimplifiedBlockKind::InfestedCrackedStoneBricks
            }
            BlockKind::JunglePlanks => SimplifiedBlockKind::Planks,
            BlockKind::BlackCandleCake => SimplifiedBlockKind::BlackCandleCake,
            BlockKind::MossyCobblestoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::YellowCandle => SimplifiedBlockKind::YellowCandle,
            BlockKind::PurpleStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::Seagrass => SimplifiedBlockKind::Seagrass,
            BlockKind::WaxedCopperBlock => SimplifiedBlockKind::WaxedCopperBlock,
            BlockKind::ChiseledQuartzBlock => SimplifiedBlockKind::ChiseledQuartzBlock,
            BlockKind::PrismarineSlab => SimplifiedBlockKind::Slab,
            BlockKind::PurpleWool => SimplifiedBlockKind::Wool,
            BlockKind::PottedBlueOrchid => SimplifiedBlockKind::Flower,
            BlockKind::QuartzSlab => SimplifiedBlockKind::Slab,
            BlockKind::Basalt => SimplifiedBlockKind::Basalt,
            BlockKind::YellowWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::Light => SimplifiedBlockKind::Light,
            BlockKind::SnowBlock => SimplifiedBlockKind::SnowBlock,
            BlockKind::Lilac => SimplifiedBlockKind::Lilac,
            BlockKind::OrangeCandleCake => SimplifiedBlockKind::OrangeCandleCake,
            BlockKind::DeadHornCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::StructureBlock => SimplifiedBlockKind::StructureBlock,
            BlockKind::TubeCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::WaxedExposedCutCopper => SimplifiedBlockKind::WaxedExposedCutCopper,
            BlockKind::BirchPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::LightGrayWool => SimplifiedBlockKind::Wool,
            BlockKind::Podzol => SimplifiedBlockKind::Podzol,
            BlockKind::PlayerHead => SimplifiedBlockKind::PlayerHead,
            BlockKind::Cobweb => SimplifiedBlockKind::Cobweb,
            BlockKind::YellowGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::OakPlanks => SimplifiedBlockKind::Planks,
            BlockKind::BlueBanner => SimplifiedBlockKind::Banner,
            BlockKind::DeepslateBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::LimeStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::LightBlueGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::BrainCoral => SimplifiedBlockKind::Coral,
            BlockKind::SpruceLog => SimplifiedBlockKind::Log,
            BlockKind::YellowConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::Allium => SimplifiedBlockKind::Flower,
            BlockKind::CrimsonFungus => SimplifiedBlockKind::CrimsonFungus,
            BlockKind::PolishedBlackstoneBrickWall => {
                SimplifiedBlockKind::PolishedBlackstoneBrickWall
            }
            BlockKind::CyanStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::DeadFireCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::AncientDebris => SimplifiedBlockKind::AncientDebris,
            BlockKind::PottedCornflower => SimplifiedBlockKind::PottedCornflower,
            BlockKind::RedSandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PackedIce => SimplifiedBlockKind::PackedIce,
            BlockKind::PottedCrimsonRoots => SimplifiedBlockKind::PottedCrimsonRoots,
            BlockKind::SkeletonWallSkull => SimplifiedBlockKind::SkeletonWallSkull,
            BlockKind::Barrier => SimplifiedBlockKind::Barrier,
            BlockKind::CutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::Bedrock => SimplifiedBlockKind::Bedrock,
            BlockKind::Azalea => SimplifiedBlockKind::Azalea,
            BlockKind::SpruceButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::StructureVoid => SimplifiedBlockKind::StructureVoid,
            BlockKind::LightGrayCandleCake => SimplifiedBlockKind::LightGrayCandleCake,
            BlockKind::NetherWart => SimplifiedBlockKind::NetherWart,
            BlockKind::StrippedCrimsonStem => SimplifiedBlockKind::StrippedCrimsonStem,
            BlockKind::WallTorch => SimplifiedBlockKind::WallTorch,
            BlockKind::GlowLichen => SimplifiedBlockKind::GlowLichen,
            BlockKind::BlackTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::CrackedNetherBricks => SimplifiedBlockKind::CrackedNetherBricks,
            BlockKind::WarpedFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::PolishedBlackstoneWall => SimplifiedBlockKind::PolishedBlackstoneWall,
            BlockKind::BirchSign => SimplifiedBlockKind::Sign,
            BlockKind::PottedCactus => SimplifiedBlockKind::PottedCactus,
            BlockKind::BlueShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::CoarseDirt => SimplifiedBlockKind::CoarseDirt,
            BlockKind::TwistingVinesPlant => SimplifiedBlockKind::TwistingVinesPlant,
            BlockKind::TallSeagrass => SimplifiedBlockKind::TallSeagrass,
            BlockKind::WaxedOxidizedCopper => SimplifiedBlockKind::WaxedOxidizedCopper,
            BlockKind::BlackBanner => SimplifiedBlockKind::Banner,
            BlockKind::SoulTorch => SimplifiedBlockKind::SoulTorch,
            BlockKind::CobbledDeepslateSlab => SimplifiedBlockKind::Slab,
            BlockKind::WarpedDoor => SimplifiedBlockKind::WarpedDoor,
            BlockKind::ChiseledDeepslate => SimplifiedBlockKind::ChiseledDeepslate,
            BlockKind::BuddingAmethyst => SimplifiedBlockKind::BuddingAmethyst,
            BlockKind::Lava => SimplifiedBlockKind::Lava,
            BlockKind::Potatoes => SimplifiedBlockKind::Potatoes,
            BlockKind::AzureBluet => SimplifiedBlockKind::Flower,
            BlockKind::RedConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::RedGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::Netherrack => SimplifiedBlockKind::Netherrack,
            BlockKind::BlackWool => SimplifiedBlockKind::Wool,
            BlockKind::WaxedWeatheredCutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::RespawnAnchor => SimplifiedBlockKind::RespawnAnchor,
            BlockKind::Andesite => SimplifiedBlockKind::Andesite,
            BlockKind::BrewingStand => SimplifiedBlockKind::BrewingStand,
            BlockKind::YellowShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::GreenConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::LimeWool => SimplifiedBlockKind::Wool,
            BlockKind::Bricks => SimplifiedBlockKind::Bricks,
            BlockKind::RedSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::MossyStoneBricks => SimplifiedBlockKind::MossyStoneBricks,
            BlockKind::DeadFireCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::DarkOakDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::OakFence => SimplifiedBlockKind::Fence,
            BlockKind::Sunflower => SimplifiedBlockKind::Sunflower,
            BlockKind::GrayStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::BlueWool => SimplifiedBlockKind::Wool,
            BlockKind::ChiseledSandstone => SimplifiedBlockKind::ChiseledSandstone,
            BlockKind::AcaciaLog => SimplifiedBlockKind::Log,
            BlockKind::GraniteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CyanCandleCake => SimplifiedBlockKind::CyanCandleCake,
            BlockKind::OrangeShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::MossyCobblestoneWall => SimplifiedBlockKind::MossyCobblestoneWall,
            BlockKind::BlueIce => SimplifiedBlockKind::BlueIce,
            BlockKind::DeepslateBrickWall => SimplifiedBlockKind::DeepslateBrickWall,
            BlockKind::FloweringAzaleaLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::OakStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PinkTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::TubeCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::GrassBlock => SimplifiedBlockKind::GrassBlock,
            BlockKind::AzaleaLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::Melon => SimplifiedBlockKind::Melon,
            BlockKind::WhiteConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::PurpleTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::SculkSensor => SimplifiedBlockKind::SculkSensor,
            BlockKind::CyanWool => SimplifiedBlockKind::Wool,
            BlockKind::WarpedTrapdoor => SimplifiedBlockKind::WarpedTrapdoor,
            BlockKind::SporeBlossom => SimplifiedBlockKind::SporeBlossom,
            BlockKind::Bookshelf => SimplifiedBlockKind::Bookshelf,
            BlockKind::PottedFern => SimplifiedBlockKind::PottedFern,
            BlockKind::EndStoneBrickWall => SimplifiedBlockKind::EndStoneBrickWall,
            BlockKind::FletchingTable => SimplifiedBlockKind::FletchingTable,
            BlockKind::BlueStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::BrownCandle => SimplifiedBlockKind::BrownCandle,
            BlockKind::Carrots => SimplifiedBlockKind::Carrots,
            BlockKind::LightBlueWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::StrippedDarkOakLog => SimplifiedBlockKind::Log,
            BlockKind::Hopper => SimplifiedBlockKind::Hopper,
            BlockKind::PolishedDioriteSlab => SimplifiedBlockKind::Slab,
            BlockKind::TripwireHook => SimplifiedBlockKind::TripwireHook,
            BlockKind::AcaciaDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::NetheriteBlock => SimplifiedBlockKind::NetheriteBlock,
            BlockKind::WitherSkeletonWallSkull => SimplifiedBlockKind::WitherSkeletonWallSkull,
            BlockKind::AcaciaFence => SimplifiedBlockKind::Fence,
            BlockKind::DeepslateIronOre => SimplifiedBlockKind::DeepslateIronOre,
            BlockKind::Dandelion => SimplifiedBlockKind::Flower,
            BlockKind::BrownBed => SimplifiedBlockKind::Bed,
            BlockKind::BrownMushroomBlock => SimplifiedBlockKind::BrownMushroomBlock,
            BlockKind::DeadBubbleCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::BlueConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::Fern => SimplifiedBlockKind::Fern,
            BlockKind::GreenBanner => SimplifiedBlockKind::Banner,
            BlockKind::JungleTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::PolishedBlackstoneButton => SimplifiedBlockKind::PolishedBlackstoneButton,
            BlockKind::InfestedMossyStoneBricks => SimplifiedBlockKind::InfestedMossyStoneBricks,
            BlockKind::WeatheredCopper => SimplifiedBlockKind::WeatheredCopper,
            BlockKind::GrayConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::StoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::AmethystBlock => SimplifiedBlockKind::AmethystBlock,
            BlockKind::SandstoneWall => SimplifiedBlockKind::SandstoneWall,
            BlockKind::LightBlueBed => SimplifiedBlockKind::Bed,
            BlockKind::EnchantingTable => SimplifiedBlockKind::EnchantingTable,
            BlockKind::DioriteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CoalBlock => SimplifiedBlockKind::CoalBlock,
            BlockKind::HangingRoots => SimplifiedBlockKind::HangingRoots,
            BlockKind::Spawner => SimplifiedBlockKind::Spawner,
            BlockKind::LightBlueConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::WhiteCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::LimeCandleCake => SimplifiedBlockKind::LimeCandleCake,
            BlockKind::JungleButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::PottedWarpedRoots => SimplifiedBlockKind::PottedWarpedRoots,
            BlockKind::PolishedAndesiteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::WarpedFungus => SimplifiedBlockKind::WarpedFungus,
            BlockKind::Beacon => SimplifiedBlockKind::Beacon,
            BlockKind::LightGrayConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::PinkTulip => SimplifiedBlockKind::Flower,
            BlockKind::NetherSprouts => SimplifiedBlockKind::NetherSprouts,
            BlockKind::MossyStoneBrickWall => SimplifiedBlockKind::MossyStoneBrickWall,
            BlockKind::LightBlueCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::PointedDripstone => SimplifiedBlockKind::PointedDripstone,
            BlockKind::RedMushroomBlock => SimplifiedBlockKind::RedMushroomBlock,
            BlockKind::CyanTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::PottedJungleSapling => SimplifiedBlockKind::Sapling,
            BlockKind::WaxedCutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::BoneBlock => SimplifiedBlockKind::BoneBlock,
            BlockKind::CaveVinesPlant => SimplifiedBlockKind::CaveVinesPlant,
            BlockKind::NetherWartBlock => SimplifiedBlockKind::NetherWartBlock,
            BlockKind::WaterCauldron => SimplifiedBlockKind::WaterCauldron,
            BlockKind::BrownGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::FireCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::Lever => SimplifiedBlockKind::Lever,
            BlockKind::BlackstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::PurpleCandleCake => SimplifiedBlockKind::PurpleCandleCake,
            BlockKind::AcaciaWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::LightBlueCandleCake => SimplifiedBlockKind::LightBlueCandleCake,
            BlockKind::DripstoneBlock => SimplifiedBlockKind::DripstoneBlock,
            BlockKind::AmethystCluster => SimplifiedBlockKind::AmethystCluster,
            BlockKind::DeadFireCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::DarkOakButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::DeadTubeCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::FloweringAzalea => SimplifiedBlockKind::FloweringAzalea,
            BlockKind::LimeGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::Bell => SimplifiedBlockKind::Bell,
            BlockKind::AttachedMelonStem => SimplifiedBlockKind::AttachedMelonStem,
            BlockKind::AcaciaButton => SimplifiedBlockKind::WoodenButton,
            BlockKind::BrownConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::CraftingTable => SimplifiedBlockKind::CraftingTable,
            BlockKind::DarkOakFence => SimplifiedBlockKind::Fence,
            BlockKind::Observer => SimplifiedBlockKind::Observer,
            BlockKind::RedBed => SimplifiedBlockKind::Bed,
            BlockKind::YellowTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::LargeFern => SimplifiedBlockKind::LargeFern,
            BlockKind::ChorusFlower => SimplifiedBlockKind::ChorusFlower,
            BlockKind::SmoothRedSandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DarkOakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::StrippedDarkOakWood => SimplifiedBlockKind::Log,
            BlockKind::PolishedDeepslate => SimplifiedBlockKind::PolishedDeepslate,
            BlockKind::WarpedButton => SimplifiedBlockKind::WarpedButton,
            BlockKind::DarkOakSign => SimplifiedBlockKind::Sign,
            BlockKind::LightGrayWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::StrippedOakLog => SimplifiedBlockKind::Log,
            BlockKind::GreenTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::StickyPiston => SimplifiedBlockKind::StickyPiston,
            BlockKind::CreeperWallHead => SimplifiedBlockKind::CreeperWallHead,
            BlockKind::LightGrayGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::DamagedAnvil => SimplifiedBlockKind::Anvil,
            BlockKind::PolishedDioriteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::NoteBlock => SimplifiedBlockKind::NoteBlock,
            BlockKind::GreenShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::PottedOrangeTulip => SimplifiedBlockKind::Flower,
            BlockKind::BubbleColumn => SimplifiedBlockKind::BubbleColumn,
            BlockKind::CobbledDeepslateWall => SimplifiedBlockKind::CobbledDeepslateWall,
            BlockKind::WeatheredCutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::AcaciaTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::LapisOre => SimplifiedBlockKind::LapisOre,
            BlockKind::DeepslateTileSlab => SimplifiedBlockKind::Slab,
            BlockKind::BlackGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::WhiteGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::DarkOakLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::WaxedCutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::MagmaBlock => SimplifiedBlockKind::MagmaBlock,
            BlockKind::SpruceSign => SimplifiedBlockKind::Sign,
            BlockKind::SmoothStoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::OakPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::DarkOakLog => SimplifiedBlockKind::Log,
            BlockKind::WaxedOxidizedCutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::LightBlueWool => SimplifiedBlockKind::Wool,
            BlockKind::OrangeBanner => SimplifiedBlockKind::Banner,
            BlockKind::SmoothRedSandstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::PrismarineWall => SimplifiedBlockKind::PrismarineWall,
            BlockKind::NetherBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::GraniteSlab => SimplifiedBlockKind::Slab,
            BlockKind::Water => SimplifiedBlockKind::Water,
            BlockKind::PolishedBasalt => SimplifiedBlockKind::PolishedBasalt,
            BlockKind::ChiseledNetherBricks => SimplifiedBlockKind::ChiseledNetherBricks,
            BlockKind::CobbledDeepslate => SimplifiedBlockKind::CobbledDeepslate,
            BlockKind::LilyPad => SimplifiedBlockKind::LilyPad,
            BlockKind::SmallDripleaf => SimplifiedBlockKind::SmallDripleaf,
            BlockKind::WhiteShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::BrownWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::Comparator => SimplifiedBlockKind::Comparator,
            BlockKind::CrimsonStairs => SimplifiedBlockKind::Stairs,
            BlockKind::WetSponge => SimplifiedBlockKind::WetSponge,
            BlockKind::PolishedAndesiteSlab => SimplifiedBlockKind::Slab,
            BlockKind::PlayerWallHead => SimplifiedBlockKind::PlayerWallHead,
            BlockKind::SpruceStairs => SimplifiedBlockKind::Stairs,
            BlockKind::OxidizedCopper => SimplifiedBlockKind::OxidizedCopper,
            BlockKind::CrimsonNylium => SimplifiedBlockKind::CrimsonNylium,
            BlockKind::OrangeConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::PrismarineBricks => SimplifiedBlockKind::PrismarineBricks,
            BlockKind::LimeConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::MagentaBed => SimplifiedBlockKind::Bed,
            BlockKind::AcaciaPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::RedStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::DeepslateTiles => SimplifiedBlockKind::DeepslateTiles,
            BlockKind::GrayCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::DeadHornCoral => SimplifiedBlockKind::Coral,
            BlockKind::DioriteSlab => SimplifiedBlockKind::Slab,
            BlockKind::BirchTrapdoor => SimplifiedBlockKind::WoodenTrapdoor,
            BlockKind::RedNetherBrickWall => SimplifiedBlockKind::RedNetherBrickWall,
            BlockKind::Tuff => SimplifiedBlockKind::Tuff,
            BlockKind::OxidizedCutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CutRedSandstone => SimplifiedBlockKind::CutRedSandstone,
            BlockKind::WarpedStairs => SimplifiedBlockKind::Stairs,
            BlockKind::LightBlueStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::EndStoneBrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::MagentaWool => SimplifiedBlockKind::Wool,
            BlockKind::SmoothRedSandstone => SimplifiedBlockKind::SmoothRedSandstone,
            BlockKind::GreenCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::SweetBerryBush => SimplifiedBlockKind::SweetBerryBush,
            BlockKind::Ladder => SimplifiedBlockKind::Ladder,
            BlockKind::CrimsonFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::WhiteBed => SimplifiedBlockKind::Bed,
            BlockKind::Fire => SimplifiedBlockKind::Fire,
            BlockKind::GrayWool => SimplifiedBlockKind::Wool,
            BlockKind::TurtleEgg => SimplifiedBlockKind::TurtleEgg,
            BlockKind::EndStoneBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::Air => SimplifiedBlockKind::Air,
            BlockKind::BlackstoneWall => SimplifiedBlockKind::BlackstoneWall,
            BlockKind::Deepslate => SimplifiedBlockKind::Deepslate,
            BlockKind::PottedPinkTulip => SimplifiedBlockKind::Flower,
            BlockKind::SlimeBlock => SimplifiedBlockKind::SlimeBlock,
            BlockKind::ExposedCutCopper => SimplifiedBlockKind::ExposedCutCopper,
            BlockKind::WaxedWeatheredCutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::CrimsonPressurePlate => SimplifiedBlockKind::CrimsonPressurePlate,
            BlockKind::GrayWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::Cactus => SimplifiedBlockKind::Cactus,
            BlockKind::PolishedDeepslateSlab => SimplifiedBlockKind::Slab,
            BlockKind::HornCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::StrippedOakWood => SimplifiedBlockKind::Log,
            BlockKind::DragonHead => SimplifiedBlockKind::DragonHead,
            BlockKind::DarkOakPressurePlate => SimplifiedBlockKind::WoodenPressurePlate,
            BlockKind::QuartzBlock => SimplifiedBlockKind::QuartzBlock,
            BlockKind::SpruceDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::TallGrass => SimplifiedBlockKind::TallGrass,
            BlockKind::MagentaConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::WhiteConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::GrayBed => SimplifiedBlockKind::Bed,
            BlockKind::OakDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::DeepslateTileStairs => SimplifiedBlockKind::Stairs,
            BlockKind::OakSign => SimplifiedBlockKind::Sign,
            BlockKind::LimeWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::Loom => SimplifiedBlockKind::Loom,
            BlockKind::StrippedSpruceLog => SimplifiedBlockKind::Log,
            BlockKind::BlackCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::SmoothSandstone => SimplifiedBlockKind::SmoothSandstone,
            BlockKind::PolishedBlackstonePressurePlate => {
                SimplifiedBlockKind::PolishedBlackstonePressurePlate
            }
            BlockKind::HoneycombBlock => SimplifiedBlockKind::HoneycombBlock,
            BlockKind::PinkBanner => SimplifiedBlockKind::Banner,
            BlockKind::Poppy => SimplifiedBlockKind::Flower,
            BlockKind::PolishedGraniteSlab => SimplifiedBlockKind::Slab,
            BlockKind::DarkOakStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PrismarineStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DarkOakSlab => SimplifiedBlockKind::Slab,
            BlockKind::WaxedOxidizedCutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::DarkOakWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::BlueWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::PurpleWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::BlueStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::RedTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::BrickStairs => SimplifiedBlockKind::Stairs,
            BlockKind::RedstoneWire => SimplifiedBlockKind::RedstoneWire,
            BlockKind::PottedOakSapling => SimplifiedBlockKind::Sapling,
            BlockKind::BrownConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::WarpedNylium => SimplifiedBlockKind::WarpedNylium,
            BlockKind::Cake => SimplifiedBlockKind::Cake,
            BlockKind::GrayBanner => SimplifiedBlockKind::Banner,
            BlockKind::RedMushroom => SimplifiedBlockKind::Mushroom,
            BlockKind::YellowWool => SimplifiedBlockKind::Wool,
            BlockKind::CrimsonWallSign => SimplifiedBlockKind::WallSign,
            BlockKind::Tripwire => SimplifiedBlockKind::Tripwire,
            BlockKind::StonePressurePlate => SimplifiedBlockKind::StonePressurePlate,
            BlockKind::MagentaBanner => SimplifiedBlockKind::Banner,
            BlockKind::WarpedFence => SimplifiedBlockKind::Fence,
            BlockKind::OxidizedCutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::BlueCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::PottedCrimsonFungus => SimplifiedBlockKind::PottedCrimsonFungus,
            BlockKind::RedTulip => SimplifiedBlockKind::Flower,
            BlockKind::BlueTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::JungleLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::BlackConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::Dirt => SimplifiedBlockKind::Dirt,
            BlockKind::AcaciaStairs => SimplifiedBlockKind::Stairs,
            BlockKind::BirchStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PinkCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::ChorusPlant => SimplifiedBlockKind::ChorusPlant,
            BlockKind::BrownCandleCake => SimplifiedBlockKind::BrownCandleCake,
            BlockKind::DeepslateCopperOre => SimplifiedBlockKind::DeepslateCopperOre,
            BlockKind::WaxedExposedCutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PottedAcaciaSapling => SimplifiedBlockKind::Sapling,
            BlockKind::OrangeWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::HornCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::DetectorRail => SimplifiedBlockKind::DetectorRail,
            BlockKind::IronBlock => SimplifiedBlockKind::IronBlock,
            BlockKind::LightBlueTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::GrayStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::LightBlueConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::TrappedChest => SimplifiedBlockKind::TrappedChest,
            BlockKind::CrimsonSign => SimplifiedBlockKind::Sign,
            BlockKind::CandleCake => SimplifiedBlockKind::CandleCake,
            BlockKind::PurpleConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::StoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::PolishedBlackstoneBricks => SimplifiedBlockKind::PolishedBlackstoneBricks,
            BlockKind::Cauldron => SimplifiedBlockKind::Cauldron,
            BlockKind::RedConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::BrownStainedGlass => SimplifiedBlockKind::StainedGlass,
            BlockKind::CyanCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::WeepingVines => SimplifiedBlockKind::WeepingVines,
            BlockKind::DragonWallHead => SimplifiedBlockKind::DragonWallHead,
            BlockKind::CrimsonSlab => SimplifiedBlockKind::Slab,
            BlockKind::LimeShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::RawCopperBlock => SimplifiedBlockKind::RawCopperBlock,
            BlockKind::PottedWarpedFungus => SimplifiedBlockKind::PottedWarpedFungus,
            BlockKind::DeadBrainCoralWallFan => SimplifiedBlockKind::CoralWallFan,
            BlockKind::WaxedExposedCutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::ExposedCutCopperSlab => SimplifiedBlockKind::Slab,
            BlockKind::Pumpkin => SimplifiedBlockKind::Pumpkin,
            BlockKind::PumpkinStem => SimplifiedBlockKind::PumpkinStem,
            BlockKind::JungleDoor => SimplifiedBlockKind::WoodenDoor,
            BlockKind::GreenWallBanner => SimplifiedBlockKind::WallBanner,
            BlockKind::DeadTubeCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::Obsidian => SimplifiedBlockKind::Obsidian,
            BlockKind::AcaciaSapling => SimplifiedBlockKind::Sapling,
            BlockKind::SandstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::RedWool => SimplifiedBlockKind::Wool,
            BlockKind::BrainCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::Terracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::Vine => SimplifiedBlockKind::Vine,
            BlockKind::CrimsonTrapdoor => SimplifiedBlockKind::CrimsonTrapdoor,
            BlockKind::IronBars => SimplifiedBlockKind::IronBars,
            BlockKind::AcaciaFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::CartographyTable => SimplifiedBlockKind::CartographyTable,
            BlockKind::BubbleCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::CutSandstone => SimplifiedBlockKind::CutSandstone,
            BlockKind::StrippedBirchWood => SimplifiedBlockKind::Log,
            BlockKind::DeadHornCoralBlock => SimplifiedBlockKind::CoralBlock,
            BlockKind::DeadBrainCoral => SimplifiedBlockKind::Coral,
            BlockKind::Glowstone => SimplifiedBlockKind::Glowstone,
            BlockKind::StrippedAcaciaLog => SimplifiedBlockKind::Log,
            BlockKind::AndesiteStairs => SimplifiedBlockKind::Stairs,
            BlockKind::WarpedPressurePlate => SimplifiedBlockKind::WarpedPressurePlate,
            BlockKind::PolishedBlackstoneStairs => SimplifiedBlockKind::Stairs,
            BlockKind::LimeCarpet => SimplifiedBlockKind::Carpet,
            BlockKind::LimeCandle => SimplifiedBlockKind::LimeCandle,
            BlockKind::TintedGlass => SimplifiedBlockKind::TintedGlass,
            BlockKind::BrownTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::EndStoneBricks => SimplifiedBlockKind::EndStoneBricks,
            BlockKind::Ice => SimplifiedBlockKind::Ice,
            BlockKind::WaxedWeatheredCopper => SimplifiedBlockKind::WaxedWeatheredCopper,
            BlockKind::OakLeaves => SimplifiedBlockKind::Leaves,
            BlockKind::PowderSnow => SimplifiedBlockKind::PowderSnow,
            BlockKind::OrangeStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::SpruceSlab => SimplifiedBlockKind::Slab,
            BlockKind::AcaciaSign => SimplifiedBlockKind::Sign,
            BlockKind::CyanBanner => SimplifiedBlockKind::Banner,
            BlockKind::LimeStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::SoulWallTorch => SimplifiedBlockKind::SoulWallTorch,
            BlockKind::OakWood => SimplifiedBlockKind::Log,
            BlockKind::ActivatorRail => SimplifiedBlockKind::ActivatorRail,
            BlockKind::DeadBrainCoralFan => SimplifiedBlockKind::CoralFan,
            BlockKind::PurpleShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::SpruceSapling => SimplifiedBlockKind::Sapling,
            BlockKind::JungleSign => SimplifiedBlockKind::Sign,
            BlockKind::CyanBed => SimplifiedBlockKind::Bed,
            BlockKind::EnderChest => SimplifiedBlockKind::EnderChest,
            BlockKind::Chest => SimplifiedBlockKind::Chest,
            BlockKind::PrismarineBrickSlab => SimplifiedBlockKind::Slab,
            BlockKind::PottedOxeyeDaisy => SimplifiedBlockKind::Flower,
            BlockKind::Anvil => SimplifiedBlockKind::Anvil,
            BlockKind::SoulFire => SimplifiedBlockKind::SoulFire,
            BlockKind::CobbledDeepslateStairs => SimplifiedBlockKind::Stairs,
            BlockKind::GraniteWall => SimplifiedBlockKind::GraniteWall,
            BlockKind::DeadTubeCoral => SimplifiedBlockKind::Coral,
            BlockKind::BubbleCoral => SimplifiedBlockKind::Coral,
            BlockKind::Jukebox => SimplifiedBlockKind::Jukebox,
            BlockKind::CyanConcrete => SimplifiedBlockKind::Concrete,
            BlockKind::TwistingVines => SimplifiedBlockKind::TwistingVines,
            BlockKind::MossyCobblestone => SimplifiedBlockKind::MossyCobblestone,
            BlockKind::BrownShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::LightGrayShulkerBox => SimplifiedBlockKind::ShulkerBox,
            BlockKind::StrippedJungleLog => SimplifiedBlockKind::Log,
            BlockKind::DeepslateDiamondOre => SimplifiedBlockKind::DeepslateDiamondOre,
            BlockKind::LightWeightedPressurePlate => {
                SimplifiedBlockKind::LightWeightedPressurePlate
            }
            BlockKind::BlueGlazedTerracotta => SimplifiedBlockKind::GlazedTeracotta,
            BlockKind::Grindstone => SimplifiedBlockKind::Grindstone,
            BlockKind::DragonEgg => SimplifiedBlockKind::DragonEgg,
            BlockKind::Cornflower => SimplifiedBlockKind::Cornflower,
            BlockKind::CobblestoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::PottedAzaleaBush => SimplifiedBlockKind::PottedAzaleaBush,
            BlockKind::CutCopperStairs => SimplifiedBlockKind::Stairs,
            BlockKind::MovingPiston => SimplifiedBlockKind::MovingPiston,
            BlockKind::CarvedPumpkin => SimplifiedBlockKind::CarvedPumpkin,
            BlockKind::BlueConcretePowder => SimplifiedBlockKind::ConcretePowder,
            BlockKind::CoalOre => SimplifiedBlockKind::CoalOre,
            BlockKind::CopperOre => SimplifiedBlockKind::CopperOre,
            BlockKind::PolishedBlackstoneSlab => SimplifiedBlockKind::Slab,
            BlockKind::WhiteTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::BigDripleaf => SimplifiedBlockKind::BigDripleaf,
            BlockKind::ChainCommandBlock => SimplifiedBlockKind::ChainCommandBlock,
            BlockKind::BrownStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::BirchFenceGate => SimplifiedBlockKind::FenceGate,
            BlockKind::PolishedDeepslateStairs => SimplifiedBlockKind::Stairs,
            BlockKind::BigDripleafStem => SimplifiedBlockKind::BigDripleafStem,
            BlockKind::GreenStainedGlassPane => SimplifiedBlockKind::StainedGlassPane,
            BlockKind::GreenCandle => SimplifiedBlockKind::GreenCandle,
            BlockKind::StoneButton => SimplifiedBlockKind::StoneButton,
            BlockKind::VoidAir => SimplifiedBlockKind::Air,
            BlockKind::ChiseledStoneBricks => SimplifiedBlockKind::ChiseledStoneBricks,
            BlockKind::SmithingTable => SimplifiedBlockKind::SmithingTable,
            BlockKind::MagentaTerracotta => SimplifiedBlockKind::Teracotta,
            BlockKind::AndesiteWall => SimplifiedBlockKind::AndesiteWall,
        }
    }
}
