#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Block {
    Air,
    Stone,
    Granite,
    PolishedGranite,
    Diorite,
    PolishedDiorite,
    Andesite,
    PolishedAndesite,
    Dirt,
    CoarseDirt,
    Cobblestone,
    OakPlanks,
    SprucePlanks,
    BirchPlanks,
    JunglePlanks,
    AcaciaPlanks,
    DarkOakPlanks,
    Bedrock,
    Sand,
    RedSand,
    Gravel,
    GoldOre,
    IronOre,
    CoalOre,
    Sponge,
    WetSponge,
    Glass,
    LapisOre,
    LapisBlock,
    Sandstone,
    ChiseledSandstone,
    CutSandstone,
    Cobweb,
    Grass,
    Fern,
    DeadBush,
    Seagrass,
    WhiteWool,
    OrangeWool,
    MagentaWool,
    LightBlueWool,
    YellowWool,
    LimeWool,
    PinkWool,
    GrayWool,
    LightGrayWool,
    CyanWool,
    PurpleWool,
    BlueWool,
    BrownWool,
    GreenWool,
    RedWool,
    BlackWool,
    Dandelion,
    Poppy,
    BlueOrchid,
    Allium,
    AzureBluet,
    RedTulip,
    OrangeTulip,
    WhiteTulip,
    PinkTulip,
    OxeyeDaisy,
    BrownMushroom,
    RedMushroom,
    GoldBlock,
    IronBlock,
    Bricks,
    Bookshelf,
    MossyCobblestone,
    Obsidian,
    Torch,
    Spawner,
    DiamondOre,
    DiamondBlock,
    CraftingTable,
    Ice,
    SnowBlock,
    Clay,
    Pumpkin,
    Netherrack,
    SoulSand,
    Glowstone,
    WhiteStainedGlass,
    OrangeStainedGlass,
    MagentaStainedGlass,
    LightBlueStainedGlass,
    YellowStainedGlass,
    LimeStainedGlass,
    PinkStainedGlass,
    GrayStainedGlass,
    LightGrayStainedGlass,
    CyanStainedGlass,
    PurpleStainedGlass,
    BlueStainedGlass,
    BrownStainedGlass,
    GreenStainedGlass,
    RedStainedGlass,
    BlackStainedGlass,
    InfestedStone,
    InfestedCobblestone,
    InfestedStoneBricks,
    InfestedMossyStoneBricks,
    InfestedCrackedStoneBricks,
    InfestedChiseledStoneBricks,
    StoneBricks,
    MossyStoneBricks,
    CrackedStoneBricks,
    ChiseledStoneBricks,
    Melon,
    LilyPad,
    NetherBricks,
    EnchantingTable,
    EndPortal,
    EndStone,
    DragonEgg,
    EmeraldOre,
    EmeraldBlock,
    Beacon,
    FlowerPot,
    PottedOakSapling,
    PottedSpruceSapling,
    PottedBirchSapling,
    PottedJungleSapling,
    PottedAcaciaSapling,
    PottedDarkOakSapling,
    PottedFern,
    PottedDandelion,
    PottedPoppy,
    PottedBlueOrchid,
    PottedAllium,
    PottedAzureBluet,
    PottedRedTulip,
    PottedOrangeTulip,
    PottedWhiteTulip,
    PottedPinkTulip,
    PottedOxeyeDaisy,
    PottedRedMushroom,
    PottedBrownMushroom,
    PottedDeadBush,
    PottedCactus,
    RedstoneBlock,
    NetherQuartzOre,
    QuartzBlock,
    ChiseledQuartzBlock,
    WhiteTerracotta,
    OrangeTerracotta,
    MagentaTerracotta,
    LightBlueTerracotta,
    YellowTerracotta,
    LimeTerracotta,
    PinkTerracotta,
    GrayTerracotta,
    LightGrayTerracotta,
    CyanTerracotta,
    PurpleTerracotta,
    BlueTerracotta,
    BrownTerracotta,
    GreenTerracotta,
    RedTerracotta,
    BlackTerracotta,
    SlimeBlock,
    Barrier,
    Prismarine,
    PrismarineBricks,
    DarkPrismarine,
    SeaLantern,
    WhiteCarpet,
    OrangeCarpet,
    MagentaCarpet,
    LightBlueCarpet,
    YellowCarpet,
    LimeCarpet,
    PinkCarpet,
    GrayCarpet,
    LightGrayCarpet,
    CyanCarpet,
    PurpleCarpet,
    BlueCarpet,
    BrownCarpet,
    GreenCarpet,
    RedCarpet,
    BlackCarpet,
    Terracotta,
    CoalBlock,
    PackedIce,
    RedSandstone,
    ChiseledRedSandstone,
    CutRedSandstone,
    SmoothStone,
    SmoothSandstone,
    SmoothQuartz,
    SmoothRedSandstone,
    PurpurBlock,
    EndStoneBricks,
    GrassPath,
    EndGateway,
    MagmaBlock,
    NetherWartBlock,
    RedNetherBricks,
    StructureVoid,
    WhiteConcrete,
    OrangeConcrete,
    MagentaConcrete,
    LightBlueConcrete,
    YellowConcrete,
    LimeConcrete,
    PinkConcrete,
    GrayConcrete,
    LightGrayConcrete,
    CyanConcrete,
    PurpleConcrete,
    BlueConcrete,
    BrownConcrete,
    GreenConcrete,
    RedConcrete,
    BlackConcrete,
    WhiteConcretePowder,
    OrangeConcretePowder,
    MagentaConcretePowder,
    LightBlueConcretePowder,
    YellowConcretePowder,
    LimeConcretePowder,
    PinkConcretePowder,
    GrayConcretePowder,
    LightGrayConcretePowder,
    CyanConcretePowder,
    PurpleConcretePowder,
    BlueConcretePowder,
    BrownConcretePowder,
    GreenConcretePowder,
    RedConcretePowder,
    BlackConcretePowder,
    KelpPlant,
    DriedKelpBlock,
    DeadTubeCoralBlock,
    DeadBrainCoralBlock,
    DeadBubbleCoralBlock,
    DeadFireCoralBlock,
    DeadHornCoralBlock,
    TubeCoralBlock,
    BrainCoralBlock,
    BubbleCoralBlock,
    FireCoralBlock,
    HornCoralBlock,
    BlueIce,
    VoidAir,
    CaveAir,
}
impl Block {
    pub fn block_state_id(&self) -> u16 {
        match self {
            Block::Air => 0,
            Block::Stone => 1,
            Block::Granite => 2,
            Block::PolishedGranite => 3,
            Block::Diorite => 4,
            Block::PolishedDiorite => 5,
            Block::Andesite => 6,
            Block::PolishedAndesite => 7,
            Block::Dirt => 10,
            Block::CoarseDirt => 11,
            Block::Cobblestone => 14,
            Block::OakPlanks => 15,
            Block::SprucePlanks => 16,
            Block::BirchPlanks => 17,
            Block::JunglePlanks => 18,
            Block::AcaciaPlanks => 19,
            Block::DarkOakPlanks => 20,
            Block::Bedrock => 33,
            Block::Sand => 66,
            Block::RedSand => 67,
            Block::Gravel => 68,
            Block::GoldOre => 69,
            Block::IronOre => 70,
            Block::CoalOre => 71,
            Block::Sponge => 228,
            Block::WetSponge => 229,
            Block::Glass => 230,
            Block::LapisOre => 231,
            Block::LapisBlock => 232,
            Block::Sandstone => 245,
            Block::ChiseledSandstone => 246,
            Block::CutSandstone => 247,
            Block::Cobweb => 1040,
            Block::Grass => 1041,
            Block::Fern => 1042,
            Block::DeadBush => 1043,
            Block::Seagrass => 1044,
            Block::WhiteWool => 1083,
            Block::OrangeWool => 1084,
            Block::MagentaWool => 1085,
            Block::LightBlueWool => 1086,
            Block::YellowWool => 1087,
            Block::LimeWool => 1088,
            Block::PinkWool => 1089,
            Block::GrayWool => 1090,
            Block::LightGrayWool => 1091,
            Block::CyanWool => 1092,
            Block::PurpleWool => 1093,
            Block::BlueWool => 1094,
            Block::BrownWool => 1095,
            Block::GreenWool => 1096,
            Block::RedWool => 1097,
            Block::BlackWool => 1098,
            Block::Dandelion => 1111,
            Block::Poppy => 1112,
            Block::BlueOrchid => 1113,
            Block::Allium => 1114,
            Block::AzureBluet => 1115,
            Block::RedTulip => 1116,
            Block::OrangeTulip => 1117,
            Block::WhiteTulip => 1118,
            Block::PinkTulip => 1119,
            Block::OxeyeDaisy => 1120,
            Block::BrownMushroom => 1121,
            Block::RedMushroom => 1122,
            Block::GoldBlock => 1123,
            Block::IronBlock => 1124,
            Block::Bricks => 1125,
            Block::Bookshelf => 1128,
            Block::MossyCobblestone => 1129,
            Block::Obsidian => 1130,
            Block::Torch => 1131,
            Block::Spawner => 1648,
            Block::DiamondOre => 3049,
            Block::DiamondBlock => 3050,
            Block::CraftingTable => 3051,
            Block::Ice => 3424,
            Block::SnowBlock => 3425,
            Block::Clay => 3442,
            Block::Pumpkin => 3493,
            Block::Netherrack => 3494,
            Block::SoulSand => 3495,
            Block::Glowstone => 3496,
            Block::WhiteStainedGlass => 3578,
            Block::OrangeStainedGlass => 3579,
            Block::MagentaStainedGlass => 3580,
            Block::LightBlueStainedGlass => 3581,
            Block::YellowStainedGlass => 3582,
            Block::LimeStainedGlass => 3583,
            Block::PinkStainedGlass => 3584,
            Block::GrayStainedGlass => 3585,
            Block::LightGrayStainedGlass => 3586,
            Block::CyanStainedGlass => 3587,
            Block::PurpleStainedGlass => 3588,
            Block::BlueStainedGlass => 3589,
            Block::BrownStainedGlass => 3590,
            Block::GreenStainedGlass => 3591,
            Block::RedStainedGlass => 3592,
            Block::BlackStainedGlass => 3593,
            Block::InfestedStone => 3978,
            Block::InfestedCobblestone => 3979,
            Block::InfestedStoneBricks => 3980,
            Block::InfestedMossyStoneBricks => 3981,
            Block::InfestedCrackedStoneBricks => 3982,
            Block::InfestedChiseledStoneBricks => 3983,
            Block::StoneBricks => 3984,
            Block::MossyStoneBricks => 3985,
            Block::CrackedStoneBricks => 3986,
            Block::ChiseledStoneBricks => 3987,
            Block::Melon => 4244,
            Block::LilyPad => 4495,
            Block::NetherBricks => 4496,
            Block::EnchantingTable => 4613,
            Block::EndPortal => 4626,
            Block::EndStone => 4635,
            Block::DragonEgg => 4636,
            Block::EmeraldOre => 4731,
            Block::EmeraldBlock => 4884,
            Block::Beacon => 5137,
            Block::FlowerPot => 5266,
            Block::PottedOakSapling => 5267,
            Block::PottedSpruceSapling => 5268,
            Block::PottedBirchSapling => 5269,
            Block::PottedJungleSapling => 5270,
            Block::PottedAcaciaSapling => 5271,
            Block::PottedDarkOakSapling => 5272,
            Block::PottedFern => 5273,
            Block::PottedDandelion => 5274,
            Block::PottedPoppy => 5275,
            Block::PottedBlueOrchid => 5276,
            Block::PottedAllium => 5277,
            Block::PottedAzureBluet => 5278,
            Block::PottedRedTulip => 5279,
            Block::PottedOrangeTulip => 5280,
            Block::PottedWhiteTulip => 5281,
            Block::PottedPinkTulip => 5282,
            Block::PottedOxeyeDaisy => 5283,
            Block::PottedRedMushroom => 5284,
            Block::PottedBrownMushroom => 5285,
            Block::PottedDeadBush => 5286,
            Block::PottedCactus => 5287,
            Block::RedstoneBlock => 5684,
            Block::NetherQuartzOre => 5685,
            Block::QuartzBlock => 5696,
            Block::ChiseledQuartzBlock => 5697,
            Block::WhiteTerracotta => 5805,
            Block::OrangeTerracotta => 5806,
            Block::MagentaTerracotta => 5807,
            Block::LightBlueTerracotta => 5808,
            Block::YellowTerracotta => 5809,
            Block::LimeTerracotta => 5810,
            Block::PinkTerracotta => 5811,
            Block::GrayTerracotta => 5812,
            Block::LightGrayTerracotta => 5813,
            Block::CyanTerracotta => 5814,
            Block::PurpleTerracotta => 5815,
            Block::BlueTerracotta => 5816,
            Block::BrownTerracotta => 5817,
            Block::GreenTerracotta => 5818,
            Block::RedTerracotta => 5819,
            Block::BlackTerracotta => 5820,
            Block::SlimeBlock => 6493,
            Block::Barrier => 6494,
            Block::Prismarine => 6559,
            Block::PrismarineBricks => 6560,
            Block::DarkPrismarine => 6561,
            Block::SeaLantern => 6820,
            Block::WhiteCarpet => 6824,
            Block::OrangeCarpet => 6825,
            Block::MagentaCarpet => 6826,
            Block::LightBlueCarpet => 6827,
            Block::YellowCarpet => 6828,
            Block::LimeCarpet => 6829,
            Block::PinkCarpet => 6830,
            Block::GrayCarpet => 6831,
            Block::LightGrayCarpet => 6832,
            Block::CyanCarpet => 6833,
            Block::PurpleCarpet => 6834,
            Block::BlueCarpet => 6835,
            Block::BrownCarpet => 6836,
            Block::GreenCarpet => 6837,
            Block::RedCarpet => 6838,
            Block::BlackCarpet => 6839,
            Block::Terracotta => 6840,
            Block::CoalBlock => 6841,
            Block::PackedIce => 6842,
            Block::RedSandstone => 7175,
            Block::ChiseledRedSandstone => 7176,
            Block::CutRedSandstone => 7177,
            Block::SmoothStone => 7354,
            Block::SmoothSandstone => 7355,
            Block::SmoothQuartz => 7356,
            Block::SmoothRedSandstone => 7357,
            Block::PurpurBlock => 8074,
            Block::EndStoneBricks => 8158,
            Block::GrassPath => 8163,
            Block::EndGateway => 8164,
            Block::MagmaBlock => 8193,
            Block::NetherWartBlock => 8194,
            Block::RedNetherBricks => 8195,
            Block::StructureVoid => 8199,
            Block::WhiteConcrete => 8378,
            Block::OrangeConcrete => 8379,
            Block::MagentaConcrete => 8380,
            Block::LightBlueConcrete => 8381,
            Block::YellowConcrete => 8382,
            Block::LimeConcrete => 8383,
            Block::PinkConcrete => 8384,
            Block::GrayConcrete => 8385,
            Block::LightGrayConcrete => 8386,
            Block::CyanConcrete => 8387,
            Block::PurpleConcrete => 8388,
            Block::BlueConcrete => 8389,
            Block::BrownConcrete => 8390,
            Block::GreenConcrete => 8391,
            Block::RedConcrete => 8392,
            Block::BlackConcrete => 8393,
            Block::WhiteConcretePowder => 8394,
            Block::OrangeConcretePowder => 8395,
            Block::MagentaConcretePowder => 8396,
            Block::LightBlueConcretePowder => 8397,
            Block::YellowConcretePowder => 8398,
            Block::LimeConcretePowder => 8399,
            Block::PinkConcretePowder => 8400,
            Block::GrayConcretePowder => 8401,
            Block::LightGrayConcretePowder => 8402,
            Block::CyanConcretePowder => 8403,
            Block::PurpleConcretePowder => 8404,
            Block::BlueConcretePowder => 8405,
            Block::BrownConcretePowder => 8406,
            Block::GreenConcretePowder => 8407,
            Block::RedConcretePowder => 8408,
            Block::BlackConcretePowder => 8409,
            Block::KelpPlant => 8436,
            Block::DriedKelpBlock => 8437,
            Block::DeadTubeCoralBlock => 8450,
            Block::DeadBrainCoralBlock => 8451,
            Block::DeadBubbleCoralBlock => 8452,
            Block::DeadFireCoralBlock => 8453,
            Block::DeadHornCoralBlock => 8454,
            Block::TubeCoralBlock => 8455,
            Block::BrainCoralBlock => 8456,
            Block::BubbleCoralBlock => 8457,
            Block::FireCoralBlock => 8458,
            Block::HornCoralBlock => 8459,
            Block::BlueIce => 8588,
            Block::VoidAir => 8591,
            Block::CaveAir => 8592,
        }
    }

    pub fn from_block_state_id(id: u16) -> Self {
        match id {
            0 => Block::Air,
            1 => Block::Stone,
            2 => Block::Granite,
            3 => Block::PolishedGranite,
            4 => Block::Diorite,
            5 => Block::PolishedDiorite,
            6 => Block::Andesite,
            7 => Block::PolishedAndesite,
            10 => Block::Dirt,
            11 => Block::CoarseDirt,
            14 => Block::Cobblestone,
            15 => Block::OakPlanks,
            16 => Block::SprucePlanks,
            17 => Block::BirchPlanks,
            18 => Block::JunglePlanks,
            19 => Block::AcaciaPlanks,
            20 => Block::DarkOakPlanks,
            33 => Block::Bedrock,
            66 => Block::Sand,
            67 => Block::RedSand,
            68 => Block::Gravel,
            69 => Block::GoldOre,
            70 => Block::IronOre,
            71 => Block::CoalOre,
            228 => Block::Sponge,
            229 => Block::WetSponge,
            230 => Block::Glass,
            231 => Block::LapisOre,
            232 => Block::LapisBlock,
            245 => Block::Sandstone,
            246 => Block::ChiseledSandstone,
            247 => Block::CutSandstone,
            1040 => Block::Cobweb,
            1041 => Block::Grass,
            1042 => Block::Fern,
            1043 => Block::DeadBush,
            1044 => Block::Seagrass,
            1083 => Block::WhiteWool,
            1084 => Block::OrangeWool,
            1085 => Block::MagentaWool,
            1086 => Block::LightBlueWool,
            1087 => Block::YellowWool,
            1088 => Block::LimeWool,
            1089 => Block::PinkWool,
            1090 => Block::GrayWool,
            1091 => Block::LightGrayWool,
            1092 => Block::CyanWool,
            1093 => Block::PurpleWool,
            1094 => Block::BlueWool,
            1095 => Block::BrownWool,
            1096 => Block::GreenWool,
            1097 => Block::RedWool,
            1098 => Block::BlackWool,
            1111 => Block::Dandelion,
            1112 => Block::Poppy,
            1113 => Block::BlueOrchid,
            1114 => Block::Allium,
            1115 => Block::AzureBluet,
            1116 => Block::RedTulip,
            1117 => Block::OrangeTulip,
            1118 => Block::WhiteTulip,
            1119 => Block::PinkTulip,
            1120 => Block::OxeyeDaisy,
            1121 => Block::BrownMushroom,
            1122 => Block::RedMushroom,
            1123 => Block::GoldBlock,
            1124 => Block::IronBlock,
            1125 => Block::Bricks,
            1128 => Block::Bookshelf,
            1129 => Block::MossyCobblestone,
            1130 => Block::Obsidian,
            1131 => Block::Torch,
            1648 => Block::Spawner,
            3049 => Block::DiamondOre,
            3050 => Block::DiamondBlock,
            3051 => Block::CraftingTable,
            3424 => Block::Ice,
            3425 => Block::SnowBlock,
            3442 => Block::Clay,
            3493 => Block::Pumpkin,
            3494 => Block::Netherrack,
            3495 => Block::SoulSand,
            3496 => Block::Glowstone,
            3578 => Block::WhiteStainedGlass,
            3579 => Block::OrangeStainedGlass,
            3580 => Block::MagentaStainedGlass,
            3581 => Block::LightBlueStainedGlass,
            3582 => Block::YellowStainedGlass,
            3583 => Block::LimeStainedGlass,
            3584 => Block::PinkStainedGlass,
            3585 => Block::GrayStainedGlass,
            3586 => Block::LightGrayStainedGlass,
            3587 => Block::CyanStainedGlass,
            3588 => Block::PurpleStainedGlass,
            3589 => Block::BlueStainedGlass,
            3590 => Block::BrownStainedGlass,
            3591 => Block::GreenStainedGlass,
            3592 => Block::RedStainedGlass,
            3593 => Block::BlackStainedGlass,
            3978 => Block::InfestedStone,
            3979 => Block::InfestedCobblestone,
            3980 => Block::InfestedStoneBricks,
            3981 => Block::InfestedMossyStoneBricks,
            3982 => Block::InfestedCrackedStoneBricks,
            3983 => Block::InfestedChiseledStoneBricks,
            3984 => Block::StoneBricks,
            3985 => Block::MossyStoneBricks,
            3986 => Block::CrackedStoneBricks,
            3987 => Block::ChiseledStoneBricks,
            4244 => Block::Melon,
            4495 => Block::LilyPad,
            4496 => Block::NetherBricks,
            4613 => Block::EnchantingTable,
            4626 => Block::EndPortal,
            4635 => Block::EndStone,
            4636 => Block::DragonEgg,
            4731 => Block::EmeraldOre,
            4884 => Block::EmeraldBlock,
            5137 => Block::Beacon,
            5266 => Block::FlowerPot,
            5267 => Block::PottedOakSapling,
            5268 => Block::PottedSpruceSapling,
            5269 => Block::PottedBirchSapling,
            5270 => Block::PottedJungleSapling,
            5271 => Block::PottedAcaciaSapling,
            5272 => Block::PottedDarkOakSapling,
            5273 => Block::PottedFern,
            5274 => Block::PottedDandelion,
            5275 => Block::PottedPoppy,
            5276 => Block::PottedBlueOrchid,
            5277 => Block::PottedAllium,
            5278 => Block::PottedAzureBluet,
            5279 => Block::PottedRedTulip,
            5280 => Block::PottedOrangeTulip,
            5281 => Block::PottedWhiteTulip,
            5282 => Block::PottedPinkTulip,
            5283 => Block::PottedOxeyeDaisy,
            5284 => Block::PottedRedMushroom,
            5285 => Block::PottedBrownMushroom,
            5286 => Block::PottedDeadBush,
            5287 => Block::PottedCactus,
            5684 => Block::RedstoneBlock,
            5685 => Block::NetherQuartzOre,
            5696 => Block::QuartzBlock,
            5697 => Block::ChiseledQuartzBlock,
            5805 => Block::WhiteTerracotta,
            5806 => Block::OrangeTerracotta,
            5807 => Block::MagentaTerracotta,
            5808 => Block::LightBlueTerracotta,
            5809 => Block::YellowTerracotta,
            5810 => Block::LimeTerracotta,
            5811 => Block::PinkTerracotta,
            5812 => Block::GrayTerracotta,
            5813 => Block::LightGrayTerracotta,
            5814 => Block::CyanTerracotta,
            5815 => Block::PurpleTerracotta,
            5816 => Block::BlueTerracotta,
            5817 => Block::BrownTerracotta,
            5818 => Block::GreenTerracotta,
            5819 => Block::RedTerracotta,
            5820 => Block::BlackTerracotta,
            6493 => Block::SlimeBlock,
            6494 => Block::Barrier,
            6559 => Block::Prismarine,
            6560 => Block::PrismarineBricks,
            6561 => Block::DarkPrismarine,
            6820 => Block::SeaLantern,
            6824 => Block::WhiteCarpet,
            6825 => Block::OrangeCarpet,
            6826 => Block::MagentaCarpet,
            6827 => Block::LightBlueCarpet,
            6828 => Block::YellowCarpet,
            6829 => Block::LimeCarpet,
            6830 => Block::PinkCarpet,
            6831 => Block::GrayCarpet,
            6832 => Block::LightGrayCarpet,
            6833 => Block::CyanCarpet,
            6834 => Block::PurpleCarpet,
            6835 => Block::BlueCarpet,
            6836 => Block::BrownCarpet,
            6837 => Block::GreenCarpet,
            6838 => Block::RedCarpet,
            6839 => Block::BlackCarpet,
            6840 => Block::Terracotta,
            6841 => Block::CoalBlock,
            6842 => Block::PackedIce,
            7175 => Block::RedSandstone,
            7176 => Block::ChiseledRedSandstone,
            7177 => Block::CutRedSandstone,
            7354 => Block::SmoothStone,
            7355 => Block::SmoothSandstone,
            7356 => Block::SmoothQuartz,
            7357 => Block::SmoothRedSandstone,
            8074 => Block::PurpurBlock,
            8158 => Block::EndStoneBricks,
            8163 => Block::GrassPath,
            8164 => Block::EndGateway,
            8193 => Block::MagmaBlock,
            8194 => Block::NetherWartBlock,
            8195 => Block::RedNetherBricks,
            8199 => Block::StructureVoid,
            8378 => Block::WhiteConcrete,
            8379 => Block::OrangeConcrete,
            8380 => Block::MagentaConcrete,
            8381 => Block::LightBlueConcrete,
            8382 => Block::YellowConcrete,
            8383 => Block::LimeConcrete,
            8384 => Block::PinkConcrete,
            8385 => Block::GrayConcrete,
            8386 => Block::LightGrayConcrete,
            8387 => Block::CyanConcrete,
            8388 => Block::PurpleConcrete,
            8389 => Block::BlueConcrete,
            8390 => Block::BrownConcrete,
            8391 => Block::GreenConcrete,
            8392 => Block::RedConcrete,
            8393 => Block::BlackConcrete,
            8394 => Block::WhiteConcretePowder,
            8395 => Block::OrangeConcretePowder,
            8396 => Block::MagentaConcretePowder,
            8397 => Block::LightBlueConcretePowder,
            8398 => Block::YellowConcretePowder,
            8399 => Block::LimeConcretePowder,
            8400 => Block::PinkConcretePowder,
            8401 => Block::GrayConcretePowder,
            8402 => Block::LightGrayConcretePowder,
            8403 => Block::CyanConcretePowder,
            8404 => Block::PurpleConcretePowder,
            8405 => Block::BlueConcretePowder,
            8406 => Block::BrownConcretePowder,
            8407 => Block::GreenConcretePowder,
            8408 => Block::RedConcretePowder,
            8409 => Block::BlackConcretePowder,
            8436 => Block::KelpPlant,
            8437 => Block::DriedKelpBlock,
            8450 => Block::DeadTubeCoralBlock,
            8451 => Block::DeadBrainCoralBlock,
            8452 => Block::DeadBubbleCoralBlock,
            8453 => Block::DeadFireCoralBlock,
            8454 => Block::DeadHornCoralBlock,
            8455 => Block::TubeCoralBlock,
            8456 => Block::BrainCoralBlock,
            8457 => Block::BubbleCoralBlock,
            8458 => Block::FireCoralBlock,
            8459 => Block::HornCoralBlock,
            8588 => Block::BlueIce,
            8591 => Block::VoidAir,
            8592 => Block::CaveAir,
            _ => panic!("Unknown block state ID {}", id),
        }
    }
}
