//! Packets sent from server to client;

use super::*;

mod login;
mod play;
mod status;

pub use login::*;
pub use play::*;
pub use status::*;

packet_enum!(ServerStatusPacket {
    0x00 = Response,
    0x01 = Pong,
});

packet_enum!(ServerLoginPacket {
    0x00 = DisconnectLogin,
    0x01 = EncryptionRequest,
    0x02 = LoginSuccess,
    0x03 = SetCompression,
    0x04 = LoginPluginRequest,
});

packet_enum!(ServerPlayPacket {
    0x00 = SpawnEntity,
    0x01 = SpawnExperienceOrb,
    0x02 = SpawnWeatherEntity,
    0x03 = SpawnLivingEntity,
    0x04 = SpawnPainting,
    0x05 = SpawnPlayer,
    0x06 = EntityAnimation,
    0x07 = Statistics,
    0x09 = AcknowledgePlayerDigging,
    0x09 = BlockBreakAnimation,
    0x0A = BlockEntityData,
    0x0B = BlockAction,
    0x0C = BlockChange,
    0x0D = BossBar,
    0x0E = ServerDifficulty,
    0x0F = ChatMessage,
    0x10 = MultiBlockChange,
    0x11 = TabComplete,
    0x12 = DeclareCommands,
    0x13 = WindowConfirmation,
    0x14 = CloseWindow,
    0x15 = WindowItems,
    0x16 = WindowProperty,
    0x17 = SetSlot,
    0x18 = SetCooldown,
    0x19 = PluginMessage,
    0x1A = NamedSoundEffect,
    0x1B = Disconnect,
    0x1C = EntityStatus,
    0x1D = Explosion,
    0x1E = UnloadChunk,
    0x1F = ChangeGameState,
    0x20 = OpenHorseWindow,
    0x21 = KeepAlive,
    // 0x22 = ChunkData,
    0x23 = Effect,
    0x24 = Particle,
    // 0x25 = UpdateLight,
    0x26 = JoinGame,
    0x27 = MapData,
    // 0x28 = TradeList,
    0x29 = EntityPosition,
    0x2A = EntityPositionAndRotation,
    0x2B = EntityRotation,
    0x2C = EntityMovement,
    0x2D = VehicleMove,
    0x2E = OpenBook,
    0x2F = OpenWindow,
    0x30 = OpenSignEditor,
    0x31 = CraftRecipeResponse,
    0x32 = PlayerAbilities,
    0x33 = CombatEvent,
    0x34 = PlayerInfo,
    0x35 = FacePlayer,
    0x36 = PlayerPositionAndLook,
    // 0x37 = UnlockRecipes,
    0x38 = DestroyEntities,
    0x39 = RemoveEntityEffect,
    0x3A = ResourcePack,
    0x3B = Respawn,
    0x3C = EntityHeadLook,
    0x3D = SelectAdvancementTab,
    0x3E = WorldBorder,
    0x3F = Camera,
    0x40 = HeldItemChange,
    0x41 = UpdateViewPosition,
    0x42 = UpdateViewDistance,
    0x43 = DisplayScoreboard,
    0x44 = SendEntityMetadata,
    0x45 = AttachEntity,
    0x46 = EntityVelocity,
    0x47 = EntityEquipment,
    0x48 = SetExperience,
    0x49 = UpdateHealth,
    0x4A = ScoreboardObjective,
    0x4B = SetPassengers,
    0x4C = Teams,
    0x4D = UpdateScore,
    0x4E = SpawnPosition,
    0x4F = TimeUpdate,
    0x50 = Title,
    0x51 = EntitySoundEffect,
    0x52 = SoundEffect,
    0x53 = StopSound,
    0x54 = PlayerListHeaderAndFooter,
    0x55 = NbtQueryResponse,
    0x56 = CollectItem,
    0x57 = EntityTeleport,
    // 0x58 = Advancements,
    // 0x59 = EntityProperties,
    0x5A = EntityEffect,
    0x5B = DeclareRecipes,
    0x5C = AllTags,
});
