//! Packets sent from server to client;
use crate::VarInt;
use crate::VariantOf;

mod login;
mod play;
mod status;

pub use login::*;
pub use play::*;
pub use status::*;

packet_enum!(ServerStatusPacket {
    0x00 = Response,
    0x01 = Pong,
});

packet_enum!(ServerLoginPacket {
    0x00 = DisconnectLogin,
    0x01 = EncryptionRequest,
    0x02 = LoginSuccess,
    0x03 = SetCompression,
    0x04 = LoginPluginRequest,
});

packet_enum!(ServerPlayPacket {
    0x00 = SpawnEntity,
    0x01 = SpawnExperienceOrb,
    0x02 = SpawnLivingEntity,
    0x03 = SpawnPainting,
    0x04 = SpawnPlayer,
    0x05 = SculkVibrationSignal,
    0x06 = EntityAnimation,
    0x07 = Statistics,
    0x08 = AcknowledgePlayerDigging,
    0x09 = BlockBreakAnimation,
    0x0A = BlockEntityData,
    0x0B = BlockAction,
    0x0C = BlockChange,
    0x0D = BossBar,
    0x0E = ServerDifficulty,
    0x0F = ChatMessage,
    0x10 = ClearTitles,
    0x11 = TabComplete,
    0x12 = DeclareCommands,
    0x13 = CloseWindow,
    0x14 = WindowItems,
    0x15 = WindowProperty,
    0x16 = SetSlot,
    0x17 = SetCooldown,
    0x18 = PluginMessage,
    0x19 = NamedSoundEffect,
    0x1A = Disconnect,
    0x1B = EntityStatus,
    0x1C = Explosion,
    0x1D = UnloadChunk,
    0x1E = ChangeGameState,
    0x1F = OpenHorseWindow,
    0x20 = InitializeWorldBorder,
    0x21 = KeepAlive,
    0x22 = ChunkData,
    0x23 = Effect,
    0x24 = Particle,
    0x25 = UpdateLight,
    0x26 = JoinGame,
    0x27 = MapData,
    0x28 = TradeList,
    0x29 = EntityPosition,
    0x2A = EntityPositionAndRotation,
    0x2B = EntityRotation,
    0x2C = VehicleMove,
    0x2D = OpenBook,
    0x2E = OpenWindow,
    0x2F = OpenSignEditor,
    0x30 = Ping,
    0x31 = CraftRecipeResponse,
    0x32 = PlayerAbilities,
    0x33 = EndCombatEvent,
    0x34 = EnterCombatEvent,
    0x35 = DeathCombatEvent,
    0x36 = PlayerInfo,
    0x37 = FacePlayer,
    0x38 = PlayerPositionAndLook,
    0x39 = UnlockRecipes,
    0x3A = DestroyEntities,
    0x3B = RemoveEntityEffect,
    0x3C = ResourcePack,
    0x3D = Respawn,
    0x3E = EntityHeadLook,
    0x3F = MultiBlockChange,
    0x40 = SelectAdvancementTab,
    0x41 = ActionBar,
    0x42 = WorldBorderCenter,
    0x43 = WorldBorderLerpSize,
    0x44 = WorldBorderSize,
    0x45 = WorldBorderWarningDelay,
    0x46 = WorldBorderWarningReach,
    0x47 = Camera,
    0x48 = HeldItemChange,
    0x49 = UpdateViewPosition,
    0x4A = UpdateViewDistance,
    0x4B = SpawnPosition,
    0x4C = DisplayScoreboard,
    0x4D = SendEntityMetadata,
    0x4E = AttachEntity,
    0x4F = EntityVelocity,
    0x50 = EntityEquipment,
    0x51 = SetExperience,
    0x52 = UpdateHealth,
    0x53 = ScoreboardObjective,
    0x54 = SetPassengers,
    0x55 = Teams,
    0x56 = UpdateScore,
    0x57 = UpdateSimulationDistance,
    0x58 = SetTitleSubtitle,
    0x59 = TimeUpdate,
    0x5A = SetTitleText,
    0x5B = SetTitleTimes,
    0x5C = EntitySoundEffect,
    0x5D = SoundEffect,
    0x5E = StopSound,
    0x5F = PlayerListHeaderAndFooter,
    0x60 = NbtQueryResponse,
    0x61 = CollectItem,
    0x62 = EntityTeleport,
    0x63 = Advancements,
    0x64 = EntityProperties,
    0x65 = EntityEffect,
    0x66 = DeclareRecipes,
    0x67 = AllTags,
});
