// This file is @generated. Please do not edit.

#[derive(
    Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Deserialize, serde::Serialize,
)]
pub enum Effect {
    SpeedEffect,
    SlownessEffect,
    HasteEffect,
    MiningfatigueEffect,
    StrengthEffect,
    InstanthealthEffect,
    InstantdamageEffect,
    JumpboostEffect,
    NauseaEffect,
    RegenerationEffect,
    ResistanceEffect,
    FireresistanceEffect,
    WaterbreathingEffect,
    InvisibilityEffect,
    BlindnessEffect,
    NightvisionEffect,
    HungerEffect,
    WeaknessEffect,
    PoisonEffect,
    WitherEffect,
    HealthboostEffect,
    AbsorptionEffect,
    SaturationEffect,
    GlowingEffect,
    LevitationEffect,
    LuckEffect,
    BadluckEffect,
    SlowfallingEffect,
    ConduitpowerEffect,
    DolphinsgraceEffect,
    BadomenEffect,
    HeroofthevillageEffect,
}

#[allow(warnings)]
#[allow(clippy::all)]
impl Effect {
    /// Returns the `id` property of this `Effect`.
    pub fn id(&self) -> u8 {
        match self {
            Effect::SpeedEffect => 1,
            Effect::SlownessEffect => 2,
            Effect::HasteEffect => 3,
            Effect::MiningfatigueEffect => 4,
            Effect::StrengthEffect => 5,
            Effect::InstanthealthEffect => 6,
            Effect::InstantdamageEffect => 7,
            Effect::JumpboostEffect => 8,
            Effect::NauseaEffect => 9,
            Effect::RegenerationEffect => 10,
            Effect::ResistanceEffect => 11,
            Effect::FireresistanceEffect => 12,
            Effect::WaterbreathingEffect => 13,
            Effect::InvisibilityEffect => 14,
            Effect::BlindnessEffect => 15,
            Effect::NightvisionEffect => 16,
            Effect::HungerEffect => 17,
            Effect::WeaknessEffect => 18,
            Effect::PoisonEffect => 19,
            Effect::WitherEffect => 20,
            Effect::HealthboostEffect => 21,
            Effect::AbsorptionEffect => 22,
            Effect::SaturationEffect => 23,
            Effect::GlowingEffect => 24,
            Effect::LevitationEffect => 25,
            Effect::LuckEffect => 26,
            Effect::BadluckEffect => 27,
            Effect::SlowfallingEffect => 28,
            Effect::ConduitpowerEffect => 29,
            Effect::DolphinsgraceEffect => 31,
            Effect::BadomenEffect => 32,
            Effect::HeroofthevillageEffect => 32,
        }
    }

    /// Gets a `Effect` by its `id`.
    pub fn from_id(id: u8) -> Option<Self> {
        match id {
            1 => Some(Effect::SpeedEffect),
            2 => Some(Effect::SlownessEffect),
            3 => Some(Effect::HasteEffect),
            4 => Some(Effect::MiningfatigueEffect),
            5 => Some(Effect::StrengthEffect),
            6 => Some(Effect::InstanthealthEffect),
            7 => Some(Effect::InstantdamageEffect),
            8 => Some(Effect::JumpboostEffect),
            9 => Some(Effect::NauseaEffect),
            10 => Some(Effect::RegenerationEffect),
            11 => Some(Effect::ResistanceEffect),
            12 => Some(Effect::FireresistanceEffect),
            13 => Some(Effect::WaterbreathingEffect),
            14 => Some(Effect::InvisibilityEffect),
            15 => Some(Effect::BlindnessEffect),
            16 => Some(Effect::NightvisionEffect),
            17 => Some(Effect::HungerEffect),
            18 => Some(Effect::WeaknessEffect),
            19 => Some(Effect::PoisonEffect),
            20 => Some(Effect::WitherEffect),
            21 => Some(Effect::HealthboostEffect),
            22 => Some(Effect::AbsorptionEffect),
            23 => Some(Effect::SaturationEffect),
            24 => Some(Effect::GlowingEffect),
            25 => Some(Effect::LevitationEffect),
            26 => Some(Effect::LuckEffect),
            27 => Some(Effect::BadluckEffect),
            28 => Some(Effect::SlowfallingEffect),
            29 => Some(Effect::ConduitpowerEffect),
            31 => Some(Effect::DolphinsgraceEffect),
            32 => Some(Effect::BadomenEffect),
            32 => Some(Effect::HeroofthevillageEffect),
            _ => None,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Effect {
    /// Returns the `name` property of this `Effect`.
    pub fn name(&self) -> &'static str {
        match self {
            Effect::SpeedEffect => "Speed",
            Effect::SlownessEffect => "Slowness",
            Effect::HasteEffect => "Haste",
            Effect::MiningfatigueEffect => "MiningFatigue",
            Effect::StrengthEffect => "Strength",
            Effect::InstanthealthEffect => "InstantHealth",
            Effect::InstantdamageEffect => "InstantDamage",
            Effect::JumpboostEffect => "JumpBoost",
            Effect::NauseaEffect => "Nausea",
            Effect::RegenerationEffect => "Regeneration",
            Effect::ResistanceEffect => "Resistance",
            Effect::FireresistanceEffect => "FireResistance",
            Effect::WaterbreathingEffect => "WaterBreathing",
            Effect::InvisibilityEffect => "Invisibility",
            Effect::BlindnessEffect => "Blindness",
            Effect::NightvisionEffect => "NightVision",
            Effect::HungerEffect => "Hunger",
            Effect::WeaknessEffect => "Weakness",
            Effect::PoisonEffect => "Poison",
            Effect::WitherEffect => "Wither",
            Effect::HealthboostEffect => "HealthBoost",
            Effect::AbsorptionEffect => "Absorption",
            Effect::SaturationEffect => "Saturation",
            Effect::GlowingEffect => "Glowing",
            Effect::LevitationEffect => "Levitation",
            Effect::LuckEffect => "Luck",
            Effect::BadluckEffect => "BadLuck",
            Effect::SlowfallingEffect => "SlowFalling",
            Effect::ConduitpowerEffect => "ConduitPower",
            Effect::DolphinsgraceEffect => "DolphinsGrace",
            Effect::BadomenEffect => "BadOmen",
            Effect::HeroofthevillageEffect => "HeroOfTheVillage",
        }
    }

    /// Gets a `Effect` by its `name`.
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "Speed" => Some(Effect::SpeedEffect),
            "Slowness" => Some(Effect::SlownessEffect),
            "Haste" => Some(Effect::HasteEffect),
            "MiningFatigue" => Some(Effect::MiningfatigueEffect),
            "Strength" => Some(Effect::StrengthEffect),
            "InstantHealth" => Some(Effect::InstanthealthEffect),
            "InstantDamage" => Some(Effect::InstantdamageEffect),
            "JumpBoost" => Some(Effect::JumpboostEffect),
            "Nausea" => Some(Effect::NauseaEffect),
            "Regeneration" => Some(Effect::RegenerationEffect),
            "Resistance" => Some(Effect::ResistanceEffect),
            "FireResistance" => Some(Effect::FireresistanceEffect),
            "WaterBreathing" => Some(Effect::WaterbreathingEffect),
            "Invisibility" => Some(Effect::InvisibilityEffect),
            "Blindness" => Some(Effect::BlindnessEffect),
            "NightVision" => Some(Effect::NightvisionEffect),
            "Hunger" => Some(Effect::HungerEffect),
            "Weakness" => Some(Effect::WeaknessEffect),
            "Poison" => Some(Effect::PoisonEffect),
            "Wither" => Some(Effect::WitherEffect),
            "HealthBoost" => Some(Effect::HealthboostEffect),
            "Absorption" => Some(Effect::AbsorptionEffect),
            "Saturation" => Some(Effect::SaturationEffect),
            "Glowing" => Some(Effect::GlowingEffect),
            "Levitation" => Some(Effect::LevitationEffect),
            "Luck" => Some(Effect::LuckEffect),
            "BadLuck" => Some(Effect::BadluckEffect),
            "SlowFalling" => Some(Effect::SlowfallingEffect),
            "ConduitPower" => Some(Effect::ConduitpowerEffect),
            "DolphinsGrace" => Some(Effect::DolphinsgraceEffect),
            "BadOmen" => Some(Effect::BadomenEffect),
            "HeroOfTheVillage" => Some(Effect::HeroofthevillageEffect),
            _ => None,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Effect {
    /// Returns the `display_name` property of this `Effect`.
    pub fn display_name(&self) -> &'static str {
        match self {
            Effect::SpeedEffect => "Speed",
            Effect::SlownessEffect => "Slowness",
            Effect::HasteEffect => "Haste",
            Effect::MiningfatigueEffect => "Mining Fatigue",
            Effect::StrengthEffect => "Strength",
            Effect::InstanthealthEffect => "Instant Health",
            Effect::InstantdamageEffect => "Instant Damage",
            Effect::JumpboostEffect => "Jump Boost",
            Effect::NauseaEffect => "Nausea",
            Effect::RegenerationEffect => "Regeneration",
            Effect::ResistanceEffect => "Resistance",
            Effect::FireresistanceEffect => "Fire Resistance",
            Effect::WaterbreathingEffect => "Water Breathing",
            Effect::InvisibilityEffect => "Invisibility",
            Effect::BlindnessEffect => "Blindness",
            Effect::NightvisionEffect => "Night Vision",
            Effect::HungerEffect => "Hunger",
            Effect::WeaknessEffect => "Weakness",
            Effect::PoisonEffect => "Poison",
            Effect::WitherEffect => "Wither",
            Effect::HealthboostEffect => "Health Boost",
            Effect::AbsorptionEffect => "Absorption",
            Effect::SaturationEffect => "Saturation",
            Effect::GlowingEffect => "Glowing",
            Effect::LevitationEffect => "Levitation",
            Effect::LuckEffect => "Luck",
            Effect::BadluckEffect => "Bad Luck",
            Effect::SlowfallingEffect => "Slow Falling",
            Effect::ConduitpowerEffect => "Conduit Power",
            Effect::DolphinsgraceEffect => "Dolphin's Grace",
            Effect::BadomenEffect => "Bad Omen",
            Effect::HeroofthevillageEffect => "Hero Of The Village",
        }
    }

    /// Gets a `Effect` by its `display_name`.
    pub fn from_display_name(display_name: &str) -> Option<Self> {
        match display_name {
            "Speed" => Some(Effect::SpeedEffect),
            "Slowness" => Some(Effect::SlownessEffect),
            "Haste" => Some(Effect::HasteEffect),
            "Mining Fatigue" => Some(Effect::MiningfatigueEffect),
            "Strength" => Some(Effect::StrengthEffect),
            "Instant Health" => Some(Effect::InstanthealthEffect),
            "Instant Damage" => Some(Effect::InstantdamageEffect),
            "Jump Boost" => Some(Effect::JumpboostEffect),
            "Nausea" => Some(Effect::NauseaEffect),
            "Regeneration" => Some(Effect::RegenerationEffect),
            "Resistance" => Some(Effect::ResistanceEffect),
            "Fire Resistance" => Some(Effect::FireresistanceEffect),
            "Water Breathing" => Some(Effect::WaterbreathingEffect),
            "Invisibility" => Some(Effect::InvisibilityEffect),
            "Blindness" => Some(Effect::BlindnessEffect),
            "Night Vision" => Some(Effect::NightvisionEffect),
            "Hunger" => Some(Effect::HungerEffect),
            "Weakness" => Some(Effect::WeaknessEffect),
            "Poison" => Some(Effect::PoisonEffect),
            "Wither" => Some(Effect::WitherEffect),
            "Health Boost" => Some(Effect::HealthboostEffect),
            "Absorption" => Some(Effect::AbsorptionEffect),
            "Saturation" => Some(Effect::SaturationEffect),
            "Glowing" => Some(Effect::GlowingEffect),
            "Levitation" => Some(Effect::LevitationEffect),
            "Luck" => Some(Effect::LuckEffect),
            "Bad Luck" => Some(Effect::BadluckEffect),
            "Slow Falling" => Some(Effect::SlowfallingEffect),
            "Conduit Power" => Some(Effect::ConduitpowerEffect),
            "Dolphin's Grace" => Some(Effect::DolphinsgraceEffect),
            "Bad Omen" => Some(Effect::BadomenEffect),
            "Hero Of The Village" => Some(Effect::HeroofthevillageEffect),
            _ => None,
        }
    }
}
#[allow(warnings)]
#[allow(clippy::all)]
impl Effect {
    /// Returns the `is_good` property of this `Effect`.
    pub fn is_good(&self) -> bool {
        match self {
            Effect::SpeedEffect => true,
            Effect::SlownessEffect => false,
            Effect::HasteEffect => true,
            Effect::MiningfatigueEffect => false,
            Effect::StrengthEffect => true,
            Effect::InstanthealthEffect => true,
            Effect::InstantdamageEffect => false,
            Effect::JumpboostEffect => true,
            Effect::NauseaEffect => false,
            Effect::RegenerationEffect => true,
            Effect::ResistanceEffect => true,
            Effect::FireresistanceEffect => true,
            Effect::WaterbreathingEffect => true,
            Effect::InvisibilityEffect => true,
            Effect::BlindnessEffect => false,
            Effect::NightvisionEffect => true,
            Effect::HungerEffect => false,
            Effect::WeaknessEffect => false,
            Effect::PoisonEffect => false,
            Effect::WitherEffect => false,
            Effect::HealthboostEffect => true,
            Effect::AbsorptionEffect => true,
            Effect::SaturationEffect => true,
            Effect::GlowingEffect => false,
            Effect::LevitationEffect => false,
            Effect::LuckEffect => true,
            Effect::BadluckEffect => false,
            Effect::SlowfallingEffect => true,
            Effect::ConduitpowerEffect => true,
            Effect::DolphinsgraceEffect => true,
            Effect::BadomenEffect => true,
            Effect::HeroofthevillageEffect => true,
        }
    }
}
